Optimization for use of Distinct with Limit clause
prestodb/presto pull request #14661
Opened 2020-06-17 08:00 UTC by fgwang7w

== RELEASE NOTES ==

General Changes

Presto optimizer transforms a DISTINCT with LIMIT clause into a DistinctLimit Operator. This operator works well when Limit count size is in low watermark. It does not perform once the count goes beyond certain level. The reason is that the operator accumulates the aggregation the dataset which consumes node's memory significantly. Under a performance benchmark, it has been measured that the optimal performance for this operator is set when the limit count is less than 1 million rows.  

Hence, this fix allows user to query a large dataset using DISTINCT with LIMIT clause and ensures that the query does not consumes all memory in a single node. Beyond the threshold, the optimizer will choose to generate a different operator for streaming data back to the user.

Hive Changes

```

== NO RELEASE NOTE ==
```

2020-06-20 17:15 UTC, fgwang7w commented
fixed #14661

2020-11-04 16:39 UTC, kaikalur requested changes
See inline.

2020-11-04 16:39 UTC, kaikalur commented on presto-main/src/main/java/com/facebook/presto/sql/analyzer/FeaturesConfig.java
> +    private long allowedDistrinctLimitThreshold = 1000000;
typo - s/Distrinct/Distinct

2020-11-04 16:39 UTC, kaikalur commented on presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/MergeLimitWithDistinct.java
> +        allowedLimitThreshold = SystemSessionProperties.getDistinctLimitOperatorThreshold(session);
This doesn't look clean. I say do it in the constructor in PlanOptimizers or something.

2020-11-04 16:39 UTC, kaikalur commented on presto-tests/src/test/java/com/facebook/presto/tests/TestLocalQueries.java
> +
Also add a test with the higher limit like 500k or so and make sure it generates the right plan

2021-06-22 20:22 UTC, fgwang7w commented
It appears that the use case for this PR is very limited, close now and in the future if there's any requirement, we can pick it up

2021-06-22 20:22 UTC, closed without merging