Push partial Top N through outer join.
prestodb/presto pull request #15229
Opened 2020-09-26 18:49 UTC by simmend

Pushes a partial Top N operation through a left or right outer join onto the preserved input. The ordering columns of the top N must be rewriteable to refer to only columns of the preserved input. Note that full outer joins are excluded as they can inject order affecting null rows into the join result.

Test plan - New tests that verify plan correctness were added to TestPushTopNThroughOuterJoin.java and TestLogicalPlanner.java. 

== NO RELEASE NOTE ==

2020-09-27 21:07 UTC, simmend commented
Test this please.

2020-09-27 21:53 UTC, simmend commented
Test this please

2020-09-28 17:15 UTC, simmend commented
@highker James would you take a look? Thanks.

2020-09-29 18:29 UTC, aweisberg commented
Was there code in this PR copied from another project? If so please follow the [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).

2020-09-29 21:32 UTC, simmend commented
Updated. Thanks.
DS

On Tue, Sep 29, 2020 at 11:30 AM aweisberg <notifications@github.com> wrote:

> Was there code in this PR copied from another project? If so please follow
> the attribution guidelines
> <https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution>
> .
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/prestodb/presto/pull/15229#issuecomment-700899884>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEMBPVXWWQBT2XNUDX6QUMTSIIRSTANCNFSM4R3BZWKA>
> .
>

2020-09-29 23:21 UTC, simmend commented
@aweisberg Updated the commit as per your comment.

2020-09-30 16:13 UTC, aweisberg commented
@rongrong do you have bandwidth to review (or can you find someone?)

2020-10-13 21:29 UTC, simmend commented
@rongrong @aweisberg can i please get a review? thanks

2020-11-01 19:54 UTC, fgwang7w commented
@rschlussel could you please also help review this pr as it also ties the performance enhancement with my other pr #14915 ? Thanks

2020-11-06 04:11 UTC, fgwang7w commented
LGTM, @rongrong @rschlussel  could you please help review or find someone to review this PR? thanks

2020-11-19 16:51 UTC, kaikalur requested changes
I would like to see an end-to-end test with query and results to validate the actual execution. Also make sure to cover order by with:
  * LIMIT
  * NULL treatment (FIRST/LAST)
  * DISTINCT in the outer select as well

as those are all things that can be potentially impacted by this.

2020-11-19 16:51 UTC, kaikalur commented on presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/PushTopNThroughOuterJoin.java
> +                && ImmutableSet.copyOf(right.getOutputVariables()).containsAll(orderBySymbols)
Instead of repeating the code, just have two variables inner and outer, setting them appropriately based on join type so it's more robust.

2020-12-03 00:57 UTC, rongrong commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/TopNMatcher.java
> +        this.step = requireNonNull(step, "step is null");
This is not used?

2020-12-03 00:57 UTC, rongrong commented on presto-main/src/test/java/com/facebook/presto/sql/planner/assertions/PlanMatchPattern.java
> +        return node(TopNNode.class, source).with(new TopNMatcher(count, orderBy, TopNNode.Step.SINGLE));
static import.

2021-02-02 00:20 UTC, closed without merging