Add local cache for Parquet Metadata
prestodb/presto pull request #15276
Opened 2020-10-06 22:41 UTC by ClarenceThreepwood

Test plan - TravisCI and unit tests in AbstractTestParquetReader

Fixes #13921

```
== RELEASE NOTES ==

Hive Changes
* Add caching module for Parquet metadata
```

2020-10-09 17:11 UTC, shixuan-fan reviewed
Minor nits. LGTM. @zhenxiao could you also take a quick pass since you are more familiar with Parquet? :)

2020-10-09 17:11 UTC, shixuan-fan commented on presto-hive/src/main/java/com/facebook/presto/hive/HiveClientModule.java
> +        if (parquetCacheConfig.ismetadataCacheEnabled()) {
nit: `isMetadataCacheEnabled()`

2020-10-09 17:11 UTC, shixuan-fan commented on presto-hive/src/main/java/com/facebook/presto/hive/HiveClientModule.java
> +                    .maximumWeight(parquetCacheConfig.getmetadataCacheSize().toBytes())
nit: getMetadataCacheSize()

2020-10-09 17:11 UTC, shixuan-fan commented on presto-hive/src/main/java/com/facebook/presto/hive/HiveClientModule.java
> +                    .expireAfterAccess(parquetCacheConfig.getmetadataCacheTtlSinceLastAccess().toMillis(), TimeUnit.MILLISECONDS)
nit: `getMetadataCacheTtlSinceLastAccess`

2020-10-09 17:11 UTC, shixuan-fan commented on presto-parquet/src/main/java/com/facebook/presto/parquet/cache/ParquetCacheConfig.java
> +    public ParquetCacheConfig setmetadataCacheEnabled(boolean metadataCacheEnabled)
nit: Capitalize the first letter after `get` and `set` in this class

2020-10-09 22:22 UTC, zhenxiao approved these changes
nice work, @ClarenceThreepwood 
LGTM, just one minor thing. please address @shixuan-fan 's comments

2020-10-09 23:27 UTC, zhenxiao commented on presto-hive/src/test/java/com/facebook/presto/hive/parquet/AbstractTestParquetReader.java
> +        Logger.getLogger(CodecConfig.class.getName()).setLevel(Level.WARNING);
duplicate line?

2020-10-10 23:44 UTC, zhenxiao requested changes
some testcase failures. could you please take a look?

2020-10-12 21:38 UTC, ClarenceThreepwood commented
Thanks for the reviews @shixuan-fan and @zhenxiao. This should be all set to merge now

2020-10-12 23:06 UTC, zhenxiao approved these changes

2020-10-14 00:55 UTC, merged