Fix constant analysis for prepared statement parameters
prestodb/presto pull request #15322
Opened 2020-10-16 20:29 UTC by rschlussel

We were allowing anything without an explicit column reference, which
included SELECT * from table and SELECT 1 from table.  Now only
expressions that reference neither tables nor columns (nor *) will be
allowed.

Test plan -  unit tests

Fixes #15297 

```
== RELEASE NOTES ==

General Changes
* Fix an issue where prepared statements would allow some non-constant parameters.
```

2020-10-16 21:13 UTC, kaikalur reviewed
I see there is a RowExpressionInterpeter class. Maybe you can use that to make sure the expression evaluates a constant and reject if it doesn't?

2020-10-16 21:13 UTC, kaikalur commented on presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java
> +            assertEquals(e.getMessage(), "line 1:24: Constant expression cannot contain column references");
Also add a test for passing * - AllColumns I assume that you just added a visitor above.

2020-10-16 21:13 UTC, kaikalur commented on presto-main/src/main/java/com/facebook/presto/sql/analyzer/ConstantExpressionVerifier.java
> +        }
How about things like UDFs? Maybe we should disallow those as well?

2020-12-02 18:00 UTC, rschlussel commented
@kaikalur I updated this to only allow literal expressions.  I'm not sure if there are other cases like the map constructor though that I've missed.

2020-12-04 17:11 UTC, kaikalur requested changes

2020-12-04 17:23 UTC, kaikalur commented
> @kaikalur I updated this to only allow literal expressions. I'm not sure if there are other cases like the map constructor though that I've missed.

Actually, I remember now - can't we just use RowExpressionInterpter like I suggested earier?

2020-12-04 17:43 UTC, kaikalur commented on presto-main/src/main/java/com/facebook/presto/sql/analyzer/ParameterVerifier.java
> +    private static class ParameterVerifierVisitor
Also, I see another similar class:

presto-main/src/main/java/com/facebook/presto/sql/analyzer/ConstantExpressionVerifier.java

Can we use that?

2020-12-07 15:16 UTC, rschlussel commented
@kaikalur updated the pr.  As discussed over chat, I switched this back to allowing any constants, as we decided we are okay with any functions as long as the expressions are constant.  Also, as discussed we can't use the RowExpressionInterpreter since the expressions have not been converted to row expressions at the time we replace the prepared statements.

2020-12-07 23:06 UTC, rongrong approved these changes

2020-12-08 14:26 UTC, merged