Support Trino bitwise shift functions in Presto
prestodb/presto pull request #15730
Opened 2021-02-19 01:30 UTC by djsstarburst

To promote convergence between Trino and Presto, this commit
adds to Presto the bitwise functions present in Trino but missing
in Presto.

Test plan - Appropriate tests have been added to class TestBitwiseFunctions as part of this commit.

== RELEASE NOTES ==

General Changes
* The 12 integral shift functions defined by Trino's BitwiseFunctions class have been added to Presto's BitwiseFunctions class.  These shift functions represent a complete set of shift operations on tinyints, smallints, integers and longs.

2021-03-01 14:55 UTC, aweisberg commented
@Lewuathe appears to be the original author of this code. Please add them as a co-author. [See our attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).

2021-03-01 15:12 UTC, djsstarburst commented
> @Lewuathe appears to be the original author of this code. Please add them as a co-author. [See our attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).

Done.

2021-03-01 15:33 UTC, aweisberg approved these changes
LGTM. Checks were originally passing, but I imagine it has fallen far enough behind at this point that the FB integration check fails.

Thank you!

2021-03-01 15:42 UTC, djsstarburst commented
> LGTM. Checks were originally passing, but I imagine it has fallen far enough behind at this point that the FB integration check fails.

Thanks for pointing that out - - I just rebased on tip master and force-pushed, so that should fix it.

2021-03-11 13:34 UTC, mbasmanova requested changes
@djsstarburst Would you add documentation for these functions?

2021-03-11 16:02 UTC, djsstarburst commented
> @djsstarburst Would you add documentation for these functions?

@mbasmanova, I added documentation and examples for the new shift functions in bitwise.rst.  While I was at it, I fixed the broken formatting in the examples of the previously existing shift functions.

2021-03-11 17:13 UTC, mbasmanova approved these changes
Thanks.

2021-03-16 15:39 UTC, aweisberg commented
@mbasmanova I restarted it and it looks like it is passing this time.

2021-03-16 16:18 UTC, merged

2021-03-16 16:18 UTC, mbasmanova commented
@djsstarburst Thank you, David, for the contribution. Thanks @aweisberg for restarting a failing job.