fix parquet column stats bug
prestodb/presto pull request #15849
Opened 2021-03-19 09:15 UTC by zybing

Test plan - (Please fill in how you tested your changes)
In current version, for parquet files, the null_count statistics info is aways initial to 0. this will lead to error, when where condition is '*** = null' and actual parquet file don't have null_count statistics info. 
we should change it to :  0 means the null_count is 0, -1 means we don't have statistics info about null_count.

== RELEASE NOTES ==

== NO RELEASE NOTE ==

2021-03-31 16:29 UTC, v-jizhang commented on presto-parquet/src/main/java/com/facebook/presto/parquet/cache/MetadataReader.java
> +        stats.setNumNulls(-1);
According to https://www.javadoc.io/doc/org.apache.parquet/parquet-column/1.10.0/org/apache/parquet/column/statistics/Statistics.html#isNumNullsSet--, there is a method that can tell if numNulls is set or not. Why should we set it to -1?
```
public boolean isNumNullsSet()

Returns:
    whether numNulls is set and can be used 
```

2021-05-04 18:24 UTC, v-jizhang requested changes
Change requested: Please remove the lines
```
        //manual initial num_nulls
        stats.setNumNulls(-1);
```

2021-10-04 18:25 UTC, rohanpednekar commented
@zybing  Hi, are you still working on this or it's ready for review, Do you think you can incorporate review feedback and pass these checks so that we can get reviewed. Thanks, Rohan

2022-05-10 06:12 UTC, zybing commented
> @zybing Hope all is well with you. Just checking in to see if you are still planning to work on this PR?



> @zybing Hope all is well with you. Just checking in to see if you are still planning to work on this PR?

thanks for the reminder,  I found this problem has been solved in the PR. https://github.com/prestodb/presto/pull/16376. so, we can close this PR.

2023-11-14 14:30 UTC, closed without merging