Use searchInterruptible for Joni regexp matching
prestodb/presto pull request #16109
Opened 2021-05-17 20:24 UTC by kaikalur

Joni regexp search can be very slow. This can cause runaway splits issue. So we use the searchInterruptible method so it can be interrupted in such cases.

Test plan - Non

```
== NO RELEASE NOTE ==
```

2021-05-17 20:39 UTC, aweisberg requested changes
I tested this change from `TaskExecutor` and it seems to work reasonably well. I did find that it doesn't check interrupt on some regexes.

2021-05-17 20:39 UTC, aweisberg commented on presto-main/src/main/java/com/facebook/presto/operator/scalar/JoniRegexpFunctions.java
> +        try {
In my testing I noticed this. Would be helpful for this piece of knowledge to be available to anyone reading the code.
```suggestion
        try {
            // Joni is not guaranteed to detect that interrupt was set with simple expressions
```

2021-05-17 20:50 UTC, kaikalur commented
> I tested this change from `TaskExecutor` and it seems to work reasonably well. I did find that it doesn't check interrupt on some regexes.

Hmm - can you repro reliably? Maybe some other function handled it already before it came to Joni?

2021-05-17 23:00 UTC, aweisberg approved these changes
It not always detecting interrupt is fine I just noticed that its contract is not guaranteed to throw. This means there are cases where it will execute the regex without ever checking for interrupt.

So for example you could call `Thread.interrupt()`, then `searchInterruptible` and it will complete normally.

2021-05-17 23:01 UTC, aweisberg commented
Can you squash (fixup) the additional commit before it gets merged? Thanks!

2021-05-18 00:24 UTC, kaikalur commented
> Can you squash (fixup) the additional commit before it gets merged? Thanks!

Done

2021-05-19 02:50 UTC, aweisberg requested changes
See added comment.

2021-05-19 02:50 UTC, aweisberg commented on presto-main/src/main/java/com/facebook/presto/operator/scalar/JoniRegexpFunctions.java
> +    private static int getMatchingOffset(Matcher matcher, int at, int range, int option)
@highker suggested adding `Options.DEFAULT` directly here instead of passing it in since it is always the same.

2021-05-20 22:51 UTC, aweisberg approved these changes

2021-05-24 16:12 UTC, rschlussel approved these changes

2021-05-24 16:13 UTC, rschlussel commented
@kaikalur can you add to the test plan the manual testing you did that demonstrated that this was helpful.

2021-05-24 16:14 UTC, rschlussel commented
also, this should probablby get a release note, since it caused production issues.

2021-05-24 17:06 UTC, aweisberg commented
I tested this with https://github.com/prestodb/presto/pull/16111 on this query 20210518_201931_00000_y9r9j
In theory this should also help with query timeouts (wall, CPU) and cancellation.

2021-05-24 18:33 UTC, kaikalur commented
> @kaikalur can you add to the test plan the manual testing you did that demonstrated that this was helpful.

See Ariel's response below. He tested it.

2021-05-24 19:04 UTC, rschlussel commented
Just add a release note, and I'll merge this.

2021-05-24 19:59 UTC, kaikalur commented
> Just add a release note, and I'll merge this.

Done

2021-05-24 20:12 UTC, merged

2021-05-24 20:14 UTC, rschlussel commented
I updated the release note to be more focused on the impact of the change.  Feel free to fix it if it's not accurate.