Rename example.properties to example.properties.example
prestodb/presto pull request #16108
Opened 2021-05-17 19:27 UTC by berikv

Fresh installations of Presto fail because `example.properties` assumes it has access to a MySQL server on localhost. Rename `example.properties` such that is isn't used by default.

Test plan - Run the setup instructions from the project readme.  `presto-main/etc/function-namespace/example.properties`

```
== NO RELEASE NOTE ==
```

2021-05-18 21:03 UTC, aweisberg commented
@rongrong Doing this rename allows PrestoServe to start up using the instructions from in the README.

2021-05-18 21:03 UTC, aweisberg approved these changes

2021-05-19 15:14 UTC, aweisberg requested changes
The commit message needs to be shorter. Less than 50 characters so it isn't truncated by GH. https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests

2021-05-20 12:54 UTC, xumingming commented
+1 on this.

2021-05-24 20:01 UTC, closed without merging