Modification on toPartitionNamesAndValues() function
prestodb/presto pull request #16129
Opened 2021-05-20 01:50 UTC by jzzhaofb

Test plan 

- Tested the function through the testMaterializedDataPredicates() function in TestHiveMaterializedViewUtils.java

2021-05-20 16:25 UTC, jainxrohit commented
Can you please write few tests in the TestHiveUtils to verify it?

2021-05-20 17:19 UTC, jainxrohit commented
Commit messages should follow these guidelines (http://chris.beams.io/posts/git-commit/)

2021-05-20 17:56 UTC, jainxrohit requested changes
Please also squash all commits in to one commit.

2021-05-20 17:56 UTC, jainxrohit commented on presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/MetastoreUtil.java
> +        int len = partitionName.length();
Presto codebase guidelines recommends using complete names. Hence lets call it length.

2021-05-20 17:56 UTC, jainxrohit commented on presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/MetastoreUtil.java
> +            String key = partitionName.substring(keyStart,keyEnd);
use unescapePathName

2021-05-20 17:56 UTC, jainxrohit commented on presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/MetastoreUtil.java
> +            if(index >= len){
Replace it with checkState(index < len, "Invalid partition spec: " + partitionName);

2021-05-20 17:56 UTC, jainxrohit commented on presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/MetastoreUtil.java
> +        boolean invalidName = false;
Not required.

2021-05-20 17:56 UTC, jainxrohit commented on presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/MetastoreUtil.java
> +        if(invalidName){
Not required after using checkState

2021-05-20 17:57 UTC, jainxrohit commented
Use the commit message and PR title as
Implement efficient way to fetch partition name and values

2021-05-20 20:01 UTC, jainxrohit requested changes

2021-05-20 20:01 UTC, jainxrohit commented on presto-hive/src/test/java/com/facebook/presto/hive/TestHiveMaterializedViewUtils.java
> +    public void testMaterializedDataPredicatesWithSingleColumn()
By moving to TestHiveUtil, you can simplify many of these details.

2021-05-20 20:01 UTC, jainxrohit commented on presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/MetastoreUtil.java
>      {
Remove the TODO

2021-05-20 23:35 UTC, jainxrohit requested changes

2021-05-20 23:35 UTC, jainxrohit commented on presto-hive/src/test/java/com/facebook/presto/hive/TestHiveUtil.java
> +import static org.apache.hadoop.hive.common.FileUtils.unescapePathName;
remove unused imports. Make sure to build(mvn install) locally to verify.

2021-05-20 23:35 UTC, jainxrohit commented on presto-hive/src/test/java/com/facebook/presto/hive/TestHiveUtil.java
> +        assertTrue(equalMaps);
rather checking in the end, may we should assert it when the equal fails at first spot?

2021-05-21 00:27 UTC, jainxrohit requested changes

2021-05-21 00:27 UTC, jainxrohit commented on presto-hive/src/test/java/com/facebook/presto/hive/TestHiveUtil.java
> +            assertTrue(true);
This is redundant.

2021-05-21 00:30 UTC, jainxrohit requested changes

2021-05-21 00:30 UTC, jainxrohit commented on presto-hive/src/test/java/com/facebook/presto/hive/TestHiveUtil.java
> +            assertTrue(false);
replace this with 
`checkstate(actual.keySet().size() == expectedKeyList.size())`

Similarly at other place.

2021-05-21 17:34 UTC, jainxrohit approved these changes
LGTM

2021-05-21 17:36 UTC, highker approved these changes

2021-05-22 03:41 UTC, merged