Add PrestoConnection getProperties method to presto-jdbc
prestodb/presto pull request #16329
Opened 2021-06-24 15:23 UTC by imillan

Introduce a method to access PrestoConnection properties at runtime.
The usecase behind this request is described in issue #16320  

Addresses issue #16320 

Test plan 
- Run new test  in TestJdbcConnection
- mvn clean install  -rf :presto-jdbc
- Integration test used by loading the new driver and checking that method returns the properties used to open a presto connection
```
== RELEASE NOTES ==

PrestoConnection getProperties method inclusion
* Adds a method to get the properties used to open a presto conenction in runtime to allwo property reused during queryInterceptor implementations
```

2021-07-07 15:47 UTC, tdcmeehan requested changes

2021-07-07 15:47 UTC, tdcmeehan commented on presto-jdbc/src/main/java/com/facebook/presto/jdbc/PrestoConnection.java
> +    public Properties getConnectionProperties()
I would make a defensive copy here, search for examples on defensive copy for Properties objects.

2021-07-08 14:09 UTC, tdcmeehan reviewed
Small nit.  Also be sure to squash commits

2021-07-08 14:09 UTC, tdcmeehan commented on presto-jdbc/src/main/java/com/facebook/presto/jdbc/PrestoConnection.java
> +        for (Map.Entry<Object, Object> entry : this.connectionProperties.entrySet()) {
Small nit: 

```suggestion
        for (Map.Entry<Object, Object> entry : connectionProperties.entrySet()) {
```

2021-07-20 22:01 UTC, imillan commented
@tdcmeehan  I worked on the suggested nit and submitted a new request for review. thx

2021-07-21 04:07 UTC, tdcmeehan approved these changes

2021-07-21 04:07 UTC, merged

2021-07-30 00:22 UTC, ajaygeorge commented
@imillan 
Can you please format the Release notes as described by the guidelines [here](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) . The current one does not mention what type of change it is and has typos.

cc @tdcmeehan

2021-07-30 08:50 UTC, imillan commented
@ajaygeorge 
I reformatted the release notes. Let me know if something else is required.