support oracle udf remainder in presto
prestodb/presto pull request #16355
Opened 2021-06-29 12:12 UTC by shenh062326

Test plan - (Please fill in how you tested your changes)

Please make sure your submission complies with our [Development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [Formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), and [Commit Message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests) guidelines. Don't forget to follow our [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution) for any code copied from other projects.

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2021-06-29 21:51 UTC, rongrong requested changes
Thanks for contributing. Please add unit tests in `TestMathFunctions` and documentation in `math.rst`. Thanks!

2021-07-04 14:29 UTC, shenh062326 commented
> Thanks for contributing. Please add unit tests in `TestMathFunctions` and documentation in `math.rst`. Thanks!

Done.

2021-07-27 20:35 UTC, tdcmeehan commented on presto-docs/src/main/sphinx/functions/math.rst
> +    Like oracle remainder, it returns the modulus (remainder) of m - (n * Math.round(m / n)).
```suggestion
    Returns the modulus (remainder) of m - (n * Math.round(m / n)).
```

2021-07-27 20:35 UTC, tdcmeehan commented on presto-main/src/test/java/com/facebook/presto/operator/scalar/TestMathFunctions.java
> +                float fl = (float) left;
Call these floatLeft and floatRight for consistency.

2022-04-16 17:11 UTC, closed without merging