Mv filter containment
prestodb/presto pull request #16361
Opened 2021-06-30 14:30 UTC by jzzhaofb

Add filter containment testcases

2021-07-08 02:55 UTC, jainxrohit commented on presto-main/src/main/java/com/facebook/presto/sql/analyzer/MaterializedViewQueryOptimizer.java
> +    private boolean isRewritable = true;
We can handle this via exceptions. no need to maintain the state.

2021-07-08 02:57 UTC, jainxrohit commented on presto-main/src/main/java/com/facebook/presto/sql/analyzer/MaterializedViewQueryOptimizer.java
> +            if (!node.getFrom().isPresent() || !(node.getFrom().get() instanceof Table)) {
The first check is redundant?

2021-07-08 03:46 UTC, jainxrohit requested changes
I tried the test case however it did not work. Not sure if some changes are pending from your side.

2021-07-27 05:07 UTC, jainxrohit requested changes

2021-07-27 05:07 UTC, jainxrohit commented on presto-main/src/main/java/com/facebook/presto/sql/analyzer/MaterializedViewQueryOptimizer.java
> +            RowExpression rewriteLogicExpression = and(baseQueryWhereCondition, call("not", new FunctionResolution(metadata.getFunctionAndTypeManager()).notFunction(), materializedViewWhereCondition.
break in to multiple lines.

2021-07-27 05:07 UTC, jainxrohit commented on presto-main/src/main/java/com/facebook/presto/sql/analyzer/MaterializedViewQueryOptimizer.java
> +                throw new IllegalStateException("View filter condition does not contains base query's filter condition");
does not contain

2021-07-27 16:36 UTC, jainxrohit commented
Looks good at higher level, will check in more details. 
One thing I noticed is that there are many long lines, please make sure there are no lines longer than 200 chars.
@highker you can also check if there are any higher level issues.

2021-07-28 19:57 UTC, jainxrohit requested changes

2021-07-28 22:32 UTC, jainxrohit requested changes

2021-07-28 22:32 UTC, jainxrohit commented on presto-main/src/test/java/com/facebook/presto/sql/analyzer/TestMaterializedViewQueryOptimizer.java
> +        String originalViewSql = format("SELECT %s.a, %s.b FROM %s JOIN %s ON %s.c = %s.c",
keep format in separate line for cases when overall function is breaking into multiple lines

2021-07-28 22:32 UTC, jainxrohit commented on presto-main/src/test/java/com/facebook/presto/sql/analyzer/TestMaterializedViewQueryOptimizer.java
> +        originalViewSql = format("SELECT a, b, c FROM %s WHERE a = 5 OR a = 7", BASE_TABLE_1);
Seems like same as above test case.

2021-07-28 22:32 UTC, jainxrohit commented on presto-main/src/test/java/com/facebook/presto/sql/analyzer/TestMaterializedViewQueryOptimizer.java
> +        originalViewSql = format("SELECT a, b, c FROM %s WHERE a > 5 OR a < 7", BASE_TABLE_1);
May be lets have more realistic OR conditions in MV filter?

2021-07-28 22:53 UTC, jainxrohit commented on presto-main/src/test/java/com/facebook/presto/sql/analyzer/TestMaterializedViewQueryOptimizer.java
> +    // Valid case that does not work
Can we create an issue to track this?

2021-07-29 21:23 UTC, jainxrohit approved these changes
Can you please fix the commit and PR title as 

Add filter validation for query optimization

2021-07-30 15:33 UTC, jzzhaofb commented on presto-main/src/test/java/com/facebook/presto/sql/analyzer/TestMaterializedViewQueryOptimizer.java
> +    }
@highker CNFConversion does not work for some of the examples:

```
A : a = 5 AND b = 7 AND c = 9
B: a = 5 AND c = 9
A ^ ~ B : a = 5 AND b = 7 AND c = 9 AND (a <> 5 OR c <> 9)
```
In this case, domainTranslator will only evaluate the first half of the logic expression and leave (a <> 5 OR c <> 9) as the remainingExpression in the result.

2021-07-30 17:12 UTC, jainxrohit commented on presto-hive/src/test/java/com/facebook/presto/hive/TestHiveLogicalPlanner.java
> +    @Test(enabled = false)
We don't have metastore integration to fetch tables. This is enabled in this PR
https://github.com/prestodb/presto/pull/16462

2021-07-30 17:13 UTC, jainxrohit commented on presto-main/src/main/java/com/facebook/presto/sql/analyzer/MaterializedViewInformationExtractor.java
> +        materializedViewInfo.setWhereClause(node.getWhere());
It was handled in lower level before.

2021-07-30 21:21 UTC, yuanzhanhku approved these changes

2021-08-02 06:01 UTC, highker approved these changes

2021-08-02 06:01 UTC, highker commented on presto-main/src/main/java/com/facebook/presto/sql/analyzer/MaterializedViewQueryOptimizer.java
> +             */
- no need to add a java doc; comments are good enough
- can we also link the SAT solver ticket here?

2021-08-02 06:01 UTC, highker commented on presto-main/src/test/java/com/facebook/presto/sql/analyzer/TestMaterializedViewQueryOptimizer.java
> +    public void testFilterContainmentDNF()
don't call these DNFs. Spell them out DisjunctiveNormalForm

2021-08-02 06:01 UTC, highker commented on presto-main/src/test/java/com/facebook/presto/sql/analyzer/TestMaterializedViewQueryOptimizer.java
> +                "OR a = 5 AND b = 7 AND c = 6", VIEW);
Same; fix the formatting of these calls

2021-08-03 05:01 UTC, merged

2021-08-31 00:05 UTC, kaikalur commented
It will be good to make PR title more specific - that it's MV-related filter.