Add cache_enabled session property into hive
prestodb/presto pull request #16474
Opened 2021-07-23 19:43 UTC by BlueStalker

This PR adds cache_enabled session property into hive to control whether use Filesystem cache in the session level
```
== RELEASE NOTES ==

Hive Changes
* adds cache_enabled session property  to control whether use Filesystem cache
```

2021-07-29 19:09 UTC, BlueStalker commented
ping @apc999 @beinan

2021-07-29 19:12 UTC, BlueStalker commented
also, ping @shixuan-fan and @jainxrohit who seemed also been working on presto <-> alluxio  integration before.

2021-08-06 19:38 UTC, BlueStalker commented
any comments on this? @jainxrohit

2021-08-25 15:58 UTC, tdcmeehan commented
@BlueStalker can you please squash these commits?  Thank you!

2021-08-28 02:02 UTC, jainxrohit commented
> @BlueStalker overall looks good to me.
> One minor change: many lines with new changes are too long, lets break them in to multiple lines.

@BlueStalker Can you please fix this as well?

2021-08-30 07:12 UTC, highker commented on presto-hive/src/test/java/com/facebook/presto/hive/TestHivePartitionManager.java
> +                        new HiveClientConfig(), new OrcFileWriterConfig(), new ParquetFileWriterConfig(), new CacheConfig()).getSessionProperties()));
one param per line

2021-08-30 07:12 UTC, highker commented on presto-hive/src/test/java/com/facebook/presto/hive/TestHivePartitionManager.java
> +                new HiveClientConfig().setMaxBucketsForGroupedExecution(100), new OrcFileWriterConfig(), new ParquetFileWriterConfig(), new CacheConfig()).getSessionProperties());
same

2021-08-30 07:12 UTC, highker commented on presto-hive/src/test/java/com/facebook/presto/hive/TestHivePartitionManager.java
> +                new HiveClientConfig().setMaxBucketsForGroupedExecution(100), new OrcFileWriterConfig(), new ParquetFileWriterConfig(), new CacheConfig()).getSessionProperties());
same for all other places

2021-08-30 22:59 UTC, BlueStalker commented
> > @BlueStalker overall looks good to me.
> > One minor change: many lines with new changes are too long, lets break them in to multiple lines.
> 
> @BlueStalker Can you please fix this as well?

fixed

2021-08-30 23:47 UTC, jainxrohit requested changes

2021-08-30 23:47 UTC, jainxrohit commented on presto-hive/src/test/java/com/facebook/presto/hive/parquet/ParquetTester.java
> +    private static final TestingConnectorSession SESSION = new TestingConnectorSession(new HiveSessionProperties(HIVE_CLIENT_CONFIG, new OrcFileWriterConfig(), new ParquetFileWriterConfig(), new Cach
too long line, Lets break in to multi lines.

2021-08-30 23:47 UTC, jainxrohit commented on presto-hive/src/test/java/com/facebook/presto/hive/parquet/ParquetTester.java
> +        ConnectorSession session = new TestingConnectorSession(new HiveSessionProperties(config, new OrcFileWriterConfig(), new ParquetFileWriterConfig(), new CacheConfig()).getSessionProperties());
too long line

2021-08-30 23:47 UTC, jainxrohit commented on presto-hive/src/test/java/com/facebook/presto/hive/parquet/ParquetTester.java
> +        ConnectorSession session = new TestingConnectorSession(new HiveSessionProperties(config, new OrcFileWriterConfig(), new ParquetFileWriterConfig(), new CacheConfig()).getSessionProperties());
too long line

2021-08-30 23:47 UTC, jainxrohit commented on presto-hive/src/test/java/com/facebook/presto/hive/statistics/TestMetastoreHiveStatisticsProvider.java
> +        TestingConnectorSession session = new TestingConnectorSession(new HiveSessionProperties(new HiveClientConfig(), new OrcFileWriterConfig(), new ParquetFileWriterConfig(), new CacheConfig()).ge
too long line

2021-08-30 23:47 UTC, jainxrohit commented on presto-hive/src/test/java/com/facebook/presto/hive/statistics/TestMetastoreHiveStatisticsProvider.java
> +        TestingConnectorSession session = new TestingConnectorSession(new HiveSessionProperties(new HiveClientConfig(), new OrcFileWriterConfig(), new ParquetFileWriterConfig(), new CacheConfig()).ge
too long line

2021-08-30 23:47 UTC, jainxrohit commented on presto-hive/src/test/java/com/facebook/presto/hive/statistics/TestMetastoreHiveStatisticsProvider.java
> +        TestingConnectorSession session = new TestingConnectorSession(new HiveSessionProperties(new HiveClientConfig(), new OrcFileWriterConfig(), new ParquetFileWriterConfig(), new CacheConfig()).ge
too long line

2021-08-30 23:47 UTC, jainxrohit commented on presto-hive/src/test/java/com/facebook/presto/hive/TestBackgroundHiveSplitLoader.java
> +                new HiveSessionProperties(new HiveClientConfig().setMaxSplitSize(new DataSize(1.0, GIGABYTE)), new OrcFileWriterConfig(), new ParquetFileWriterConfig(), new CacheConfig()).getSessionP
long line

2021-08-30 23:47 UTC, jainxrohit commented on presto-hive/src/test/java/com/facebook/presto/hive/TestHiveFileFormats.java
> +    private static TestingConnectorSession parquetPageSourceSession = new TestingConnectorSession(new HiveSessionProperties(createParquetHiveClientConfig(false), new OrcFileWriterConfig(), new Parque
long line

2021-08-30 23:47 UTC, jainxrohit commented on presto-hive/src/test/java/com/facebook/presto/hive/TestHiveFileFormats.java
> +                new HiveSessionProperties(new HiveClientConfig().setRcfileOptimizedWriterEnabled(true), new OrcFileWriterConfig(), new ParquetFileWriterConfig(), new CacheConfig()).getSessionProperti
long line

2021-08-30 23:47 UTC, jainxrohit commented on presto-hive/src/test/java/com/facebook/presto/hive/TestHiveFileFormats.java
> +                new HiveSessionProperties(new HiveClientConfig().setRcfileOptimizedWriterEnabled(true), new OrcFileWriterConfig(), new ParquetFileWriterConfig(), new CacheConfig()).getSessionProperti
long line

2021-08-30 23:47 UTC, jainxrohit commented on presto-hive/src/test/java/com/facebook/presto/hive/TestHiveFileFormats.java
> +        TestingConnectorSession session = new TestingConnectorSession(new HiveSessionProperties(new HiveClientConfig(), new OrcFileWriterConfig(), new ParquetFileWriterConfig(), new CacheConfig()).ge
long line

2021-09-01 17:14 UTC, yuanzhanhku approved these changes
Looks good. Thanks.

2021-09-01 21:47 UTC, merged