Ignore Hadoop marker files when reading from S3.
prestodb/presto pull request #16743
Opened 2021-09-15 16:19 UTC by sambekar15

Hadoop creates empty placeholders (which ends with $folder$) files during mkdir operation. More details here - https://aws.amazon.com/premiumsupport/knowledge-center/emr-s3-empty-files/ . Presto-Spark job fails as it expects the files to be parquet but this is an empty file
Solution is to ignore these files while reading objects from S3

Cherry-pick of  https://github.com/trinodb/trino/commit/d72622da2d04ec9ce56fe0a4e4772b548315cb2a

Co-authored-by: Alexander Jo  <jo.alex2144@gmail.com>

Test plan - 
Before Fix - Job failed with below error
```
com.facebook.presto.spi.PrestoException: s3://<s3Path>/year=2019/month=09/day=24/hour=20/part=0/part=0_$folder$ is not a valid Parquet File
at com.facebook.presto.hive.parquet.ParquetPageSourceFactory.createParquetPageSource(ParquetPageSourceFactory.java:315)
at com.facebook.presto.hive.parquet.ParquetPageSourceFactory.createPageSource(ParquetPageSourceFactory.java:172)
at com.facebook.presto.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:394)
at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:184)
at co

```
After fix - Job completes fine

Please make sure your submission complies with our [Development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [Formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), and [Commit Message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests) guidelines. Don't forget to follow our [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution) for any code copied from other projects.

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2021-09-15 16:25 UTC, sambekar15 commented
@v-jizhang  Please review this PR. I have closed the previous one https://github.com/prestodb/presto/pull/16701. Thanks

2021-09-17 22:15 UTC, v-jizhang requested changes
Any reason why this test is not ported? https://github.com/trinodb/trino/commit/d72622da2d04ec9ce56fe0a4e4772b548315cb2a#diff-81a5a4beb6be076226a4b338b568ba1c93fec4211ee513e4189982997c779aefR79

2021-09-23 15:57 UTC, sambekar15 commented
> Any reason why this test is not ported? [trinodb/trino@d72622d#diff-81a5a4beb6be076226a4b338b568ba1c93fec4211ee513e4189982997c779aefR79](https://github.com/trinodb/trino/commit/d72622da2d04ec9ce56fe0a4e4772b548315cb2a#diff-81a5a4beb6be076226a4b338b568ba1c93fec4211ee513e4189982997c779aefR79)

@v-jizhang Added missing tests

2021-09-23 21:14 UTC, v-jizhang approved these changes
LGTM. Thanks for your contribution!

2021-09-28 15:12 UTC, rohanpednekar commented
@yingsu00 Do you think you can merge this PR if it looks good to you?

2021-09-30 08:25 UTC, yingsu00 reviewed
@sambekar15 Thank you for the contribution! There're several minor issues:
1. Please squash the two commits into one. When back porting changes, we want to keep the original structure as much as possible for easy tracking.
2. The commit message needs to have the cherry pick and co-auther information. Example: https://github.com/prestodb/presto/pull/16704/commits/61d7022fd6d404f5e50278b26665f640360001dd  Guideline: https://github-wiki-see.page/m/prestodb/presto/wiki/Review-and-Commit-guidelines
3. The PR message needs to have cherry pick of the source PR: https://github.com/trinodb/trino/pull/4552
cc @v-jizhang

2021-10-11 22:33 UTC, sambekar15 commented
> @sambekar15 Thank you for the contribution! There're several minor issues:
> 
>     1. Please squash the two commits into one. When back porting changes, we want to keep the original structure as much as possible for easy tracking.
> 
>     2. The commit message needs to have the cherry pick and co-auther information. Example: [61d7022](https://github.com/prestodb/presto/commit/61d7022fd6d404f5e50278b26665f640360001dd)  Guideline: https://github-wiki-see.page/m/prestodb/presto/wiki/Review-and-Commit-guidelines
> 
>     3. The PR message needs to have cherry pick of the source PR: [trinodb/trino#4552](https://github.com/trinodb/trino/pull/4552)
>        cc @v-jizhang

@yingsu00
I have taken care of the above things. Can you please check if it looks ok to you. Thanks.

2021-11-05 21:27 UTC, sambekar15 commented
> @sambekar15 thanks for the update. I saw the commit message content was duplicated twice, could you fix it please? Also, in the commit message it's better to refer to the original "commit" not "PR" number.

@yingsu00  I have taken care of the above . Could you please review again. Thanks

2021-11-06 00:15 UTC, yingsu00 approved these changes
LGTM

2021-11-06 00:15 UTC, merged