document null vs nan
prestodb/presto pull request #16750
Opened 2021-09-17 00:12 UTC by mdavis-xyz

Fixes #16739

This clarifies in the docs that NaN and NULL are different.

I'm not sure whether the text should say `nan()` or `NaN`.

2021-09-17 00:13 UTC, mdavis-xyz commented
@rohanpednekar

2021-09-17 00:19 UTC, mdavis-xyz commented
Oh this is one of those projects that require a Linux Foundation CLA.
Ok, it's going to take me a while to get that signed. (More effort than it took to write the PR.)

2021-09-22 02:22 UTC, mdavis-xyz commented
Ok, CLA signed. How do I re-trigger the CI bot to run the usual workflow tests?

2021-09-23 21:03 UTC, v-jizhang requested changes

2021-09-23 21:03 UTC, v-jizhang commented on presto-docs/src/main/sphinx/functions/math.rst
> +    ``is_nan(NULL)`` returns ``false``.
is_nan(NULL) returns NULL.
```
presto> select is_nan(NULL);
 _col0 
-------
 NULL  
(1 row)
```

2021-09-23 23:11 UTC, mdavis-xyz commented
Apparently the bots want me to sign *two* CLAs. Corporate and individual. This is getting ridiculous.

And how do I retrigger the CLA CI bot now, to let me through?

2021-09-28 15:10 UTC, rohanpednekar commented
Sorry @mdavis-xyz for the confusion. 
@aweisberg do you think you can help here?

2021-09-28 15:12 UTC, rohanpednekar commented
@yingsu00 Do you think you can merge this PR if it looks good to you?

2021-09-28 15:41 UTC, aweisberg commented
The CLA bot only checks that the CLA has been signed when the PR changes. If you force push it will recheck. I can do that for you.

2021-09-28 15:46 UTC, aweisberg commented
It's still not approving. What email and github ID did you use when signing the CLA? The email on the commit has to be linked to the GH accounted you signed the CLA with so the bot can verify the commit is from that GH account.

2021-11-11 04:50 UTC, mdavis-xyz commented
I can't figure it out. 

I've whitelisted my github user, and email address. I've rewritten the commit username to be my work email address. Still it doesn't recognise me. I am a CLA manager for my org, so I can see the org settings for this repo.

The link to raise a support ticket with LF doesn't work. That login page for their Jira just redirects me back to the login page after I've logged in.

2021-11-11 15:17 UTC, aweisberg commented
There seem to be two github accounts in play here? `mdavis-xyz` is the one you are commenting with and the commit is attributed to `matt-telstra`. Is there any possibility that this is contributing to the mix up?

2021-11-11 22:55 UTC, mdavis-xyz commented
It was initially all `mdavis-xyz`, and I whitelisted that username in my org's CLF settings. But that didn't work. So I amended the commits to use my work email address instead of my normal email address for github, which github now recognises as my other github user. Both email addresses and both github usernames are whitelisted in my org's settings.

I just tried creating PR #16980, which is identical in content, but the PR creator and commit author are both the other one (matt-telstra). Still I'm getting the same error.

2021-11-11 23:23 UTC, aweisberg commented
So unfortunately I don't have any tools to help debug this. I don't think there is any sort of admin panel for anyone on the project.

What the CLA bot is looking for as far as I can tell is a github account linked to the email on the commit that has signed the CLA. It only notices when you have signed after you update the PR and it rechecks. The only other trick is it pops up a box telling you to click through the UI and accept as an individual or something after you have been added to the allow list for your company.

I don't actually go through the process myself, so I don't know what the exact steps look like, but once you get through them it really does work.

I will say I have had instances where I added people for the company CLA and then they disappeared from the UI on reload. Retrying eventually worked.

2021-11-15 00:25 UTC, matt-telstra commented
Ok the CLA bot is working now in #16980.

2022-01-18 01:59 UTC, matt-telstra commented
What's the status of this PR now?

The CLA bot says it's working.

2022-01-18 02:00 UTC, matt-telstra commented
Ah woops, I got confused after the holiday.

I'll close this, replaced by #16980

2023-02-20 22:14 UTC, mdavis-xyz commented
Closing this PR because it's a duplicate of #16980. Although that one is still stuck because of CLA issues.

2023-02-20 22:14 UTC, closed without merging