Document TDigest functions and type
prestodb/presto pull request #16911
Opened 2021-10-26 00:21 UTC by amellnik

This adds documentation for the t-digest type (#15674), similar to what
already exists for the QDigest type. The t-digest library was added in
#12961 and functions to use it were added in #13940.

Test plan - Documentation changes only, manual inspection of output.

Open questions:

- [x]  This adds a separate rst file for the tdigest documentation, but it could be merged with the file for qdigest.
- [x]  There might be a better way to handle the fact that tdigest currently only support doubles (#16910).

```
== NO RELEASE NOTE ==
```

2021-10-31 20:06 UTC, amellnik commented on presto-docs/src/main/sphinx/language/types.rst
> +    numbers.
Updated as per suggestions. My takeaway from the linked paper as well as some testing  suggests that T-Digest offers better performance in general.  The main limitation is that it only supports DOUBLE at the moment.

2021-10-31 20:31 UTC, amellnik commented
Also rebased on upstream master, some automated tests are failing but they definitely appear unrelated.

2021-11-01 19:49 UTC, aweisberg requested changes
This is excellent. Please fix the two typos and then I will approve.

2021-11-01 19:49 UTC, aweisberg commented on presto-docs/src/main/sphinx/functions/qdigest.rst
> +implementation of quantile digests supports more numberic types.
```suggestion
implementation of quantile digests supports more numeric types.
```

2021-11-01 19:49 UTC, aweisberg commented on presto-docs/src/main/sphinx/functions/tdigest.rst
> +implementation of quantile digests supports more numberic types.
```suggestion
implementation of quantile digests supports more numeric types.
```

2021-11-02 04:58 UTC, agrawalreetika approved these changes

2021-11-03 15:33 UTC, aweisberg approved these changes

2021-11-04 18:56 UTC, highker commented
@tdcmeehan wanna take a look? It's tdigest related

2021-11-05 00:45 UTC, tdcmeehan requested changes
Thanks for adding this!  Just some minor changes requested. 😄

2021-11-05 00:45 UTC, tdcmeehan commented on presto-docs/src/main/sphinx/functions/tdigest.rst
> +The presto type for this data structure is called :ref:`tdigest <tdigest_type>`,
```suggestion
The Presto type for this data structure is called :ref:`tdigest <tdigest_type>`,
```

2021-11-05 00:45 UTC, tdcmeehan commented on presto-docs/src/main/sphinx/functions/tdigest.rst
> +    Returns the approximate percentile values from the t-digest given the
Please make sure we consistently capitalize the T.

```suggestion
    Returns the approximate percentile values from the t-digest given the
```

2021-11-05 00:45 UTC, tdcmeehan commented on presto-docs/src/main/sphinx/functions/tdigest.rst
> +    Returns the raw ``tdigest`` data structure in the form of its component
```suggestion
    Returns a row that represents a ``tdigest`` data structure in the form of its component
```

2021-11-05 00:45 UTC, tdcmeehan commented on presto-docs/src/main/sphinx/functions/tdigest.rst
> +implementation of quantile digests supports more numeric types.
In these headers, I would also mention:

*) T-Digest has better accuracy at the tails, often dramatically better, but may have worse accuracy at the median, depending on the compression factor used.  In comparison, Q-Digest supports a maximum rank error, which guarantees relative uniformity of precision along the quantiles.
*) T-Digest is empirically proven to support lossless merge, although this is not formally proven.

2021-11-23 14:29 UTC, amellnik commented
@tdcmeehan Just following up, let me know if there's anything else needed here.  Thanks!

2021-11-24 14:47 UTC, tdcmeehan approved these changes

2021-11-24 14:47 UTC, tdcmeehan commented
@amellnik commit message looks incomplete? 

> This adds documentation for the t-digest type (prestodb#15674), similar to what
> already exists for the QDigest type. The t-digest library was added in

2021-11-30 03:33 UTC, amellnik commented
@tdcmeehan Not sure what happened there, but it's now fixed!

2021-12-08 20:34 UTC, amellnik commented
@highker Any feedback or is this good to go?

2021-12-16 21:17 UTC, highker approved these changes

2021-12-16 21:18 UTC, merged

2022-02-15 22:51 UTC, mbasmanova commented on presto-docs/src/main/sphinx/functions/tdigest.rst
> +    the per-item weight ``w`` and maximum error of ``accuracy``. ``accuracy``
Looking at the implementation, it seems this description of the accuracy parameter is in correct. This appears to be the "compression factor" parameter instead. CC: @tdcmeehan @aweisberg