clickhouse connector(initial version) commit
prestodb/presto pull request #17037
Opened 2021-11-25 12:35 UTC by ellison840611

```
== RELEASE NOTES ==

General Changes
* Developed a new presto connector for clickhouse
* Passed the official 440 test cases

```

2021-11-26 03:20 UTC, ellison840611 commented
@zhenxiao Could you please help me review the code?

2022-01-28 11:45 UTC, zhenxiao requested changes
nice work, @ellison840611 
left some comments. could you please rebased on top of current master? and squash all commits into one?

2022-01-28 11:45 UTC, zhenxiao commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/ClickHouseClient.java
> +        StringBuilder sb = new StringBuilder()
s/sb/builder/g

2022-01-28 11:45 UTC, zhenxiao commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/ClickHouseClient.java
> +        String vars = Joiner.on(',').join(nCopies(handle.getColumnNames().size(), "?"));
s/vars/columns/g

2022-01-28 11:45 UTC, zhenxiao commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/ClickHouseClient.java
> +                            //"datasets",
if `"datasets"`is the comment for null, let's keep it in the same line

2022-01-28 11:45 UTC, zhenxiao commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/ClickHouseClient.java
> +        StringBuilder sb = new StringBuilder();
s/sb/builder/g

2022-01-28 11:45 UTC, zhenxiao commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/ClickHouseClient.java
> +        return "tmp_presto_" + UUID.randomUUID().toString().replace("-", "");
shall we make `tmp_presto_` a constant? or make it configurable? so that it could be easy to clean up

2022-01-28 11:45 UTC, zhenxiao commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/ClickHouseClient.java
> +            PrestoException exception = new PrestoException(JDBC_ERROR, e);
throw new PrestoException(JDBC_ERROR, "Query: " + sql, e);

2022-01-28 11:45 UTC, zhenxiao commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/ClickHouseClient.java
> +    private String toWriteMapping(Type type)
`toWriteMapping` is used twice in the same function. Would be nice to inline it. We could consider keeping a map, and just make a call?

2022-01-28 11:45 UTC, zhenxiao commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/ClickHouseConfig.java
> +    @Config("connection-url")
`clickhouse.connection-url`

2022-01-28 11:45 UTC, zhenxiao commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/ClickHouseConfig.java
> +    @Config("connection-user")
`clickhouse.connection-user` same for all configurations, let's add connector prefix

2022-01-28 11:45 UTC, zhenxiao commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/ClickHouseConfig.java
> +    @Config("case-insensitive-name-matching")
`clickhouse.case-sensitive-enabled`

2022-01-28 11:45 UTC, zhenxiao commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/ClickHouseEngineType.java
> +    STRIPELOG("StripeLog"),
I think ClickHouse has many other engine types, shall we include them all? Or, we could consider static import from clickhouse code

2022-01-28 11:45 UTC, zhenxiao commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/ClickHouseErrorCode.java
> +    JDBC_ERROR(0, EXTERNAL),
I think we need fine granularity errors for clickhouse. It is fine we leverage JDBC as a first step. Let's add TODO for more error processing

2022-01-28 11:45 UTC, zhenxiao commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/ClickHouseMetadataConfig.java
> +    @Config("allow-drop-table")
how about we merge `ClickHouseMetadataConfig` into `ClickhouseConfig`?
`clickhouse.allow-drop-table`

2022-01-28 11:45 UTC, zhenxiao commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/ClickHouseModule.java
> +        //binder.bind(ClickHouseTableProperties.class).in(Scopes.SINGLETON);
let's remove this line?

2022-01-28 11:45 UTC, zhenxiao commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/ClickHouseTableProperties.java
> +    public static final String ORDER_BY_PROPERTY = "order_by"; //required
is it possible to import these constants from clickhouse code?

2022-01-28 11:45 UTC, zhenxiao commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/QueryBuilder.java
> +            if (typeAndValue.getType().equals(BigintType.BIGINT)) {
static import BigintType.BIGINT
and for all type names

2022-01-28 11:45 UTC, zhenxiao commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/ReadFunction.java
> +    // This should be considered to have a method as below (it doesn't to avoid autoboxing)
shall we keep the read function?

2022-04-06 07:38 UTC, ellison840611 commented
to be continued in: https://github.com/prestodb/presto/pull/17596

2022-04-06 07:38 UTC, closed without merging