Cardinality map optimization
prestodb/presto pull request #17191
Opened 2022-01-15 22:40 UTC by nlaptev

A simple sql to sql rewrite to transform Cardinality(Map_Values(map)) into Cardinality(map)

Test plan - Created a new set of tests for this query rewrite

== NO RELEASE NOTE ==

2022-01-16 22:41 UTC, kaikalur requested changes

2022-01-16 22:41 UTC, kaikalur commented on presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/SimplifyCardinalityMapRewriter.java
> +                        ((FunctionCall) argument).getArguments().size() > 0) {
map_keys should also be the same

2022-01-17 20:34 UTC, nlaptev commented on presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/SimplifyCardinalityMapRewriter.java
> +                        ((FunctionCall) argument).getArguments().size() > 0) {
Agreed.

2022-01-17 23:43 UTC, kaikalur commented
Please squash the commits.

2022-01-18 15:43 UTC, closed without merging