Add requirements for Prometheus connector
prestodb/presto pull request #17207
Opened 2022-01-19 17:46 UTC by v-jizhang

Cherry-pick of https://github.com/trinodb/trino/pull/8424
Add a standardized requirements to the Prometheus connector page.

Co-authored-by: Joe Lodin <joe.lodin@starburstdata.com>

```
== RELEASE NOTES ==

General Changes
* Add requirements for Prometheus connector

```

2022-01-19 18:18 UTC, mayankgarg1990 requested changes
You don't need any release notes for this PR . You can just say - 

```
== NO RELEASE NOTES ==
```

2022-01-19 18:18 UTC, mayankgarg1990 commented on presto-docs/src/main/sphinx/connector/prometheus.rst
> +  server. The default port is 9090.
```
``9090``
```

2022-01-19 18:42 UTC, v-jizhang commented
> You don't need any release notes for this PR . You can just say -
> 
> ```
> == NO RELEASE NOTES ==
> ```

Fixed. Thanks

2022-01-19 18:42 UTC, v-jizhang commented on presto-docs/src/main/sphinx/connector/prometheus.rst
> +  server. The default port is 9090.
Fixed. Thanks!

2022-01-19 18:59 UTC, mayankgarg1990 approved these changes

2024-07-08 18:35 UTC, steveburnett requested changes
Local doc build failed: 

ImportError: cannot import name 'environmentfilter' from 'jinja2' (/Users/steveburnett/Documents/GitHub/presto/presto-docs/presto-docs-venv/lib/python3.9/site-packages/jinja2/__init__.py)
make: *** [html] Error 1

git merge master, then the doc build ran successfully. 

Reviewed local doc build and the doc looks good. Update the PR and re-request my review.

2024-07-15 19:22 UTC, steveburnett commented
Closing due to lack of activity and age. If this is still relevant, please re-open this PR, rebase, and resolve any file conflicts.

2024-07-15 19:22 UTC, closed without merging