Add last_day_of_month function
prestodb/presto pull request #17219
Opened 2022-01-24 22:03 UTC by ericyuliu

Cherry-pick of https://github.com/trinodb/trino/commit/2718f1a9cb3eec1fef62e5571f966c7f7c1bdcea

Co-authored-by: Yuya Ebihara <ebyhry@gmail.com>
Co-authored-by: David Phillips <david@acz.org>

Test plan
testLastDayOfMonth is cherry-picked into base class, and can be tested from derived classes.

2022-01-25 17:23 UTC, aweisberg commented
First random comment, this does need a release note because it adds use visible changes.

2022-01-25 17:34 UTC, aweisberg requested changes
I think this operates slightly different in master on Trino because we are missing some important fixes https://github.com/trinodb/trino/commit/07d2758920ad74d15508918d94e4a2fcd0d7db68

See https://github.com/trinodb/trino/issues/2452

2022-01-26 18:17 UTC, aweisberg approved these changes
LGTM, thank you!

2022-01-27 18:31 UTC, highker approved these changes

2022-01-27 18:32 UTC, merged