Skip synthetic members to enable code coverage
prestodb/presto pull request #17273
Opened 2022-02-09 10:47 UTC by g1y

Code coverage will add synthetic members to classes that has been
causing issues for getting tests to run with code coverage
enabled. Skipping or ignoring these members is the fix.

Test plan - (Please fill in how you tested your changes)
```
 mvn clean install -pl presto-common  -pl presto-main -DfailIfNoTests=false
```

```
== NO RELEASE NOTE ==
```

2022-02-09 21:29 UTC, mayankgarg1990 requested changes

2022-02-09 21:29 UTC, mayankgarg1990 commented on presto-common/src/main/java/com/facebook/presto/common/block/BlockBuilderStatus.java
> +    private static int deepInstanceSize(Class<?> clazz, String name)
this was for debugging the issue - remove the `name` argument

2022-02-17 00:50 UTC, g1y commented on presto-common/src/main/java/com/facebook/presto/common/block/BlockBuilderStatus.java
> +            throw new IllegalArgumentException(format("Cannot determine size of %s %s because it contains an array", clazz.getSimpleName()));
forgot this %s. I'll remove it

2022-02-23 01:34 UTC, highker approved these changes

2022-02-23 01:34 UTC, highker commented on presto-common/src/main/java/com/facebook/presto/common/block/BlockBuilderStatus.java
>                  size += deepInstanceSize(field.getType());
Can we add a comment here to indicate `isSynthetic` is only used for code coverage?

2022-02-23 17:22 UTC, merged