Detect the scalar subqueries for unnest in statement analyzer
prestodb/presto pull request #17344
Opened 2022-02-23 22:49 UTC by tenpercent

The query fails at planning stage due to illegal state:
```
presto:sf1> select * from (select 1) cross join unnest((select array[1])) AS T(x);
Query 20220223_215553_00017_e3qbq failed: Unexpected subquery expression in logical plan: (SELECT ARRAY[1]

)
java.lang.IllegalStateException: Unexpected subquery expression in logical plan: (SELECT ARRAY[1]

)

```
The fix is to detect nested scalar query at the query analysis stage.
The result will look like:

```
presto:sf1> select * from (select 1) cross join unnest((select array[1])) AS T(x);
Query 20220223_223750_00025_uy3s2 failed: Unnested expression is a scalar subquery: (SELECT ARRAY[1]

)
com.facebook.presto.spi.PrestoException: Unnested expression is a scalar subquery: (SELECT ARRAY[1]

)

```

Signed-off-by: Maksim Dmitriyevich Podkorytov <maxdp@fb.com>

Test plan - run the query in presto-cli

```
== NO RELEASE NOTE ==
```

2022-02-23 23:20 UTC, kaikalur commented
Please add tests and also make sure it works properly when the scalar subquery is a select item - like:

select (select array[1,2] a) a from T cross join unnest(a)

2022-02-24 19:52 UTC, kaikalur commented on presto-main/src/test/java/com/facebook/presto/sql/analyzer/TestAnalyzer.java
> +        assertFails(NOT_SUPPORTED, "SELECT * FROM (SELECT 1) CROSS JOIN UNNEST((SELECT array[1])) AS T(x)");
Also check that the error message has the correct line/col/text using regexp match

2022-02-24 22:34 UTC, kaikalur requested changes

2022-02-24 22:34 UTC, kaikalur commented on presto-main/src/test/java/com/facebook/presto/sql/analyzer/TestAnalyzer.java
> +            expectedExceptionsMessageRegExp = "line 1:37: unnested expression is a scalar subquery")
A better message text:

Scalar subqueries in UNNEST are not yet supported

2022-02-24 23:04 UTC, kaikalur commented
Fix the build (style violations)

2022-02-25 05:20 UTC, jainxrohit commented
Change the commit message to
Handle the scalar subqueries for unnest

2022-02-25 05:37 UTC, jainxrohit commented
We can get rid of Test plan and Signed of by from the description, commit description.

2022-02-25 05:38 UTC, jainxrohit requested changes
Overall looks good, some cosmetic changes requested.

2022-02-25 05:38 UTC, jainxrohit commented on presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java
> +                            "Scalar subqueries in UNNEST are not yet supported");
I think we can get rid of word "yet"
Scalar subqueries in UNNEST are not supported

2022-02-25 18:46 UTC, jainxrohit commented
Last comment, can you please match the PR title as commit?

2022-02-25 18:46 UTC, jainxrohit approved these changes

2022-02-26 00:58 UTC, highker approved these changes

2022-02-26 00:58 UTC, highker commented on presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java
> +                    throw new SemanticException(NOT_SUPPORTED,
move `NOT_SUPPORTED` to its own line

2022-02-26 00:58 UTC, highker commented on presto-main/src/test/java/com/facebook/presto/sql/analyzer/TestAnalyzer.java
> +            expectedExceptionsMessageRegExp = "line 1:37: Scalar subqueries in UNNEST are not supported")
put into the same line

2022-02-28 17:42 UTC, kaikalur approved these changes

2022-02-28 17:52 UTC, tenpercent commented on presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java
> +                    throw new SemanticException(NOT_SUPPORTED,
done

2022-02-28 17:52 UTC, tenpercent commented on presto-main/src/test/java/com/facebook/presto/sql/analyzer/TestAnalyzer.java
> +            expectedExceptionsMessageRegExp = "line 1:37: Scalar subqueries in UNNEST are not supported")
done

2022-03-01 16:58 UTC, merged