clickhouse connector
prestodb/presto pull request #17596
Opened 2022-04-06 07:37 UTC by ellison840611

== RELEASE NOTES ==

General Changes
* Developed a new presto connector for clickhouse

2022-04-06 13:16 UTC, zhenxiao requested changes
looks nice, @ellison840611 
a few more comments

2022-04-06 13:16 UTC, zhenxiao commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/ClickHouseConfig.java
> +    @Config("clickhouse.case-insensitive-name-matching")
clickhouse.case-sensitive?

2022-04-06 13:16 UTC, zhenxiao commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/ClickHouseConfig.java
> +    public ClickHouseConfig setCaseInsensitiveNameMatchingCacheTtl(Duration caseInsensitiveNameMatchingCacheTtl)
clickhouse.remote-name-cache-ttl

2022-04-06 13:16 UTC, zhenxiao commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/ClickHouseConnectorFactory.java
> +                        //binder.bind(TypeManager.class).toInstance(context.getTypeManager());
let's remove this line

2022-04-06 13:16 UTC, zhenxiao commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/ClickHouseEngineType.java
> +    MERGETREE("MergeTree()"),
why MergeTree has `()`? could we import clickhouse engine type from clickhouse classes?

2022-04-06 13:16 UTC, zhenxiao commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/DriverConnectionFactory.java
> +    private final Optional<String> userCredentialName;
s/userCredentialName/userCredential/g

2022-04-06 13:16 UTC, zhenxiao commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/DriverConnectionFactory.java
> +    private final Optional<String> passwordCredentialName;
s/passwordCredentialName/passwordCredential/g

2022-04-06 13:16 UTC, zhenxiao commented on presto-clickhouse/src/test/java/com/facebook/presto/plugin/clickhouse/TestClickHouseConfig.java
> +                .put("clickhouse.connection-url", "jdbc:h2:mem:config")
let's fix all these properties names

2022-04-06 13:16 UTC, zhenxiao commented on presto-clickhouse/src/test/java/com/facebook/presto/plugin/clickhouse/TestClickHouseDistributedQueries.java
> +//        String createTableStatement = "CREATE TABLE " + catalog + ".tpch.test_not_null_with_insert (\n" +
let's remove all these commented code

2022-04-06 13:16 UTC, zhenxiao commented on presto-clickhouse/src/test/java/com/facebook/presto/plugin/clickhouse/TestClickHouseDistributedQueries.java
> +        //assertUpdate("ALTER TABLE test_not_null_with_insert ADD COLUMN column_c BIGINT NOT NULL");
remove commented code

2022-04-06 13:16 UTC, zhenxiao commented on presto-clickhouse/src/test/java/com/facebook/presto/plugin/clickhouse/TestClickHouseDistributedQueries.java
> +//
remove commented code

2022-04-06 13:16 UTC, zhenxiao commented on presto-docs/src/main/sphinx/connector/clickhouse.rst
> +`Yandex ClickHouse <https://clickhouse.tech/>`_ server. This can be used to
let's remove Yandex

2022-04-06 13:16 UTC, zhenxiao commented on presto-docs/src/main/sphinx/connector/clickhouse.rst
> +* Network access from the Trino coordinator and workers to the ClickHouse
s/Trino/Presto/g

2022-04-14 03:46 UTC, ellison840611 commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/ClickhouseDXLKeyWords.java
> +public class ClickhouseDXLKeyWords
thanks a lot for your review. On this issue, the information currently known is：clickhouse is written in c++, and no definition of such constants is found in the jdbc jar of clickhouse.

2022-04-24 08:07 UTC, zhenxiao approved these changes
@ellison840611 mostly good
a few minor things

2022-04-24 08:07 UTC, zhenxiao commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/ClickhouseDXLKeyWords.java
> +public class ClickhouseDXLKeyWords
get it. In this case, no need to import

2022-04-24 08:07 UTC, zhenxiao commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/ClickHouseConfig.java
> +    public ClickHouseConfig setPasswordCredentialName(String passwordCredentialName)
s/setPasswordCredentialName/setPasswordCredential/g

2022-04-24 08:07 UTC, zhenxiao commented on presto-clickhouse/src/main/java/com/facebook/presto/plugin/clickhouse/ClickHouseConfig.java
> +    @Config("clickhouse.user-credential-name")
s/setUserCredentialName/setUserCredential/g

2022-04-24 16:16 UTC, zhenxiao commented
hi @beinan @highker could you please take a look at Clickhouse connector? This PR looks good to me

2022-04-24 19:15 UTC, highker reviewed
@zhenxiao, I will pass the review given the connector change is pretty much contained. Feel free to merge if it looks good to you.

2022-04-25 15:50 UTC, merged