Add Thrift Support for ClusterStatsResource
prestodb/presto pull request #17636
Opened 2022-04-13 00:04 UTC by derek-xia

Adds thrift serde support for the getClusterStats endpoint.

Test plan - Unit tests

```
== NO RELEASE NOTE ==
```

2022-04-13 16:49 UTC, derek-xia commented
@ajaygeorge Picked this up as a bootcamp task, am I on the right track with the unit tests?

2022-04-13 22:02 UTC, ajaygeorge commented
@derek-xia Yes. Let me know if this PR is ready to be reviewed.

2022-04-13 22:07 UTC, derek-xia commented
I think this is ready for review.

2022-04-14 00:31 UTC, ajaygeorge commented on presto-tests/src/test/java/com/facebook/presto/server/TestClusterStatsResource.java
> +                    .setHeader("Accept", ThriftRequestUtils.APPLICATION_THRIFT_COMPACT)
you can use `ThriftRequestUtils.prepareThriftGet` which gives you a builder.
Also this just tests for one protocol and misses out on `APPLICATION_THRIFT_BINARY` and `APPLICATION_THRIFT_FB_COMPACT` . You can create enhance the

2022-04-14 00:32 UTC, ajaygeorge requested changes

2022-04-14 00:32 UTC, ajaygeorge commented on presto-tests/src/test/java/com/facebook/presto/server/TestClusterStatsResource.java
> +                    .setHeader("Accept", ThriftRequestUtils.APPLICATION_THRIFT_COMPACT)
you can use `ThriftRequestUtils.prepareThriftGet` which gives you a builder.
Also this just tests for one protocol and misses out on `APPLICATION_THRIFT_BINARY` and `APPLICATION_THRIFT_FB_COMPACT` . You can create enhance the data provider to add these types as well.

2022-04-14 17:55 UTC, ajaygeorge commented on presto-tests/src/test/java/com/facebook/presto/server/TestClusterStatsResource.java
> +            return client.execute(request, new ThriftResponseHandler<>(codecManager.getCodec(ClusterStatsResource.ClusterStats.class))).getValue();
static import for ClusterStatsResource.ClusterStats.class

2022-04-14 17:56 UTC, ajaygeorge approved these changes
LGTM % a comment

2022-04-15 21:19 UTC, derek-xia commented
Addressed the comment

2022-04-18 14:27 UTC, rschlussel approved these changes

2022-04-18 14:28 UTC, merged