Support casting of microsecond and nanosecond precision date time for…
prestodb/presto pull request #17689
Opened 2022-04-25 20:07 UTC by fengpengyuan

…mats to timestamp

Test plan - (Please fill in how you tested your changes)

Please make sure your submission complies with our [Development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [Formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), and [Commit Message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests) guidelines. Don't forget to follow our [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution) for any code copied from other projects.

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2022-04-27 22:03 UTC, prithvip requested changes
1) Please start the commit message with "Add support for..." and limit the commit title to 50 characters
2) Squash both commits into one commit 
3) Since this a user-visible feature, add a release note describing the change

2022-04-28 13:40 UTC, fengpengyuan commented on presto-main/src/main/java/com/facebook/presto/util/DateTimeUtils.java
> +                DateTimeFormat.forPattern("yyyy-MM-dd H:m:ss.SSSSSS").getParser(),
Yep, should be d and s.
updated.

2022-04-29 06:05 UTC, arunthirupathi commented
The change looks good.

Would this result in a perf regression for existing use cases as it tries new formats ?  I can think of error cases, will have more results to try before it fails, but want to confirm your thoughts.

Change the release note to 
support casting microseconds/nanoseconds to Timestamp type, though with precision loss to Milliseconds.

2022-04-29 16:10 UTC, arunthirupathi commented
Today in Presto, all the timestamps are stripped to Milliseconds at the converter layer, so the precision loss is ok. 

but after this change, some operators will have weird behavior. 

"cast('2001-1-22 03:04:05.321123' as timestamp)" = "cast('2001-1-22 03:04:05.321999' as timestamp)"

Since this is already happening other places at the connector, this precision loss is ok.

2022-04-29 16:11 UTC, arunthirupathi approved these changes

2022-05-01 08:15 UTC, prithvip approved these changes

2022-05-02 16:31 UTC, prithvip commented
@fengpengyuan Thank you very much for contributing this change. The code looks good to me, but could you please edit your initial comment to follow our release notes guidelines? https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines

2022-05-02 16:59 UTC, prithvip commented
@fengpengyuan Thank you for updating the release notes. @arunthirupathi Let's go ahead and merge this.

2022-05-02 18:57 UTC, merged