removed presto-geospatial module and moved the types and functions to presto-main
prestodb/presto pull request #17937
Opened 2022-06-24 12:41 UTC by pratyakshsharma

Test plan - (Please fill in how you tested your changes)

Please make sure your submission complies with our [Development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [Formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), and [Commit Message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests) guidelines. Don't forget to follow our [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution) for any code copied from other projects.

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2022-06-24 12:49 UTC, pratyakshsharma commented
@fgwang7w please take a look and add any relevant stakeholders.

cc @imjalpreet @agrawalreetika

2022-06-29 00:55 UTC, fgwang7w requested changes
Thank you for making the changes. Please merge all 4 commits into one. GeoQueryRunner is removed in this PR so it'd be better to include this note in a commit message to document that geospatial function is supported in mainline logic and does not need to include any geoplugin to enable the feature.

2022-06-29 00:55 UTC, fgwang7w commented on presto-main/src/main/java/com/facebook/presto/geospatial/SphericalGeoFunctions.java
> +        validateSphericalType("ST_Area", geometry, EnumSet.of(com.facebook.presto.geospatial.GeometryType.POLYGON, com.facebook.presto.geospatial.GeometryType.MULTI_POLYGON));
nit: use import static for POLYGON and MULTI_POLYGON members

2022-06-29 00:55 UTC, fgwang7w commented on presto-main/src/main/java/com/facebook/presto/geospatial/SphericalGeoFunctions.java
> +        validateSphericalType("ST_Length", geometry, EnumSet.of(com.facebook.presto.geospatial.GeometryType.LINE_STRING, com.facebook.presto.geospatial.GeometryType.MULTI_LINE_STRING));
nit: use import static instead

2022-06-29 00:55 UTC, fgwang7w commented on presto-main/src/main/java/com/facebook/presto/geospatial/SphericalGeoFunctions.java
> +        validateSphericalType("ST_Centroid", geometry, EnumSet.of(com.facebook.presto.geospatial.GeometryType.POINT, com.facebook.presto.geospatial.GeometryType.MULTI_POINT));
nit: use import static instead

2022-06-29 00:55 UTC, fgwang7w commented on presto-main/src/main/java/com/facebook/presto/server/testing/TestingPrestoServer.java
> +    public PluginManager getPluginManager()
who's the caller of this method? if no caller, please remove this public method

2022-06-29 00:55 UTC, fgwang7w commented on presto-main/src/main/java/com/facebook/presto/server/PluginManager.java
> +    public Metadata getMetadata()
who's the caller of this method? if no caller, pls remove this public method

2022-06-29 00:55 UTC, fgwang7w commented on presto-main/src/test/java/com/facebook/presto/geospatial/TestExtractSpatialInnerJoin.java
> +//        super(new GeoPlugin());
nit: remove this line

2022-06-29 00:55 UTC, fgwang7w commented on presto-main/src/test/java/com/facebook/presto/geospatial/TestExtractSpatialLeftJoin.java
> +//        super(new GeoPlugin());
nit: remove this line

2022-06-29 00:55 UTC, fgwang7w commented on presto-main/src/test/java/com/facebook/presto/geospatial/TestRewriteSpatialPartitioningAggregation.java
> +//        super(new GeoPlugin());
nit: remove this line

2022-06-29 00:55 UTC, fgwang7w commented on presto-memory/src/test/java/com/facebook/presto/plugin/memory/geospatial/BenchmarkGeometryAggregations.java
> +//            queryRunner.installPlugin(new GeoPlugin());
nit: remove this line

2022-06-29 00:55 UTC, fgwang7w commented on presto-memory/src/test/java/com/facebook/presto/plugin/memory/geospatial/BenchmarkSpatialJoin.java
> +//            queryRunner.installPlugin(new GeoPlugin());
nit: remove this line

2022-06-29 00:55 UTC, fgwang7w commented on presto-memory/src/test/java/com/facebook/presto/plugin/memory/geospatial/TestSpatialJoinPlanning.java
> +//        queryRunner.installPlugin(new GeoPlugin());
nit: remove this line

2022-06-29 01:01 UTC, fgwang7w commented
Hi @zhenxiao I've given 1st pass of code review, please help review as well. 
Hi @tdcmeehan This is a straight forward lib moving from one module to `presto-main`, I suppose there's a need to document the changes for release notes, any suggestion? Thanks

2022-06-30 11:05 UTC, pratyakshsharma commented on presto-main/src/main/java/com/facebook/presto/metadata/BuiltInTypeAndFunctionNamespaceManager.java
> +                .scalars(KdbTreeCasts.class) //TODO: check this
removed

2022-07-21 19:09 UTC, tdcmeehan approved these changes

2022-07-21 19:10 UTC, tdcmeehan commented
@pratyakshsharma please fix the merge conflicts, thanks!

2022-08-17 16:44 UTC, pratyakshsharma commented
fixed the merge conflicts. Verified the changes using `show functions;` command and by invoking few simple functions as in the attached screenshot
<img width="1051" alt="Screenshot 2022-08-17 at 10 11 45 PM" src="https://user-images.githubusercontent.com/30863489/185196151-3ae834ba-610c-4ae8-88e8-35821a143069.png">
.

2022-08-17 18:14 UTC, pratyakshsharma commented
@tdcmeehan let us merge this!

2022-08-17 20:44 UTC, merged

2022-08-25 20:27 UTC, pratyakshsharma commented
@arunthirupathi sure. Actually the user facing release notes are present in the commit message body. Providing them as below - 

1. presto-geospatial module has been removed and GeoPlugin class has been deleted. 
2. User does not need to do anything now to make use of presto's geospatial functions. All the functions are auto registered, one can simply start using them after starting the server. 

Does this look good?