Implement handling of pinot binary columns
prestodb/presto pull request #17977
Opened 2022-07-04 13:25 UTC by svkap

Test plan

* Have BigDecimal columns in Pinot table (saved as binary). 
* Make a select in Presto for the binary column in Pinot. 
* Test aggregation functions (e.g. sum) and the newly added Pinot UDF: pinot_binary_decimal_to_double. 

```
== RELEASE NOTES ==

General Changes
* Implement handling of Pinot binary columns
* Added Pinot UDF for transforming Pinot binary column to Double. UDF: 'pinot_binary_decimal_to_double'

Hive Changes
* n/a

2022-07-31 07:22 UTC, xiangfu0 reviewed
Overall lgtm, please revert the catalog changes for postgresql.properties.

2022-07-31 07:22 UTC, xiangfu0 commented on presto-pinot-toolkit/src/test/java/com/facebook/presto/pinot/TestPinotSegmentPageSource.java
> +                                // nothing to do here
just throw an exception here.

2022-09-08 03:24 UTC, tdcmeehan requested changes
One nit, otherwise LGTM

2022-09-08 03:24 UTC, tdcmeehan commented on presto-pinot/src/main/java/com/facebook/presto/pinot/udf/PinotFunctions.java
> +//        return Decimals.encodeScaledValue(new BigDecimal(new BigInteger(hex, (int) bigIntegerRadix),
Please remove the commented out code

2022-09-08 13:29 UTC, tdcmeehan approved these changes

2022-09-08 13:30 UTC, merged