Make logical property classes immutable
prestodb/presto pull request #18337
Opened 2022-09-13 17:57 UTC by nmahadevuni

Test plan - This PR only made the classes immutable. Existing tests work.

```
== NO RELEASE NOTE ==
```

2022-09-14 04:52 UTC, nmahadevuni commented
@rschlussel Can you please review this?

2022-09-16 16:00 UTC, rschlussel requested changes

2022-09-16 16:00 UTC, rschlussel commented on presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/properties/MaxCardProperty.java
> +    public static MaxCardProperty getUpdatedMaxCardProperty(MaxCardProperty thisMaxCardProperty, MaxCardProperty otherMaxCardProperty)
call this getMinMaxCardProperty

2022-09-23 13:29 UTC, nmahadevuni commented on presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/properties/KeyProperty.java
> +    public static Set<Key> combineKey(Set<Key> keys, Key newKey)
combineKey method is called in many places. Prefer not to merge these two methods.

2022-09-25 10:33 UTC, nmahadevuni commented on presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/properties/EquivalenceClassProperty.java
> +    public static RowExpression getEquivalenceClassHead(EquivalenceClassProperty thisEquivalenceClassProperty, RowExpression expression)
Changed all such methods back to class methods.

2022-09-25 10:35 UTC, nmahadevuni commented on presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/properties/EquivalenceClassProperty.java
>          //note that we do not check head1.equal(head2) so that two different variable reference objects
@simmend : Can you please respond here?

2022-10-04 21:11 UTC, pranjalssh commented on presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/properties/LogicalPropertiesImpl.java
> +            //keyProperty.addKeys(normalizedKeyProperty.get());
Remove comented code

2022-10-17 06:44 UTC, nmahadevuni commented on presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/properties/EquivalenceClassProperty.java
> +            ImmutableList.Builder<RowExpression> newExprs = ImmutableList.<RowExpression>builder()
This is already using ImmutableList.builder()

2022-10-17 09:24 UTC, nmahadevuni commented
@pranjalssh : Thank you. Addressed the comments. Please review.

2022-10-17 10:54 UTC, pranjalssh commented on presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/properties/EquivalenceClassProperty.java
> +            ImmutableList.Builder<RowExpression> newExprs = ImmutableList.<RowExpression>builder()
I mean you can just use ImmutableList.builder() instead of ImmutableList.<>builder(). See other examples in codebase

2022-10-17 12:03 UTC, nmahadevuni commented on presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/properties/EquivalenceClassProperty.java
> +            ImmutableList.Builder<RowExpression> newExprs = ImmutableList.<RowExpression>builder()
Ok. I made the change. Tests are running.

2022-10-19 04:50 UTC, pranjalssh approved these changes

2022-10-20 14:13 UTC, rschlussel approved these changes

2022-10-20 14:13 UTC, merged

2022-10-20 16:25 UTC, nmahadevuni commented
Thank you!