Allow overridding max revocable memory using 'query_max_revocable_mem…
prestodb/presto pull request #18374
Opened 2022-09-20 19:41 UTC by amr-meta

Reads the session property `query_max_revocable_memory_per_node` and if it is null, falls back to config property `experimental.max-revocable-memory-per-node` 

Test plan - Existing tests

```
== NO RELEASE NOTE ==
```

2022-09-21 19:47 UTC, pgupta2 requested changes

2022-09-21 20:58 UTC, amr-meta commented
Good callout, I missed the session property metadata defined here: https://github.com/prestodb/presto/blob/52400593df57097d606ff95208f3f330b50ac0eb/presto-main/src/main/java/com/facebook/presto/SystemSessionProperties.java#L726-L734.

From: Arjun Gupta ***@***.***>
Date: Wednesday, September 21, 2022 at 12:47
To: prestodb/presto ***@***.***>
Cc: Amr Elroumy ***@***.***>, Mention ***@***.***>
Subject: Re: [prestodb/presto] Allow overridding max revocable memory using 'query_max_revocable_mem… (PR #18374)
@pgupta2 requested changes on this pull request. In presto-spark-base/src/main/java/com/facebook/presto/spark/execution/PrestoSparkTaskExecutorFactory. java: > + DataSize maxRevocableMemory = getQueryMaxRevocableMemoryPerNode(session); +
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
ZjQcmQRYFpfptBannerEnd

@pgupta2 requested changes on this pull request.

________________________________

In presto-spark-base/src/main/java/com/facebook/presto/spark/execution/PrestoSparkTaskExecutorFactory.java<https://github.com/prestodb/presto/pull/18374#discussion_r976922851>:

> +        DataSize maxRevocableMemory = getQueryMaxRevocableMemoryPerNode(session);

+        if(maxRevocableMemory == null) {

+             maxRevocableMemory = this.maxRevocableMemory;

+        }

+

getQueryMaxRevocableMemoryPerNode(session); should automatically pick up corresponding config property experimental.max-revocable-memory-per-node, if session property is not defined. If you look into SystemSessionProperties.java class, you will see that default value for query_max_revocable_memory_per_node is configured to be value coming from experimental.max-revocable-memory-per-node

So, ideally the IF block is not needed here. We can also remove references to this.maxRevocableMemory in the code.

—
Reply to this email directly, view it on GitHub<https://github.com/prestodb/presto/pull/18374#pullrequestreview-1116002060>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A3DZ6USMWJJSMTHFIIP4F7DV7NQ5DANCNFSM6AAAAAAQRMRTIM>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-09-21 21:02 UTC, amr-meta commented on presto-spark-base/src/main/java/com/facebook/presto/spark/execution/PrestoSparkTaskExecutorFactory.java
> +
Good callout, I missed the session property metadata defined here: https://github.com/prestodb/presto/blob/52400593df57097d606ff95208f3f330b50ac0eb/presto-main/src/main/java/com/facebook/presto/SystemSessionProperties.java#L726-L734.

This should be resolved in the latest commit.

2022-09-23 03:42 UTC, pgupta2 approved these changes

2022-09-23 03:46 UTC, pgupta2 commented
@amr-meta : I have accepted the PR. Can you please fix the commit subject/body using following guidelines mentioned here: https://cbea.ms/git-commit/
1. Limit the subject line to 50 characters
2. Wrap the body at 72 characters

2022-09-23 18:22 UTC, highker approved these changes

2022-09-23 18:23 UTC, highker commented
- Can we squash the two commits into one?
- Also, as @pgupta2 mentioned, please cap the commit title within 72 characters.

2022-09-23 18:36 UTC, amr-meta commented
> * Can we squash the two commits into one?
> * Also, as @pgupta2 mentioned, please cap the commit title within 72 characters.

Done.

2022-09-24 05:23 UTC, merged