Fix broken "Function Namespace Managers" links
prestodb/presto pull request #18591
Opened 2022-10-31 18:08 UTC by devozerov

```
== NO RELEASE NOTE ==
```

2022-12-29 11:01 UTC, agrawalreetika approved these changes
LGTM

2022-12-29 11:01 UTC, agrawalreetika commented
@rohanpednekar this looks good to me for merge

2024-07-08 17:06 UTC, steveburnett requested changes
Thanks for the docs! 

1) 
Local doc build fails with
"Running Sphinx v4.4.0
Sphinx version error: The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version. make: *** [html] Error 2"
Related to PR #21708.
Ran git merge master, then the doc build ran successfully.

2. 
Reviewed local doc build, and fixed the links. Update the PR and re-request my review.

2024-07-08 17:06 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/function-namespace-managers.rst
> +:doc:`/sql/create-function`, :doc:`/sql/alter-function`, :doc:`/sql/drop-function`, :doc:`/sql/show-functions`
```suggestion
:doc:`../sql/create-function`, :doc:`../sql/alter-function`, :doc:`../sql/drop-function`, :doc:`../sql/show-functions`
```

2024-07-15 19:24 UTC, steveburnett commented
Closing due to lack of activity and age. If this is still relevant, please re-open this PR, rebase, and resolve any file conflicts.

2024-07-15 19:24 UTC, closed without merging