Fix bugs in duplicate items in UNNEST expression
prestodb/presto pull request #18909
Opened 2023-01-09 22:53 UTC by feilong-liu

### What's the change?

Current UNNEST node will fail if there are duplicate expressions in UNNEST, for example, query `SELECT * from (select * FROM (values 1) as t(k)) CROSS JOIN unnest(array[2, 3], ARRAY[2, 3]) AS r(r1, r2)`. This is because we use a map to store the mapping between expressions in UNNEST and output symbols. Duplicate expressions will produce the same key for the map.

In this PR, I add an intermediate projection node between the UNNEST node and it's source, to project the duplicate items into different variables, so as to avoid fail the query.

### Test plan - (Please fill in how you tested your changes)

Added unit test.

```
== RELEASE NOTES ==

General Changes
* Fix the bug where duplicate items in UNNEST leads to query compilation failure
```

2023-01-11 01:27 UTC, kaikalur requested changes
How about the Simple UNNEST. It seems to work OK but good to add test

SELET * from UNNEST(ARRAY[1,2], ARRAY[1,2])

2023-01-12 00:55 UTC, feilong-liu commented on presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java
> +    }
Test added.

2023-01-12 01:05 UTC, kaikalur requested changes

2023-01-12 01:05 UTC, kaikalur commented on presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java
> +                        unnestVariables.put(inputVariable, ImmutableList.of(unnestedVariablesIterator.next()));
See if you can refactor this part into a separate method - legacy on/off the only difference is single var vs. multiple should be easy to merge the two cases and create a method.

2023-01-12 01:05 UTC, kaikalur commented on presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java
> +        }
Move this into a separate method as well.

2023-01-12 02:50 UTC, kaikalur approved these changes
LGTM

2023-01-12 16:30 UTC, rschlussel reviewed
Why can't we just use a multimap instead?

2023-01-12 17:28 UTC, kaikalur commented
> Why can't we just use a multimap instead?

That was my first suggestion too :) except there is a canonicalize method that removes them further down.

2023-01-12 17:35 UTC, rschlussel commented
> > Why can't we just use a multimap instead?
> 
> That was my first suggestion too :) except there is a canonicalize method that removes them further down.

can you clarify this more? Would it make more sense to fix that to be able to support the duplicate entries.  Just seems weird to make plan choices based on the data structure representations we've chosen.

2023-01-12 17:50 UTC, kaikalur commented
> > > Why can't we just use a multimap instead?
> > 
> > 
> > That was my first suggestion too :) except there is a canonicalize method that removes them further down.
> 
> can you clarify this more? Would it make more sense to fix that to be able to support the duplicate entries? Just seems weird to make plan choices based on the data structure representations we've chosen.

The main thing is it's not done in a principled way - the output are just the map keys! They are relying on the fact that the Builder is adding in order which I'm not a big fan of. So yeah we could do a bigger change to have list of inputs and outputs explicitly but this one is actually also a small optimization as we unnest only one array :) and the change is self-contained (corner case too - only 2 failures in the last year+)

2023-01-12 17:59 UTC, rschlussel approved these changes
looks good. just the one nit.  
I'll note that this means that if you have any non-deterministic functions in the duplicates, they will get executed only once, but since we do that already in other cases, i don't think it's something to worry about.

2023-01-12 17:59 UTC, rschlussel commented on presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java
> +        if (!unnestOutputMappingBuilder.build().isEmpty()) {
nit: extract a variable for unnestOutputMappingBuilder so you don't build 2x.

2023-01-12 21:12 UTC, merged