Fix blocking resource groups when query queue full
prestodb/presto pull request #18910
Opened 2023-01-10 04:01 UTC by rmarduga

When Presto Coordinator cannot run query nor queue query, it fails the error. And Coordinator does it under root resource group lock. Failing query triggers query state change that in particular triggers event listener handler that could be expensive. Doing it under resource group lock essentially blocks the resource group and severely degrades performance.

Test plan - (Please fill in how you tested your changes)
I ran the coordinator without and with the change. Within 1 hour I sent around 61668 queries to the cluster. 1275 queries successfully executed. 60393 queries finished with the error. Around 75% of the queries failures were due to QUERY_QUEUE_FULL error.  I recorded the sessions with Java Flight Recorder. Picture below shows selected threads that were locked on RootInternalResourceGroup lock. 
![image](https://user-images.githubusercontent.com/25698333/211457915-ee28354f-e1fa-4a66-a37c-1db9ca8e2b05.png)

Here, the yellow blocks depict the thread waiting on the lock. 
The picture below demonstrate the same settings with applied this code change.
![image](https://user-images.githubusercontent.com/25698333/211457622-63aaf448-9402-4174-b8b0-f1dfeb5656d6.png)

Overall, the locking time for  RootInternalResourceGroup monitor type reduced from 3 hour 24 min to 1 min 11 sec and for InternalResourceGroupManager monitor type it reduced from 4 days 4 hour to 9 sec. 

Please make sure your submission complies with our [Development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [Formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), and [Commit Message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests) guidelines. Don't forget to follow our [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution) for any code copied from other projects.

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2023-01-11 00:40 UTC, swapsmagic approved these changes

2023-01-11 15:45 UTC, tdcmeehan requested changes

2023-01-11 15:45 UTC, tdcmeehan commented on presto-main/src/main/java/com/facebook/presto/execution/resourceGroups/InternalResourceGroup.java
> +        Boolean isQueryQueueFull = false;
```suggestion
        boolean isQueryQueueFull = false;
```

2023-01-18 15:44 UTC, tdcmeehan approved these changes

2023-01-18 15:45 UTC, merged