[native] BugFix: resize output partitions array correctly
prestodb/presto pull request #19118
Opened 2023-02-27 22:02 UTC by shrinidhijoshi

```
== NO RELEASE NOTE ==
```

2023-02-27 22:22 UTC, mbasmanova reviewed
@shrinidhijoshi Would you add a test that reproduces the problem?

2023-02-27 22:24 UTC, shrinidhijoshi commented
@mbasmanova  Yes. I can do that. Might take some time as I am new to C++ ecosystem :)

2023-02-27 22:25 UTC, spershin approved these changes
Looks good.

2023-02-27 22:37 UTC, mbasmanova commented
> @shrinidhijoshi Would you add a test that reproduces the problem?

That would be great. Let's make sure all changes come with tests going forward.

2023-02-28 01:33 UTC, v-jizhang commented
@prestobot kick off tests.

2023-02-28 08:39 UTC, mbasmanova requested changes
Let's add a test.

2023-03-13 22:12 UTC, shrinidhijoshi commented
@mbasmanova This has dropped from my radar. Added a test now. Please check

2023-03-14 11:21 UTC, mbasmanova reviewed
@shrinidhijoshi Thank you for adding a test. Looks good % commit message needs updating to explain the problem this change is addressing. 

> [native] BugFix : Resize output partitions array correctly

```
[native] Fix PartitionAndSerializeOperator when number of partitions is 1
```

BTW, is this a valid use case to use PartitionAndSerializeOperator with numPartitions == 1 ? Why would we want to do that?

2023-03-14 20:40 UTC, shrinidhijoshi commented
@mbasmanova Won't we need to serialize the rows (by calling UnsafeRowSerializer) even if partition count is 1 ? So that's the reason we still use PartitionAndSerialize operator

2023-03-14 20:44 UTC, mbasmanova commented
> @mbasmanova Won't we need to serialize the rows (by calling UnsafeRowSerializer) even if partition count is 1 ? So that's the reason we still use PartitionAndSerialize operator

I expect numPartitions == 1 to be true only for broadcast. In this case, I assume we do not use Cosco and serialize data into PrestoPage (columnar), not UnsafeRow (row-wise).

2023-03-14 20:51 UTC, shrinidhijoshi commented
Ah.. I see what you mean. But another use-case I encountered was global aggregations scenario, with partial aggregation enabled. This code change is actually targeted for this use-case.

2023-03-14 21:00 UTC, mbasmanova commented
> Ah.. I see what you mean. But another use-case I encountered where numPartitions==1 is global aggregations scenario, with partial aggregation enabled. This code change is actually targeted for this use-case.

Got it. Thank you for clarifying. Might be helpful to mention this in the commit message.

2023-03-14 21:24 UTC, shrinidhijoshi commented
@mbasmanova Done

2023-03-14 21:26 UTC, mbasmanova approved these changes
@shrinidhijoshi Thanks.

2023-03-15 01:25 UTC, tdcmeehan approved these changes

2023-03-15 01:25 UTC, merged