Add presto-native deps to gitignore
prestodb/presto pull request #19421
Opened 2023-04-18 02:16 UTC by pranjalssh

I got a bunch of presto-native related deps in my git changes after running make. We should add them to .gitignore

```
== NO RELEASE NOTE ==
```

2023-04-18 02:32 UTC, amitkdutta approved these changes
Thanks @pranjalssh

2023-04-18 16:29 UTC, majetideepak commented
We should fix `make` to not install them in the root directory. Do you know which make command is causing this?

2023-04-18 18:21 UTC, mbasmanova requested changes
@pranjalssh Please, check out @majetideepak 's comment.

2023-04-18 20:16 UTC, pranjalssh commented
Actually, this is coming from setup-macos.sh

https://github.com/prestodb/presto/blob/0786aa6aebde023063f63653f802295d797b7305/presto-native-execution/scripts/setup-macos.sh#L35

2023-04-18 20:27 UTC, pranjalssh commented
I can call it so that its in presto-native-execution/ directory. Is that ok @majetideepak

2023-04-19 08:42 UTC, majetideepak commented
@pranjalssh We mention creating a directory named `dependencies` in our README.  This directory need not exist in the Velox root. So we don't have to add anything to gitignore in my opinion. Git users should know how to work around an untracked file/directory if they create one.
https://github.com/prestodb/presto/tree/master/presto-native-execution#build-from-source

2023-04-19 17:12 UTC, closed without merging