Add a MapType test for checksum function
prestodb/presto pull request #19471
Opened 2023-04-25 18:05 UTC by v-jizhang

Add a MapType test for checksum function.

```
== NO RELEASE NOTE ==
```

2023-04-25 18:22 UTC, ericyuliu commented
LGTM.

2023-04-25 18:44 UTC, ericyuliu approved these changes
@v-jizhang 
testMap looks good, but when I compare with other tests, they are building the block with multiple items, such as  arrayType 
`createArrayBigintBlock(asList(null, asList(1L, 2L), asList(3L, 4L), asList(5L, 6L)));`

shall we extend that or add another test to cover that ( block with multiple maps) ?

2023-04-26 19:34 UTC, ericyuliu commented
Also, lets fix the bug in createMapBlock, where BIGINT is hardcoded, with dynamic type

2023-05-02 21:05 UTC, ericyuliu commented
LGTM, thanks for fixing the bug and adding more unit tests

2023-05-03 15:43 UTC, rschlussel approved these changes
Looks good.  All the tests in this class are a little funny as the expectedChecksum() function basically duplicates the logic from ChecksumAggregationFunction. But I guess they are valuable in that they ensure that the function generation for different types happens correctly.

2023-05-03 15:43 UTC, rschlussel commented on presto-main/src/test/java/com/facebook/presto/operator/aggregation/TestChecksumAggregation.java
> +        Block mutiMapBlock = fromKeyValueBlock(3, Optional.ofNullable(null), offsets, keyBlock, valueBlock);
typo: should say multiMapBlock (missing 'l' from "multi")

2023-05-03 16:24 UTC, rschlussel requested changes
requesting changes so i don't accidentally merge before the commits are squashed.

2023-05-03 23:22 UTC, rschlussel approved these changes

2023-05-04 16:40 UTC, v-jizhang commented
@prestobot kick off tests

2023-05-04 21:41 UTC, v-jizhang commented
@prestobot kick off tests.

2023-05-11 16:38 UTC, v-jizhang commented
@rschlussel Could this be merged? Thanks

2023-05-11 18:20 UTC, merged