[native] Disable failing tests in TaskManagerTest and PrestoExchangeSourceTest
prestodb/presto pull request #19549
Opened 2023-05-03 16:04 UTC by vermapratyush

```
== NO RELEASE NOTE ==
```

2023-05-03 16:05 UTC, vermapratyush commented
Create an issue for tracking https://github.com/prestodb/presto/issues/19550

2023-05-03 16:12 UTC, mbasmanova approved these changes
@vermapratyush Would you update the PR to mention the offending PR and a GitHub issue?

2023-05-03 16:14 UTC, mbasmanova commented
CC: @GuChangyang

2023-05-04 12:56 UTC, mbasmanova reviewed
CC: @xiaoxmeng

2023-05-04 14:02 UTC, mbasmanova commented on presto-native-execution/presto_cpp/main/tests/PrestoExchangeSourceTest.cpp
> -TEST_P(PrestoExchangeSourceTestSuite, exceedingMemoryCapacityForHttpResponse) {
I just ran this test on my laptop and it succeeded. Is the failure intermittent?

2023-05-04 14:03 UTC, mbasmanova commented on presto-native-execution/presto_cpp/main/types/tests/ValuesPipeTest.cpp
> -TEST_F(TestValues, valuesPlan) {
This test succeeds for me. Are you sure it is failing?

2023-05-04 14:04 UTC, mbasmanova requested changes
see comments

2023-05-04 14:12 UTC, vermapratyush commented on presto-native-execution/presto_cpp/main/tests/PrestoExchangeSourceTest.cpp
> -TEST_P(PrestoExchangeSourceTestSuite, exceedingMemoryCapacityForHttpResponse) {
This one seems to consistently fail on github CI.
Here is one of them: https://github.com/prestodb/presto/actions/runs/4881560698/jobs/8710612851?pr=19546

2023-05-04 14:12 UTC, vermapratyush commented on presto-native-execution/presto_cpp/main/types/tests/ValuesPipeTest.cpp
> -TEST_F(TestValues, valuesPlan) {
This one if flaky even on github CI. Unable to find the exact github CI link

2023-05-04 15:04 UTC, mbasmanova approved these changes
@vermapratyush Thanks.

2023-05-05 11:37 UTC, closed without merging