WIP: Log Presto-on-spark bootstrap time with breakdowns
prestodb/presto pull request #19703
Opened 2023-05-18 23:59 UTC by JasmineWeii

Test plan - (Please fill in how you tested your changes)

Please make sure your submission complies with our [Development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [Formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), and [Commit Message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests) guidelines. Don't forget to follow our [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution) for any code copied from other projects.

Fill in the release notes towards the bottom of the PR description.
See [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) for details.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2023-06-02 23:28 UTC, mbasmanova reviewed
@JasmineWeii Thank you for a nice PR description. Please, update the commit message as well to provide same level of detail.

Check out [How to Write Better Git Commit Messages – A Step-By-Step Guide](https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/) and [How to Write a Git Commit Message](https://cbea.ms/git-commit/) to learn more about how to write good commit messages.

2023-06-02 23:30 UTC, mbasmanova approved these changes
@JasmineWeii Nice, clean PR. I didn't read every line carefully though. Please, make sure to update commit message before merging.

2023-06-07 17:49 UTC, miaoever approved these changes
Thanks for the change @JasmineWeii , the PR looks good to me.

2023-06-07 18:23 UTC, mbasmanova requested changes
@JasmineWeii Please, update the commit message.

2023-06-07 19:27 UTC, JasmineWeii commented
> @JasmineWeii Please, update the commit message.



> @JasmineWeii Please, update the commit message.

2023-06-07 19:32 UTC, JasmineWeii commented
> @JasmineWeii Please, update the commit message.


Updated, took a while to figure out the Github UI, let me know if the message make sense!

2023-06-07 19:33 UTC, mbasmanova commented
@JasmineWeii Thanks. Please add [native pos] prefix to commit title and provide some details about the change in the commit message.

2023-06-07 21:17 UTC, mbasmanova approved these changes

2023-06-07 22:12 UTC, merged