[native] Update README with instructions for M1 mac
prestodb/presto pull request #19813
Opened 2023-06-07 08:34 UTC by imjalpreet

```
== NO RELEASE NOTE ==
```

2023-06-07 16:47 UTC, majetideepak requested changes
@imjalpreet Most of the updates here should be handled by the setup scripts.
Can you open an issue? We should fix this.

2023-06-07 16:47 UTC, majetideepak commented on presto-native-execution/README.md
> +CPU_TARGET="arm64" INSTALL_PREFIX="/opt/homebrew" ./scripts/setup-macos.sh
We need to and can automate this. I will add a fix and we can avoid this update.

2023-06-08 14:24 UTC, majetideepak commented
> Should I revert the other document changes apart from that?

Let's fix the CPU_ARCH, INSTALL_PREFIX first. We can then document whatever is remaining. I will update here.
But yes, likely only the adapters.sh change is needed.

2023-06-08 15:26 UTC, majetideepak commented
CPU_ARCH requirement should be fixed with this https://github.com/facebookincubator/velox/issues/5204

2023-06-08 15:36 UTC, majetideepak commented
@imjalpreet feel free to keep the adapters.sh fix and revert others. We can get that merged.

2023-06-08 15:48 UTC, imjalpreet commented
@majetideepak Updated the PR

2023-06-16 11:07 UTC, majetideepak approved these changes

2023-06-16 11:09 UTC, merged