Add ascii functionality
prestodb/presto pull request #20604
Opened 2023-08-18 14:55 UTC by setyven

## Description
Add ascii function to return the ASCII code of the first character

## Test Plan
Test ran successfully in local machine
```
./mvnw clean install -Dtest=TestStringSqlFunctions -Dmaven.javadoc.skip=true -T1C -fn -pl presto-main
```
Test cases are also compared with results from running `ascii` function in Spark.

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
```
== RELEASE NOTES ==

General Changes
* add :func:`ascii` to return ASCII code of the first character.
```

2023-08-18 15:05 UTC, steveburnett requested changes
LGTM! I suggested a rephrasing for the doc. If my suggested phrasing does not make sense to you, please rephrase in a way that you think better. Thanks!

2023-08-18 15:05 UTC, steveburnett commented on presto-docs/src/main/sphinx/functions/string.rst
> +    Parameter `n` needs to be convertible to `varchar`, which in this case are:
```suggestion
    Parameter `n` must be convertible to `varchar`, which means that `n` must be one of the following data types:
```

2023-08-18 19:27 UTC, steveburnett approved these changes
LGTM! (docs)

2023-08-22 10:18 UTC, setyven commented
hi @kaikalur do you mind taking a look on this PR please?

2023-08-23 13:52 UTC, tdcmeehan commented
These functions seem very hyper-specific.  Do you think it makes sense to move these to a separate, optional plugin?

2023-08-23 14:02 UTC, setyven commented
I thought of having just 1 generic function, however I can't get it to work with varbinary as input, and need to encode it first. Otherwise casting varbinary directly to varchar will throw an error.

2023-08-29 17:36 UTC, jainavi17 commented
LGTM

2023-09-01 14:40 UTC, kaikalur commented
codepoint already does it. So what is different here?

2023-09-07 09:33 UTC, setyven commented
> codepoint already does it. So what is different here?

this is initially added to replicate `ascii` function in spark sql, which takes in parameter of various types, rather than only char which codepoint does. to be honest, I wasn't aware `codepoint` exists already, which makes adding this function a bit off. what do you guys think? @kaikalur @jainavi17

2023-09-12 13:48 UTC, kaikalur commented
> These functions seem very hyper-specific. Do you think it makes sense to move these to a separate, optional plugin?

Not plugin but maybe a separate catalog. But I feel having more/better parity with  python functions is desirable

2023-09-12 13:50 UTC, kaikalur commented
Hmm, I'm not sure if we want to do it for all sorts of types - like timestamp? I'm confused

2023-10-06 10:16 UTC, closed without merging

2023-10-06 10:16 UTC, setyven commented
Closing PR per discussion offline (to move this to internal repo instead)