Add support for generic parameters in make_set_digest function
prestodb/presto pull request #20685
Opened 2023-08-28 12:05 UTC by Akanksha-kedia

<img width="1246" alt="MicrosoftTeams-image (17)" src="https://github.com/prestodb/presto/assets/89628774/524f8a4c-7bee-4440-9088-7f3de5b8f303">
<img width="633" alt="MicrosoftTeams-image (18)" src="https://github.com/prestodb/presto/assets/89628774/bb47c3db-aac6-4f15-a312-a01cceaf61af">

2023-08-28 15:55 UTC, tdcmeehan commented
Can you add some unit tests for this change?  I am not sure of the consequences--one unit test for every major type?  Thanks!

2023-08-29 23:15 UTC, tdcmeehan commented
Thank you for adding these tests.  To be safe, let's make them round-trip, i.e. take the output binary, re-serialize it into a set digest, and check to see if the elements are present.

2023-09-07 13:17 UTC, tdcmeehan commented
`TestTDigestAggregationFunction` has examples of round-tripping.  Basically, you need to take that output binary, then construct a SetDigest from it and infer information about the structure that is consistent with the inputs of the test.

2023-09-10 16:08 UTC, Akanksha-kedia commented
@tdcmeehan kindly review and help merge.

2023-09-11 14:28 UTC, tdcmeehan commented
This is better, but what I had in mind was this:

1. Create a set digest from values, then SELECT back the varbinary as hex.
2. Convert the hex to a format understandable and castable to varbinary, then select values back from the set digest.


TDigest tests above do this as an example.

2023-09-11 14:29 UTC, Akanksha-kedia commented
I actually tried lot to do this.

On Mon, 11 Sep 2023 at 7:58 PM, Timothy Meehan ***@***.***>
wrote:

> This is better, but what I had in mind was this:
>
>    1. Create a set digest from values, then SELECT back the varbinary as
>    hex.
>    2. Convert the hex to a format understandable and castable to
>    varbinary, then select values back from the set digest.
>
> TDigest tests above do this as an example.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/prestodb/presto/pull/20685#issuecomment-1714004268>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVL2AZRL3M6IOM7T5GNLW6TXZ4NZHANCNFSM6AAAAAA4BJ7FXA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-09-19 06:01 UTC, Akanksha-kedia commented
@tdcmeehan please check the changes and merge, getting values from setdigest i m not able to actually achieve that.As a new requirement we can take up this

2023-09-20 14:11 UTC, tdcmeehan requested changes
In lieue of round tripping, let's not assert on binary contents.  If it ever changes, the test will have to be updated in a way that will be very hard to discover if there was a regression.  Instead, let's inspect the digests--cardinality, jaccard index and insersection.

2023-09-20 14:11 UTC, tdcmeehan commented on presto-main/src/test/java/com/facebook/presto/type/setdigest/TestMakeSetDigest.java
> +        assert assertions.getQueryRunner().execute(
Please use TestNG assertions here and everywhere else in this file.  Do not use Java assert.

2023-09-20 14:11 UTC, tdcmeehan commented
Also please make sure the commit adheres to our guidelines (see CONTRIBUTING.md).  The title is too long.

2023-09-20 14:12 UTC, Akanksha-kedia commented
Ok, will do that.

On Wed, 20 Sep 2023 at 7:42 PM, Timothy Meehan ***@***.***>
wrote:

> Also please make sure the commit message adheres to our guidelines (see
> CONTRIBUTING.md). The title is too long.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/prestodb/presto/pull/20685#issuecomment-1727816655>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVL2AZRXDYRWQA2YJTA5E53X3L2THANCNFSM6AAAAAA4BJ7FXA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-09-22 14:47 UTC, tdcmeehan commented
![Screenshot 2023-09-22 at 10 47 10 AM](https://github.com/prestodb/presto/assets/7980573/3db8398f-fce5-43a0-9d4e-8bf40037ed20)
Looks like commit message still too wide.

2023-09-22 14:50 UTC, Akanksha-kedia commented
i have shortened @tdcmeehan

2023-09-22 15:51 UTC, tdcmeehan approved these changes

2023-09-25 15:17 UTC, Akanksha-kedia commented
@tdcmeehan please help to merge this PR.Thanks for review and approval !!!

2023-09-25 16:46 UTC, merged