Refactor query stats calculation about processedInputDataSize and processedInputPositions.
prestodb/presto pull request #20739
Opened 2023-09-01 10:38 UTC by hantangwangd

## Description

We may have more than one TableScanNodes in a single stage, or have no TableScanNode at all. In these cases the calculate about QueryStats's  processedInputDataSize and processedInputPositions is not correct.

## Release Notes

```
== NO RELEASE NOTE ==
```

2023-09-01 13:34 UTC, tdcmeehan requested changes
Great catch.  Can you see how feasible it is to add a unit test for this in `TestQueryStats`?

CC: @xiaoxmeng could you also have a look?

2023-09-02 19:07 UTC, hantangwangd commented
@tdcmeehan Of course, a unit test have been added to TestQueryStats. Please have a look, thanks a lot.

2023-09-04 22:27 UTC, tdcmeehan approved these changes

2023-09-11 16:20 UTC, tdcmeehan commented
Thank you @hantangwangd .  Please feel free to join our Slack channel if you'd like to discuss what you're working on with Presto. https://communityinviter.com/apps/prestodb/prestodb

2023-09-11 16:20 UTC, merged

2023-09-11 19:05 UTC, hantangwangd commented
@tdcmeehan Thank you very much for inviting, it's my pleasure to join.