[WIP] Improve documentation of Presto Resource Groups
prestodb/presto pull request #20750
Opened 2023-09-02 07:46 UTC by Akanksha-kedia

Currently we have it only for file-based resource group management. Working on Improving documentation of Presto Resource Groups.

Presto resource management can be done in two ways: File-based and Database-based.

File-Based Resource Management:

In a file-based resource manager, configuration information about the resource groups is stored in a JSON file. This file contains definitions of all resource groups and the rules to select them. The configuration file is loaded and used at the start of the Presto server. Any changes to the file require a restart of the Presto server to take effect.

Database-Based Resource Management:

In a database-based resource manager, configuration information about the resource groups is stored in a relational database. The database contains definitions of all resource groups and the rules to select them. Unlike the file-based resource manager, changes to the configuration in the database take effect immediately and do not require a restart of the Presto server.

Setting Up File-Based Resource Management:

Create a JSON file with the definitions of your resource groups and rules.
Specify the location of this file in the Presto server's configuration file under the property resource-groups.config-file.
Setting Up Database-Based Resource Management:

Set up a relational database that Presto can access.
Create tables in the database for resource groups and selection rules.
Specify the database's JDBC URL in the Presto server's configuration file under the property resource-groups.config-db-url.
Both methods have their pros and cons. File-based resource management is simpler to set up but less flexible, while database-based resource management is more complex to set up but offers more flexibility and dynamic changes.

2023-09-04 09:33 UTC, Akanksha-kedia commented
@steveburnett  @tdcmeehan please review.

2023-09-05 19:40 UTC, steveburnett requested changes
Hey, great job adding all of this documentation! Thanks. 

I made a lot of comments, most of which are small formatting fixes. I also offered some ideas or suggestions for you to consider how best to present the meaning that you want people to find. 

For formatting, I encourage you to build and view your draft locally to look for formatting errors and inconsistencies - see **Building manually** and **Viewing the documentation** in the [presto-docs README](https://github.com/prestodb/presto/tree/master/presto-docs) if you're not sure how to do that. 

Again, I appreciate your work and contributions.

2023-09-05 19:40 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +Specify the database in the Presto configuration: In the etc directory of your Presto installation,
```suggestion
Specify the database in the Presto configuration: In the ``etc`` directory of your Presto installation,
```

2023-09-05 19:40 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +``Resource Groups Table``
Consider formatting _Resource Groups Table_ and _Selectors Table_ as sub-level headers. When these are formatted like the items in them (resource_group_id, soft_memory_limit), they look like part of the list of items and not a title for the list of items. 

<img width="750" alt="Screenshot 2023-09-05 at 3 04 13 PM" src="https://github.com/prestodb/presto/assets/7013443/ac72b9fa-7c25-4c4a-83ad-e1ad0750f1b7">

2023-09-05 19:40 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +* ``schedulingPolicy`` (optional): The policy that determines how queries are scheduled within the resource group.
If you un-indent one level for the four sub-items starting with _fair_, you can remove the codeblock formatting line. 

See the difference in the two screenshots. 
**Note** unindenting in the second affect line break and vertical spacing, which I didn't change, so please adjust the four entries to show the line breaks and vertical spacing you have here. 

current code
<img width="828" alt="Screenshot 2023-09-05 at 3 08 23 PM" src="https://github.com/prestodb/presto/assets/7013443/fae39ea7-d7da-404a-9f3f-1b739cd14d02">

unindenting the four sub-items one (and only one) to the left
<img width="826" alt="Screenshot 2023-09-05 at 3 09 35 PM" src="https://github.com/prestodb/presto/assets/7013443/aa141696-6cc7-4ae0-bdb6-9bdfa6378aac">

2023-09-05 19:40 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +  This can be set to "fair", "weighted", or "query_priority". May be one of three values:
```suggestion
  This can be set to "fair", "weighted", "weighted_fair", or "query_priority". May be one of four values:
```

2023-09-05 19:40 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +scheduling policy is set to "weighted". It determines how resources are distributed
```suggestion
scheduling policy is set to ``weighted``. It determines how resources are distributed
```

2023-09-05 19:40 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +In this example, queries from the "engineering" subgroup will be prioritized over queries
```suggestion
In this example, queries from the ``engineering`` subgroup will be prioritized over queries
```

2023-09-05 19:40 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +from the "marketing" subgroup.
```suggestion
from the ``marketing`` subgroup.
```

2023-09-05 19:40 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +... literalinclude:: schedule-weight-example.json
Did you intend for this line and the next one to display as is in the documentation? 
<img width="799" alt="Screenshot 2023-09-05 at 3 21 31 PM" src="https://github.com/prestodb/presto/assets/7013443/ad08114a-844e-473f-8115-94d90302b741">

2023-09-05 19:40 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +* ``group`` (required): This is the name of the resource group where the query will be routed.
Consider if you want to move this component, the only required one, first in the unordered list, followed by all the optional components.

2023-09-05 19:40 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +  The cpuQuotaPeriod is a global property often used in container-based environments to control the amount
```suggestion
  The ``cpuQuotaPeriod`` is a global property often used in container-based environments to control the amount
```

2023-09-05 19:40 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +This property is typically used in conjunction with a cpuQuota property,
```suggestion
This property is typically used in conjunction with a ``cpuQuota`` property,
```

2023-09-05 19:40 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +which specifies the total amount of CPU time that the container can use during each cpuQuotaPeriod.
```suggestion
which specifies the total amount of CPU time that the container can use during each ``cpuQuotaPeriod``.
```

2023-09-05 19:40 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +For example, if cpuQuota is set to 100000 and cpuQuotaPeriod is set to 200000,
```suggestion
For example, if ``cpuQuota`` is set to 100000 and ``cpuQuotaPeriod`` is set to 200000,
```

2023-09-05 19:40 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +This property is typically used in conjunction with a cpuQuota property,
Is ``cpuQuota`` also a global property like ``cpuQuotaPeriod``? If yes, consider revising this line to add ``cpuQuota`` as a new unordered list item. 

Also, consider adding a line explaining what the values are for these two properties. Maybe something like "The value of ``cpuQuota`` and ``cpuQuotaPeriod`` is the number of microseconds of CPU time."

2023-09-05 22:23 UTC, yhwang commented on presto-docs/src/main/sphinx/admin/resource-groups-example1.sql
> +Please remember to replace 'user' with the actual username in your environment. Also note that this is a simple example and may not cover all your use cases. Always refer to the official PrestoDB doc
should this line be a comment too?

2023-09-05 22:27 UTC, yhwang commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +as well as its parent groups.If a resource group runs out of a certain resource, it does not cause running
```suggestion
as well as its parent groups. If a resource group runs out of a certain resource, it does not cause running
```

2023-09-05 22:28 UTC, yhwang commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +queueing policies.On the other hand, a resource group that accepts queries directly is a leaf group, and it
```suggestion
queueing policies. On the other hand, a resource group that accepts queries directly is a leaf group, and it
```

2023-09-05 22:41 UTC, yhwang commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +adhoc queries.The scheduling weight in PrestoDB's Resource Groups is used when the parent group's
```suggestion
adhoc queries. The scheduling weight in PrestoDB's Resource Groups is used when the parent group's
```

2023-09-05 22:43 UTC, yhwang commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +the container can use up to 50% of a single CPU core over each 200 millisecond period.This is useful
```suggestion
the container can use up to 50% of a single CPU core over each 200 millisecond period. This is useful
```

2023-09-05 22:49 UTC, yhwang commented
Awesome content! Thanks for the changes.

2023-09-05 22:52 UTC, yhwang approved these changes
most of my comments are minor change requests. I assume you would fix them. LGTM

2023-09-06 14:51 UTC, tdcmeehan requested changes

2023-09-06 14:51 UTC, tdcmeehan commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +improving the overall performance and stability of the system.
I would remove, there is not a lot of content in this paragraph.

2023-09-06 14:51 UTC, tdcmeehan commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +``Setting Up Database-Based Resource Management``
Can you please collapse above sections into the below

2023-09-06 14:51 UTC, tdcmeehan commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +Set up a relational database: The database should be accessible by Presto.
More details on schema

2023-09-07 03:47 UTC, Akanksha-kedia commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +among all queries.
Few will be running queries and few wll be put to queue as the cocurrent will be get executed queued will execute./Anyways i removed

2023-09-07 03:55 UTC, Akanksha-kedia commented
thanks @steveburnett  @yhwang @tdcmeehan i have done required chnages kindly have a look.

2023-09-07 15:24 UTC, steveburnett requested changes
This is much better, thank you for all your work! The work you have done already allows me to see more clearly how to structure the content. 

Most of the changes I suggest today are about making the flow of the content logical, so the reader first finds WHAT the options are, then you show them WHY they might choose one or the other based on their needs, then HOW to do the chosen option.

2023-09-07 15:24 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +With the Database Resource Group Manager, changes to the configuration in the database
This seems to repeat the content of lines 109-111, the first paragraph after the heading "Database Resource Group Manager". I suggest you delete this paragraph. 

But I like the way you describe it here. So I suggest that before you delete it here, compare these words to 109-111. Consider revising 109-111 with some or all of the words here. 
Decide which version best describes what you want to say and use the first version in 109-111, the second version here, or a combination of the two.

2023-09-07 15:24 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +adhoc queries. The scheduling weight in PrestoDB's Resource Groups is used when the parent group's
suggest adding a line after "adhoc queries" to make the next sentence a new paragraph, making it easier to read.

2023-09-07 15:24 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +Both methods have their pros and cons. File-based resource management is simpler to set up but less flexible,
I suggest moving this paragraph as a new second paragraph in Database-Based Resource Management. This explains the pros and cons of the two methods, and should be before the reader commits to choosing one in the Setting Up... sections.

2023-09-07 15:42 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +* ``schedulingPolicy`` (optional): The policy that determines how queries are scheduled within the resource group.
If you addressed this comment, I'm not seeing the change yet. Building the docs locally from the current file still shows the vertical line in the first screenshot.

2023-09-07 15:46 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +* ``queryType`` (optional): This specifies the type of the query such as READ, WRITE, or MANAGE.
I'm seeing the same too-indented formatting as above. 

first screenshot is what I'm seeing local build from the current file 
<img width="823" alt="Screenshot 2023-09-07 at 11 38 56 AM" src="https://github.com/prestodb/presto/assets/7013443/3bc12392-8595-4d91-a4a8-35e1cf5ab831">

second screenshot is built from my edited file of how I think this section should display
<img width="814" alt="Screenshot 2023-09-07 at 11 39 37 AM" src="https://github.com/prestodb/presto/assets/7013443/dc8de32b-2249-4441-886e-72e8eff3fc0e">

2023-09-07 15:52 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +--In below examples, three selectors are created for user1, user2, and user3 respectively.
I suggest you look at the formatting of the content at the bottom of the page beginning at this line. Is this how you want it to look, with dashes at the beginning of the sentences and the indentation creating the vertical bar? 

Also, consider formatting named items such as resource_group_id, resource_groups, and user_regex as code with `` before and after. 

<img width="836" alt="Screenshot 2023-09-07 at 11 47 40 AM" src="https://github.com/prestodb/presto/assets/7013443/f59e51b6-1a4c-43ab-9547-83c976e96060">

2023-09-07 15:58 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +Please note that you would need to have the respective resource groups (i.e., user1, user2, user3)
```suggestion
Please note that you would need to have the respective resource groups (that is, user1, user2, user3)
```

It is recommended to not use Latin abbreviations, such as i.e., e.g., or &. 
- For i.e, use that is. 
- For e.g., it is recommended to use for example, such as, for instance, or like instead. 
- For &, use and instead, unless you are documenting a UI element that uses an &.

Above advice taken from the [GitLab docs Recommended Word list](https://docs.gitlab.com/ee/development/documentation/styleguide/word_list.html#ie).

If you would, please make this change throughout the file.

2023-09-09 04:35 UTC, Akanksha-kedia commented
@steveburnett please review and confirm

2023-09-13 12:56 UTC, Akanksha-kedia commented
@tdcmeehan @steveburnett please review

2023-09-13 17:27 UTC, steveburnett requested changes
Thanks for the work, this is better! I have a few minor comments, and two larger topics: 

1. Please look at my new comment about the steps at the end of Database-Based Resource Management, and what I'm suggesting you consider for this section and for the sections Setting Up File-Based Resource Management and Setting Up Database-Based Resource Management. If this does not work for you, let me know and help me understand why it doesn't work for you. 

2. I also suggest you look at the Contents on the right side of the page (screenshot included) and I want you to review the structure of the headers of this page, and change the level of the headers to what you feel is important.
For example, do you intend that every header after Sub-Groups and Query Acceptance is a subheader of Sub-Groups and Query Acceptance?

<img width="236" alt="Screenshot 2023-09-13 at 12 23 36 PM" src="https://github.com/prestodb/presto/assets/7013443/8de9102e-2deb-4d70-86dc-bd8d5a3c2846">

2023-09-13 17:27 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +  This can be set to "fair", "weighted", "weighted_fair" or "query_priority". May be one of four values:
```suggestion
  This can be set to ``fair``, ``weighted``, ``weighted_fair`` or ``query_priority``. May be one of four values:
```

2023-09-13 17:27 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +* ``schedulingWeight`` (optional): The weight for the resource group when the parent group uses the "weighted"
```suggestion
* ``schedulingWeight`` (optional): The weight for the resource group when the parent group uses the ``weighted``
```

2023-09-13 17:27 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +* ``jmxExport`` (optional):  If set to true, the statistics of the resource group will be exported via JMX.
```suggestion
* ``jmxExport`` (optional):  If set to ``true``, the statistics of the resource group will be exported via JMX.
```

2023-09-13 17:27 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +scheduling policy is set to ``weighted``. It determines how resources are distributed
Does "It determines how resources are distributed among the subgroups. " add to the meaning in this paragraph, or does it repeat what is already said? 

Consider if you can delete this sentence and the paragraph still means what you want it to say.

2023-09-13 17:27 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +This allows you to prioritize certain subgroups over others in terms of resource allocation.
```suggestion
Schedule weighting allows you to prioritize certain subgroups over others in terms of resource allocation.
```
Sometimes "This" can be vague and readers are not sure what is meant by it. Is "Schedule weighting" the correct meaning of "This" in this sentence?

2023-09-15 11:53 UTC, Akanksha-kedia commented
Resolved all comments @steveburnett thanks for review.

2023-09-15 11:55 UTC, Akanksha-kedia commented
./build i m getting some issue so using pycharm. @steveburnett

2023-09-18 17:01 UTC, steveburnett requested changes
Thanks for all your work! We're getting closer. I suggest you test formatting locally as best you can - I saw your comment that you're using PyCharm because of build errors.

2023-09-24 14:16 UTC, closed without merging