Fix a binding issue in presto-verifier
prestodb/presto pull request #20829
Opened 2023-09-11 18:41 UTC by v-jizhang

## Description

The bindings are in SourceQueryModule.java, but the error complains about VerifierModule.java. Move the bindings to VerifierModule.java.

com.google.inject.CreationException: Unable to create injector, see the following errors:
1) Explicit bindings are required and
  com.facebook.presto.verifier.source.SnapshotQueryConsumer is not
  explicitly bound. while locating
  com.facebook.presto.verifier.source.SnapshotQueryConsumer for
  the 2nd parameter of
  com.facebook.presto.verifier.framework.VerificationManager.<init>
  (VerificationManager.java:133) at
  com.facebook.presto.verifier.framework.VerifierModule.setup
  (VerifierModule.java:130)
2) Explicit bindings are required and
  com.facebook.presto.verifier.source.SnapshotQuerySupplier is not
  explicitly bound. while locating
  com.facebook.presto.verifier.source.SnapshotQuerySupplier for
  the 3rd parameter of
  com.facebook.presto.verifier.framework.VerificationManager.<init>
  (VerificationManager.java:133) at
  com.facebook.presto.verifier.framework.VerifierModule.setup
  (VerifierModule.java:130)

## Motivation and Context
Quick fix for the binding issue, see Description above.

## Impact
None.

## Test Plan
Make sue all tests pass.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== NO RELEASE NOTE ==
```

2023-09-11 18:46 UTC, ericyuliu approved these changes
LG

2023-09-11 18:52 UTC, ajaygeorge requested changes
Can you add a test which fails if this change is not present so that next time we can catch such issues.

2023-09-11 18:59 UTC, v-jizhang commented
> Can you add a test which fails if this change is not present so that next time we can catch such issues.

It never happened in my environment. I'll add a test anyway.

2023-09-13 10:09 UTC, vermapratyush approved these changes
Thanks for the fix @v-jizhang

2023-09-13 10:09 UTC, vermapratyush commented on presto-verifier/src/main/java/com/facebook/presto/verifier/source/SourceQueryModule.java
> +        // Snapshots are supported by Mysql only
nit: 
```suggestion
        // Snapshots are supported by Mysql only.
```

2023-09-13 10:09 UTC, vermapratyush commented on presto-verifier/src/test/java/com/facebook/presto/verifier/source/TestSourceQueryModule.java
> +        assertTrue(injector.getInstance(SnapshotQueryConsumer.class) instanceof MysqlSnapshotQueryConsumer);
I think the tests can be merged into one.

2023-09-13 14:50 UTC, ajaygeorge commented
@v-jizhang Can you please update the description.
Now it says
> The bindings are in SourceQueryModule.java, but the error complains about VerifierModule.java. Move the bindings to VerifierModule.java.

I don't see any changes to `VerifierModule`

2023-09-13 20:02 UTC, v-jizhang commented
> @v-jizhang Can you please update the description. Now it says
> 
> > The bindings are in SourceQueryModule.java, but the error complains about VerifierModule.java. Move the bindings to VerifierModule.java.
> 
> I don't see any changes to `VerifierModule`

It doesn't matter where the binding is as long as it is bound somewhere. The problem is that the binding code in SourceQueryModule.java was guarded by an if statement. Moving the binding out of the if statement solves the problem.

2023-09-13 20:11 UTC, ajaygeorge commented
@v-jizhang sure it might not matter where the binding is. What I am recommending is to update the PR description to reflect what you are trying to do. Now they are out of sync.

2023-09-15 11:35 UTC, ajaygeorge approved these changes

2023-09-15 11:38 UTC, vermapratyush commented
@v-jizhang Can you please address the remaining commit message before merging.

2023-09-15 14:49 UTC, v-jizhang commented
> @v-jizhang sure it might not matter where the binding is. What I am recommending is to update the PR description to reflect what you are trying to do. Now they are out of sync.

Changed.

2023-09-19 00:29 UTC, v-jizhang commented
I've done before and after tests, the failures exist in both cases. They are unrelated to the PR.

2023-09-19 08:31 UTC, merged