Improve Document types.html setdigest Function
prestodb/presto pull request #20823
Opened 2023-09-11 14:43 UTC by Akanksha-kedia

docs/src/main/sphinx/language/types.rst

2023-09-11 14:44 UTC, Akanksha-kedia commented
@steveburnett @tdcmeehan please review

2023-09-11 19:09 UTC, steveburnett requested changes
Great start! I have some questions and suggestions. Please review my comments. If I have misunderstood anything, please help me understand your intent and meaning.

2023-09-11 19:09 UTC, steveburnett commented on presto-docs/src/main/sphinx/language/types.rst
> +a large dataset. It is based on the principle of observing the 'rarity' of certain patterns in a random process.
The word 'rarity' is enclosed in single vertical quotes. This is not RST formatting. Is this content copied from somewhere else? If so, it should be attributed. 

Why is the word marked like this? 
What do you mean by this? 
Is this marking needed, or can it be removed or changed?

2023-09-11 19:09 UTC, steveburnett commented on presto-docs/src/main/sphinx/language/types.rst
> +It involves creating a 'signature' or 'sketch' for each set, which is a much smaller subset that still maintains the
The words 'signature' and 'sketch' are enclosed in single vertical quotes. This is not RST formatting. Is this content copied from somewhere else? If so, it should be attributed.

Why are the words marked like this?
What do you mean by this?
Is this marking needed, or can it be removed or changed?

2023-09-11 19:09 UTC, steveburnett commented on presto-docs/src/main/sphinx/language/types.rst
> +The HyperLogLog structure is used for the approximation of the distinct elements in the original set.
```suggestion
The HyperLogLog structure is used to approximate the distinct elements in the original set.
```
Active voice is easier to read. Does this change alter the meaning of the sentence in a way you feel is less accurate?

2023-09-11 19:09 UTC, steveburnett commented on presto-docs/src/main/sphinx/language/types.rst
> +SetDigests have the property of being additive, which means that you can merge multiple SetDigests together
```suggestion
SetDigests are additive, so you can merge multiple SetDigests together
```
Does this change alter the meaning of the sentence in a way you feel is less accurate?

2023-09-11 19:09 UTC, steveburnett commented on presto-docs/src/main/sphinx/language/types.rst
> +These components work together to provide an efficient and effective way to handle and compare large sets of data.
Does this sentence add to the value of the text? Suggest deleting it, unless it is important in a way I do not understand.

2023-09-13 12:55 UTC, Akanksha-kedia commented
@steveburnett @tdcmeehan please review

2023-09-13 17:36 UTC, steveburnett approved these changes
LGTM! (docs)

2023-09-14 12:53 UTC, Akanksha-kedia commented
@tdcmeehan please review

2023-09-18 12:46 UTC, tdcmeehan approved these changes

2023-09-18 12:47 UTC, merged