Add Feature Toggles
prestodb/presto pull request #20867
Opened 2023-09-14 15:24 UTC by branimir-vujicic

Feature Toggles should allow teams to modify system behavior without changing code. Feature Toggles are configured using google guice. Basic definition of toggles are crated using FeatureToggleBinder. FeatureToggleBinder creates FeatureToggle and additional configuration can be done using feature configuration.
In current stage Feature Toggles supports:
- if / else based feature toggles
- Dependency Injection based Hot reloading implementation without restart require code refactoring to add an interface when injecting the new implementation/class
- using various toggle strategies along with simple on / off toggles

configuration:

to allow feature toggle configuration four lines are needed in config.properties file
```
features.config-source-type=file
features.refresh-period=30s
```

`configuration-source-type` is source type for Feature Toggles configuration `features.config-source` is a source (file) of the configuration `features.config-type` format in which configuration is stored (json or properties) `features.refresh-period` configuration refresh period

Defining Feature Toggles

Feature toggle definition is done in google guice module using `FeatureToggleBinder`

simple feature toggle definition
```
    featureToggleBinder(binder)
                        .featureId("featureXX")
                        .bind()
```
This example creates bindings for @Inject
```
    @Inject
    public Runner(@FeatureToggle("featureXX") Supplier<Boolean> isFeatureXXEnabled)
    {
        this.isFeatureXXEnabled = isFeatureXXEnabled;
    }
```
`isFeatureXXEnabled` can be used to test if feature is enabled or disabled:
```
    boolean testFeatureXXEnabled()
    {
        return isFeatureXXEnabled.get();
    }
```

hot reloadable feature toggle definition
```
featureToggleBinder(binder, Feature01.class)
                        .featureId("feature01")
                        .baseClass(Feature01.class)
                        .defaultClass(Feature01Impl01.class)
                        .allOf(Feature01Impl01.class, Feature01Impl02.class)
                        .bind()
```
adding Feature Toggle switching strategy
```
featureToggleBinder(binder)
                        .featureId("feature04")
                        .toggleStrategy("AllowAll")
                        .toggleStrategyConfig(ImmutableMap.of("key", "value", "key2", "value2"))
```

feature-config.properties file example
```
# feature query-logger
feature.query-logger.enabled=true
feature.query-logger.strategy=OsToggle
feature.query-logger.strategy.os_name=.*Linux.*

#feature.query-rate-limiter
feature.query-rate-limiter.currentInstance=com.facebook.presto.server.protocol.QueryBlockingRateLimiter

# feature.query-cancel
feature.query-cancel.strategy=AllowList
feature.query-cancel.strategy.allow-list-source=.*IDEA.*
feature.query-cancel.strategy.allow-list-user=.*prestodb
```
in this example for first feature `query-logger`
changing value of feature.query-logger.enabled to `false` will 'disable' this feature. Changes will be effective within refresh period.

Test plan - Unit Tests
```
== RELEASE NOTES ==

General Changes
 * Add support for Feature Toggles.

2023-09-18 22:51 UTC, ajaygeorge commented
@branimir-vujicic  I'm starting to take a look at the PR.
 I would recommend further breaking this up into commits like
1. Add Feature Toggle core classes
2. Add support for Simple feature toggle
3. Add support for Hot Reloadable feature toggle.
4. Add support for Strategy based feature toggle.
5. Add Test support for Feature toggle.

2023-09-19 12:25 UTC, branimir-vujicic commented
@ajaygeorge, I'll try to break it down furthermore, and let you know.

2024-07-08 15:46 UTC, steveburnett requested changes
Thanks for the doc! Some format suggestions, and a couple of questions for you to consider and maybe change the text.

2024-07-08 15:46 UTC, steveburnett commented on presto-feature-toggle/README.md
> +Feature Toggles should allow teams to modify system behavior without changing code. Feature Toggles are configured using Google Guice. The basic definition of toggles is created
```suggestion
Feature Toggles should allow teams to modify system behavior without changing code. Feature Toggles are configured using [Google Guice](https://github.com/google/guice). The basic definition of toggles is created
```

2024-07-08 15:46 UTC, steveburnett commented on presto-feature-toggle/README.md
> +To allow feature toggle configuration four lines are needed in the config.properties file
```suggestion
To allow feature toggle configuration, add four lines in the config.properties file:
```
Suggest active voice

2024-07-08 15:46 UTC, steveburnett commented on presto-feature-toggle/README.md
> +Feature toggle definition is done in the Google guice module using `FeatureToggleBinder`
```suggestion
Feature toggle definition is done in the Google Guice module using `FeatureToggleBinder`.
```

2024-07-08 15:46 UTC, steveburnett commented on presto-feature-toggle/README.md
> +Switching the feature toggle on/off is done by changing the enabled value from true to false in the configuration source file:
```suggestion
Switching the feature toggle on or off is done by changing the enabled value from `true` to `false` in the configuration source file:
```
Avoid slashes, see the [Gitlab documentation style guide entry for slashes](https://docs.gitlab.com/ee/development/documentation/styleguide/word_list.html#slashes).

2024-07-08 15:46 UTC, steveburnett commented on presto-feature-toggle/README.md
> +After the refresh period value of `isFeatureXXEnabled.get();`  is changed.
This reads a little confusingly for me. Can you rephrase this?

2024-07-08 15:46 UTC, steveburnett commented on presto-feature-toggle/README.md
> +Strategy-based Toggling allows us to Implement custom predicates (Strategy Pattern) to evaluate if a feature is enabled.
```suggestion
Strategy-based Toggling allows us to implement custom predicates (Strategy Pattern) to evaluate if a feature is enabled.
```
Can you rephrase to remove the parentheses around "Strategy Pattern"? Also, if Strategy Pattern is an important concept here, consider adding a link to help people learn. Maybe the wikipedia entry is appropriate? 
https://en.wikipedia.org/wiki/Strategy_pattern

2024-07-08 15:46 UTC, steveburnett commented on presto-feature-toggle/README.md
> +Some are provided out of the box: AllowAll, OS-based toggle, and AllowList toggle strategy.
```suggestion
Default toggles provided are `AllowAll`, `AllowList`, and an operating system-based toggle strategy.
```

2024-07-08 15:46 UTC, steveburnett commented on presto-feature-toggle/README.md
> +- strategy.<param>
This line doesn't appear to display the way you seem to intend it to, see screenshot. 
<img width="977" alt="Screenshot 2024-07-08 at 11 40 28 AM" src="https://github.com/prestodb/presto/assets/7013443/e541a04b-8b92-4268-89bb-639389509799">

2024-07-08 15:46 UTC, steveburnett commented on presto-feature-toggle/README.md
> +Configuration properties always start with a `feature` followed by a dot and the feature id.
```suggestion
Configuration properties always start with a `feature` followed by a dot, then the feature id. In this example the feature id is `query-cancel`. 
```

2024-07-08 15:46 UTC, steveburnett commented on presto-feature-toggle/README.md
> +In this example for feature `query-cancel`, changing the value of feature.query-cancel.enabled to `false` will 'disable' this feature.
```suggestion
In this example, change the value of `feature.query-cancel.enabled` to `false` to disable this feature.
```

2024-07-08 15:46 UTC, steveburnett commented on presto-feature-toggle/README.md
> +Changes will be effective within the refresh period.
```suggestion
Changes are effective within the refresh period. 
```
Does "within" mean the change is effective during the current refresh period, or after the refresh period?

2024-07-19 11:24 UTC, branimir-vujicic commented
Thank you, @steveburnett, for your suggestions. 
I have updated the document. Could you please review the changes?

2024-07-19 14:54 UTC, steveburnett submitted a review, later dismissed
LGTM! (docs) 

Thanks for the revision! Used "View file" on the README to review the updated file as it will be displayed, verified all changes have been addressed, found no new comments to make. Nice work!

2025-09-19 09:43 UTC, closed without merging