Update DROP TABLE in Iceberg document
prestodb/presto pull request #20981
Opened 2023-09-28 05:51 UTC by agrawalreetika

## Description
Update DROP TABLE in Iceberg document

## Motivation and Context
Refactor existing Iceberg document about DROP TABLE

## Impact
After Change -
![image](https://github.com/prestodb/presto/assets/7887476/37858e1a-6110-49fa-98a7-9ac5a02db02d)

## Test Plan

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes

```
== NO RELEASE NOTE ==
```

2023-09-28 16:44 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/iceberg.rst
> +* Dropping an Iceberg table with ``Hive Metastore`` & ``Glue`` Catalogs only removes metadata from metastore.
```suggestion
* Dropping an Iceberg table with Hive Metastore & Glue catalogs only removes metadata from metastore.
```

2023-09-28 16:50 UTC, steveburnett requested changes
Nice! I made some formatting suggestions, I wanted to explain why I made these suggestions here.
 
I don't think we need to mark Hive Metastore, Glue, Hadoop, and Nessie here as code because they're just nouns here. 

I changed "&" to "and" because Latin abbreviations such as &, i.e., e.g, and such should not be in technical documentation. For one example, see the [GitLab Recommended word list](https://docs.gitlab.com/ee/development/documentation/styleguide/word_list.html#) entry for &.

2023-09-28 16:50 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/iceberg.rst
> +* Dropping an Iceberg table with ``Hive Metastore`` & ``Glue`` Catalogs only removes metadata from metastore.
```suggestion
* Dropping an Iceberg table with Hive Metastore & Glue catalogs only removes metadata from metastore.
```

2023-09-28 16:50 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/iceberg.rst
> +* Dropping an Iceberg table with ``Hadoop`` & ``Nessie`` Catalogs removes all the data & metadata in the table.
```suggestion
* Dropping an Iceberg table with Hadoop and Nessie catalogs removes all the data and metadata in the table.
```

2023-09-29 06:41 UTC, agrawalreetika commented
Thank you for details @steveburnett 
I have made the suggested changes. Please review.

2023-09-29 14:46 UTC, steveburnett approved these changes
LGTM! (docs) Changes verified in local build. Thanks @agrawalreetika!

2023-09-29 14:58 UTC, tdcmeehan approved these changes

2023-09-30 17:31 UTC, merged