Build catalog-specific properties for IcebergQueryRunner w static method
prestodb/presto pull request #21018
Opened 2023-10-03 00:18 UTC by kiersten-stokes

## Description
Implements a static method to construct catalog-specific properties (Hive vs. Hadoop/Nessie) to pass to the query runner during Iceberg catalog creation.

## Motivation and Context
Reduce duplication in native  Iceberg tests introduced by #20912 

## Impact
Not user facing

## Test Plan
Tests passing

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
```
== NO RELEASE NOTE ==
```

2023-10-03 23:50 UTC, ChunxuTang reviewed
@kiersten-stokes Thanks for the refactoring! It helps to remove some duplicate code in the Iceberg connector tests.
Just left a minor comment.

2023-10-04 00:18 UTC, kiersten-stokes commented on presto-iceberg/src/test/java/com/facebook/presto/iceberg/IcebergQueryRunner.java
> +    public static ImmutableMap<String, String> getConnectorProperties(CatalogType icebergCatalogType, Path icebergDataDirectory)
Great catch! Will do

2023-10-04 15:07 UTC, tdcmeehan requested changes
LGTM!  Just one nit.

2023-10-04 15:07 UTC, tdcmeehan commented on presto-iceberg/src/test/java/com/facebook/presto/iceberg/IcebergQueryRunner.java
> +    public static ImmutableMap<String, String> getConnectorProperties(CatalogType icebergCatalogType, Path icebergDataDirectory)
```suggestion
    public static Map<String, String> getConnectorProperties(CatalogType icebergCatalogType, Path icebergDataDirectory)
```

2023-10-04 21:55 UTC, ChunxuTang approved these changes
LGTM. Thanks for the refactoring!

2023-10-05 15:44 UTC, tdcmeehan approved these changes
LGTM!  Please fix merge conflict and I'll give it a merge

2023-10-20 22:56 UTC, merged