Improve documentation of Presto Resource Groups
prestodb/presto pull request #21057
Opened 2023-10-06 15:43 UTC by Akanksha-kedia

Currently we have it only for file-based resource group management. Working on Improving documentation of Presto Resource Groups.

Presto resource management can be done in two ways: File-based and Database-based.

File-Based Resource Management:

In a file-based resource manager, configuration information about the resource groups is stored in a JSON file. This file contains definitions of all resource groups and the rules to select them. The configuration file is loaded and used at the start of the Presto server. Any changes to the file require a restart of the Presto server to take effect.

Database-Based Resource Management:

In a database-based resource manager, configuration information about the resource groups is stored in a relational database. The database contains definitions of all resource groups and the rules to select them. Unlike the file-based resource manager, changes to the configuration in the database take effect immediately and do not require a restart of the Presto server.

Setting Up File-Based Resource Management:

Create a JSON file with the definitions of your resource groups and rules.
Specify the location of this file in the Presto server's configuration file under the property resource-groups.config-file.
Setting Up Database-Based Resource Management:

Set up a relational database that Presto can access.
Create tables in the database for resource groups and selection rules.
Specify the database's JDBC URL in the Presto server's configuration file under the property resource-groups.config-db-url.
Both methods have their pros and cons. File-based resource management is simpler to set up but less flexible, while database-based resource management is more complex to set up but offers more flexibility and dynamic changes.

Continuation of https://github.com/prestodb/presto/pull/20750 , 20918

2023-10-06 15:44 UTC, Akanksha-kedia commented
@steveburnett @tdcmeehan please review and help to merge.

2023-10-06 15:47 UTC, Akanksha-kedia commented
<img width="821" alt="Screenshot 2023-10-06 at 9 17 10 PM" src="https://github.com/prestodb/presto/assets/89628774/a745faea-c9a1-4456-8148-f75bdad26a4f">
<img width="800" alt="Screenshot 2023-10-06 at 9 17 17 PM" src="https://github.com/prestodb/presto/assets/89628774/2c606a8c-f4e3-418b-aba5-1ecd9cd6a946">

2023-10-06 16:26 UTC, steveburnett requested changes
Thanks for this! This new PR addresses the comments I raised in the reviews on PR 20918, and starting over has allowed me to do a complete beginning to end review of this extensive documentation. 

I have only three very small suggestions, and that is all. Thank you!

2023-10-06 16:26 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +Here are the key properties that can be set for a Resource Group
```suggestion
Here are the key properties that can be set for a Resource Group:
```

2023-10-06 16:26 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +* ``subGroups`` (optional): list of sub-groups.A list of sub-groups within the resource group.
```suggestion
* ``subGroups`` (optional): list of sub-groups. A list of sub-groups within the resource group.
```

2023-10-06 16:26 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +Let's say we have a root resource group ``global`` with two subgroups: ``engineering`` and ``marketing``.
```suggestion
If you have a root resource group ``global`` with two subgroups: ``engineering`` and ``marketing``.
```
"we" should not be used in technical documentation. See GitLab's Recommended Word List entries for [we](https://docs.gitlab.com/ee/development/documentation/styleguide/word_list.html#we), and [recommend, we recommend](https://docs.gitlab.com/ee/development/documentation/styleguide/word_list.html#recommend-we-recommend), and [you, your, yours](https://docs.gitlab.com/ee/development/documentation/styleguide/word_list.html#you-your-yours) for more information.

2023-10-06 16:31 UTC, Akanksha-kedia commented
@steveburnett thanks for review , i have resolved the comments

2023-10-06 16:45 UTC, steveburnett approved these changes
LGTM! (docs) 

Thank you so much!

2023-10-06 20:33 UTC, tdcmeehan requested changes
Thank you for all the effort on this documentation.  Just one thing to fix from my end.

2023-10-06 20:33 UTC, tdcmeehan commented on presto-docs/src/main/sphinx/admin/resource-groups.rst
> +   Note : The supported databases are MySQL, PostgreSQL, and Oracle.
```suggestion
   Note : Currently only MySQL is supported.
```

2023-10-07 10:15 UTC, Akanksha-kedia commented
please review and approve, help to merge @steveburnett @tdcmeehan

2023-10-09 15:32 UTC, Akanksha-kedia commented
Please help to merge.

On Mon, 9 Oct 2023 at 7:13 PM, Timothy Meehan ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/prestodb/presto/pull/21057#pullrequestreview-1664486692>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVL2AZUP35QFIPMMZJS3NO3X6P5RBAVCNFSM6AAAAAA5WALBVGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMNRUGQ4DMNRZGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-10 14:36 UTC, Akanksha-kedia commented
@tdcmeehan

2023-10-10 14:40 UTC, merged