Introduce Rolling forward to snapshot with Presto Procedure on Iceberg table
prestodb/presto pull request #21073
Opened 2023-10-09 06:25 UTC by Hank27-zhang

## Description
The current existing pedicure rollback_to_snapshot (https://prestodb.io/docs/current/connector/iceberg.html#id2) in the Iceberg connector allows only rolling forward to an old snapshot but we can't roll forward to a different snapshot of ta Iceberg Table. Update the API to support roll-forward as well.

## Test Plan
update IcebergDistributedSmokeTestBase.testRollbackSnapshot()

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2023-10-09 07:56 UTC, imjalpreet requested changes
On looking at spark procedures in the official iceberg documentation, I feel Presto should be in sync with them so that the users who use spark as well are not confused with the working of each of them.

Spark has two separate procedures for `rollback_to_snapshot` (https://iceberg.apache.org/docs/1.3.1/spark-procedures/#rollback_to_snapshot) and `set_current_snapshot` (https://iceberg.apache.org/docs/1.3.1/spark-procedures/#set_current_snapshot).

I had a look at their implementation and they use `manageSnapshots().rollbackTo` in the case of `rollback_to_snapshot` and `manageSnapshots().setCurrentSnapshot` in the other case.

`rollback_to_snapshot`: https://github.com/apache/iceberg/blob/master/spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/procedures/RollbackToSnapshotProcedure.java#L88C67-L88C67

`set_current_snapshot`: https://github.com/apache/iceberg/blob/master/spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/procedures/SetCurrentSnapshotProcedure.java#L89

IMO we should also introduce another procedure for `setCurrentSnapshot` rather than updating the current procedure.

2023-10-09 07:58 UTC, imjalpreet commented
> [<img alt="CLA Not Signed" width="328" height="28" src="https://camo.githubusercontent.com/386c32cf1de823184a8b4907a7c1cedf6e9c4f628cdb9e0007df4a36420e9b87/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f636c612d70726f6a6563742d6c6f676f2d70726f642f636c612d6e6f742d7369676e65642e737667">](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/4238753/5349565/21073/#/?version=2)
> 
> * [❌](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/4238753/5349565/21073/#/?version=2) - login: @Hank27-zhang . The commit ([e069fb5](https://github.com/prestodb/presto/commit/e069fb550256170a3d944830a33d368f7fa6b7b8)) is not authorized under a signed CLA. [Please click here to be authorized](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/4238753/5349565/21073/#/?version=2). For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

Also, please sign the CLA.

2023-10-09 09:19 UTC, agrawalreetika commented
Hi @Hank27-zhang, 
Even I think adding a separate procedure `set_current_snapshot` for setting snapshot would be better and keep the existing one as it is. Please let us know what you think about that.

2024-01-16 20:10 UTC, tdcmeehan commented
@Hank27-zhang are you still working on this?

2024-09-06 19:15 UTC, agrawalreetika commented
Closing this in favour of https://github.com/prestodb/presto/pull/23567

2024-09-06 19:15 UTC, closed without merging