Update the Version of Dependency
prestodb/presto pull request #21094
Opened 2023-10-10 17:12 UTC by Akanksha-kedia

org.xerial.snappy:snappy-java vulnerabilities
org.apache.avro:avro vulnerabilities Upgrade to 1.11.0.
CVE-2022-45868: com.h2database 1.4.199 to 2.2.220

com.h2database : h2 : 2.2.220 -> The current version doesn't cause Release failure
org.apache.avro : avro :  Upgrade to 1.11.0
org.xerial.snappy : snappy-java : Upgrade to 1.1.10.4

2023-10-11 15:07 UTC, skairali commented
@Akanksha-kedia  Can you please fix the UT failures

2023-10-11 16:11 UTC, Akanksha-kedia commented
Sure.

On Wed, 11 Oct 2023 at 8:37 PM, Sudheesh ***@***.***> wrote:

> @Akanksha-kedia <https://github.com/Akanksha-kedia> Can you please fix
> the UT failures
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/prestodb/presto/pull/21094#issuecomment-1757907858>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVL2AZQOBUWBA53322TYUEDX62Y3LANCNFSM6AAAAAA52WDRJQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-10-16 08:42 UTC, Akanksha-kedia commented
[WARNING] Tests run: 26, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 103.531 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 26, Failures: 0, Errors: 0, Skipped: 1
 presto-kafka

2023-10-16 12:19 UTC, Akanksha-kedia commented
com.intellij.rt.testng.RemoteTestNGStarter -usedefaultlisteners false -socket56344 @w@/private/var/folders/pb/nyv26nh90dsbbnpcr22_h1880000gq/T/idea_working_dirs_testng.tmp -temp /private/var/folders/pb/nyv26nh90dsbbnpcr22_h1880000gq/T/idea_testng.tmp
2023-10-16T07:18:27.009-0500 INFO [TestNG] Running:
Library/Caches/JetBrains/IntelliJIdea2022.1/temp-testng-customsuite.xml


===============================================
Default Suite
Total tests run: 28, Passes: 28, Failures: 0, Skips: 0

2023-10-18 18:54 UTC, skairali requested changes
I suggest to close and rework this one

several checks failed

I see conflicts as well

2023-10-19 11:48 UTC, closed without merging