Improve layout of table for statistics in docs
prestodb/presto pull request #21112
Opened 2023-10-11 13:02 UTC by Akanksha-kedia

<img width="747" alt="Screenshot 2023-10-11 at 6 30 06 PM" src="https://github.com/prestodb/presto/assets/89628774/a9b743ef-d71c-4f39-a827-dcabb3391ecf">
<img width="787" alt="Screenshot 2023-10-11 at 6 30 13 PM" src="https://github.com/prestodb/presto/assets/89628774/6a4f41db-9d88-4c60-a53b-b86c4299368a">

2023-10-11 13:02 UTC, Akanksha-kedia commented
@steveburnett please help to review and edit the label as docs

2023-10-11 17:35 UTC, steveburnett commented on presto-docs/src/main/sphinx/sql/show-stats.rst
> +``SHOW STATS FOR table``: This command is used to show statistics for a specific table.
```suggestion
``SHOW STATS FOR table``: Show statistics for a specific table.
```

2023-10-11 17:36 UTC, steveburnett commented on presto-docs/src/main/sphinx/sql/show-stats.rst
> +``SHOW STATS FOR ( query )``: This command is used to show statistics for the result of a specific query.
```suggestion
``SHOW STATS FOR ( query )``: Show statistics for the result of a specific query.
```

2023-10-11 17:36 UTC, steveburnett commented on presto-docs/src/main/sphinx/sql/show-stats.rst
> +Any statistics that are not populated or unavailable on the data source will be returned as ``NULL``.
```suggestion
Any statistics that are not populated or unavailable on the data source are returned as ``NULL``.
```

2023-10-11 17:37 UTC, steveburnett commented on presto-docs/src/main/sphinx/sql/show-stats.rst
> +Also, any additional statistics collected on the data source other than those listed below
```suggestion
Any additional statistics collected on the data source other than those listed below
```

2023-10-11 17:38 UTC, steveburnett commented on presto-docs/src/main/sphinx/sql/show-stats.rst
> +are not included in the output of the ``SHOW STATS`` command. Statistics are returned as a row for each column and
```suggestion
are not included in the output of the ``SHOW STATS`` command. Because statistics are returned as a row for each column and
```

2023-10-11 17:38 UTC, steveburnett commented on presto-docs/src/main/sphinx/sql/show-stats.rst
> +summary row doesn't correspond to any specific column, so the ``column_name`` field in this row is ``NULL``.
```suggestion
summary row doesn't correspond to any specific column, the ``column_name`` field in this row is ``NULL``.
```

2023-10-11 17:39 UTC, steveburnett commented on presto-docs/src/main/sphinx/sql/show-stats.rst
> +    - ``NULL`` in the table summary row
```suggestion
    - ``NULL`` in the table summary row.
```

2023-10-11 17:40 UTC, steveburnett commented on presto-docs/src/main/sphinx/sql/show-stats.rst
> +    - ``NULL`` in the table summary row
```suggestion
    - ``NULL`` in the table summary row.
```

2023-10-11 17:41 UTC, steveburnett commented on presto-docs/src/main/sphinx/sql/show-stats.rst
> +    - ``NULL`` in column statistic rows
```suggestion
    - ``NULL`` in column statistic rows.
```

2023-10-12 05:19 UTC, Akanksha-kedia commented
@steveburnett  please review and approve.

2023-10-12 14:41 UTC, steveburnett requested changes
Thanks! One new comment that should be addressed, please.

2023-10-12 14:41 UTC, steveburnett commented on presto-docs/src/main/sphinx/sql/show-stats.rst
> +Any additional statistics collected on the data source other than those listed below are not included in the output
Lines 26-28: Your change merged two sentences into a very big sentence that I think would be easier to read and understand if it was separated into shorter sentences, similar to what I suggested in the first review. 

Consider replacing lines 26-28 with something like the following: 

```suggestion
Any additional statistics collected on the data source other than those listed below are not included in the output
of the ``SHOW STATS`` command. The summary row does not correspond to any specific column so the ``column_name`` value for the summary row is ``NULL``.
```

2023-10-13 04:30 UTC, Akanksha-kedia commented
@tdcmeehan @steveburnett please review and help to merge

2023-10-13 14:28 UTC, steveburnett approved these changes
LGTM! (docs) 

Suggest you change the commit message to something more descriptive. Maybe 

Improve layout of table for SHOW STATS in docs

2023-10-14 04:06 UTC, Akanksha-kedia commented
@tdcmeehan please review and help to merge.

2023-10-19 05:32 UTC, Akanksha-kedia commented
./piper build pr

2023-10-20 05:45 UTC, Akanksha-kedia commented
@tdcmeehan  help to merge.

2023-10-20 15:09 UTC, tdcmeehan approved these changes

2023-10-20 15:09 UTC, merged