Update com.fasterxml.jackson.core Version
prestodb/presto pull request #21170
Opened 2023-10-17 09:37 UTC by Akanksha-kedia

![image](https://github.com/prestodb/presto/assets/89628774/e856b408-2d31-4b57-a6a4-0f89c50e0c4f)

2023-10-18 00:50 UTC, 7c00 requested changes

2023-10-18 00:50 UTC, 7c00 commented on presto-hudi/pom.xml
> +            <version>2.13.2</version>
Let's use `{dep.jackson.version}` instead.

2023-10-18 00:50 UTC, 7c00 commented on presto-iceberg/pom.xml
> +                    <version>1.5.1</version>
it's unnecessary to specify the version as it is managed in base pom (airbase)

2023-10-18 00:53 UTC, 7c00 commented
@Akanksha-kedia Thanks for your contribution. I leave some comments. And please follow [Pull Request Checklist](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#pull-request-checklist) to update the PR description.

2023-11-06 05:57 UTC, jaystarshot commented on pom.xml
> -        <module>presto-docs</module>
I don't think this is intended

2023-11-06 05:58 UTC, Akanksha-kedia commented
Will check

On Mon, 6 Nov 2023 at 11:27 AM, Jay Narale ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In pom.xml
> <https://github.com/prestodb/presto/pull/21170#discussion_r1382813272>:
>
> > @@ -143,7 +144,6 @@
>          <module>presto-cli</module>
>          <module>presto-benchmark-driver</module>
>          <module>presto-server</module>
> -        <module>presto-docs</module>
>
> I don't think this is intended
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/prestodb/presto/pull/21170#pullrequestreview-1714313398>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVL2AZVL7MXAMUQP7JBGM7TYDB36HAVCNFSM6AAAAAA6DQ5OLOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMJUGMYTGMZZHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-11-06 05:59 UTC, jaystarshot reviewed
You will need to update the description of the PR as mentioned above with the template

2024-01-02 06:54 UTC, closed without merging