Updating documentation of MAP_TOP_N_KEYS
prestodb/presto pull request #21239
Opened 2023-10-25 10:11 UTC by jainavi17

## Description
Updating description of the UDF to make it super clear to the users

## Motivation and Context
We received feedback that developers assumed the function will return top n keys of the map based on the value of the map but that's not the intended behaviour of this UDF. We're updating the documentation to make it explicit to the users.

```
== NO RELEASE NOTE ==
```

2023-10-25 18:06 UTC, steveburnett requested changes
Thanks for the documentation! I made a couple of small suggestions. If my suggestions change the intended meaning in a way you feel is incorrect, let me know and I'm happy to discuss it.

2023-10-25 18:06 UTC, steveburnett commented on presto-docs/src/main/sphinx/functions/map.rst
>      ``n`` must be a non-negative integer
```suggestion
    ``n`` must be a non-negative integer.
    
```
Suggest adding a period at the end of this sentence, and adding a line to put "For bottom ``n`` keys," at the left margin so it better introduces its code example.

2023-10-25 18:06 UTC, steveburnett commented on presto-docs/src/main/sphinx/functions/map.rst
> +    Returns top n keys in the map ``x`` by sorting its keys using the given comparator ``function``. The comparator will take
```suggestion
    Returns top n keys in the map ``x`` by sorting its keys using the given comparator ``function``. The comparator takes
```

In general, avoid future tense such as "will" in documentation.

2023-10-26 13:58 UTC, jainavi17 commented
Hi @steveburnett I have made the adjustments, please have a look and let me know if it looks good now?  TIA

2023-10-26 15:24 UTC, steveburnett requested changes
Thanks for the fixes! I should have noticed these two very small formatting suggestions in my first review, my apologies for overlooking them then. 

Please make these two changes and I'll be happy to approve this doc.

2023-10-26 15:24 UTC, steveburnett commented on presto-docs/src/main/sphinx/functions/map.rst
> +    Returns top n keys in the map ``x`` by sorting its keys in descending order.
```suggestion
    Returns top ``n`` keys in the map ``x`` by sorting its keys in descending order.
```
Suggest for formatting  consistency with line 111.

2023-10-26 15:24 UTC, steveburnett commented on presto-docs/src/main/sphinx/functions/map.rst
> +    Returns top n keys in the map ``x`` by sorting its keys using the given comparator ``function``. The comparator takes
```suggestion
    Returns top ``n`` keys in the map ``x`` by sorting its keys using the given comparator ``function``. The comparator takes
```
Suggest for formatting  consistency with line 111.

2023-10-27 08:44 UTC, jainavi17 commented
Thanks @steveburnett  for taking to review the diff. Have made the changes. If you could approve it.

2023-10-27 14:45 UTC, steveburnett approved these changes
LGTM! (docs)

Local build of docs, everything looks good.

2023-10-27 14:45 UTC, steveburnett commented
> Thanks @steveburnett for taking to review the diff. Have made the changes. If you could approve it.

You're welcome! I have reviewed your latest changes and everything looks good.

2023-10-30 10:17 UTC, jainavi17 commented
@NikhilCollooru can we merge this PR?

2023-10-30 16:22 UTC, NikhilCollooru approved these changes

2023-10-30 16:22 UTC, merged