Describe Lead/Lag + Null Offset behavior more clearly
prestodb/presto pull request #21244
Opened 2023-10-25 23:28 UTC by xumingming

## Description

Describe Lead/Lag + Null Offset behavior more clearly: when the offset is null, return null(not default value).
Fixes #20835

## Motivation and Context
N/A

## Impact
N/A

## Test Plan
N/A

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes

```
== NO RELEASE NOTE ==
```

2023-10-26 16:25 UTC, steveburnett requested changes
Thanks for the documentation! I have made a couple of formatting suggestions for consistency, but I noticed no other concerns.

2023-10-26 16:25 UTC, steveburnett commented on presto-docs/src/main/sphinx/functions/window.rst
> +    offset is null, null is returned. If the offset refers to a row that is not
```suggestion
    offset is ``null``, ``null`` is returned. If the offset refers to a row that is not
```
Suggest formatting change for consistency with lines 198 and 207.

2023-10-26 16:25 UTC, steveburnett commented on presto-docs/src/main/sphinx/functions/window.rst
> +    offset is null, null is returned. If the offset refers to a row that is not
```suggestion
    offset is null, null is returned. If the offset refers to a row that is not
```
Suggest formatting change for consistency with lines 198 and 207.

2023-10-26 23:44 UTC, xumingming commented
@steveburnett Addressed the review comments.

2023-10-27 14:24 UTC, steveburnett approved these changes
LGTM! (docs) 

Thanks for the doc!

2023-10-27 22:16 UTC, aditi-pandit commented
Thanks @xumingming.

2023-10-27 22:16 UTC, merged

2023-10-27 22:58 UTC, mbasmanova commented
@xumingming Folks, next time please check commit messages. We should not have "Address review comments" commits.

2023-10-27 23:21 UTC, xumingming commented
@mbasmanova Ahh, I was thing leaving the commit which address the review comments separately would make the review more convenient to see what's changed incrementally. You prefer all commits rebased into one commit or separate commits with better commit messages?

2023-10-27 23:27 UTC, mbasmanova commented
@xumingming See https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#pull-request-checklist

2023-10-28 10:51 UTC, mbasmanova commented
@xumingming Presto project setup is different from Velox. Presto allows multi-commit PRs while Velox does not. When Presto PR is merged, all commits in the PR are rebased and merged as is. Here is what currently git log looks like:

```
2a18649d81 Add null stats for join probe
54edca6cf1 Address review comments
69bed7f13e Describe Lead/Lag + Null Offset behavior more clearly
b67703aece Support indicating partition transform when add column to Iceberg table
...
```

Notice the "Address review comments". This commit is not helpful and he commit "Describe Lead/Lag + Null Offset behavior more clearly" is not complete making it difficult to use gi blame / git log to research how the changes came to being.

When Velox PR is merged, all commits are squashed and a new commit message is created using PR title and description. Hence, in Velox, every PR ends up in a single commit on main. Hence, in Velox, it doesn't matter how many commits you have or what their commit messages. What matters is the PR title and description.

Hope this clarifies things. Let me know if you have any follow-up questions.

2023-10-28 11:02 UTC, xumingming commented
@mbasmanova Thanks for the detailed explanation, got it now. I was indeed feel a bit confused at first, because I see several times "Address review comments" commit in Velox PRs. All things clear now.