SQL statements support simple literal, as well as Unicode usage
prestodb/presto pull request #21314
Opened 2023-11-06 08:12 UTC by Akanksha-kedia

Description
This PR adds examples and documentation for using simple literal and Unicode strings in SQL statements, including how to escape single quotes in string literals.

Motivation and Context
The motivation behind this change is to provide clearer instructions and examples for users on how to use and escape different types of string literals in SQL statements.

Impact
This change will not affect the public API or any user-facing features. There will be no performance impact.

Test Plan
To test these changes, we can create SQL statements using both simple literal and Unicode strings, and check that they are processed correctly. We should also test the escaping of single quotes in string literals to ensure this works as expected.

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
General Changes
* Added documentation and examples for using simple literal and Unicode strings in SQL statements, including how to escape single quotes in string literals.
```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2023-11-06 12:16 UTC, Akanksha-kedia commented
@tdcmeehan  Query 20231106_121407_00007_gs92g, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
[Latency: client-side: 0:01, server-side: 0:01] [0 rows, 0B] [0 rows/s, 0B/s]

presto> SELECT * FROM memory.default.test_table;
                  my_column                  
---------------------------------------------
 I am big, it's the pictures that got small! 
 Hello winter <E2><98><83> !                            
 Hello winter!                               
 Hello winter <E2><98><83> !                            
(4 rows)

Query 20231106_121412_00008_gs92g, FINISHED, 1 node
Splits: 26 total, 26 done (100.00%)
[Latency: client-side: 0:01, server-side: 0:01] [4 rows, 112B] [6 rows/s, 186B/s]

<img width="1728" alt="Screenshot 2023-11-06 at 5 37 58 PM" src="https://github.com/prestodb/presto/assets/89628774/0f258103-8ce5-4f08-94b8-91b644b7c825">

2023-11-06 18:39 UTC, steveburnett requested changes
Thanks for the documentation! I made one specific comment. Here are other concerns I ask you to address and resubmit: 

* The lack of formatting in lines 107-118 make it hard to understand what is code and what is not. Please format the text that is meant as code with two ` before and after to improve readability. Examine the ``CHAR`` paragraph in lines 124-128 and use that as a model for consistent formatting. 
 
* The two sentences beginning "For example" and the _I am big_ example should be indented as part of their respective bullet points. 

As it is, a local build of the docs for this section looks like this: 
<img width="964" alt="Screenshot 2023-11-06 at 1 26 54 PM" src="https://github.com/prestodb/presto/assets/7013443/fe435d18-75e6-4a38-ac6f-5f323be3836d">

2023-11-06 18:39 UTC, steveburnett commented on presto-docs/src/main/sphinx/language/types.rst
> +    SQL supports various types of string literals, including simple and Unicode strings:
```suggestion
    SQL supports simple and Unicode string literals:
```

Suggested editing for conciseness and precision. "Various types...including" is vague and does not add information to the sentence.

2023-11-07 05:40 UTC, Akanksha-kedia commented
<img width="838" alt="Screenshot 2023-11-07 at 10 47 55 AM" src="https://github.com/prestodb/presto/assets/89628774/9ac4448d-1d3d-4bdf-b9da-c275d3acfd59">

2023-11-07 05:41 UTC, Akanksha-kedia commented
@steveburnett please review

2023-11-07 16:17 UTC, steveburnett requested changes
A few suggestions for improving the reader's ability to use the examples, and conciseness.

2023-11-07 16:17 UTC, steveburnett commented on presto-docs/src/main/sphinx/language/types.rst
> +     - Literal string : ``'Hello winter !'``.
```suggestion
     - Literal string : ``'Hello winter !'``
```
Either all, or none, of the items in a bulleted list need punctuation. If one requires punctuation then they all must. 

In this case, you end each item with inline code. Readers who copy your code examples may accidentally include the period at the end of the list item. Suggest removing the not wrong, but not needed punctuation to improve the reader's use of the doc. Remove the punctuation from every item in this list.

2023-11-07 16:17 UTC, steveburnett commented on presto-docs/src/main/sphinx/language/types.rst
> +     - Unicode string with default escape character: ``U&'Hello winter \2603 !'``.
```suggestion
     - Unicode string with default escape character: ``U&'Hello winter \2603 !'``.
```

2023-11-07 16:17 UTC, steveburnett commented on presto-docs/src/main/sphinx/language/types.rst
> +     - Unicode string with custom escape character: ``U&'Hello winter #2603 !' UESCAPE '#'``.
```suggestion
     - Unicode string with custom escape character: ``U&'Hello winter #2603 !' UESCAPE '#'``
```

2023-11-07 16:17 UTC, steveburnett commented on presto-docs/src/main/sphinx/language/types.rst
> +    before any Unicode character usage with 4 digits. In the examples above
```suggestion
    before any Unicode character usage with 4 digits. In these examples
```

2023-11-07 16:17 UTC, steveburnett commented on presto-docs/src/main/sphinx/language/types.rst
> +    with 6 digits require usage of the plus symbol before the code. For example,
```suggestion
    with 6 digits require a plus symbol ``+`` before the code. For example,
```

2023-11-07 16:17 UTC, steveburnett commented on presto-docs/src/main/sphinx/language/types.rst
> +    you need to use ``\+01F600`` for a grinning face emoji.
```suggestion
    use ``\+01F600`` for a grinning face emoji.
```

2023-11-08 15:20 UTC, steveburnett commented
> Please properly attribute the origin of this documentation.

Has this been addressed?

2023-11-08 15:22 UTC, steveburnett reviewed
LGTM! (docs) 

Local build looks okay. Thanks! 

Not Approving yet because of the open question about the proper attribution of the documentation.

2023-11-08 15:24 UTC, Akanksha-kedia commented
I have added co author as well

On Wed, 8 Nov 2023 at 8:53 PM, Steve Burnett ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> LGTM! (docs)
>
> Local build looks okay. Thanks!
>
> Not Approving yet because of the open question about the proper
> attribution of the documentation.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/prestodb/presto/pull/21314#pullrequestreview-1720628013>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVL2AZULLIA5SFPN7EJYFD3YDOPVZAVCNFSM6AAAAAA67CZM5WVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMRQGYZDQMBRGM>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-11-08 15:48 UTC, tdcmeehan approved these changes

2023-11-08 17:32 UTC, steveburnett approved these changes

2023-11-08 18:51 UTC, merged