Add docs for Prestodb to postgresql type mapping in postgresql connector
prestodb/presto pull request #21387
Opened 2023-11-15 05:12 UTC by Akanksha-kedia

##Description
This document aims to provide a comprehensive guide for PrestoDB to PostgreSQL type mapping within the PostgreSQL connector.

##Motivation and Context
The motivation behind this improvement is to enhance our PostgreSQL documentation. By providing clear type mapping details between PrestoDB and PostgreSQL, we can assist users in understanding how data types correlate and convert between these two systems.

##Impact
The main impact of this documentation is to provide clear and concise information about type mapping from PrestoDB to PostgreSQL and vice versa. This will help users in designing and implementing their data models and queries more efficiently and accurately.

##Test Plan
While there is no specific test plan for this documentation, the information provided has been validated through practical application. Tables were created in both PostgreSQL and PrestoDB, and the type mapping was cross-checked to ensure accuracy. Users are encouraged to perform similar tests to further familiarize themselves with the type mapping process.

[
<img width="740" alt="Screenshot 2023-11-15 at 10 23 02 AM" src="https://github.com/prestodb/presto/assets/89628774/3bb6a51f-58a9-4201-ab50-5db7da256f86">
<img width="1238" alt="Screenshot 2023-11-15 at 10 25 37 AM" src="https://github.com/prestodb/presto/assets/89628774/9f39fbab-fdfd-484a-967d-8dd008c37aea">
<img width="560" alt="Screenshot 2023-11-15 at 10 26 16 AM" src="https://github.com/prestodb/presto/assets/89628774/35652032-f234-45ad-897a-b844e9a32aaa">
<img width="681" alt="Screenshot 2023-11-15 at 10 30 38 AM" src="https://github.com/prestodb/presto/assets/89628774/1aa49903-9bc7-4323-bec1-0b12913a6837">
<img width="859" alt="Screenshot 2023-11-15 at 10 33 23 AM" src="https://github.com/prestodb/presto/assets/89628774/125abde0-8be5-4a94-b4e3-667fb38ae1cd">
](url)
## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2023-11-15 05:14 UTC, Akanksha-kedia commented
@tdcmeehan , 
@steveburnett please help to review

2023-11-15 18:14 UTC, steveburnett requested changes
Made suggestions to parallel your similar work in https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/connector/mysql.rst.

Also, the tables on this page look squashed narrow compared to the same tables on  https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/connector/mysql.rst , see screenshots. 

<img width="812" alt="Screenshot 2023-11-15 at 1 05 05 PM" src="https://github.com/prestodb/presto/assets/7013443/f345b6fe-2605-4856-a779-16e5cb3ec682">
<img width="622" alt="Screenshot 2023-11-15 at 1 05 09 PM" src="https://github.com/prestodb/presto/assets/7013443/22073f58-1f0c-4391-9eef-29a797e963d6">

2023-11-15 18:14 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/postgresql.rst
> +.. list-table:: PrestoDB type to PostgreSQL type mapping
```suggestion
.. list-table:: PrestoDB to PostgreSQL type mapping
```
Change suggested to parallel https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/connector/mysql.rst

2023-11-16 04:25 UTC, Akanksha-kedia commented
@steveburnett please check.

2023-11-16 04:27 UTC, Akanksha-kedia commented
> Made suggestions to parallel your similar work in https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/connector/mysql.rst.
> 
> Also, the tables on this page look squashed narrow compared to the same tables on https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/connector/mysql.rst , see screenshots.
> 
> <img alt="Screenshot 2023-11-15 at 1 05 05 PM" width="812" src="https://user-images.githubusercontent.com/7013443/283209663-f345b6fe-2605-4856-a779-16e5cb3ec682.png"> <img alt="Screenshot 2023-11-15 at 1 05 09 PM" width="622" src="https://user-images.githubusercontent.com/7013443/283209668-22073f58-1f0c-4391-9eef-29a797e963d6.png">

its becoz 
BINARY, VARBINARY, TINYBLOB, BLOB, MEDIUMBLOB, LONGBLOB | VARBINARY
-- | --
in mysql.rst

2023-11-16 15:26 UTC, steveburnett requested changes
Nice, thanks! A few minor nits for consistency.

2023-11-16 15:26 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/postgresql.rst
> +PostgreSQL type to PrestoDB type mapping
```suggestion
PostgreSQL to PrestoDB type mapping
```
Change suggested to parallel https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/connector/mysql.rst

2023-11-16 15:26 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/postgresql.rst
> +PrestoDB type to PostgreSQL type mapping
This is not addressed yet. Change suggested to parallel https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/connector/mysql.rst
<img width="653" alt="Screenshot 2023-11-16 at 10 24 15 AM" src="https://github.com/prestodb/presto/assets/7013443/0ad992e1-f4ad-4636-8590-1e577c9a36af">

2023-11-16 15:26 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/postgresql.rst
> +No other types are supported
```suggestion
No other types are supported.
```

2023-11-20 02:56 UTC, Akanksha-kedia commented
@steveburnett  please review

2023-11-20 15:26 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/postgresql.rst
> +PrestoDB type to PostgreSQL type mapping
This is still not addressed. Screenshot is from a build this morning. Before you mark a conversation as resolved, please build the doc locally and verify you've made the change. 
<img width="665" alt="Screenshot 2023-11-20 at 10 22 43 AM" src="https://github.com/prestodb/presto/assets/7013443/509a492e-83a8-42c7-a75b-68c63f897a18">

2023-12-05 05:21 UTC, Akanksha-kedia commented
@steveburnett please review, i made the necessary chnages.

2023-12-05 14:46 UTC, steveburnett approved these changes
LGTM! (docs)

Thanks for updating the release notes entry!

2023-12-05 16:39 UTC, tdcmeehan approved these changes

2023-12-05 16:40 UTC, merged