add compation for old data
prestodb/presto pull request #21391
Opened 2023-11-15 09:59 UTC by ico01

## Description
This PR modifies the handling of the hive.orc.use-column-names configuration setting in Presto to allow for improved compatibility with older ORC data that may not contain column names in the file. The new strategy uses ORC file column names by default and falls back to Hive schema column names when ORC names are not present.

## Motivation and Context
The ability for Presto to flexibly handle column names in ORC files is critical for accessing a wide range of data, including legacy datasets that may not contain embedded column names. The original hive.orc.use-column-names configuration setting only allowed access via column names and did not account for files without them. This approach helps mitigate issues with reading old ORC data and ensures that users can access their datasets consistently without manual intervention.

## Impact
The changes to hive.orc.use-column-names represent an enhancement to the existing functionality rather than a breaking change. Users specifying this option will now benefit from an intelligent fallback mechanism. There should be no performance impact as the fallback only occurs when required, and there are no changes to the public API.

## Test Plan
The changes have been tested using both new and old ORC files—both those with embedded column names and those without. The Presto cluster correctly accessed column data using the appropriate naming strategy in each case. Additional unit tests specific to the column naming fallback logic have been added to ensure the feature works as intended.

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

Hive Changes
* The `hive.orc.use-column-names` configuration setting no longer fails on reading ORC files without column names. Now it falls back to using Hive's schema, enhancing compatibility with legacy ORC files.

```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2023-11-16 02:23 UTC, jaystarshot commented
Is it possible to add unit testing? I can see some related tests at  testHiveFileFormats

2023-11-16 03:01 UTC, ico01 commented
> Is it possible to add unit testing? I can see some related tests at testHiveFileFormats

ok, i just did't know where to test

2023-11-16 09:38 UTC, ico01 commented
@jaystarshot i add unit test for it

2023-11-16 12:30 UTC, jaystarshot submitted a review, later dismissed
lgtm, deferring to a orc expert for any concerns

2023-11-16 18:02 UTC, tdcmeehan commented
CC: @sdruzkin

2023-11-30 04:44 UTC, ico01 commented
@tdcmeehan @sdruzkin @mbasmanova It's has been two weeks since last action, what should i do now

2023-11-30 17:17 UTC, tdcmeehan requested changes
Some nits.  Overall, after reading through the ORC spec, this change seems fine.  Pinging @sdruzkin one last time as our ORC expert, otherwise I'm happy to merge once the nits are addressed.

2023-11-30 17:17 UTC, tdcmeehan commented on presto-hive/src/main/java/com/facebook/presto/hive/HiveUtil.java
> +    private static boolean isFileHasColumnNames(List<String> physicalColumnNames, Path path)
```suggestion
    private static boolean fileHasColumnNames(List<String> physicalColumnNames, Path path)
```

2023-11-30 17:17 UTC, tdcmeehan commented on presto-hive/src/main/java/com/facebook/presto/hive/HiveUtil.java
> +        return hasColumnNames;
```java
    return physicalColumnNames.isEmpty || !physicalColumnNames.stream().allMatch(physicalColumnName -> DEFAULT_HIVE_COLUMN_NAME_PATTERN.matcher(physicalColumnName).matches())
```

2023-12-06 03:53 UTC, ico01 commented
thanks,I will fix these

2024-03-06 15:16 UTC, steveburnett commented
Suggest revising release note entry following the [Order of changes](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines#order-of-changes) in the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines). Perhaps something like this: 

```
== RELEASE NOTES ==

Hive Changes
* Improves the `hive.orc.use-column-names` configuration setting to no longer fail on reading ORC files 
  without column names but falls back to using Hive's schema, enhancing compatibility with legacy ORC files.
```

2024-03-07 10:36 UTC, ico01 commented on presto-hive/src/test/java/com/facebook/presto/hive/TestHiveFileFormats.java
> +        //Creates a new list of TestColumn objects with Hive-style column names based on their indices.
fixed

2024-03-07 10:36 UTC, ico01 commented on presto-hive/src/test/java/com/facebook/presto/hive/TestHiveFileFormats.java
> +        // only have old hive style name _col1, _clo2, _clo3
fixed

2024-03-07 10:36 UTC, ico01 commented on presto-hive/src/test/java/com/facebook/presto/hive/TestHiveFileFormats.java
> +        // test hive.orc.use-column-names can fallback to use hive column names, if in orc file has no real column name
fixed

2024-03-07 10:37 UTC, ico01 commented on presto-hive/src/main/java/com/facebook/presto/hive/HiveUtil.java
> +        return hasColumnNames;
fixed

2024-03-07 10:37 UTC, ico01 commented on presto-hive/src/main/java/com/facebook/presto/hive/HiveUtil.java
> +    private static boolean isFileHasColumnNames(List<String> physicalColumnNames, Path path)
fixed

2024-03-07 10:37 UTC, ico01 commented on presto-hive/src/main/java/com/facebook/presto/hive/HiveUtil.java
> +        boolean hasColumnNames = isFileHasColumnNames(columnNames, path);
fixed

2024-03-08 16:32 UTC, tdcmeehan approved these changes

2024-03-09 08:43 UTC, ico01 commented
i found it's very difficult to run all check passed, each time it will have different test not passed. even though i didn't change code

2024-03-09 16:16 UTC, tdcmeehan commented
@ico01 the CI environment has become unstable lately.  We are working on making it more stable again.  In the meantime, maintainers will ensure tests pass and will merge.

2024-03-10 02:42 UTC, ico01 commented
ok

2024-04-16 16:43 UTC, merged