Update CONTRIBUTING.md with development and contribution documentation
prestodb/presto pull request #21450
Opened 2023-11-28 18:10 UTC by VishnuSanal

## Description

## Motivation and Context

fixes #19834

## Impact

## Test Plan

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [x] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== NO RELEASE NOTE ==
```

2023-11-28 20:42 UTC, steveburnett commented
I'm glad you took the initiative to get this moving! This looks good as a combination of the Presto [CONTRIBUTING.md](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md) with [README.md](https://github.com/prestodb/presto/blob/master/README.md). 

My assumption here is that the intent of #19834 is to reduce the number of pages, making it easier to find content. 

I also assume that if [CONTRIBUTING.md](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md) and [README.md](https://github.com/prestodb/presto/blob/master/README.md) are combined, that one of the two will go away. 

(If we keep both pages we run the risk of the same content on separate pages becoming out of sync and at least one being out of date.)

Let me know if my assumptions are incorrect!

Perhaps it might be better to combine the two files the other way, into README.md, as I believe README is more common a default starting page for a repo than CONTRIBUTING.

2023-11-29 14:13 UTC, steveburnett commented
@VishnuSanal please sign the Contributor License Agreement to make contributions to Presto. For more information, see the [Contributor License Agreement](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) topic in [CONTRIBUTING.md](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md).  

To sign a CLA, see the message above from the [linux-foundation-easycla](https://github.com/apps/linux-foundation-easycla) bot, and follow the link in [Please click here to be authorized](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/4238753/5349565/21450/#/?version=2).

2023-11-29 16:17 UTC, steveburnett commented
@VishnuSanal , after you've signed the CLA, you can re-run the tests and pass the failing EasyCLA test. To do so, squash your commits and push, as described in the [Pull Release Checklist](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#pull-request-checklist) topic in [CONTRIBUTING.md](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md).

2023-12-15 06:40 UTC, VishnuSanal commented
hi, this is ready for review. I have moved the contribution guidelines exclusively to the CONTRIBUTING.md file & removed 'em from the project README. a link to CONTRIBUTING.md was given from the README to make it accessible. expecting a review & corrections if my assumptions are wrong, thanks!

2023-12-15 21:47 UTC, tdcmeehan requested changes
Two minor comments--I think the examples need updating

2023-12-15 21:47 UTC, tdcmeehan commented on CONTRIBUTING.md
> +- Example PR message
This is not accurate.  Please look at the PR template.

2023-12-15 21:47 UTC, tdcmeehan commented on CONTRIBUTING.md
> +Cherry-pick of https://github.com/foo/bar/pull/123/commits/c2bf3b025ff456921c4c5ff4bcb814740e823061 (https://github.com/foo/bar/pull/123/commits/c2bf3b025ff456921c4c5ff4bcb814740e823061)
```suggestion
Cherry-pick of c2bf3b0 (https://github.com/foo/bar/pull/123/commits/c2bf3b025ff456921c4c5ff4bcb814740e823061)
```

2023-12-18 15:12 UTC, tdcmeehan commented
Please squash commits--thanks!

2023-12-19 16:19 UTC, tdcmeehan commented
Looks good, but please rewrite the commit message to conform to our guidelines.  Consider: `Improve CONTRIBUTING.md`

2023-12-20 20:48 UTC, tdcmeehan approved these changes

2023-12-20 20:48 UTC, tdcmeehan commented
Thank you @VishnuSanal

2023-12-20 20:48 UTC, merged