[native]Advance velox and update memory part
prestodb/presto pull request #21559
Opened 2023-12-16 19:36 UTC by xiaoxmeng

Update the memory management code based on velox side change.
To ensure not breaking Meta internal build, we temporarily switch to
use deprecated APIs instead of calling MemoryManager::getInstance()
which currently has two versions

2023-12-18 22:07 UTC, aditi-pandit approved these changes

2023-12-19 00:31 UTC, tanjialiang approved these changes
Thanks for the fix

2023-12-19 01:25 UTC, majetideepak requested changes
@xiaoxmeng can you please add a description of the changes to the commit?
It is not clear to me what `deprecatedAddDefaultLeafMemoryPool` does.
Thank you!

2023-12-19 02:12 UTC, xiaoxmeng commented
> @xiaoxmeng can you please add a description of the changes to the commit? It is not clear to me what `deprecatedAddDefaultLeafMemoryPool` does. Thank you!

Updated. It is to be compatible with Meta internal code once the deprecated getInstance() is removed and
we can cleanup this part. Thanks!

2023-12-19 03:09 UTC, majetideepak approved these changes
@xiaoxmeng Thanks! Please update the git commit description as well next time.
It's fine this time since this is a temporary change.

2023-12-19 04:27 UTC, tanjialiang approved these changes

2023-12-19 04:31 UTC, merged