Preserve original page objects when region remains unchanged
prestodb/presto pull request #21566
Opened 2023-12-18 17:31 UTC by Akanksha-kedia

## Description
Optimized code to preserve the original page objects when the region remains unchanged. This means that new objects will no longer be created unnecessarily when the region is the same as the original page.

## Motivation and Context
By avoiding the creation of new objects when the region is the same as the original page, we can reduce memory usage

## Impact

## Test Plan
NO MAJOR IMPACT, PRESTO-COMMON MODULE
Unit tests to verify that new objects are not created when the region remains unchanged in presto-common module.
[INFO] Tests run: 261, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.106 s - in TestSuite
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 261, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 41.197 s
[INFO] Finished at: 2023-12-15T14:43:24+05:30
[INFO] ------------------------------------------------------------------------

[INFO] Tests run: 264, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.527 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 264, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  56.268 s
[INFO] Finished at: 2023-12-18T22:53:56+05:30
[INFO] ------------------------------------------------------------------------
akedia@WM-TQRH2J4TPW presto-common % git status

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes

```
== NO RELEASE NOTE ==
```

2023-12-18 17:36 UTC, Akanksha-kedia commented
@tdcmeehan some issue with old pr closed and created new one, please review this.

2023-12-18 18:29 UTC, tdcmeehan requested changes

2023-12-18 18:29 UTC, tdcmeehan commented on presto-common/src/main/java/com/facebook/presto/common/Page.java
> +        //It creates a new page with the specified region.
```suggestion
        // Avoid creating new objects when region is same as original page
        if (positionOffset == 0 && length == positionCount) {
            return this;
        }
        // Create a new page view with the specified region
```

2023-12-19 15:26 UTC, tdcmeehan approved these changes

2023-12-19 15:26 UTC, merged