Control number of writers for CTE materialization effectively
prestodb/presto pull request #21625
Opened 2024-01-04 01:29 UTC by jaystarshot

…arate CTE hash paritition count session property

## Description

## Motivation and Context

## Impact

## Test Plan

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2024-01-11 22:59 UTC, feilong-liu approved these changes

2024-01-12 15:57 UTC, tdcmeehan approved these changes

2024-01-12 20:19 UTC, steveburnett commented
Could documentation for this new session property be added? Possibly in [Properties Reference](https://prestodb.io/docs/0.284/admin/properties.html).

2024-01-17 15:30 UTC, steveburnett requested changes
Thanks for the documentation! One nit only.

2024-01-17 15:30 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/properties.rst
> +    This setting determines how many buckets/writers should be used when materializing the CTEs, potentially affecting the performance of queries involving CTE materialization.
```suggestion
    This setting determines how many buckets or writers should be used when materializing the CTEs, potentially affecting the performance of queries involving CTE materialization.
```
Avoid slashes. See [GitLab doc recommended word list entry for slashes](https://docs.gitlab.com/ee/development/documentation/styleguide/word_list.html#slashes) for advice and suggestions.

2024-01-17 19:01 UTC, jaystarshot commented
Added the docs, but isn't this page redundant since we already have @ConfigDescription? Does it make more sense to add @ConfigDescription to all new session properties and pull them in the docs page during releases?

2024-01-17 19:40 UTC, steveburnett commented
> Added the docs, but isn't this page redundant since we already have @ConfigDescription? Does it make more sense to add @ConfigDescription to all new session properties and pull them in the docs page during releases?

That's a great idea! I'll look into this possibility for generating the docs. Thanks very much for bringing it up.

2024-01-22 20:35 UTC, jaystarshot commented
@steveburnett  Added documentation for cte-materialization-strategy property, please review

2024-01-22 21:13 UTC, steveburnett approved these changes
LGTM! (docs)

Pull branch, local build of docs, looks good. Thanks!

2024-01-22 21:21 UTC, tdcmeehan requested changes
LGTM % nit on the first commit, and please also add session property documentation.

Please make sure it follows our guidelines.  Suggested:

```
Add cte_hash_partition_count and config property
This commit adds the `cte_hash_partition_count`, and corresponding config property `query.cte-hash-partition-count`, which controls number of writers for CTE materialization effectively
```

2024-01-22 21:29 UTC, steveburnett requested changes
Took another look, two minor suggestions.

2024-01-22 21:29 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/properties.rst
> +    The name of the catalog to be used for cte materialization and which provides custom partitioning for Common Table Expression (CTE) materialization.
```suggestion
    The name of the catalog to be used for Common Table Expressions (CTE) materialization and which provides custom partitioning for CTE materialization.
```

2024-01-22 21:29 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/properties.rst
> +    This setting specifies which catalog should be used for cte materialization and for determining how to partition the materialization of CTEs in queries.
```suggestion
    This setting specifies which catalog should be used for CTE materialization and for determining how to partition the materialization of CTEs in queries.
```

2024-01-22 21:50 UTC, steveburnett requested changes
The tiniest of nits.

2024-01-22 21:50 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/properties.rst
> +    Recommended value: 4 - 10x times the size of the cluster
```suggestion
    Recommended value: 4 - 10x times the size of the cluster.
```
Without the period the paragraph looks like this in a new build
<img width="1041" alt="Screenshot 2024-01-22 at 4 47 32 PM" src="https://github.com/prestodb/presto/assets/7013443/dd238099-4f44-49c7-8bca-2f824c2798dd">

2024-01-22 22:38 UTC, steveburnett approved these changes
LGTM! (docs)

Pull branch, local build of docs.

2024-01-23 02:00 UTC, tdcmeehan approved these changes

2024-01-23 02:10 UTC, merged