Deprecate hive config `hive.s3.use-instance-credentials`
prestodb/presto pull request #21648
Opened 2024-01-07 23:25 UTC by imjalpreet

## Description

After the introduction of DefaultAWSCredentialsProviderChain, this config has become redundant as instance credentials can still be used even if this config is false, as they are the last item in the DefaultAWSCredentialsProviderChain.

## Motivation and Context

#21633 

## Impact

Deprecation of config `hive.s3.use-instance-credentials`

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

Hive Changes
* Deprecate hive config ``hive.s3.use-instance-credentials``. This config will be removed in the upcoming release (:issue:`21633`)
```

2024-01-08 16:47 UTC, steveburnett requested changes
Thanks for adding the doc that this property is deprecated! 

Documentation should use the present tense and describe only the current state of the software. See the Google developer documentation style guide for [present tense](https://developers.google.com/style/tense), [Document future features](https://developers.google.com/style/future), and [Timeless documentation](https://developers.google.com/style/timeless-documentation).

When this property is removed, I also suggest that its deletion is included in the release notes for that release.

2024-01-08 16:47 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/hive.rst
> +                                              **Note:** This property is deprecated and it will be
```suggestion
                                              **Note:** This property is deprecated.
```

2024-01-08 16:47 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/hive.rst
> +                                              removed in the upcoming release.
```suggestion
```

2024-01-09 13:40 UTC, yingsu00 approved these changes
lgtm for non-doc part

2024-01-09 15:45 UTC, tdcmeehan approved these changes

2024-01-09 20:33 UTC, imjalpreet commented
Thanks for the review @steveburnett @yingsu00 @tdcmeehan. I have updated the PR.

2024-01-10 02:16 UTC, merged