Remove the dependency of kCastToIntByTruncate in Velox
prestodb/presto pull request #21663
Opened 2024-01-10 01:18 UTC by rui-mo

## Description
The config `kCastToIntByTruncate` is going to be removed from Velox, so we need to remove the dependency to it in presto_cpp.

## Motivation and Context

A refactor on cast is going on in Velox, which will remove unneeded configs.
https://github.com/facebookincubator/velox/pull/7377#issuecomment-1883846849

## Impact

N.A.

## Test Plan

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== NO RELEASE NOTE ==
```

2024-01-10 17:58 UTC, aditi-pandit approved these changes
Thanks @rui-mo

2024-01-10 18:00 UTC, aditi-pandit commented
@rui-mo : Please can you sign the CLA. I tried re-running some failed tests and was unable to trigger workflows for you.

2024-01-11 03:16 UTC, rui-mo commented
@aditi-pandit Thanks for your review! I signed the CLA and updated this PR.

2024-01-11 11:24 UTC, mbasmanova reviewed
@rui-mo Rui, thank you for the change.

Please, update commit message to [native] Remove deprecated config kCastToIntByTruncate

Presto is setup differently from Velox. In Velox, all commits are squashed and final commit uses PR's title + description as commit message on merge. In Presto, commits are merged as is.

2024-01-11 11:24 UTC, mbasmanova requested changes
Will approve once commit message is updated.

2024-01-11 12:34 UTC, rui-mo commented
@mbasmanova Thank you. Understood. Updated the commit message as suggested.

2024-01-11 12:36 UTC, mbasmanova approved these changes
Thanks! Ping me when tests are green and I'll merge.

2024-01-11 13:23 UTC, rui-mo commented
@mbasmanova The CI passes. Could you help merge? Thanks.

2024-01-11 13:24 UTC, merged

2024-01-11 13:24 UTC, mbasmanova commented
@rui-mo Thank you, Rui.