Direct vulnerabilities for io.grpc
prestodb/presto pull request #21668
Opened 2024-01-10 07:09 UTC by Akanksha-kedia

## Description
outlines the direct vulnerabilities and vulnerabilities from dependencies for io.grpc and com.google.protobuf.

## Motivation and Context
The io.grpc package, specifically the grpc-protobuf artifact version 1.35.0, has several identified vulnerabilities:

Direct vulnerabilities:

[CVE-2023-32732](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-32732)
[CVE-2023-32731](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-32731)
[CVE-2023-1428](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-1428)
Vulnerabilities from dependencies:

[CVE-2023-2976](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-2976)
[CVE-2022-3510](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-3510)
[CVE-2022-3509](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-3509)
[CVE-2022-3171](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-3171)
[CVE-2021-22570](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-22570)
[CVE-2021-22569](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-22569)
[CVE-2020-8908](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-8908)
The com.google.protobuf package, specifically the protobuf-java artifact version 3.12.0, has several identified vulnerabilities:

Direct vulnerabilities:

[CVE-2022-3510](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-3510)
[CVE-2022-3509](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-3509)
[CVE-2022-3171](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-3171)
[CVE-2021-22570](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-22570)
[CVE-2021-22569](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-22569)
Vulnerabilities from dependencies:

[CVE-2023-2976](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-2976)
[CVE-2020-8908](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-8908)
[CVE-2020-15250](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-15250)

## Impact
At this time, these vulnerabilities are not expected to have a major impact.

## Test Plan
Unit tests for presto-bigquery and other relevant components will be conducted to ensure system stability.

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes

== NO RELEASE NOTE ==

2024-01-10 12:50 UTC, Akanksha-kedia commented
@tdcmeehan please help to review

2024-01-10 20:26 UTC, steveburnett commented
Would it help to mention these changes in the release notes? I wasn't sure what the title "Direct vulnerabilities for io.grpc" meant until I read the files being changed, and also not only io.grpc appears to be changed by this PR. 

Perhaps release note entries for these changes similar to the following suggestion might be appropriate: 

```
== RELEASE NOTES ==
Security Changes
* Upgrade io.grpc to 1.60.1
* Upgrade com.google.protobuf to 3.25.1
```

I suggest `Security Changes` as a potential better heading than `General Changes` for these entries, given the CVEs affecting the older versions of these two items appear to be the motivation for this PR.

2024-01-16 08:37 UTC, skairali requested changes
@Akanksha-kedia     This is a needed change for many use cases, Thank you


But I see that grpc version is not changed at all places

Example : https://github.com/Akanksha-kedia/prestodb/blob/fi2/presto-pinot/pom.xml

Could you please make sure that upgrade is comprehensive?

2024-01-16 11:41 UTC, Akanksha-kedia commented
I ll quickly check and revert back to you

On Tue, 16 Jan 2024 at 2:07 PM, Sudheesh ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> @Akanksha-kedia <https://github.com/Akanksha-kedia> This is a needed
> change for many use cases, Thank you
>
> But I see that grpc version is not changed at all places
>
> Example :
> https://github.com/Akanksha-kedia/prestodb/blob/fi2/presto-pinot/pom.xml
>
> Could you please make sure that upgrade is comprehensive?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/prestodb/presto/pull/21668#pullrequestreview-1822776361>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVL2AZSBDRFGLAYRKDPRMZTYOY34TAVCNFSM6AAAAABBUJEKS2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQMRSG43TMMZWGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-01-16 16:36 UTC, Akanksha-kedia commented
@skairali please review, i see presto-docs is failing but i see no changes related to mine.

2024-01-17 04:45 UTC, Akanksha-kedia commented
@skairali please review

2024-01-17 15:14 UTC, steveburnett commented
Please format the release note entry with a row of three ` above and below. If my description here isn't clear, you can see an example by selecting Edit on [my earlier comment](https://github.com/prestodb/presto/pull/21668#issuecomment-1885663701).

2024-01-18 01:49 UTC, skairali commented
@Akanksha-kedia  Changes looks good.

Please complete the release notes as @steveburnett  requested in this case.

Also can you please explain why do we have packages in exclusion list?

2024-01-18 08:36 UTC, Akanksha-kedia commented
@steveburnett i have corrected please review or guide how to correctly do, @skairali can you reframe the question?

2024-01-18 14:50 UTC, steveburnett commented
> @steveburnett i have corrected please review or guide how to correctly do, @skairali can you reframe the question?

Your release note entry is not properly formatted, and contains lines it does not need to. 

1. Delete the following lines in your release note entry 
```
General Changes

No change
Hive Changes

No change
```
2. _Above_ the line `Security Changes`, add a new line containing three `, like this:

\```

3. _Below_ the line `Upgrade com.google.protobuf to 3.25.1`, add a new line containing three `, like this:

\```

Your final result should look like the example that I provided in [my comment last week](https://github.com/prestodb/presto/pull/21668#issuecomment-1885663701).

2024-01-19 10:21 UTC, skairali commented
@Akanksha-kedia   I see below

<img width="827" alt="image" src="https://github.com/prestodb/presto/assets/11347833/36467ea4-6604-4423-8bd2-d83f068f50cf">


Just need an explanation of why this is required?

2024-01-21 12:59 UTC, Akanksha-kedia commented
> @Akanksha-kedia I see below
> 
> <img alt="image" width="827" src="https://private-user-images.githubusercontent.com/11347833/298032162-36467ea4-6604-4423-8bd2-d83f068f50cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NDIyMTcsIm5iZiI6MTcwNTg0MTkxNywicGF0aCI6Ii8xMTM0NzgzMy8yOTgwMzIxNjItMzY0NjdlYTQtNjYwNC00NDIzLThiZDItZDgzZjA2OGY1MGNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDEyNTgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhODVjZjQ3NGQ3OTdiNGZlNjQ4MWVhMTAwNTFhN2NhMDE5ZGRkMWZjYWFkMDZjMTRhMGQ5NzdkYzlhYjQzMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0GrLill7d-epOEBPAoxOrEfuO8mTnHs-b5dowssPqsk">
> Just need an explanation of why this is required?

@skairali i was getting this error :
`[WARNING] Found duplicate (but equal) classes in [io.grpc:grpc-api:1.60.1, io.grpc:grpc-context:1.35.0]:
[WARNING]   io.grpc.PersistentHashArrayMappedTrie
[WARNING]   io.grpc.ThreadLocalContextStorage
[WARNING] Found duplicate and different classes in [io.grpc:grpc-api:1.60.1, io.grpc:grpc-context:1.35.0]:
[WARNING]   io.grpc.Context
[WARNING]   io.grpc.Deadline
[WARNING] Found duplicate classes/resources in compile classpath.
[WARNING] Found duplicate (but equal) classes in [io.grpc:grpc-api:1.60.1, io.grpc:grpc-context:1.35.0]:
[WARNING]   io.grpc.PersistentHashArrayMappedTrie
[WARNING]   io.grpc.ThreadLocalContextStorage
[WARNING] Found duplicate and different classes in [io.grpc:grpc-api:1.60.1, io.grpc:grpc-context:1.35.0]:
[WARNING]   io.grpc.Context
[WARNING]   io.grpc.Deadline
[WARNING] Found duplicate classes/resources in runtime classpath.
[WARNING] Found duplicate (but equal) classes in [io.grpc:grpc-api:1.60.1, io.grpc:grpc-context:1.35.0]:
[WARNING]   io.grpc.PersistentHashArrayMappedTrie
[WARNING]   io.grpc.ThreadLocalContextStorage
[WARNING] Found duplicate and different classes in [io.grpc:grpc-api:1.60.1, io.grpc:grpc-context:1.35.0]:
[WARNING]   io.grpc.Context
[WARNING]   io.grpc.Deadline
[WARNING] Found duplicate classes/resources in test classpath.`


@steveburnett please review @skairali and help to merge.

2024-01-29 03:50 UTC, Akanksha-kedia commented
> @steveburnett @skairali @tdcmeehan please review.

please review @skairali

2024-01-30 04:07 UTC, Akanksha-kedia commented
@tdcmeehan please review

2024-01-30 14:51 UTC, skairali commented
@Akanksha-kedia   Please squash the commits and let me know

2024-01-30 14:58 UTC, Akanksha-kedia commented
> @Akanksha-kedia Please squash the commits and let me know

i have done @skairali

2024-01-30 15:06 UTC, skairali approved these changes
Approved

2024-01-30 15:12 UTC, steveburnett approved these changes
Reviewed at @skairali's request - the release note looks good and I have no other concerns.

2024-01-30 15:38 UTC, Akanksha-kedia commented
Ran ut for testing

On Tue, 30 Jan 2024 at 9:07 PM, Timothy Meehan ***@***.***>
wrote:

> @Akanksha-kedia <https://github.com/Akanksha-kedia> how have you tested
> these changs?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/prestodb/presto/pull/21668#issuecomment-1917255449>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVL2AZSMI63XXZH6SMA72KTYREHTBAVCNFSM6AAAAABBUJEKS2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMJXGI2TKNBUHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-05 12:06 UTC, Akanksha-kedia commented
@skairali @tdcmeehan review please

2024-02-08 14:11 UTC, Akanksha-kedia commented
@tdcmeehan review please

2024-02-13 16:25 UTC, tdcmeehan commented
@Akanksha-kedia I am not confident in just the UT coverage.  Please try to run against actual deployments of BigQuery and Pinot and report your findings.

2024-09-24 13:00 UTC, elharo commented
moot, we're now at 1.64.0

2024-09-24 13:00 UTC, closed without merging