chore(ci): disable running unneeded tests for docs-only PRs
prestodb/presto pull request #21716
Opened 2024-01-17 15:46 UTC by hainenber

## Description

Disable running lengthy and computationally expensive `dist-compile` workflow for docs-only PRs

## Motivation and Context

Closes #21689 

## Impact

N/A

## Test Plan

Other contributor with CI executing permission to invoke the test CI

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== NO RELEASE NOTE ==

```

2024-01-17 17:44 UTC, yhwang commented
thanks for the change and I believe you would revert the dummy change in `presto-docs/README.md`. LGTM!

2024-01-17 17:44 UTC, yhwang approved these changes

2024-01-17 17:58 UTC, steveburnett reviewed
The not-run tests are showing as Required and Expected, so merging is blocked. 
<img width="887" alt="Screenshot 2024-01-17 at 12 53 16 PM" src="https://github.com/prestodb/presto/assets/7013443/d4a290fd-1829-42a1-b696-ee5a63f9a8c5">

I'd expect the bypassed tests to be skipped and automatically marked as successful for purposes of merging.

2024-01-17 17:58 UTC, yhwang commented
the CircleCI Pipeline state is incorrect although the state is `Success` in the Circle CI and I guess it doesn't update the status for those skipped jobs. Similar issue I encountered when I tweaked the GitHub actions before.

2024-01-17 18:01 UTC, steveburnett commented
> the CircleCI Pipeline state is incorrect although the state is `Success` in the Circle CI and I guess it doesn't update the status for those skipped jobs. Similar issue I encountered when I tweaked the GitHub actions before.

How did you solve that?

2024-01-17 18:06 UTC, yhwang commented
For GitHub action, there are several approaches you can filter/skip a job. Need to use a specific one that treats skipped jobs as complete and successful. I am searching for that in CircleCI now

2024-01-17 18:17 UTC, yhwang commented
how about pushing down the `when` condition from workflow level to job level?

2024-01-17 18:25 UTC, yhwang requested changes
Looks like need to figure out how to skip jobs but still report the status as succeeded

2024-01-17 18:29 UTC, yhwang commented
Do you want to try the `when` step: https://circleci.com/docs/configuration-reference/#the-when-step

2024-01-20 08:26 UTC, hainenber commented
Thanks @yhwang for the suggestion, let me see if it works out :D

2024-01-20 09:19 UTC, hainenber commented
@yhwang Your proposal works out! :D 

Previous commit's CI shows skipped CircleCI jobs as succeeded, that is before I reverted temporary change in `presto-docs`

![image](https://github.com/prestodb/presto/assets/41283691/958d286c-b44b-430d-9c0f-c43e0309c64a)

2024-01-21 04:14 UTC, yhwang approved these changes

2024-01-22 15:08 UTC, steveburnett commented
Do you need to squash merge commits as described in the [Pull Release Checklist](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#pull-request-checklist)?

2024-01-22 15:29 UTC, tdcmeehan commented
Nice change, please squash commits and we'll merge. :)

2024-01-22 15:38 UTC, hainenber commented
Thanks all! Commits squashed :D

2024-01-22 15:40 UTC, tdcmeehan commented
Per the linked guidelines, change the PR commit message to something along the lines of `Disable running CircleCI tests for docs-only PRs`

2024-01-22 20:36 UTC, tdcmeehan approved these changes

2024-01-23 20:18 UTC, mshang816 approved these changes

2024-01-23 20:39 UTC, merged