[native] Add more e2e cases for division short decimals
prestodb/presto pull request #21857
Opened 2024-02-04 10:02 UTC by xiaodouchen

## Description
Decimal divide function returned wrong results when short decimal / long decimal in velox, and we fix it in [1]. We add this case in native e2e test to ensure its correctness.

[1] https://github.com/facebookincubator/velox/pull/8599

2024-02-04 22:16 UTC, karteekmurthys approved these changes

2024-02-04 23:45 UTC, majetideepak approved these changes

2024-02-04 23:47 UTC, majetideepak requested changes
Looks like these tests are failing.

2024-02-05 01:33 UTC, xiaodouchen commented
@majetideepak The PR in Velox needs to be merged first before the tests in this PR can pass; please have a look. https://github.com/facebookincubator/velox/pull/8599

2024-02-05 01:36 UTC, majetideepak commented
@xiaodouchen thank you for the clarification. I did not realize the Velox PR is still open. I am making this a draft until then so that the reviewers know this.

2024-02-18 04:39 UTC, xiaodouchen commented
@majetideepak Please help review this PR. All tests have passed.

2024-02-22 12:49 UTC, xiaodouchen commented
@majetideepak Please take a look. All tests have passed.

2024-02-22 14:33 UTC, majetideepak commented
@xiaodouchen You have to squash the commits into one. We cannot squash merge in the Presto project.
Let me know if a test fails, I can help rerun it.

2024-02-23 02:09 UTC, majetideepak approved these changes

2024-02-23 02:31 UTC, xiaodouchen commented
@majetideepak Thanks.

2024-02-23 10:43 UTC, merged