fix(main/util): fix DeleteNode not having Graphviz visitor
prestodb/presto pull request #21918
Opened 2024-02-13 11:13 UTC by hainenber

Add basic support for DeleteNode to GraphvizPrinter, preventing stacktrace produced when print DELETE event

## Description

## Motivation and Context

Fixes #21903 

## Impact

Prevent stacktraces when printing DELETE event in console

## Test Plan

N/A

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
*  Fixes exception of DeleteNode not having Graphviz vistor
```

2024-02-13 20:21 UTC, tdcmeehan requested changes
Can you please add a test?

2024-02-15 09:33 UTC, hainenber commented
I was following these commits for reference and (cmiiw) am not sure if a unit test is feasible for these ones 🤔 
- https://github.com/prestodb/presto/commit/d89b68310564bc44416c29c582a37ddc986054f7
- https://github.com/prestodb/presto/commit/4dc0826f8f727963c7b310f49f290b5f31234f7c

2024-02-17 01:26 UTC, tdcmeehan commented
I think just proving that the query doesn't fail is sufficient.  Here's an example of using the Graphviz explain plan in a test, please use this as inspiration to create a new test that proves this functionality no longer fails (and perhaps helps us catch other problems with Graphviz rendering): https://github.com/prestodb/presto/blob/e12deb66cbe75d7a10f5812601dfcee868f5f6a3/presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java#L2482

2024-02-21 16:39 UTC, hainenber commented
Thanks @tdcmeehan, I've amended the commit message to adhere the guideline

2024-02-21 16:50 UTC, hainenber commented on presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java
> +            getGraphvizExplainPlan("EXPLAIN (FORMAT GRAPHVIZ) ", query, LOGICAL);
It'll return a Graphviz-rendered string for `EXPLAIN`ing the DELETE query. If there are any exceptions got thrown then the test got failed, which is the original vision, I think.

2024-02-21 16:51 UTC, tdcmeehan commented on presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java
> +            getGraphvizExplainPlan("EXPLAIN (FORMAT GRAPHVIZ) ", query, LOGICAL);
Then can we delete lines 2499-2503?

2024-02-21 16:54 UTC, hainenber commented on presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java
> +            getGraphvizExplainPlan("EXPLAIN (FORMAT GRAPHVIZ) ", query, LOGICAL);
My bad, miss out 1 crucial detail

That is for connectors not supporting delete operations yet, they still throw exception but atm, we only care for connectors supporting deleting *and* not have `visitDelete` implemented

2024-02-21 20:43 UTC, tdcmeehan commented on presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueries.java
> +            getGraphvizExplainPlan("EXPLAIN (FORMAT GRAPHVIZ) ", query, LOGICAL);
OK, makes sense.  There's at least one implementation that should return.

2024-02-21 20:44 UTC, tdcmeehan approved these changes

2024-02-21 21:36 UTC, tdcmeehan commented
@hainenber could you look into the test failure?

2024-02-29 05:57 UTC, yashkrishnan commented
There is this predating PR https://github.com/prestodb/presto/pull/21927/commits/fed9fdd04b4c0d0f1b1bde76adfe259339187cd3 which has same implementation with proper return type returning accepting `context` and `GraphVizPrinter` instance.

2024-03-05 16:33 UTC, closed without merging