Enable logical property propagation by default
prestodb/presto pull request #22013
Opened 2024-02-26 22:27 UTC by ClarenceThreepwood

Fixes #21968

```
== RELEASE NOTES ==

General Changes
* Enable propagation of logical properties by default
```

2024-02-27 14:59 UTC, steveburnett commented
The only place in the docs that `exploit_constraints` or `optimizer.exploit-constraints` are mentioned is in the [0.274 release notes](prestodb.io/docs/current/release/release-0.274.html). Could docs for these two properties be added as part of this PR?

2024-03-04 04:06 UTC, aaneja approved these changes

2024-03-04 18:02 UTC, steveburnett requested changes
Thanks! A few nits on formatting and punctuation. 

Consider adding entries for ``exploit_constraints`` and ``optimizer.exploit-constraints`` to the [Properties Reference](http://prestodb.io/docs/current/admin/properties.html) doc, maybe in the [Optimizer Properties](http://prestodb.io/docs/current/admin/properties.html#optimizer-properties) topic.

2024-03-04 18:06 UTC, tdcmeehan commented
> I'm not sure we want to do this by default (unless the optimizations that use the property are off by default). We are not sure how they would affect our prod workloads. In any case, an installation can always turn it on cluster-wide using feature config. So I say keep it off for now.

If you're worried about that, can't you just disable it for your deployment and figure out a way (if any) to enable it gradually?

2024-03-04 18:10 UTC, kaikalur commented
> > I'm not sure we want to do this by default (unless the optimizations that use the property are off by default). We are not sure how they would affect our prod workloads. In any case, an installation can always turn it on cluster-wide using feature config. So I say keep it off for now.
> 
> If you're worried about that, can't you just disable it for your deployment and figure out a way (if any) to enable it gradually?

Yeah - we were just talking about it. We will shut it off on our side.

2024-03-04 19:38 UTC, ZacBlanco submitted a review, later dismissed
minor nit, otherwise lgtm

2024-03-04 19:59 UTC, tdcmeehan commented on presto-docs/src/main/sphinx/optimizer/logical-properties.rst
> +Logical Properties of Query Plans
Should this be linked in the parent section?

2024-03-05 18:09 UTC, steveburnett requested changes
Looks good! A couple of nits, nothing big.

2024-03-05 18:09 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/properties.rst
> +    Enable analysis and propagation of logical properties (distinct keys, cardinality, etc.) among the nodes of
```suggestion
    Enable analysis and propagation of logical properties such as distinct key, cardinality, and other properties, among the nodes of
```
Try to avoid etc. For suggestions, see the GitLab Documentation Style Guide [recommended word list entry for etc.](https://docs.gitlab.com/ee/development/documentation/styleguide/word_list.html#etc). 
My suggested revision is one way to rephrase this, and you may have a better rephrasing you can think of.

2024-03-05 20:14 UTC, ClarenceThreepwood commented on presto-docs/src/main/sphinx/admin/properties.rst
> +    Enable analysis and propagation of logical properties (distinct keys, cardinality, etc.) among the nodes of
Unfortunately this file has 7 other occurrences of etc. - we'll leave that for another time

2024-03-07 17:45 UTC, tdcmeehan approved these changes

2024-03-07 18:13 UTC, steveburnett approved these changes
LGTM! (docs)

Pull updated branch, new local build.

2024-03-07 18:46 UTC, merged

2024-03-12 18:49 UTC, feilong-liu commented
@ClarenceThreepwood @tdcmeehan 

We found a correctness bug for the logical property propagation framework, a reproduce query is as follows:

Returns 0 rows when the framework is on:
```
presto:tpch> set session exploit_constraints=true;
SET SESSION
presto:tpch> with t as (select orderkey, count(1) cnt from (select * from (select * from orders where 1=0) left join (select partkey, suppkey from lineitem where 1=0) on partkey=10 where suppkey is not null) group by rollup(orderkey)) select t1.orderkey, t1.cnt from t t1 cross join t t2;
 orderkey | cnt 
----------+-----
(0 rows)
```

Returns 1 row when the framework is off:
```
presto:tpch> set session exploit_constraints=false;
SET SESSION
presto:tpch> with t as (select orderkey, count(1) cnt from (select * from (select * from orders where 1=0) left join (select partkey, suppkey from lineitem where 1=0) on partkey=10 where suppkey is not null) group by rollup(orderkey)) select t1.orderkey, t1.cnt from t t1 cross join t t2;
 orderkey | cnt 
----------+-----
 NULL     |   0 
(1 row)
```

Looking into the query plan, looks like that the framework incorrectly oversimplify the plan
When framework is on:
```
presto:tpch> set session exploit_constraints=true;
SET SESSION
presto:tpch> explain (type distributed) with t as (select orderkey, count(1) cnt from (select * from (select * from orders where 1=0) left join (select partkey, suppkey from lineitem where 1=0) on partkey=10 where suppkey is not null) group by rollup(orderkey)) select t1.orderkey, t1.cnt from t t1 cross join t t2;
                                                                                                   Query Plan                                                                                                   
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Fragment 0 [SINGLE]                                                                                                                                                                                            
     Output layout: [orderkey$gid, count]                                                                                                                                                                       
     Output partitioning: SINGLE []                                                                                                                                                                             
     Stage Execution Strategy: UNGROUPED_EXECUTION                                                                                                                                                              
     - Output[PlanNodeId 63][orderkey, cnt] => [orderkey$gid:bigint, count:bigint]                                                                                                                              
             orderkey := orderkey$gid (1:257)                                                                                                                                                                   
             cnt := count (1:270)                                                                                                                                                                               
         - CrossJoin[PlanNodeId 370] => [orderkey$gid:bigint, count:bigint]                                                                                                                                     
                 Distribution: REPLICATED                                                                                                                                                                       
             - Project[PlanNodeId 24][projectLocality = LOCAL] => [orderkey$gid:bigint, count:bigint]                                                                                                           
                 - Aggregate(FINAL)[orderkey$gid, groupid][$hashvalue][PlanNodeId 23] => [orderkey$gid:bigint, groupid:bigint, $hashvalue:bigint, count:bigint]                                                 
                         count := "presto.default.count"((count_246)) (1:56)                                                                                                                                    
                     - LocalExchange[PlanNodeId 1597][HASH][$hashvalue] (orderkey$gid, groupid) => [orderkey$gid:bigint, groupid:bigint, count_246:bigint, $hashvalue:bigint]                                   
                         - Aggregate(PARTIAL)[orderkey$gid, groupid][$hashvalue_247][PlanNodeId 1595] => [orderkey$gid:bigint, groupid:bigint, $hashvalue_247:bigint, count_246:bigint]                         
                                 count_246 := "presto.default.count"((expr_93)) (1:56)                                                                                                                          
                             - Project[PlanNodeId 1624][projectLocality = LOCAL] => [orderkey$gid:bigint, expr_93:integer, groupid:bigint, $hashvalue_247:bigint]                                               
                                     Estimates: {source: CostBasedSourceInfo, rows: 0 (0B), cpu: 0.00, memory: 0.00, network: 0.00}                                                                             
                                     $hashvalue_247 := combine_hash(combine_hash(BIGINT'0', COALESCE($operator$hash_code(orderkey$gid), BIGINT'0')), COALESCE($operator$hash_code(groupid), BIGINT'0')) (1:239) 
                                 - Values[PlanNodeId 1474] => [orderkey$gid:bigint, expr_93:integer, groupid:bigint]                                                                                            
                                         Estimates: {source: CostBasedSourceInfo, rows: 0 (0B), cpu: 0.00, memory: 0.00, network: 0.00}                                                                         
             - Values[PlanNodeId 1478] => []                                                                                                                                                                    
                     Estimates: {source: CostBasedSourceInfo, rows: 0 (0B), cpu: 0.00, memory: 0.00, network: 0.00}                                                                                             
                                                                                                                                                                                                                
                                                                                                                                                                                                                
(1 row)
```

When framework is off:
```
presto:tpch> set session exploit_constraints=false;
SET SESSION
presto:tpch> explain (type distributed) with t as (select orderkey, count(1) cnt from (select * from (select * from orders where 1=0) left join (select partkey, suppkey from lineitem where 1=0) on partkey=10 where suppkey is not null) group by rollup(orderkey)) select t1.orderkey, t1.cnt from t t1 cross join t t2;
                                                                                                         Query Plan                                                                                                >
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------->
 Fragment 0 [SINGLE]                                                                                                                                                          [...]