Remove unused field
prestodb/presto pull request #22036
Opened 2024-02-27 22:47 UTC by elharo

## Description

## Motivation and Context

## Impact

## Test Plan

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2024-03-04 14:11 UTC, elharo commented
2024-02-27T23:33:05.1670158Z [ERROR] com.facebook.presto.hive.TestHiveDistributedQueriesWithThriftRpc.testViewAccessControlInvokerDefault  Time elapsed: 0.038 s  <<< FAILURE!
2024-02-27T23:33:05.1672167Z java.lang.RuntimeException: View already exists: 'tpch.test_view_access'

2024-03-04 15:08 UTC, elharo commented
Completely different failure this time, so yes, it's just flaky:

2024-03-04T14:16:17.7263256Z [ERROR] Tests run: 473, Failures: 1, Errors: 0, Skipped: 472, Time elapsed: 20.789 s <<< FAILURE! - in com.facebook.presto.mongodb.TestMongoDistributedQueries
2024-03-04T14:16:17.7267200Z [ERROR] com.facebook.presto.mongodb.TestMongoDistributedQueries.init  Time elapsed: 20.106 s  <<< FAILURE!
2024-03-04T14:16:17.7268776Z java.lang.RuntimeException: Prematurely reached end of stream

2024-03-04 16:48 UTC, elharo commented
The most important thing to note here is not the change itself, which is minor at most, but that I had to rerun the CI tests at least three times before it got to a passing state. This is not a good place to be, and the team should think about how we can improve this.

2024-03-04 19:35 UTC, mlyublena commented
nit: add a bit more context to description, for example: "Remove unused view field from Analysis class"

2024-03-04 19:35 UTC, mlyublena submitted a review, later dismissed

2024-03-06 11:52 UTC, elharo commented
@rschlussel @ajaygeorge for approval

2024-03-06 14:46 UTC, tdcmeehan approved these changes

2024-03-06 15:02 UTC, rschlussel commented
> Tangential, but this flakiness is probably fixable. It looks like two different tests create a view with the same name, so there's a race condition

i have a fix for that that i added to a different pr when i had the same issue.  just waiting for final approval to merge https://github.com/prestodb/presto/pull/22011/commits.

2024-03-06 15:02 UTC, rschlussel approved these changes

2024-03-06 15:02 UTC, tdcmeehan requested changes
Looks good but please squash commits

2024-03-06 18:14 UTC, elharo commented
Commits are squashed

2024-03-06 20:08 UTC, tdcmeehan approved these changes

2024-03-06 21:47 UTC, merged