Use ThreadLocalRandom instead of RandomizationStrategy
prestodb/presto pull request #22117
Opened 2024-03-07 19:18 UTC by mohandhar

## Description
- Replace RandomizationStrategy with ThreadLocalRandom

## Motivation and Context
- ThreadLocalRandom is more efficient because it avoids the overhead of synchronization.

## Impact
- noisy_approx_distinct_sfm
- noisy_approx_set_sfm
- merge

## Test Plan
- Unit tests

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2024-03-08 21:23 UTC, jonhehir commented on presto-main/src/test/java/com/facebook/presto/operator/aggregation/noisyaggregation/sketch/TestSfmSketch.java
> +        sketch.mergeWith(sketch2);
This could be a problem, as it makes the test random (i.e., potentially flaky). It'd probably be best to keep this test seeded if possible.

2024-03-08 21:24 UTC, jonhehir commented on presto-main/src/test/java/com/facebook/presto/operator/aggregation/noisyaggregation/sketch/TestSfmSketch.java
> +        sketch.mergeWith(sketch2);
(I believe the other test is technically fine, though.)

2024-03-11 23:22 UTC, jonhehir requested changes

2024-03-11 23:22 UTC, jonhehir commented on presto-main/src/main/java/com/facebook/presto/operator/aggregation/noisyaggregation/sketch/SfmSketch.java
> +        return new ThreadLocalRandomizationStrategy();
This should not be the default. We should use SecureRandom in all cases except one (which does not require it): merging sketches.

Consequently, this change should only really affect the merge() and merge_sfm() functions. (The other aggregators do use merges, but only on noiseless sketches anyway, which are deterministic operations.)

2024-03-11 23:22 UTC, jonhehir commented on presto-main/src/test/java/com/facebook/presto/operator/aggregation/noisyaggregation/sketch/TestSfmSketch.java
> -        sketch.mergeWith(sketch2, new TestingSeededRandomizationStrategy(2));
I think this should still be seeded?

2024-03-12 20:37 UTC, jonhehir commented
This looks good to me in terms of functionality. Can we just add maybe a small comment in the code and edit the PR description to better document this change?

To summarize, after this change, the SFM sketch will use `SecureRandom` when adding noise to sketches, but it will use `ThreadLocalRandom` when combining sketches that have already had noise added to them. The reason for this is that the SFM sketch algorithm [calls](https://proceedings.mlr.press/v202/hehir23a/hehir23a.pdf) for the noise addition to ensure certain privacy-preserving properties, which should be cryptographically secure. The merging of already-random bits, however, does not need to be cryptographically secure.

Because this only affects merges of noisy sketches, this change only affects `merge(SfmSketch)`, and `merge_sfm(Array)`. The other functions are not actually affected.

2024-03-14 17:30 UTC, jonhehir approved these changes
Looks good to me, thank you!

2024-03-14 17:33 UTC, arhimondr approved these changes

2024-03-14 17:34 UTC, merged