[Doc]Document all the currently supported SQL operation for postgresql connector
prestodb/presto pull request #22246
Opened 2024-03-20 04:55 UTC by Akanksha-kedia

Document all the currently supported SQL operations for postgresql connector along with an example similar to https://prestodb.io/docs/current/connector/iceberg.html#sql-support

## Expected Behavior or Use Case
To provide more concrete details to users.
Once we have documentation for postgresql connector, we can document similar supported SQL operations for other JDBC connectors as well.

## Presto Component, Service, or Connector
Presto Docs(postgresql)

## Possible Implementation
[](https://prestodb.io/docs/current/connector/iceberg.html#sql-support)

## Example Screenshots (if appropriate):
presently only :
<img width="1158" alt="Screenshot 2024-03-20 at 9 24 49 AM" src="https://github.com/prestodb/presto/assets/89628774/0a83ff59-3267-4d48-a81e-282e92799b7f">

## Context

To provide more concrete details to users

## Impact
No impact

## Test Plan
manually built the doc and using mvn install and generated html .

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```
 
 Testing ss:
 
<img width="750" alt="Screenshot 2024-03-20 at 10 17 13 AM" src="https://github.com/prestodb/presto/assets/89628774/94807cab-dc66-4fee-8d15-feffcb84706c">
<img width="793" alt="Screenshot 2024-03-20 at 10 17 21 AM" src="https://github.com/prestodb/presto/assets/89628774/0b1f3362-7739-40a4-aa8c-5006e97b5bee">
<img width="790" alt="Screenshot 2024-03-20 at 10 17 29 AM" src="https://github.com/prestodb/presto/assets/89628774/b79d4fc0-7c83-4b2c-ab66-de3db5220b58">

2024-03-20 14:30 UTC, steveburnett requested changes
In the cited [Iceberg Connector](https://prestodb.io/docs/current/connector/iceberg.html#sql-support) page, the topic is titled "SQL Support". In this draft you call the topic "PostgreSQL Connector Support". Why the difference? "PostgreSQL Connector Support" of what?

Also consider the review I did yesterday for your https://github.com/prestodb/presto/pull/21949 and apply the suggestions I made there, as appropriate, to this draft.

2024-03-21 11:02 UTC, Akanksha-kedia commented
@steveburnett done.

2024-03-21 17:11 UTC, steveburnett requested changes
Thanks for the revision and fixes! I had some suggestions to the text, and a couple of questions I hope you can help with.

2024-03-21 17:11 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/postgresql.rst
> +* :doc:`/sql/alter-table` (ALTER COLUMN TYPE)
I am not sure I understand the meaning of `(ALTER COLUMN TYPE)` here. The capitalization suggests that when I follow the link to the ALTER TABLE page, I might find ALTER COLUMN TYPE but those words are not there. 
Can you explain?

2024-03-21 17:11 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/postgresql.rst
> +* :doc:`/sql/create-table` (WITH PRIMARY KEY)
I also do not understand what you mean by the words `(WITH PRIMARY KEY)` here. Can you explain?

2024-03-22 09:47 UTC, Akanksha-kedia commented
i have added scenario and removed from not supported.

2024-03-23 08:56 UTC, Akanksha-kedia commented
<img width="439" alt="Screenshot 2024-03-23 at 2 25 35 PM" src="https://github.com/prestodb/presto/assets/89628774/fe77fa04-faf1-4319-93c3-03d83d3ed1e2">
@steveburnett please review.

2024-03-25 18:39 UTC, steveburnett approved these changes
LGTM! (docs)

2024-03-25 18:42 UTC, steveburnett commented
Please add a release note of 
```
== NO RELEASE NOTE ==
```

2024-03-26 05:22 UTC, Akanksha-kedia commented
@tdcmeehan please review and help to merge.

2024-03-26 16:57 UTC, merged