[Doc]Document all the currently supported SQL operation for memory connector
prestodb/presto pull request #22249
Opened 2024-03-20 07:02 UTC by Akanksha-kedia

## Description
[Doc]Document all the currently supported SQL operation for memory connector

## Motivation and Context
To provide more concrete details to users.

## Impact
No impact (Presto Docs(memory.rst))

## Test Plan
Built manually and tested.
<img width="812" alt="Screenshot 2024-03-20 at 12 25 52 PM" src="https://github.com/prestodb/presto/assets/89628774/1d3dafa4-f11b-4c53-9b15-68af03e68a22">
<img width="750" alt="Screenshot 2024-03-20 at 12 26 00 PM" src="https://github.com/prestodb/presto/assets/89628774/8910fdc2-c5d7-4333-a9e1-3151063bf73d">

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2024-03-20 07:03 UTC, Akanksha-kedia commented
As we are updated other connectors documentation with an example similar to https://prestodb.io/docs/current/connector/iceberg.html#sql-support.

2024-03-20 14:27 UTC, steveburnett requested changes
In the cited [Iceberg Connector](https://prestodb.io/docs/current/connector/iceberg.html#sql-support) page, the topic is titled "SQL Support". In this draft you call the topic "Memory Connector Support". Why the difference? "Memory Connector Support" of what? 

Please format the schema and table names for consistency with the formatting of schema and table names in the cited [Iceberg Connector](https://prestodb.io/docs/current/connector/iceberg.html#sql-support) page. 

Also consider the review I did yesterday for your [PR 21949](https://github.com/prestodb/presto/pull/21949) and apply the suggestions I made there, as appropriate, to this draft.

2024-03-21 11:11 UTC, Akanksha-kedia commented
![Uploading Screenshot 2024-03-21 at 4.40.54 PM.png…]()
@steveburnett

2024-03-21 11:12 UTC, Akanksha-kedia commented
@steveburnett 
<img width="788" alt="Screenshot 2024-03-21 at 4 40 54 PM" src="https://github.com/prestodb/presto/assets/89628774/6792f6a0-b55f-4a8c-9905-26e7e795578f">

2024-03-23 09:02 UTC, Akanksha-kedia commented
<img width="473" alt="Screenshot 2024-03-23 at 2 32 10 PM" src="https://github.com/prestodb/presto/assets/89628774/c9149127-dd5e-4850-8fc9-a6be32108b86">

@steveburnett please review.

2024-03-25 18:47 UTC, steveburnett requested changes
Thanks, a couple of nits.

2024-03-25 18:47 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/memory.rst
> +Create a new table named ``my_table`` in the default1 schema:
```suggestion
Create a new table named ``my_table`` in the ``default1`` schema:
```

2024-03-25 18:47 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/memory.rst
> +The ``DROP TABLE`` statement is used to delete an existing table:
```suggestion
To delete an existing table:
```

2024-03-25 18:48 UTC, steveburnett commented
Please add a release note entry of 
```
== NO RELEASE NOTE ==
```

2024-03-26 05:31 UTC, Akanksha-kedia commented
Thanks!!!! @steveburnett please review.

2024-03-26 15:04 UTC, Akanksha-kedia commented
@steveburnett done.

2024-03-26 16:50 UTC, steveburnett approved these changes
LGTM! (docs)

Pull updated branch, new local build, everything looks good.

2024-03-26 16:58 UTC, merged