[DOC] Update JMX connector documentation
prestodb/presto pull request #22248
Opened 2024-03-20 05:41 UTC by Akanksha-kedia

## Description
[DOC] Update JMX connector documentation

## Motivation and Context
To provide more accurate and detailed information to users about the SQL operations supported by the JMX connector in Presto. The current documentation mentions only two schemas (current and history), but the JMX connector actually provides three schemas (current, history, and information_schema). We need to update this information to maintain consistency and accuracy. Also add few examples for information_schema.

## Impact
No impact. Changes in presto-docs(jmx.rst)

## Test Plan
Manually built and tested.
<img width="842" alt="Screenshot 2024-03-20 at 11 01 55 AM" src="https://github.com/prestodb/presto/assets/89628774/a676f69e-6554-4da0-a21c-29178daf628b">
<img width="774" alt="Screenshot 2024-03-20 at 11 02 03 AM" src="https://github.com/prestodb/presto/assets/89628774/5d372469-dcca-4006-9689-7a258d0afcce">
<img width="784" alt="Screenshot 2024-03-20 at 11 02 08 AM" src="https://github.com/prestodb/presto/assets/89628774/3de14aad-5d62-4e0b-b2db-058347cde7f6">

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2024-03-20 05:41 UTC, Akanksha-kedia commented
@steveburnett

2024-03-21 11:08 UTC, Akanksha-kedia commented
> @steveburnett
please review.

2024-03-22 07:03 UTC, Akanksha-kedia commented
Fixes #22247

2024-03-22 08:59 UTC, Akanksha-kedia commented
Fixes https://github.com/prestodb/presto/issues/22247

2024-03-23 09:00 UTC, Akanksha-kedia commented
@steveburnett @tdcmeehan please review @agrawalreetika

2024-03-23 19:17 UTC, agrawalreetika approved these changes
LGTM

2024-03-25 18:48 UTC, steveburnett commented
Please add a release note entry of 
```
== NO RELEASE NOTE ==
```

2024-03-25 18:54 UTC, steveburnett requested changes
Thanks. A couple of nits only.

2024-03-25 18:54 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/jmx.rst
> +You can see all the available tables in this schema by running the following command:
```suggestion
To list all the available tables in this schema, run the following command:
```

2024-03-25 18:54 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/jmx.rst
>  cluster. You can see all of the available MBeans by running ``SHOW TABLES``::
```suggestion
cluster. To see all of the available MBeans, runn ``SHOW TABLES``::
```

2024-03-26 05:27 UTC, Akanksha-kedia commented
@steveburnett @tdcmeehan please review.

2024-03-26 14:34 UTC, steveburnett requested changes
Thanks! One minor spelling nit that I should have caught in my previous review.

2024-03-26 14:34 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/jmx.rst
> +cluster. To see all of the available MBeans, runn ``SHOW TABLES``::
```suggestion
cluster. To see all of the available MBeans, run ``SHOW TABLES``::
```
I should have caught this last review.

2024-03-26 16:51 UTC, steveburnett approved these changes
LGTM! (docs)

Pull updated branch, new local build, everything looks good. Thanks!

2024-03-26 16:57 UTC, merged