Enable logical property propagation by default
prestodb/presto pull request #22266
Opened 2024-03-20 22:04 UTC by ClarenceThreepwood

Fixes #21968 

== RELEASE NOTES ==

General Changes
* Enable propagation of logical properties by default

2024-03-27 00:03 UTC, jaystarshot commented
cc: @feilong-liu

2024-03-27 13:50 UTC, steveburnett requested changes
Thanks for the documentation! A few nits and some rephrasing suggestions mostly to improve readability.

2024-03-27 13:50 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/properties.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```suggestion
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

2024-03-27 13:50 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/properties.rst
> +    Enable analysis and propagation of logical properties (distinct keys, cardinality, etc.) among the nodes of
```suggestion
    Enable analysis and propagation of logical properties like distinct keys or cardinality among the nodes of
```
Avoid Latin expressions or abbreviations in documentation. For context and suggestions, see [the Gitlab documentation style guide recommended word list entry for etc.](https://docs.gitlab.com/ee/development/documentation/styleguide/word_list.html#etc). 

I'm suggesting a possible revision, but if this one doesn't work for you please read the linked entry and propose an alternate revision.

2024-03-27 13:50 UTC, steveburnett commented on presto-docs/src/main/sphinx/optimizer.rst
> +    optimizer/logical-properties
Thanks for remembering to add the new page to its appropriate index page!

2024-03-27 13:50 UTC, steveburnett commented on presto-docs/src/main/sphinx/optimizer/logical-properties.rst
> +might either initially derive from constraints defined on tables, or from
```suggestion
might either derive from constraints defined on tables, or from
```
Suggest deleting the word "initially".

2024-03-27 13:50 UTC, steveburnett commented on presto-docs/src/main/sphinx/optimizer/logical-properties.rst
> +operations performed by intermediate nodes in the query plan, such as
```suggestion
operations performed by intermediate nodes in the query plan such as
```

2024-03-27 13:50 UTC, steveburnett commented on presto-docs/src/main/sphinx/optimizer/logical-properties.rst
> +may then exploit these logical properties to perform optimizations such as
```suggestion
may then use these logical properties to perform optimizations such as
```
Suggestion made to improve readability with a simpler word.

2024-03-27 13:50 UTC, steveburnett commented on presto-docs/src/main/sphinx/optimizer/logical-properties.rst
> +Currently Presto detects and propagates the following logical properties:
```suggestion
Presto detects and propagates the following logical properties:
```
Because the default state for documentation is present tense describing the current state of the application, suggest deleting "Currently" as redundant.

2024-03-27 13:50 UTC, steveburnett commented on presto-docs/src/main/sphinx/optimizer/logical-properties.rst
> +* ``KeyProperty`` - Represents a collection of distinct attributes that hold for
```suggestion
* ``KeyProperty`` - A collection of distinct attributes that hold for
```
If this and the following two suggestions rephrase the meaning in a way that you feel is not correct, please dismiss these.

2024-03-27 13:50 UTC, steveburnett commented on presto-docs/src/main/sphinx/optimizer/logical-properties.rst
> +* ``MaxCardProperty`` - Represents a provable maximum number of rows in a final or
```suggestion
* ``MaxCardProperty`` - A provable maximum number of rows in a final or
```

2024-03-27 13:50 UTC, steveburnett commented on presto-docs/src/main/sphinx/optimizer/logical-properties.rst
> +* ``EquivalenceClassProperty`` - Represents classes of equivalent variable and
```suggestion
* ``EquivalenceClassProperty`` - Classes of equivalent variable and
```

2024-03-28 15:48 UTC, steveburnett submitted a review, later dismissed
LGTM! (docs)

Pull updated branch, new local build, everything looks good. Thanks!

2024-04-04 22:38 UTC, mlyublena commented on presto-main/src/main/java/com/facebook/presto/sql/planner/iterative/rule/RemoveRedundantAggregateDistinct.java
> +            if (node.getGroupingKeys().stream().allMatch(key -> key instanceof VariableReferenceExpression) &&
I know most of this code was here before but perhaps refactor that as functions to increase readability?

2024-04-04 22:41 UTC, mlyublena commented
Can you also add description to the PR and/or commit message about the bug that got fixed (in addition to changing the default value of the flag)?

2024-04-09 14:56 UTC, tdcmeehan approved these changes
LGTM

2024-04-09 16:45 UTC, merged