Allow leading and trailing spaces in CAST(str as INTEGER)
prestodb/presto pull request #22284
Opened 2024-03-21 18:37 UTC by spershin

## Description
Allow leading and trailing spaces in CAST(str as INTEGER). Also as BIGING, SMALLINT and TINYINT.
This is according to SQL standard.

## Motivation and Context
This is according to SQL standard.

## Impact
This is query behavior change.

## Test Plan
Need to determine if there will be any tests failing.
Then either fix and upgrade these or add new tests.
Also maybe need to update documentation to reflect this.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* CAST(str as INTEGER), CAST(str as BIGINT), CAST(str as SMALLINT), CAST(str as TINYINT) now allow leading and trailing spaces in the string.

```

2024-03-21 18:41 UTC, mbasmanova commented
CC: @tdcmeehan @steveburnett

2024-03-21 18:52 UTC, elharo requested changes
This needs a test that fails with the old rules and passes with the new ones

2024-03-21 19:23 UTC, spershin commented
@elharo 

> This needs a test that fails with the old rules and passes with the new ones

Of course. We will have them.
Thing is, I haven't found the existing tests and wasn't sure if we don't have them or I just can't find them.
So decided to see if any checks/tests will fail.
See the comment in the "Test Plan" section of the PR Description.

2024-03-21 20:58 UTC, spershin commented
@elharo 

I have added a unit test as requested.

2024-03-21 23:58 UTC, kaikalur approved these changes

2024-03-22 13:07 UTC, tdcmeehan approved these changes
Thanks for fixing this.

2024-03-25 17:17 UTC, merged