Add log for canonicalized plans in HBO
prestodb/presto pull request #22306
Opened 2024-03-22 20:03 UTC by feilong-liu

## Description

## Motivation and Context

## Impact

## Test Plan

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2024-03-22 23:25 UTC, feilong-liu commented on presto-main/src/main/java/com/facebook/presto/cost/HistoryBasedPlanStatisticsCalculator.java
> +                historyBasedStatisticsCacheManager.setStatsEquivalentPlan(session.getQueryId(), statsEquivalentPlanString.get());
Record stats equivalent plan

2024-03-23 09:58 UTC, jaystarshot commented on presto-main/src/main/java/com/facebook/presto/sql/analyzer/FeaturesConfig.java
> +    private boolean logPlansUsedInHBO = true;
Since this going to add substantial weight to the stored entry, better to have this off by default.

2024-03-25 18:27 UTC, steveburnett commented
"This feature is controlled by session property `log_query_plans_used_in_history_based_optimizer`. 

Suggest adding doc for the session property. Would http://prestodb.io/docs/current/plugin/redis-hbo-provider.html or http://prestodb.io/docs/current/admin/properties.html#optimizer-properties be the correct place for it?

2024-03-25 19:39 UTC, jaystarshot approved these changes

2024-03-25 21:07 UTC, steveburnett requested changes
Thanks for the doc! One tiny nit suggestion for readability.

2024-03-25 21:07 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/properties.rst
> +    Log stats equivalent plan and canonicalized plans used in history based optimization.
```suggestion
    Log the stats equivalent plan and canonicalized plans used in history based optimization.
```
"Log stats equivalent plan" seems a little hard to parse. Suggestion of "the" taken from the Description of the PR makes it easier to understand.

2024-03-25 22:30 UTC, steveburnett requested changes
Thanks for the quick response! Two small nits.

2024-03-25 22:30 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/properties.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```suggestion
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Suggest changing the heading formatting to the same character length as the character length in line 814.

2024-03-25 22:30 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/properties.rst
> +    Log stats equivalent plan and canonicalized plans used in history based optimization.
```suggestion
    Log the stats equivalent plan and canonicalized plans used in history based optimization.
```
Let me know if this change doesn't work for you, I'd like to understand why.

2024-03-25 22:52 UTC, steveburnett approved these changes
LGTM! (docs) 

Pull updated branch, new local build,looks good. Thanks for the rapid response!

2024-03-26 03:11 UTC, jaystarshot approved these changes

2024-03-26 22:10 UTC, feilong-liu commented on presto-main/src/main/java/com/facebook/presto/cost/HistoryBasedPlanStatisticsCalculator.java
> +import static com.facebook.presto.SystemSessionProperties.logQueryPlansUsedInHBO;
Changed to logQueryPlansUsedInHistoryBasedOptimizer

2024-03-26 22:11 UTC, feilong-liu commented on presto-main/src/main/java/com/facebook/presto/sql/planner/CachingPlanCanonicalInfoProvider.java
> +    public Optional<String> hash(Session session, PlanNode planNode, PlanCanonicalizationStrategy strategy, boolean cacheOnly, boolean recordPlan)
Removed the record argument.

2024-03-29 01:42 UTC, pranjalssh approved these changes
LGTM

2024-03-29 01:42 UTC, merged