[native] update velox
prestodb/presto pull request #22434
Opened 2024-04-05 23:58 UTC by czentgr

This updates the fbos dependencies among other
things to v2024.04.01.00 and proxygen needs to match this version.

## Description
See above.

## Motivation and Context
See above.

## Impact
n/a

## Test Plan
n/a

## Contributor checklist

- [X] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [X] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [X] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [X] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [X] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes

```
== NO RELEASE NOTE ==
```

2024-04-05 23:59 UTC, czentgr commented
@majetideepak FYI

2024-04-08 15:22 UTC, majetideepak commented
@czentgr can you rebase?

2024-04-09 19:54 UTC, majetideepak approved these changes

2024-04-09 19:56 UTC, majetideepak requested changes
@czentgr If we are not updating Velox, can we correct the commit title and subject?

2024-04-09 20:03 UTC, czentgr commented
@majetideepak I was updating velox. After the rebase the velox submodule update is gone. The original commit still has it. I didn't notice that this was dropped on the rebase. I will make a new commit.

2024-04-10 01:24 UTC, majetideepak approved these changes
thanks, @czentgr

2024-04-10 01:25 UTC, merged