[WIP]Support forwarded https
prestodb/presto pull request #22492
Opened 2024-04-11 19:23 UTC by wills-feng

## Description
Currently Presto will skip authentication when request is inSecure(http), but in a common situation that presto is deployed behind a load balancer which will handle SSL termination, we expect presto can recognize `X-Forwarded-Proto` header and continue with configured authentication. 
This feature was added in Ahana presto by this [PR](https://github.com/Ahana-Inc/prestodb/pull/14/).

## Motivation and Context
Support authentication for Presto behind a proxy

## Impact
The flag is turned off by default.

## Test Plan
Deploy presto with password authentication behind nginx, authentication method applied.

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ...
* ...

Hive Connector Changes
* ...
* ...
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2024-04-11 19:25 UTC, wills-feng commented
@yzhang1991 @wanglinsong @tdcmeehan

2024-04-12 00:24 UTC, wills-feng commented
Fixed the CLA and update the docs

2024-04-12 13:20 UTC, steveburnett requested changes
Thanks for adding the doc! Found a few minor nits of formatting for consistency with the rest of the documentation, but looks good!

2024-04-12 13:20 UTC, steveburnett commented on presto-docs/src/main/sphinx/security/ldap.rst
> +                                                        Requires the X-Forwarded-Proto header to be set to https on forwarded requests.
```suggestion
                                                        Requires the ``X-Forwarded-Proto`` header to be set to ``https`` on forwarded requests.
```

2024-04-12 13:20 UTC, steveburnett commented on presto-docs/src/main/sphinx/security/ldap.rst
> +                                                        Default value is false.
```suggestion
                                                        Default value is ``false``.
```

2024-04-17 20:02 UTC, tdcmeehan commented
LGTM but please incorporate suggestions from @steveburnett

2024-04-19 19:29 UTC, steveburnett approved these changes
LGTM! (docs) 

Pull updated branch, new local build, everything looks good.

2024-04-23 18:05 UTC, wills-feng commented
Thanks @steveburnett. @wanglinsong just confirmed the change works in our env. @tdcmeehan Could you please approval and merge?

2024-04-23 19:31 UTC, wanglinsong approved these changes
I have deployed the updates and verified the password requirement is enabled.

2024-04-24 18:42 UTC, tdcmeehan approved these changes

2024-04-24 18:42 UTC, merged