Delay Presto map hash table build when lookups are few
prestodb/presto pull request #22587
Opened 2024-04-22 22:23 UTC by pranjalssh

Add session property `map_lookups_without_hashtable`, which denotes how many map lookups will be done using linear search, before resorting to hash table build of the entire map. Default is 0.

Usually hashing cost is high enough that its best to not build the hash table for map objects. Only when number of lookups exceed some threshold, we should resort to build the hashtable. This change controls that using a session prop.

```
== RELEASE NOTES ==

General Changes
* Add session property `map_lookups_without_hashtable`, which denotes how many map lookups will be done using linear search, before resorting to hash table build of the entire map. Default is 0.

2024-04-22 23:24 UTC, elharo requested changes

2024-04-22 23:24 UTC, elharo commented on presto-common/src/main/java/com/facebook/presto/common/block/SingleMapBlock.java
> +                catch (Throwable throwable) {
Per Effective Java, you should almost never catch Throwable. What's the more specific exception here?

2024-04-22 23:24 UTC, elharo commented on presto-common/src/main/java/com/facebook/presto/common/block/SingleMapBlock.java
> +                catch (Throwable throwable) {
ditto

2024-04-22 23:24 UTC, elharo commented on presto-common/src/main/java/com/facebook/presto/common/block/SingleMapBlock.java
> +                catch (Throwable throwable) {
ditto

2024-04-22 23:24 UTC, elharo commented on presto-common/src/main/java/com/facebook/presto/common/block/SingleMapBlock.java
> +                catch (Throwable throwable) {
ditto

2024-04-22 23:24 UTC, elharo commented on presto-common/src/main/java/com/facebook/presto/common/block/SingleMapBlock.java
> +                catch (Throwable throwable) {
ditto

2024-04-23 14:53 UTC, steveburnett commented
* Please add documentation for the session property, and then I'll be happy to review this PR. 

* Thanks for writing a release note entry! Consider the following small suggestion adding your PR# in the entry to make easier the work of assembling the release note for the next release:

```
== RELEASE NOTES ==

General Changes
* Add session property `map_lookups_without_hashtable`, which denotes how many map lookups will be done using linear search, before resorting to hash table build of the entire map. Default is 0. :pr:`22587`
```

2024-04-23 23:06 UTC, aditi-pandit commented
@pranjalssh, @mbasmanova : Is there an equivalent for this in Prestissimo engine ? My intuition is that because of runtime optimizations in HashTable build we might not need this. But just thought to ask anyways.

2024-12-08 06:15 UTC, closed without merging