[native] Fix file format mapping error for Iceberg Connector.
prestodb/presto pull request #22726
Opened 2024-05-13 06:21 UTC by wypb

## Description

Iceberg's ORC format should be mapped to Velox's ORC format, not the DWRF format.

## Motivation and Context

## Impact

## Test Plan

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes

```
== NO RELEASE NOTE ==
```

2024-05-23 07:28 UTC, yingsu00 reviewed
@wypb The queries all failed, have you taken a look what caused it? Was it Iceberg related issue?

2024-05-23 09:45 UTC, wypb commented
No, This is due to the fact that the open source Velox does not support reading ORC files. I made an adaptation internally, and I need to remove this part of the code.

2024-05-25 22:00 UTC, majetideepak approved these changes

2024-05-25 22:06 UTC, majetideepak requested changes
@wypb This is not limited to the Iceberg connector correct? This is a general protocol::FileFormat mapping issue.
Can you update the commit title and add a description?

2024-05-25 22:18 UTC, majetideepak commented
I am also assuming the current mapping is a bug.

2024-05-27 03:49 UTC, wypb commented
> This is not limited to the Iceberg connector correct? 

@majetideepak Currently, `toVeloxFileFormat(const presto::protocol::FileFormat format)` is only used by the Iceberg connector, but it is not ruled out that other connectors will also use it in the future.

2024-05-27 05:10 UTC, majetideepak approved these changes
Thanks, @wypb

2024-05-27 05:10 UTC, merged