Support functionc all rewrite by Presto Verifier
prestodb/presto pull request #22783
Opened 2024-05-18 18:41 UTC by gggrace14

Enable Presto Verifier to substitute function call expressions in a source query, according to the user specified substitution pattern, by the config function-substitutes. Support function call substitutions when rewriting Query, CreateTableAsSelect and Insert source queries.

## Description

## Motivation and Context

## Impact

## Test Plan

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ... :pr:`12345`
* ... :pr:`12345`

Hive Connector Changes
* ... :pr:`12345`
* ... :pr:`12345`
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2024-05-20 15:05 UTC, steveburnett requested changes
Nice work, thanks! Nits of formatting suggested to improve readability.

2024-05-20 15:05 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/verifier.rst
> +                                            applied to the corresponding positions. Concatenate function substitutions with comma.
```suggestion
                                            applied to the corresponding positions. 
                                            
                                            Concatenate function substitutions with a comma.
```
Suggest adding line break to left-justify this sentence in the Description column for readability.

2024-05-20 15:05 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/verifier.rst
> +                                            Make sure to select a function substitute that has the return type and argument types
```suggestion
                                            
                                            Select a function substitute that has the return type and argument types
```
Same line break, and nit of a rephrasing suggestion.

2024-05-20 15:05 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/verifier.rst
> +                                            Declare the function arguments as identifiers if they need to be applied to
```suggestion
                                            
                                            Declare the function arguments as identifiers if they need to be applied to
```
Same line break. 

Here's a screenshot of my local build with these suggestions. 
<img width="796" alt="Screenshot 2024-05-20 at 11 03 31 AM" src="https://github.com/prestodb/presto/assets/7013443/f7f96cdd-b31e-4b9f-b1bc-a42684de70e1">

2024-05-22 06:27 UTC, gggrace14 commented
> Nice work, thanks! Nits of formatting suggested to improve readability.

Hi @steveburnett , I revised the .rst doc based on my understanding of the comments. Let me know if I miss anything.

2024-05-22 14:26 UTC, steveburnett reviewed
Looks good! One tiny nit.

2024-05-22 14:26 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/verifier.rst
> +                                            Concatenate function substitutions with comma.
```suggestion
                                            Concatenate function substitutions with a comma.
```

2024-05-25 12:06 UTC, arhimondr approved these changes

2024-05-27 01:25 UTC, gggrace14 commented on presto-docs/src/main/sphinx/admin/verifier.rst
> +                                            Concatenate function substitutions with comma.
Revised

2024-05-28 16:09 UTC, merged