add new tests for TestPage.java
prestodb/presto pull request #22790
Opened 2024-05-20 21:23 UTC by ymmarissa

## Description
Added tests for prependColumn and appendColumns methods in TestPage to ensure they handle cases where the number of rows in new columns does not match existing columns.

## Motivation and Context

This change adds necessary test coverage for TestPage to prevent bugs related to mismatched row counts in new columns.

## Impact

No public API changes. Ensures internal method reliability.

## Test Plan

Tests included within the pull request. Verified by running ./mvnw test.

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ... :pr:`12345`
* ... :pr:`12345`

Hive Connector Changes
* ... :pr:`12345`
* ... :pr:`12345`
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2024-05-20 22:26 UTC, ZacBlanco requested changes

2024-05-20 22:26 UTC, ZacBlanco commented on presto-common/src/test/java/com/facebook/presto/common/TestPage.java
> +    public void testPrependColumn_WrongNumberOfRows()
nit: by convention we use camelCase. 
```suggestion
    public void testPrependColumnWrongNumberOfRows()
```

2024-05-20 22:26 UTC, ZacBlanco commented on presto-common/src/test/java/com/facebook/presto/common/TestPage.java
> +    public void testAppendColumns_WrongNumberOfRows()
similar comment on camelCase
```suggestion
    public void testAppendColumnsWrongNumberOfRows()
```

2024-05-23 11:58 UTC, elharo approved these changes
Nice! Thanks.

2024-05-29 17:02 UTC, ZacBlanco approved these changes

2024-05-29 17:05 UTC, tdcmeehan commented
Please fix the commit message, perhaps to the below:

`Add boundary tests for Page`

2024-06-05 15:00 UTC, tdcmeehan approved these changes

2024-06-05 15:00 UTC, tdcmeehan commented
Thank you @ymmarissa !

2024-06-05 15:00 UTC, merged