Add presto-openapi module and QueryResource definition
prestodb/presto pull request #22982
Opened 2024-06-11 06:10 UTC by ymmarissa

## Description
Added an OpenAPI specification for Presto queries in `query.yaml`. Updated Maven configuration to include OpenAPI generator plugin for generating API documentation. It makes sure that API endpoints are well-documented and accessible.

## Motivation and Context
This change is required to provide a standardized and comprehensive documentation for the Presto query API. It helps developers understand and interact with the API more effectively. Closes issue #1234.

## Impact
This update adds detailed OpenAPI documentation for the Presto query endpoints, making it easier for users to discover and use these endpoints. No performance impact is expected.

## Test Plan
- Verified the OpenAPI specification by generating the documentation and viewing it in the browser.
- Tested the API endpoints using Postman to ensure they work as expected.

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ... :pr:`12345`
* ... :pr:`12345`

Hive Connector Changes
* ... :pr:`12345`
* ... :pr:`12345`
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2024-06-11 16:12 UTC, swapsmagic commented on pom.xml
> +        <module>presto-ui</module>
why are we adding this dependency again? It was removed as part of this PR https://github.com/prestodb/presto/pull/22823

2024-06-13 13:55 UTC, ZacBlanco requested changes

2024-06-13 13:55 UTC, ZacBlanco commented on presto-openapi/src/main/resources/query.yaml
> +          description: The time when the query was created
nit: add a newline at the end of the file

2024-06-13 13:55 UTC, ZacBlanco commented on presto-openapi/src/main/resources/query.yaml
> +    description: Optional server description, e.g. Main (production) server
Let's remove this server since there is no "production" server for OSS. It's up to users to deploy their own endpoint.

2024-06-13 13:55 UTC, ZacBlanco commented on presto-openapi/src/main/resources/query.yaml
> +    description: Optional server description, e.g. Internal staging server for testing
Let's use `http://localhost:8080` here for the URL as that's the endpoint for the API when running Presto locally. The description should also be updated to reflect that. Something like: `Presto endpoint when running locally`

2024-06-13 13:55 UTC, ZacBlanco commented on presto-openapi/src/main/resources/query.yaml
> +      description: Retrieves information about all queries with optional filtering and limiting
```suggestion
      description: Retrieves information about all queries with the ability to filter and limit the result list using optional parameters
```

2024-06-20 15:08 UTC, ZacBlanco requested changes

2024-06-20 15:08 UTC, ZacBlanco commented on presto-openapi/src/main/resources/cluster.yaml
> +  - url: http://staging-api.example.com
let's keep the server section the same as in `query.yaml`

2024-06-20 15:08 UTC, ZacBlanco commented on presto-openapi/src/main/resources/cluster.yaml
> +          description: Time-to-live value for the cluster
we should add a newline at the end of the file

2024-06-20 15:08 UTC, ZacBlanco commented on pom.xml
> +        <module>presto-ui</module>
please remove the line with `presto-ui`

2024-06-27 16:58 UTC, swapsmagic commented on 5c6995b857742eb028932693d55ca8feccbc8f8b.patch
> +From 5c6995b857742eb028932693d55ca8feccbc8f8b Mon Sep 17 00:00:00 2001
remove the patch files

2024-06-27 16:58 UTC, swapsmagic commented on patchfile.patch
> +From 5c6995b857742eb028932693d55ca8feccbc8f8b Mon Sep 17 00:00:00 2001
remove the file

2024-07-03 16:00 UTC, ZacBlanco submitted a review, later dismissed
I think most of the REST methods look OK. I will need to take a closer pass at those later. The main issue is the schemas need to match exactly their corresponding java classes. Otherwise this is great!

2024-07-03 16:00 UTC, ZacBlanco commented on presto-openapi/src/main/resources/cluster.yaml
> +  version: 1
Should be a string: i.e. "1"

2024-07-03 16:00 UTC, ZacBlanco commented on presto-openapi/src/main/resources/cluster.yaml
> +          default: false
`default` is not valid here. It should be under the `schema` block

2024-07-03 16:00 UTC, ZacBlanco commented on presto-openapi/src/main/resources/cluster.yaml
> +        workers:
So the output of the `getWorkerMemoryInfo` method which generates the response for this API is a `Map<String, MemoryInfo>`, so this schema need to be updated to reflect that - it isn't an array. You'll also need to add the `MemoryInfo`, `DataSize`, `MemoryPoolId`, and `MemoryPoolInfo` schema objects.

2024-07-03 16:00 UTC, ZacBlanco commented on presto-openapi/src/main/resources/cluster.yaml
> +    ClusterTtl:
This object should mirror the `ConfidenceBasedTtlInfo` class. Currently it is missing the correct fields

2024-07-03 16:00 UTC, ZacBlanco commented on presto-openapi/src/main/resources/cluster.yaml
> +        pools:
Where did you find this property on the `ClusterMemoryPoolInfo` class? I don't see this field defined. This object should mirror the `ClusterMemoryPoolInfo` class fields

2024-07-03 16:00 UTC, ZacBlanco commented on presto-openapi/src/main/resources/cluster.yaml
> +                $ref: '#/components/schemas/ClusterMemoryPoolInfo'
the returned schema is actually a map of `MemoryPoolId` to `MemoryPoolInfo` objects

2024-07-03 16:00 UTC, ZacBlanco commented on presto-openapi/src/main/resources/cluster.yaml
> +                $ref: '#/components/schemas/ClusterTtl'
Let's keep names consistent with the java class name. Can we rename to `ConfidenceBasedTtlInfo`?

2024-07-03 16:00 UTC, ZacBlanco commented on presto-openapi/src/main/resources/query.yaml
> +      properties:
We're missing a lot of fields from the `BasicQueryInfo` class here. They should all be added to this. Look at `BasicQueryInfo.java` and include all of the `private final` fields in this schema definition

2024-07-03 16:00 UTC, ZacBlanco commented on presto-openapi/src/main/resources/query.yaml
> +    QueryStats:
I think this should be `BasicQueryStats`. There's also a lot of missing fields. All the constructor parameters annotated with `@JsonProperty` should be included in this schema

2024-07-03 16:00 UTC, ZacBlanco commented on presto-openapi/src/main/resources/queued_statement.yaml
> +    QueryResults:
We're missing a lot of fields here. Make sure all the `@JsonProperty`-annotated constructor arguments in `QueryResults.java` are reflected in this schema

2024-07-03 16:00 UTC, ZacBlanco commented on presto-openapi/src/main/resources/queued_statement.yaml
> +      properties:
similar comment about missing fields. Check the `@JsonProperty`-annotated fields in the constructor

2024-07-03 16:00 UTC, ZacBlanco commented on presto-openapi/pom.xml
> +        <version>0.288-SNAPSHOT</version>
This needs to be updated to `0.289-SNAPSHOT` since a new release has occurred recently

2024-07-29 15:37 UTC, ZacBlanco commented
FYI @tdcmeehan @steveburnett . As a start we could incorporate the generated documentation into out docs website.

2024-07-29 17:29 UTC, steveburnett commented
> FYI @tdcmeehan @steveburnett . As a start we could incorporate the generated documentation into out docs website.

I think that would be great!

2024-08-06 20:00 UTC, tdcmeehan commented
It seems a `_full_spec.yaml` file is generated after each Maven run.  Is it expected that this file is checked in?  Is there any way to make it go to the target directory, then referenced as needed as a purely generated artifact?

2024-08-07 19:48 UTC, tdcmeehan approved these changes

2024-08-07 19:48 UTC, merged