Improve the documentation for two memory counters
prestodb/presto pull request #23126
Opened 2024-07-02 20:57 UTC by yingsu00

## Description
Following the discussion of 0.288 release notes, I'm making these changes to clarify the two memory counters meanings. They are `query-memory-gb` and `query-reserved-memory-gb`.

## Impact
Help the user to understand these counters better

## Test Plan

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

```
== NO RELEASE NOTE ==
```

2024-07-02 21:08 UTC, steveburnett requested changes
Looks good, thanks! Nits of formatting, nothing else. Let me know if my suggestions are not correct, please.

2024-07-02 21:08 UTC, steveburnett commented on presto-docs/src/main/sphinx/presto_cpp/properties.rst
> +  1) the non-reserved space in "query-memory-gb" is used up; and 2) the amount
```suggestion
  1) the non-reserved space in ``query-memory-gb`` is used up; and 2) the amount
```

2024-07-02 21:08 UTC, steveburnett commented on presto-docs/src/main/sphinx/presto_cpp/properties.rst
> +  it is trying to get is less than 'memory-pool-reserved-capacity'.
```suggestion
  it is trying to get is less than ``memory-pool-reserved-capacity``.
```

2024-07-02 21:08 UTC, steveburnett commented on presto-docs/src/main/sphinx/presto_cpp/properties.rst
> +  1) Memory used by the queries as specified in "query-memory-gb"; 2) System memory usage,
```suggestion
  1) Memory used by the queries as specified in ``query-memory-gb``; 2) System memory usage,
```

2024-07-02 23:40 UTC, xiaoxmeng approved these changes
@yingsu00 LGTM. Thanks for the improvement!

2024-07-02 23:40 UTC, xiaoxmeng commented on presto-native-execution/presto_cpp/main/common/Configs.h
> +  /// a query is trying to allocate memory from the reserved space whose size is
```
nit: s/is trying/tries/
```

2024-07-02 23:40 UTC, xiaoxmeng commented on presto-native-execution/presto_cpp/main/common/Configs.h
> +  /// it is trying to get is less than 'memory-pool-reserved-capacity'.
```
s/is trying/tries/
```

2024-07-03 16:17 UTC, yingsu00 commented
@steveburnett Thanks for reviewing! I have updated the PR with your comment addressed. Can you please review again?

2024-07-03 16:46 UTC, steveburnett submitted a review, later dismissed
LGTM! (docs) 
Pull updated branch, new local docs build, looks good. Thanks!

2024-07-03 18:41 UTC, yingsu00 commented
Thanks @xiaoxmeng and @steveburnett for reviewing! 
@steveburnett if this looks ok to you, will you be able to approve this PR? THanks!

2024-07-03 18:45 UTC, steveburnett approved these changes
LGTM! (docs) 

Pull updated branch, new local docs build, looks good. Thanks!

2024-07-05 16:35 UTC, merged