Revert "[native]Add data cache related server operations"
prestodb/presto pull request #23157
Opened 2024-07-09 21:21 UTC by majetideepak

This reverts commit b73ab7df31e4d969c44fd953e5cb8e36a18eb55b.

## Description

## Motivation and Context

## Impact

## Test Plan

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ... :pr:`12345`
* ... :pr:`12345`

Hive Connector Changes
* ... :pr:`12345`
* ... :pr:`12345`
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2024-07-09 23:24 UTC, xiaoxmeng requested changes
@majetideepak do you know what's the failure of the test? I think the server operation change is unrelated to the failed test. I am on vocation but you can also ask @zacw7 to help fix this. Thanks!

2024-07-10 02:02 UTC, zacw7 requested changes
This change itself doesn't have issue. It just includes a breaking change in Velox: https://github.com/facebookincubator/velox/pull/10261

2024-07-10 02:20 UTC, tdcmeehan commented
@zacw7 @xiaoxmeng unfortunately, this commit included *both* an update to Velox and the server operations endpoint.  So to avoid keeping trunk in a broken state, let's revert, then re-add without the Velox bump.

@yingsu00 please note the above, can you please address?  Thanks.

2024-07-10 02:20 UTC, tdcmeehan approved these changes

2024-07-10 03:57 UTC, xiaoxmeng commented
> @zacw7 @xiaoxmeng unfortunately, this commit included _both_ an update to Velox and the server operations endpoint. So to avoid keeping trunk in a broken state, let's revert, then re-add without the Velox bump.
> 
> @yingsu00 please note the above, can you please address? Thanks.

@tdcmeehan since we know the issue, why not make a forward fix from Velox side?

2024-07-10 04:01 UTC, zacw7 commented
This change and the advanced Velox version are already being released to prod. Instead of reverting a whole bunch of change together, is it possible to revert the one breaking change in Velox if we really want to fix the broken trunk ASAP to minimize the disruption.

2024-07-10 15:08 UTC, tdcmeehan commented
It's fine to revert in Velox first, then advance Velox here.  But I have a question @zacw7: if we were to revert this PR here, are you suggesting this might affect your production deployment?

2024-07-10 17:20 UTC, majetideepak commented
I am closing this in favor of advancing Velox.

2024-07-10 17:20 UTC, closed without merging

2024-07-10 17:30 UTC, zacw7 commented
> It's fine to revert in Velox first, then advance Velox here. But I have a question @zacw7: if we were to revert this PR here, are you suggesting this might affect your production deployment?

It doesn't affect deployment directly. But this is already being rolled out to prod so we would prefer not have it reverted.