[Iceberg] Add table refresh retry configurations
prestodb/presto pull request #23174
Opened 2024-07-10 21:47 UTC by ZacBlanco

## Description

1. Add configurations for the table refresh retries inside of `HiveTableOperations`
2. Catch and rethrow the original exception when all retries on table refresh fail.
3. Fix a test which executed very slowly (6 minutes -> 3 seconds!) due to not being able to configure these retries

## Motivation and Context

We have a test which takes a long time to finish due to this retry being unconfigurable. Additionally, there have been community reports where the errors are opaque and queries hang due to this retry.

Adding a configuration and error logging should help determine root causes and allow users to improve the behavior of query hangs by specifying these configuration properties.

## Impact

Additional configurations available in the Iceberg connector.

## Test Plan

- Added relevant configuration tests

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [x] CI passed.

## Release Notes

```
== RELEASE NOTES ==

General Changes
* The Iceberg connector when configured with Hive, can now configure table metadata refresh timeouts. See documentation for details.
```

2024-07-11 14:39 UTC, steveburnett requested changes
Local doc build throws the following warnings. Could you fix the table problems in these warnings, and then re-request my review? 

/Users/steveburnett/Documents/GitHub/presto/presto-docs/src/main/sphinx/connector/iceberg.rst:51: ERROR: Malformed table.
Bottom/header table border does not match top border.
/Users/steveburnett/Documents/GitHub/presto/presto-docs/src/main/sphinx/connector/iceberg.rst:106: WARNING: Blank line required after table.
/Users/steveburnett/Documents/GitHub/presto/presto-docs/src/main/sphinx/connector/iceberg.rst:152: ERROR: Malformed table.
Text in column margin in table line 10.
/Users/steveburnett/Documents/GitHub/presto/presto-docs/src/main/sphinx/connector/iceberg.rst:206: WARNING: Blank line required after table.
/Users/steveburnett/Documents/GitHub/presto/presto-docs/src/main/sphinx/connector/iceberg.rst:225: ERROR: Malformed table.
Bottom/header table border does not match top border.
/Users/steveburnett/Documents/GitHub/presto/presto-docs/src/main/sphinx/connector/iceberg.rst:242: WARNING: Blank line required after table.
/Users/steveburnett/Documents/GitHub/presto/presto-docs/src/main/sphinx/connector/iceberg.rst:269: WARNING: Inline literal start-string without end-string.

2024-07-11 16:15 UTC, steveburnett requested changes
Thanks! Some nits of punctuation only, no text issues.

2024-07-11 16:15 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/iceberg.rst
> +                                                         refreshing table metadata
```suggestion
                                                         refreshing table metadata.
```

2024-07-11 16:15 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/iceberg.rst
> +                                                         refreshing table metadata
```suggestion
                                                         refreshing table metadata.
```

2024-07-11 16:15 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/iceberg.rst
> +                                                         failing a table metadata refresh operation
```suggestion
                                                         failing a table metadata refresh operation.
```

2024-07-11 16:15 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/iceberg.rst
> +                                                         table metadata using the Hive metastore
```suggestion
                                                         table metadata using the Hive metastore.
```

2024-07-11 16:15 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/iceberg.rst
> +                                                         retries
```suggestion
                                                         retries.
```

2024-07-12 15:01 UTC, steveburnett approved these changes
LGTM! (docs)

Pull updated branch, new local doc build, looks good. Thanks!

2024-07-12 15:12 UTC, tdcmeehan approved these changes

2024-07-12 16:16 UTC, hantangwangd approved these changes

2024-07-12 16:27 UTC, merged