Fix docs links
prestodb/presto pull request #23216
Opened 2024-07-15 18:04 UTC by elharo

## Description

fixes #23209

## Motivation and Context

## Impact

## Test Plan
CI

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [x] CI passed.

## Release Notes

```
== NO RELEASE NOTE ==
```

2024-07-15 18:16 UTC, steveburnett requested changes
Thanks! Tested the links and one failed, suggested a change that worked for me.

2024-07-15 18:16 UTC, steveburnett commented on README.md
> +See the [Presto installation documentation](https://prestodb.io/docs/current/installation) for deployment instructions.
```suggestion
See the [Presto installation documentation](https://prestodb.io/docs/current/installation.html) for deployment instructions.
```
https://prestodb.io/docs/current/installation fails, returning a 403 Forbidden. Suggest this link.

2024-07-15 18:49 UTC, steveburnett approved these changes
LGTM! (docs) 

Squash commits, and it's done.

2024-07-16 16:56 UTC, hantangwangd approved these changes

2024-07-17 11:49 UTC, merged