Add support for ALTER TABLE statement in MongoDB
prestodb/presto pull request #23266
Opened 2024-07-20 14:20 UTC by NaveenNitturu

## Description

## Motivation and Context

[#23265 ](url)
Adding the ALTER TABLE support for MongoDB connector.

## Impact

Introducing a new feature in the MongoDB connector: support for ALTER TABLE statements to ADD, DROP and RENAME columns.

## Test Plan

Configured the MongoDB connector, by creating a catalog properties file in etc/catalog named mongodb.properties, to mount the MongoDb connector as the MongoDB catalog. Tested all three statements: ADD, DROP, and RENAME.

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

MongoDB Changes
* Add support for MongoDB ALTER TABLE statement.
```

2024-08-30 13:25 UTC, tdcmeehan requested changes
Please squash commits

2024-08-30 13:25 UTC, tdcmeehan commented on presto-mongodb/src/test/java/com/facebook/presto/mongodb/TestMongoIntegrationSmokeTest.java
> +        assertUpdate("ALTER TABLE test_alter.tmp_alter_table RENAME COLUMN email TO email_id");
Please query the renamed column

2024-08-30 14:49 UTC, steveburnett submitted a review, later dismissed
LGTM! (docs) 

Pull branch, local doc build, looks good. Thanks!

2024-08-30 14:51 UTC, steveburnett commented
Nits of suggested changes for the release note entry:

```
== RELEASE NOTES ==

MongoDB Connector Changes
* Add support for MongoDB ``ALTER TABLE`` statement. :pr:`23266`
```

2024-08-30 15:44 UTC, NaveenNitturu commented on presto-mongodb/src/test/java/com/facebook/presto/mongodb/TestMongoIntegrationSmokeTest.java
> +        assertUpdate("ALTER TABLE test_alter.tmp_alter_table RENAME COLUMN email TO email_id");
added the query for renamed column.

2024-08-31 08:03 UTC, NaveenNitturu commented
> Please squash commits

squashed the commits, Could you please review.

2024-09-03 19:04 UTC, tdcmeehan approved these changes

2024-09-03 19:04 UTC, merged