[wip] Update docker compose scripts for docker compose v2
prestodb/presto pull request #23360
Opened 2024-08-01 19:59 UTC by rschlussel

## Description
Update docker compose scripts for docker compose v2, as legacy docker-compose v1 is no longer supported for github actions.

This is blindly/naively changed. going to run in the ci and see if it works.

## Motivation and Context

## Impact

## Test Plan
CI
## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ... :pr:`12345`
* ... :pr:`12345`

Hive Connector Changes
* ... :pr:`12345`
* ... :pr:`12345`
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2024-08-01 21:55 UTC, steveburnett requested changes
A single nit of formatting, looks good otherwise!

2024-08-01 21:55 UTC, steveburnett commented on presto-product-tests/README.md
> +* [`docker compose >= 2.3.4](https://docs.docker.com/compose/install/)
```suggestion
* [`docker compose >= 2.3.4`](https://docs.docker.com/compose/install/)
```

2024-08-01 21:55 UTC, ZacBlanco submitted a review, later dismissed

2024-08-01 21:57 UTC, steveburnett submitted a review, later dismissed
LGTM! (docs)

2024-08-02 14:57 UTC, tdcmeehan approved these changes

2024-08-02 14:57 UTC, merged