Add release notes for 0.288.1
prestodb/presto pull request #23424
Opened 2024-08-12 08:16 UTC by wanglinsong

## Description
Add release notes for 0.288.1

```
== NO RELEASE NOTE ==
```

2024-08-12 14:09 UTC, steveburnett requested changes
Thanks for the doc! Everything builds and looks good. Suggest adding a link to the issue.

2024-08-12 14:09 UTC, steveburnett commented on presto-docs/src/main/sphinx/release/release-0.288.rst
> +   Package presto-server-0.288.tar.gz does not have presto-ui module, Presto Console does not work.
```suggestion
   Package presto-server-0.288.tar.gz does not have presto-ui module, Presto Console does not work. :issue:`23327`
```
Add issue number.

2024-08-12 14:09 UTC, steveburnett commented on presto-docs/src/main/sphinx/release/release-0.288.1.rst
> +* Rebuild package presto-server to include presto-ui module.
```suggestion
* Rebuild package presto-server to include presto-ui module. :issue:`23327`
```

2024-08-12 15:02 UTC, tdcmeehan requested changes

2024-08-12 15:02 UTC, tdcmeehan commented on presto-docs/src/main/sphinx/release/release-0.288.rst
> +   Package presto-server-0.288.tar.gz does not have presto-ui module, Presto Console does not work.
```suggestion
   The tarball package ``presto-server-0.288.tar.gz`` does not include the Presto Console.  This has been fixed in the patch version ``0.288.1``. :issue:`23327`
```

2024-08-12 15:02 UTC, tdcmeehan commented on presto-docs/src/main/sphinx/release/release-0.288.1.rst
> +* Rebuild package presto-server to include presto-ui module.
```suggestion
* The Presto Console is included in this release. :issue:`23327`
```

2024-08-12 19:20 UTC, steveburnett approved these changes
LGTM! (docs) 

Pull updated branch, new local doc build. Thanks!

2024-08-14 11:24 UTC, tdcmeehan approved these changes

2024-08-14 11:24 UTC, merged