Unescape like pattern, and check for one character escape string when in row expression interpreter
prestodb/presto pull request #23456
Opened 2024-08-15 21:41 UTC by auden-woolfson

## Description
fix bug described in issue #23450 

```
== RELEASE NOTES ==

General Changes
* Unescape like pattern and validate escape string with no unresolved value :pr:`12345`
```

2024-08-15 21:52 UTC, steveburnett commented
Nit suggestion to revise release note entry for consistency with the [Order of Changes](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines#order-of-changes) in the Release Notes Guidelines. 

```
== RELEASE NOTES ==

General Changes
* Fix bug to unescape like pattern and validate escape string with no unresolved value :pr:`23456`
```

2024-08-15 23:49 UTC, tdcmeehan commented
Thanks for the quick work. Can you please add a test?

2024-08-16 19:35 UTC, tdcmeehan commented
This looks good, but I think we should add one more test that shows this works in a query.

2024-08-17 16:18 UTC, elharo commented on presto-tests/src/main/java/com/facebook/presto/tests/TestLikeQueries.java
> +    public void testLikeQueriesWithEscape()
This should be 4 separate tests that can pass or fail independently.

2024-08-19 15:39 UTC, tdcmeehan requested changes

2024-08-19 15:39 UTC, tdcmeehan commented on presto-tests/src/main/java/com/facebook/presto/tests/TestLikeQueries.java
> +        extends AbstractTestQueries
This will create a new suite of tests derived from the parent class.  Perhaps instead inherit from `AbstractTestQueryFramework`, which won't do this.

2024-08-20 15:31 UTC, tdcmeehan commented
Looks good.  Please squash commits and check our contributing guide for commit message guidelines.

2024-08-21 19:59 UTC, tdcmeehan commented
@auden-woolfson there is a test failure

2024-08-21 21:09 UTC, auden-woolfson commented
> @auden-woolfson there is a test failure

There are 4 test cases that assert like functions with empty escapes in `TestConditions`. Should I just remove these? Or assert that they fail?

2024-08-23 19:02 UTC, tdcmeehan commented
LGTM.  Please rebase to fix the conflict.

2024-08-26 14:28 UTC, tdcmeehan approved these changes

2024-08-26 18:25 UTC, merged