Adding Build-enabled properties LinuxMemoryChecker for documentation
prestodb/presto pull request #23460
Opened 2024-08-16 18:49 UTC by minhancao

## Description

Adding Build-enabled properties LinuxMemoryChecker for documentation. Documenting the work done for LinuxMemoryChecker in https://github.com/prestodb/presto/pull/22997.

## Motivation and Context

## Impact

## Test Plan

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ... :pr:`12345`
* ... :pr:`12345`

Hive Connector Changes
* ... :pr:`12345`
* ... :pr:`12345`
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2024-08-16 19:24 UTC, steveburnett requested changes
Thanks for the doc! A few nits of formatting and one of phrasing, looks good otherwise.

2024-08-16 19:24 UTC, steveburnett commented on presto-docs/src/main/sphinx/presto_cpp/properties.rst
> +The following properties are available only if certain properties are enabled at build time via CMakeLists.txt.
```suggestion
The following properties are available only if certain properties are enabled at build time by using CMakeLists.txt.
```
Do not use via. See the [GitLab documentation style guide recommended word list entry for via](https://docs.gitlab.com/ee/development/documentation/styleguide/word_list.html#via) for alternatives: I suggested one but please choose another rephrasing if "by using" doesn't work for you.

2024-08-16 19:24 UTC, steveburnett commented on presto-docs/src/main/sphinx/presto_cpp/properties.rst
> +to ON in presto-native-execution/CMakeLists.txt will make the following properties available:
```suggestion
to ``ON`` in presto-native-execution/CMakeLists.txt will make the following properties available:
```
Format values to emphasize them in text.

2024-08-16 19:24 UTC, steveburnett commented on presto-docs/src/main/sphinx/presto_cpp/properties.rst
> +If true, starts memory limit checker to trigger memory pushback when
```suggestion
If set to ``true``, starts memory limit checker to trigger memory pushback when
```

2024-08-16 19:24 UTC, steveburnett commented on presto-docs/src/main/sphinx/presto_cpp/properties.rst
> +``systemMemPushbackEnabled`` is true.
```suggestion
``systemMemPushbackEnabled`` is set to ``true``.
```

2024-08-16 19:24 UTC, steveburnett commented on presto-docs/src/main/sphinx/presto_cpp/properties.rst
> +triggered. This only applies if ``systemMemPushbackEnabled`` is true.
```suggestion
triggered. This only applies if ``systemMemPushbackEnabled`` is set to ``true``.
```

2024-08-16 21:34 UTC, steveburnett approved these changes
LGTM! (docs)

Pulled updated branch, new local doc build, looks good. Thanks!

2024-08-21 01:28 UTC, yingsu00 approved these changes
@minhancao Can you please clean up the release note section? Only the "no release note" part shall remain.

2024-08-21 07:24 UTC, aditi-pandit requested changes
@minhancao : Please merge your commits and change the subject to that of the PR.

2024-08-21 18:52 UTC, minhancao commented
Merged this doc PR into https://github.com/prestodb/presto/pull/22997, closing this PR since it's not needed.

2024-08-21 18:52 UTC, closed without merging