Fix to avoid retrying the metadata loading once a FileNotFoundException is thrown, when trying to drop Iceberg/Hive tables, whose metadata is deleted from its S3 storage
prestodb/presto pull request #23510
Opened 2024-08-23 17:10 UTC by dmariamgeorge

## Description
According to the current behaviour, when a table's metadata is deleted from S3, it repeatedly tries to access the metadata file, leading to multiple retries and delays in dropping the table. with this fix, upon encountering a FileNotFoundException, it immediately halts retries and proceeds with the drop operation, completing the task in a fraction of the time.

## Motivation and Context
Fixes issue: 

## Impact
Users will experience significantly faster drop operations for Iceberg or Hive tables whose metadata has already been deleted from S3 storage. Instead of encountering long delays due to unnecessary retries, it will now recognize when the metadata is missing and complete the drop operation more quickly.

## Test Plan

1. Connected Presto to an S3 Minio storage through the Hive connector.
2. Created a schema, and within the schema created a table.
3. Now, deleted the metadata and the bucket.
4. Tried dropping the associated the table.
5. The table drop operation got completed quickly. 

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes

```
== RELEASE NOTES ==

Hive Connector Changes
* Fix to reduce drop time for Iceberg/Hive tables with deleted metadata in S3 storage:pr:`12345`.

Iceberg Connector Changes
* Fix to reduce drop time for Iceberg/Hive tables with deleted metadata in S3 storage:pr:`12345`.
```

2024-08-23 18:45 UTC, tdcmeehan commented
Nice change @dmariamgeorge .  Can you please try to create a test case for this?

2024-08-24 11:53 UTC, dmariamgeorge commented
> Nice change @dmariamgeorge . Can you please try to create a test case for this?

@tdcmeehan - There exists a testcase testTableDropWithMissingMetadata() for this: https://github.com/prestodb/presto/blob/d7ca7af192d3647ed1ef93a6b008f9158f3ce847/presto-iceberg/src/test/java/com/facebook/presto/iceberg/TestIcebergMetadataListing.java#L124

2024-08-25 03:51 UTC, hantangwangd reviewed
Nice catch, the change looks good to me!

Maybe in `TestIcebergMetadataListing` we can set `iceberg.hive.table-refresh.max-retry-time` to a longer period, and validate the `timeOut` of `testTableDropWithMissingMetadata()` to a shorter period, so that we can confirm that it did not trigger the retry?

2024-08-27 18:38 UTC, tdcmeehan requested changes

2024-08-27 18:38 UTC, tdcmeehan commented on presto-iceberg/src/test/java/com/facebook/presto/iceberg/TestIcebergMetadataListing.java
> +        assertQuerySucceedsWithTimeout("DROP TABLE iceberg.test_metadata_schema.iceberg_table1", expectedDropTableDuration);
Can you separate this into a different test case, and use `@Test(timeOut = ...)` instead of measuring manually?

2024-08-30 03:11 UTC, hantangwangd commented on presto-iceberg/src/test/java/com/facebook/presto/iceberg/TestIcebergMetadataListing.java
> +        queryRunner.createCatalog(ICEBERG_CATALOG, "iceberg", testIcebergProperties);
We shouldn't create a new query runner here, and it is not the query runner used for executing the following statements. I think just  set `iceberg.hive.table-refresh.max-retry-time` to `50s` for the query runner created in method `createQueryRunner()` would be ok. Or we can simultaneously lower this value and the timeout value to 20s and 10s.

2024-08-30 13:35 UTC, tdcmeehan commented on presto-iceberg/src/test/java/com/facebook/presto/iceberg/TestIcebergMetadataListing.java
> +    @Test (timeOut = TEST_TIMEOUT)
Looks good.  Just add a comment explaining that the `iceberg.hive.table-refresh.max-retry-time` property is important, and if the test starts to fail, to look at your code change in `HiveTableOperations`.

2024-08-30 15:05 UTC, steveburnett commented
Nit of formatting on the release note entry - need a space before `:pr:`

```
== RELEASE NOTES ==

Iceberg Connector Changes
* Fix to reduce drop time for Iceberg tables with deleted metadata in S3 storage. :pr:`23510`
```

2024-08-30 15:29 UTC, tdcmeehan approved these changes

2024-08-30 15:31 UTC, hantangwangd approved these changes
Thanks for the fix.

2024-08-30 15:34 UTC, ZacBlanco approved these changes

2024-08-31 07:12 UTC, merged