[iceberg] Add procedure rollback_to_timestamp
prestodb/presto pull request #23559
Opened 2024-08-30 11:11 UTC by imjalpreet

## Description

This PR adds a procedure to rollback a table to a given point in time.

Example:

```
CALL iceberg.system.rollback_to_timestamp('schema_name', 'table_name', TIMESTAMP '1995-04-26 00:00:00.000');
```

## Motivation and Context

Ability to rollback a table to a given point in time

## Impact

New Procedure `rollback_to_snapshot` added

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

Iceberg Connector Changes
* Add procedure `rollback_to_timestamp` to rollback an iceberg table to a given point in time. :pr:`23559`
```

2024-08-30 15:15 UTC, steveburnett requested changes
Thanks for the doc! One nit of formatting, otherwise this looks good.

2024-08-30 15:15 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/iceberg.rst
> +^^^^^^^^^^^^^^^^^^^^
```suggestion
^^^^^^^^^^^^^^^^^^^^^
```
Formatting line must match the number of characters in the line it is formatting.

2024-09-03 08:27 UTC, hantangwangd reviewed
Thanks for adding this procedure. Overall looks good to me, just one nit.

2024-09-03 09:48 UTC, imjalpreet commented on presto-iceberg/src/test/java/com/facebook/presto/iceberg/procedure/TestRollbackToTimestampProcedure.java
> +                "tableName is empty");
Thanks, I have added a new test

2024-09-03 10:55 UTC, hantangwangd approved these changes
Thanks for the fix, lgtm!

2024-09-03 19:45 UTC, imjalpreet commented
@ZacBlanco @tdcmeehan let me know if you have any suggestions otherwise we can get this merged.

2024-09-03 19:52 UTC, ZacBlanco approved these changes

2024-09-03 21:14 UTC, merged