Reduce size of Presto distribution
prestodb/presto pull request #23647
Opened 2024-09-13 15:18 UTC by tdcmeehan

Remove presto-example-http, presto-hana, presto-blackhole, presto-kudu, presto-ml, presto-teradata-functions, presto-accumulo and presto-hive-function-namespace from the default distribution.  Users can add these plugins to their deployments manually if these plugins are desired.

## Description
Presto 0.289 cannot be downloaded due to the size of the distribution.  Remove uncommon plugins from the default distribution (these can always be added manually).

## Motivation and Context
Fix 0.289

## Impact
Certain plugins will now need to be manually included.

## Test Plan
Product tests should be sufficient

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes

```
== NO RELEASE NOTE ==
```

2024-09-13 23:12 UTC, imjalpreet reviewed
We may need to make additional changes to exclude the removed plugins from the default configurations, such as removing them from the plugin.bundles in config.properties.

I also noticed product-test failures due to the removal of the blackhole connector, as there are tests for it enabled in the Presto product test suite(s). We might need to either retain the blackhole connector or disable those tests.

2024-09-17 11:55 UTC, elharo approved these changes
Test failures don't look related but just to be certain let's get a passing CI before merging. 

Error running command: java.net.UnknownHostException: presto-master: Temporary failure in name resolution

2024-09-17 12:03 UTC, imjalpreet commented
@elharo The real reason for failure is the removal of the blackhole connector plugin.

```
presto-master-1  | 2024-09-13T21:11:04.089+0545	INFO	main	com.facebook.presto.metadata.StaticCatalogStore	-- Loading catalog blackhole --
presto-master-1  | 2024-09-13T21:11:04.090+0545	ERROR	main	com.facebook.presto.server.PrestoServer	No factory for connector blackhole
presto-master-1  | java.lang.IllegalArgumentException: No factory for connector blackhole
presto-master-1  | 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218)
presto-master-1  | 	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:217)
presto-master-1  | 	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:123)
presto-master-1  | 	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:98)
presto-master-1  | 	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:80)
presto-master-1  | 	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
presto-master-1  | 	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:150)
presto-master-1  | 	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:85)
presto-master-1  | 
presto-master-1  | 
presto-master-1  | 2024-09-13T21:11:04.097+0545	INFO	Thread-85	com.facebook.airlift.bootstrap.LifeCycleManager	Life cycle stopping...
presto-master-1  | 2024-09-13T21:11:04.098+0545	INFO	Thread-85	com.facebook.airlift.bootstrap.LifeCycleManager	Life cycle stopped.
``` 

Due to this, Presto server is not able to start successfully and the test command to check whether Presto is up and running is failing with the below exception:
`Error running command: java.net.UnknownHostException: presto-master: Temporary failure in name resolution`

2024-09-17 12:24 UTC, elharo requested changes
Good catch @imjalpreet 

Likely the quickest path forward is to reenable presto-blackhole and remove it, if ever, in a separate PR.

2024-09-17 13:56 UTC, tdcmeehan commented
Folks, thanks for the reviews, but I don't think it's necessary to remove these projects from our distribution.  Will open a new PR momentarily.

2024-09-17 13:56 UTC, closed without merging