[native] Add support for DEPENDENCY_DIR, INSTALL_PREFIX, PYTHON_VENV
prestodb/presto pull request #23776
Opened 2024-10-07 10:12 UTC by majetideepak

## Description

DEPENDENCY_DIR and INSTALL_PREFIX help developers manage dependencies.
PYTHON_VENV is used to configure the clang-format package.

## Motivation and Context

## Impact

## Test Plan

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ... :pr:`12345`
* ... :pr:`12345`

Hive Connector Changes
* ... :pr:`12345`
* ... :pr:`12345`
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2024-10-07 14:11 UTC, steveburnett requested changes
Thanks for the doc! A couple of minor nits, and a suggestion to rephrase for easier understanding.

2024-10-07 14:11 UTC, steveburnett commented on presto-native-execution/README.md
> +location (eg. `/usr/local`) on linux.
```suggestion
location (for example, `/usr/local`) on linux.
```

2024-10-07 14:11 UTC, steveburnett commented on presto-native-execution/README.md
> +Using the default install location `/usr/local` on macOS is discouraged since this
```suggestion
Using the default install location `/usr/local` on macOS is discouraged because this
```

2024-10-07 14:11 UTC, steveburnett commented on presto-native-execution/README.md
> +Manually add the `INSTALL_PREFIX` value in the IDE or bash environment,
```suggestion
Manually add the `INSTALL_PREFIX` value in the IDE or bash environment so subsequent Velox builds can use the installed packages.
```
Suggest revising this to describe in one sentence what you want the user to do, then separate out the example as a second sentence. I've tried doing this here, let me know if my suggestion makes sense.

2024-10-07 14:11 UTC, steveburnett commented on presto-native-execution/README.md
> +subsequent Velox builds can use the installed packages.
```suggestion
```

2024-10-07 17:03 UTC, czentgr approved these changes
Looks good.

2024-10-07 18:25 UTC, steveburnett approved these changes
LGTM! (docs)

2024-10-07 19:34 UTC, majetideepak commented on presto-native-execution/scripts/setup-macos.sh
> +BUILD_DUCKDB="${BUILD_DUCKDB:-false}"
@czentgr I added this change as well.

2024-10-08 14:08 UTC, czentgr approved these changes

2024-10-08 14:10 UTC, majetideepak commented
@tdcmeehan can you please help approve and merge this? Thanks.
This needs a committer approval due to the changes to .gitignore.

2024-10-08 19:42 UTC, tdcmeehan approved these changes

2024-10-08 19:42 UTC, merged