Upgrade elasticsearch module to
prestodb/presto pull request #23894
Opened 2024-10-28 08:38 UTC by infvg

## Description

## Motivation and Context

## Impact

## Test Plan

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ... :pr:`12345`
* ... :pr:`12345`

Hive Connector Changes
* ... :pr:`12345`
* ... :pr:`12345`
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2025-02-16 16:56 UTC, imjalpreet reviewed
@infvg I’m still reviewing the PR, but once the changes are approved, please squash all commits into a single commit that specifies the final Elasticsearch version we are upgrading to. You can include all co-authors in that commit.

2025-02-18 22:17 UTC, ZacBlanco requested changes

2025-02-18 22:17 UTC, ZacBlanco commented on presto-elasticsearch/src/main/java/com/facebook/presto/elasticsearch/client/ElasticsearchClient.java
> +                ElasticSearchClientUtils.setHosts(client, hosts);
static import

2025-02-18 22:17 UTC, ZacBlanco commented on presto-elasticsearch/src/main/java/com/facebook/presto/elasticsearch/client/ElasticsearchClient.java
> -                .setMaxRetryTimeoutMillis((int) config.getMaxRetryTime().toMillis());
Is this setting no longer available?

2025-02-18 22:17 UTC, ZacBlanco commented on presto-elasticsearch/src/main/java/com/facebook/presto/elasticsearch/client/ElasticsearchClient.java
> +            return ElasticSearchClientUtils.search(request, client);
static import

2025-02-18 22:17 UTC, ZacBlanco commented on presto-elasticsearch/src/main/java/com/facebook/presto/elasticsearch/client/ElasticsearchClient.java
> +            return ElasticSearchClientUtils.searchScroll(request, client);
static import

2025-02-18 22:17 UTC, ZacBlanco commented on presto-elasticsearch/src/main/java/com/facebook/presto/elasticsearch/client/ElasticsearchClient.java
> +            response = ElasticSearchClientUtils.performRequest(
static import

2025-02-18 22:17 UTC, ZacBlanco commented on presto-elasticsearch/src/main/java/com/facebook/presto/elasticsearch/client/ElasticsearchClient.java
> +            ElasticSearchClientUtils.clearScroll(request, client);
static import

2025-02-18 22:17 UTC, ZacBlanco commented on presto-elasticsearch/src/main/java/com/facebook/presto/elasticsearch/client/ElasticsearchClient.java
> +            response = ElasticSearchClientUtils.performRequest("GET", path, client);
static import

2025-02-18 22:17 UTC, ZacBlanco commented on presto-elasticsearch/src/test/java/com/facebook/presto/elasticsearch/ElasticsearchLoader.java
> +                restClient.bulk(request, RequestOptions.DEFAULT);
static import 
```suggestion
                restClient.bulk(request, DEFAULT);
```

2025-02-18 22:17 UTC, ZacBlanco commented on presto-elasticsearch/src/test/java/com/facebook/presto/elasticsearch/ElasticsearchNode.java
> +        // Need to provide implementation for the abstract method if required
is this a TODO?

2025-02-18 22:17 UTC, ZacBlanco commented on presto-elasticsearch/src/test/java/com/facebook/presto/elasticsearch/TestElasticsearchIntegrationSmokeTest.java
> +        ElasticSearchClientUtils.performRequest("PUT", "/emptyindex", client);
static import on all `ElasticSearchClientUtils`

2025-02-19 09:58 UTC, infvg commented on presto-elasticsearch/src/main/java/com/facebook/presto/elasticsearch/client/ElasticsearchClient.java
> +            ElasticSearchClientUtils.clearScroll(request, client);
The function is called clearScroll so the static import prevents it from calling itself

2025-02-19 10:02 UTC, infvg commented on presto-elasticsearch/src/main/java/com/facebook/presto/elasticsearch/client/ElasticsearchClient.java
> -                .setMaxRetryTimeoutMillis((int) config.getMaxRetryTime().toMillis());
Yep it was removed:
https://artifacts.elastic.co/javadoc/org/elasticsearch/client/elasticsearch-rest-client/6.7.1/org/elasticsearch/client/RestClientBuilder.html#setMaxRetryTimeoutMillis(int)
https://github.com/anthonygauthier/jmeter-elasticsearch-backend-listener/issues/79

2025-02-19 10:16 UTC, infvg commented
@ZacBlanco responded to comments
@imjalpreet squashed all commits into one

2025-02-19 16:43 UTC, ZacBlanco commented on presto-elasticsearch/src/test/java/com/facebook/presto/elasticsearch/ElasticsearchConnectorTest.java
> +    private final String elasticsearchServer = "docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.23";
Why don't we use a server version which matches the dependency version `7.17.24`?

2025-02-19 18:02 UTC, ZacBlanco commented on presto-elasticsearch/src/test/java/com/facebook/presto/elasticsearch/TestElasticsearchIntegrationSmokeTest.java
> +    private final String elasticsearchServer = "docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.23";
It seems this also needs to be updated?

2025-02-24 18:39 UTC, infvg commented
@ZacBlanco bumped the version

2025-02-25 20:27 UTC, agrawalreetika requested changes

2025-02-25 20:27 UTC, agrawalreetika commented on presto-elasticsearch/src/main/java/com/facebook/presto/elasticsearch/client/ElasticsearchClient.java
> +                throw new PrestoException(ELASTICSEARCH_QUERY_FAILURE, "SELECT * not allowed from relation that has no columns");
Would this exception be better here? Since this can only occur if there are no JsonNode returned from `OBJECT_MAPPER.readTree(body)`

```suggestion
                throw new PrestoException(ELASTICSEARCH_INVALID_RESPONSE, "No mappings found for index: " + index");
```

2025-02-25 20:27 UTC, agrawalreetika commented on presto-elasticsearch/src/main/java/com/facebook/presto/elasticsearch/client/ElasticsearchClient.java
> -
Undo this please

2025-02-26 16:07 UTC, infvg commented on presto-elasticsearch/src/main/java/com/facebook/presto/elasticsearch/client/ElasticsearchClient.java
> +                throw new PrestoException(ELASTICSEARCH_QUERY_FAILURE, "SELECT * not allowed from relation that has no columns");
Done

2025-02-26 17:33 UTC, ZacBlanco submitted a review, later dismissed
Changes LGTM, but in the PR impact section we should probably note that we're upgrading to Elastic 7 from 6. We should research the incompatibilities and document them in this PR. e.g. there seems to be a change in the result of the queries structure from  `doc` to `_doc`. 

We don't need to be exhaustive, but we should highlight the biggest incompatibilities since users who may have relied on an old elastic version would likely need to upgrade.

2025-02-26 19:33 UTC, agrawalreetika commented
I think it would be good to call out details on the ES connector document 
@infvg Now I think there will not be backward compatibility with ES 6.0.0? If that the case then the document requirement section would be good to add. https://prestodb.io/docs/current/connector/elasticsearch.html#overview

2025-03-02 12:43 UTC, infvg commented
@ZacBlanco @agrawalreetika 
I've added a warning under the impact. 
The impact of using a 7.x client on a 6.x cluster isn't guaranteed to cause issues - the "doc" -> "_doc" change was due to us updating the test cluster to 7.x which requires "_doc". On IBM's side, the test uses a 6.x cluster so it uses "doc" and passes successfully so that isn't a issue.

2025-03-02 13:22 UTC, agrawalreetika commented
Yeah, as I'm checking, it looks like a document type is required in ES 6.x. In ES 7.x, document types were deprecated, but `_doc` is still allowed for backward compatibility. However, in ES 8.x, document types are completely removed.

2025-03-02 13:22 UTC, agrawalreetika submitted a review, later dismissed

2025-03-05 19:53 UTC, steveburnett commented
Please resolve the file conflict in presto-elasticsearch/pom.xml.

2025-03-06 06:15 UTC, bibith4 approved these changes

2025-03-19 11:59 UTC, pratyakshsharma reviewed
Minor comments, looks good otherwise.

2025-03-19 11:59 UTC, pratyakshsharma commented on pom.xml
> +        <dep.lucene.version>8.11.3</dep.lucene.version>
are we updating to 8.11.3 to be in sync with ES7 or because the original commit updated to it? Else the latest stable version is way ahead of 8.11.3.

2025-03-19 11:59 UTC, pratyakshsharma commented on presto-elasticsearch/pom.xml
> +            <version>4.1.4</version>
Will be better to update this to 4.1.5 to only have vulnerabilities from test dependencies. 4.1.4 has one additional vulnerability from httpclient (compile scope). 
https://mvnrepository.com/artifact/org.apache.httpcomponents/httpasyncclient/4.1.5

2025-03-19 11:59 UTC, pratyakshsharma commented on presto-elasticsearch/pom.xml
> +            <version>1.20.5</version>
Any specific reason for introducing a different dependency version than what is present in root pom?

2025-03-19 11:59 UTC, pratyakshsharma commented on presto-elasticsearch/pom.xml
> +            <version>1.20.5</version>
ditto

2025-03-20 02:15 UTC, infvg commented on presto-elasticsearch/pom.xml
> +            <version>1.20.5</version>
The old testcontainers has bugs when it came to ES7 (new internal indexes were returned as a table when they weren't meant to) which caused test failures.

2025-03-20 02:16 UTC, infvg commented on pom.xml
> +        <dep.lucene.version>8.11.3</dep.lucene.version>
ES7 requires at a minimum 8.11.3

2025-03-20 15:29 UTC, pratyakshsharma commented on presto-elasticsearch/pom.xml
> +            <version>1.20.5</version>
can we update previous ones as well to this version in that case?

2025-03-20 15:30 UTC, pratyakshsharma commented on pom.xml
> +        <dep.lucene.version>8.11.3</dep.lucene.version>
we can consider upgrading it to the latest stable version in that case?

2025-04-03 07:53 UTC, infvg commented on pom.xml
> +        <dep.lucene.version>8.11.3</dep.lucene.version>
Lucene version 9.x requires JDK 11 or above & Lucene 10.x requires JDK 21 or above so we can't upgrade to those versions yet.

2025-04-04 08:26 UTC, infvg commented on presto-elasticsearch/pom.xml
> +            <version>4.1.4</version>
Upgraded

2025-04-07 08:31 UTC, pratyakshsharma commented on pom.xml
> +        <dep.lucene.version>8.11.3</dep.lucene.version>
alright

2025-04-07 17:15 UTC, ZacBlanco approved these changes

2025-04-07 18:26 UTC, agrawalreetika submitted a review, later dismissed

2025-04-10 00:27 UTC, yingsu00 commented on presto-elasticsearch/src/main/java/com/facebook/presto/elasticsearch/client/ElasticSearchClientUtils.java
> +    public static Response performRequest(String method, String endpoint, Map<String, String> params, HttpEntity entity, RestHighLevelClient client, Header... headers)
Add empty line above

2025-04-10 00:27 UTC, yingsu00 commented on presto-elasticsearch/src/main/java/com/facebook/presto/elasticsearch/client/ElasticSearchClientUtils.java
> +    public static Request toRequest(String method, String endpoint, Map<String, String> params, HttpEntity entity, Header... headers)
Add empty line above

2025-04-10 08:07 UTC, yingsu00 approved these changes

2025-04-10 21:36 UTC, merged