Add a config property for excluding java-worker session properties in a native cluster
prestodb/presto pull request #23968
Opened 2024-11-06 23:15 UTC by pdabre12

Resolves: 

```
== RELEASE NOTES ==

General Changes
* ... :pr:`12345`
* ... :pr:`12345`

Hive Connector Changes
* ... :pr:`12345`
* ... :pr:`12345`
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2024-11-07 13:53 UTC, steveburnett requested changes
Thanks for the doc! Nit for tense. Pull branch, local doc build, formatting looks good.

2024-11-07 13:53 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/properties.rst
> +When ``exclude-java-worker-session-properties`` is ``true``, java-worker session properties will
```suggestion
When ``exclude-java-worker-session-properties`` is ``true``, java-worker session properties are 
```

2024-11-07 13:53 UTC, steveburnett commented on presto-docs/src/main/sphinx/admin/properties.rst
> +be excluded from a native cluster.
```suggestion
excluded from a native cluster.
```

2024-11-07 13:55 UTC, steveburnett commented
Thanks for the release note entry! A couple of nits in the formatting: 

```
== RELEASE NOTES ==

General Changes
 Add configuration property ``exclude-java-worker-session-properties``. : pr:`23968`
```

2024-11-07 20:22 UTC, pdabre12 commented
@steveburnett Thank you for the suggestions. Please have another look.

2024-11-07 20:27 UTC, pdabre12 commented
CC: @tdcmeehan @rschlussel

2024-11-07 20:47 UTC, steveburnett approved these changes
LGTM! (docs)

Pull updated branch, reviewed the new local doc build, looks good. Thanks!

2024-11-11 20:59 UTC, rschlussel commented on presto-main/src/main/java/com/facebook/presto/server/ServerMainModule.java
>              mapBinder.addBinding("native-worker").to(NativeWorkerSessionPropertyProvider.class).in(Scopes.SINGLETON);
Do we need the same for native-worker session properties?  Maybe the config could have a generic name to exclude properties that aren't relevant for that worker type.

2024-11-11 20:59 UTC, rschlussel commented on presto-main/src/main/java/com/facebook/presto/sql/analyzer/FeaturesConfig.java
> +    @ConfigDescription("Exclude java-worker session properties")
maybe elaborate a bit more
```suggestion
    @ConfigDescription("Exclude session properties from Java workers when running on native workers")
```

2024-12-03 00:18 UTC, pdabre12 commented
@tdcmeehan @rschlussel Made the changes, now setting the config property should help exclude properties that aren't relevant for that worker type. 
Please have another look. Thanks !

2024-12-03 21:01 UTC, rschlussel commented on presto-native-sidecar-plugin/src/test/java/com/facebook/presto/sidecar/TestNativeSidecarPluginSystemPropertyProvider.java
>      public void testSetJavaWorkerSessionProperty()
need a test that when exclude-invalid-session-properties is false that the session properties are visible. (and make sure we have true and false tests both for java and cpp.

2025-01-31 20:50 UTC, pdabre12 commented on presto-main/src/main/java/com/facebook/presto/server/ServerMainModule.java
> +        if (featuresConfig.isExcludeInvalidWorkerSessionProperties()) {
Thanks for the suggestion, updated.

2025-01-31 20:56 UTC, pdabre12 commented on presto-native-sidecar-plugin/src/test/java/com/facebook/presto/sidecar/TestNativeSidecarPluginSystemPropertyProvider.java
>      public void testSetJavaWorkerSessionProperty()
Test cases added:
1. Native cluster invalid test : https://github.com/prestodb/presto/blob/e36b36e2009f3fa9352588debf05851bd389b861/presto-native-sidecar-plugin/src/test/java/com/facebook/presto/sidecar/TestNativeSidecarPluginSystemPropertyProvider.java#L73
2. Native cluster valid test:
https://github.com/prestodb/presto/blob/e36b36e2009f3fa9352588debf05851bd389b861/presto-native-execution/src/test/java/com/facebook/presto/nativeworker/AbstractTestNativeGeneralQueries.java#L1186

Added files for true and false tests for java clusters.

2025-01-31 21:00 UTC, pdabre12 commented
@rschlussel Can you please have another look? Thanks.

2025-01-31 23:02 UTC, pdabre12 commented on presto-tests/src/test/java/com/facebook/presto/tests/TestSetWorkerSessionPropertiesExcludingInvalidProperties.java
> +public class TestSetWorkerSessionPropertiesExcludingInvalidProperties
Updated, thanks.

2025-02-03 15:00 UTC, steveburnett commented
New release note guidelines as of last week: PR #24354 automatically adds links to this PR to the release notes. Please remove the manual PR link in the following format from the release note entries for this PR. 

```
:pr:`12345`
```

I have updated the [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) to remove the examples of manually adding the PR link.

2025-02-03 17:13 UTC, pdabre12 commented
@steveburnett Thank you, made the change. Can you have another look?

2025-02-03 17:32 UTC, steveburnett commented
> @steveburnett Thank you, made the change. Can you have another look?

LGTM! Thank you!

2025-02-05 19:36 UTC, rschlussel approved these changes

2025-02-05 23:03 UTC, merged