Add javadoc on internal UUID format
prestodb/presto pull request #23961
Opened 2024-11-06 17:22 UTC by ZacBlanco

## Description

Adds a javadoc for presto-native developers to reference the internal format of UUIDs

## Motivation and Context

Helps better specify the format to maintain compatibility

## Impact

N/A

## Test Plan

N/A

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [x] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ... :pr:`12345`
* ... :pr:`12345`

Hive Connector Changes
* ... :pr:`12345`
* ... :pr:`12345`
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2024-11-06 17:26 UTC, ZacBlanco commented
Discussed with @BryanCutler about this. This will be the officially-documented format for now. However, in the future we would like to update our `slice` library to be able to perform comparisons without byte swapping the longs internally. This should improve performance for UUIDs in both java and native. The improvement to the behavior of byte-wise comparisons in slices will likely be done in tandem with the JDK upgrade as it allows us to use some new JDK libraries to do this comparison.

2024-11-06 18:16 UTC, BryanCutler submitted a review, later dismissed
LGTM, thanks!

2024-11-16 22:38 UTC, zation99 approved these changes

2024-11-22 18:45 UTC, steveburnett requested changes
A couple of nits, nothing significant. Thanks for the doc.

2024-11-22 18:45 UTC, steveburnett commented on presto-common/src/main/java/com/facebook/presto/common/type/UuidType.java
> + * library assumes longs used in byte-wise comparisons are stored in
```suggestion
 * library assumes that longs used in byte-wise comparisons are stored in
```

2024-11-22 18:45 UTC, steveburnett commented on presto-common/src/main/java/com/facebook/presto/common/type/UuidType.java
> + * On-disk storage specifications such as parquet or ORC may require different
```suggestion
 * On-disk storage specifications such as Parquet or ORC may require different
```

2024-11-25 17:16 UTC, aditi-pandit submitted a review, later dismissed
Thanks @ZacBlanco

2024-12-03 18:14 UTC, ZacBlanco commented on presto-common/src/main/java/com/facebook/presto/common/type/UuidType.java
> + * On-disk storage specifications such as parquet or ORC may require different
Fixed!

2024-12-03 18:14 UTC, ZacBlanco commented on presto-common/src/main/java/com/facebook/presto/common/type/UuidType.java
> + * library assumes longs used in byte-wise comparisons are stored in
Fixed!

2024-12-04 06:20 UTC, ScrapCodes commented on presto-common/src/main/java/com/facebook/presto/common/type/UuidType.java
> + *
Wrapping in a  `<pre> ... </pre>` block might be better

2024-12-04 06:22 UTC, ScrapCodes commented on presto-common/src/main/java/com/facebook/presto/common/type/UuidType.java
> + *
```suggestion
 * </pre>
```

2024-12-04 06:22 UTC, ScrapCodes commented on presto-common/src/main/java/com/facebook/presto/common/type/UuidType.java
> + *
```suggestion
 * <pre>
```

2024-12-04 06:23 UTC, ScrapCodes approved these changes

2024-12-04 08:02 UTC, hantangwangd approved these changes
Thanks for the Clarification.

2024-12-04 17:14 UTC, tdcmeehan approved these changes

2024-12-04 17:15 UTC, merged