add session properties for prefixsort
prestodb/presto pull request #24043
Opened 2024-11-14 07:55 UTC by zation99

## Description

## Motivation and Context

## Impact

## Test Plan

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ... :pr:`12345`
* ... :pr:`12345`

Hive Connector Changes
* ... :pr:`12345`
* ... :pr:`12345`
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2024-11-14 14:44 UTC, steveburnett requested changes
Thanks for the doc! One formatting nit, looks good.

2024-11-14 14:44 UTC, steveburnett commented on presto-docs/src/main/sphinx/presto_cpp/properties-session.rst
> +Use 0 to disable prefix-sort.
```suggestion
Use ``0`` to disable prefix-sort.
```

2024-11-14 14:47 UTC, steveburnett commented
Suggest adding a release note entry similar to: 

```
== RELEASE NOTES ==

Prestissimo (Native Execution) Changes
* Add session properties ``spill_enable_prefix_sort``, ``prefixsort_normalized_key_max_bytes``, and ``prefixsort_min_rows``. :pr:`24043`
```

2024-11-14 18:35 UTC, xiaoxmeng approved these changes
@zation99 LGTM. Thanks!

2024-11-14 18:35 UTC, xiaoxmeng commented on presto-docs/src/main/sphinx/presto_cpp/properties-session.rst
> +Enable the prefix sort or fallback to timsort in spill.
s/timsort/std::sort/

2024-11-14 18:35 UTC, xiaoxmeng commented on presto-docs/src/main/sphinx/presto_cpp/properties-session.rst
> +The prefix sort is faster than timsort but requires the memory to build prefix data,
ditto

2024-11-14 21:05 UTC, xiaoxmeng approved these changes

2024-11-14 23:40 UTC, NikhilCollooru commented
Please squash all the commits into a single commit.

2024-11-14 23:40 UTC, NikhilCollooru submitted a review, later dismissed

2024-11-15 15:28 UTC, zation99 commented
> Please squash all the commits into a single commit.

Thanks for mentioning it. I'll do "Squash and merge".

2024-11-15 15:31 UTC, zation99 commented
> Thanks for the doc! One formatting nit, looks good.

@steveburnett I've updated the doc. Could you pls help solve the requested change? Thank you!

2024-11-15 15:40 UTC, steveburnett requested changes
Two should-be-final formatting nits.

2024-11-15 15:40 UTC, steveburnett commented on presto-docs/src/main/sphinx/presto_cpp/properties-session.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```suggestion
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Formatting lines should be the same number of characters as the line being formatted.

2024-11-15 15:40 UTC, steveburnett commented on presto-docs/src/main/sphinx/presto_cpp/properties-session.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```suggestion
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

2024-11-15 17:13 UTC, steveburnett approved these changes
LGTM! (docs)

Pull updated branch, new local doc build, checked build warnings, looks good. Thanks!

2024-11-15 18:06 UTC, xiaoxmeng approved these changes

2024-11-15 18:49 UTC, NikhilCollooru approved these changes

2024-11-15 18:51 UTC, merged