Pluggable JWT Authenticators
prestodb/presto pull request #24053
Opened 2024-11-15 11:02 UTC by imsayari404

## Description

A pluggable authenticator in Presto allows the authentication process to be customized based on specific use cases, such as integrating with different identity providers or token validation strategies. 

## Motivation and Context

Fixes #24052 

## Test Plan

Added Unit Tests

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

Security Changes
* Add support for pluggable JWT Authenticators :pr:`12345`

```

2024-11-15 20:37 UTC, imjalpreet reviewed
For history, a partial review was done here: https://github.com/imsayari404/presto/pull/1

2024-11-18 06:30 UTC, imjalpreet commented on presto-main/src/main/java/com/facebook/presto/server/security/ServerSecurityModule.java
Please add a binding to JWTAuthenticatorManager in the setup method

2024-11-18 10:29 UTC, imjalpreet commented on presto-main/pom.xml
> -        <dependency>
Could you please confirm if we can eliminate this dependency? The error may be caused by removing it.

2024-11-18 17:28 UTC, majetideepak commented
CC: @czentgr

2024-11-18 21:01 UTC, czentgr reviewed
I suppose we should also add documentation on how to use it. The options for the config were already around but never documented.
Now that there is a new config file we should add how a user would use the plugin and what the default plugin provides and how to configure it?

2024-11-18 22:24 UTC, imjalpreet commented
> I suppose we should also add documentation on how to use it. The options for the config were already around but never documented.
Now that there is a new config file we should add how a user would use the plugin and what the default plugin provides and how to configure it?

@czentgr We are finalizing some minor adjustments to the current design in the linked issue (#24052), and this PR will also include the documentation changes.

2024-11-20 11:06 UTC, imjalpreet requested changes
@imsayari404 @namya28 As discussed offline, we will proceed with the following adjustments to the current implementation:

- **Introduce a Generic Authenticator SPI:**
    - Create PrestoAuthenticator and PrestoAuthenticatorFactory to unify the existing PasswordAuthenticator and JwtAuthenticator SPIs.
    - The new SPI will define a common method:
       ```
       Principal createAuthenticatedPrincipal(Map<String, String> credentials, HttpServletRequest request);
       ```
     - This will establish a consistent interface for all authentication mechanisms.
- **Introduce a Generic Authenticator Manager in presto-main:**
    - Implement a unified PrestoAuthenticatorManager to consolidate the functionality of JwtAuthenticatorManager and PasswordAuthenticatorManager.
- **Refactor Existing Authenticators in presto-main:**
    - Update the JsonWebTokenAuthenticator and PasswordAuthenticator classes to align with the new generic Authenticator SPI and Authenticator Manager.
- **Update Custom Implementations:**
    - Refactor all custom authenticators to conform to the new generic SPI structure.

2025-01-15 15:57 UTC, closed without merging