Add lookup function API to StandardFunctionResolution
prestodb/presto pull request #24105
Opened 2024-11-20 21:29 UTC by feilong-liu

## Description
FunctionAndTypeResolver is in presto-main, and for code which has no access to presto-main, it relies on the interface StandardFunctionResolution in SPI to get function handle. 
In this PR, I add a API lookUpFunction so that it can work with internal functions which does not exist in OSS

## Motivation and Context
I need to create function call in connector optimizer, which has no access to presto-main. This change will enable resolve internal functions not exist in OSS

## Impact
As above

## Test Plan
Easy change. Existing tests

## Contributor checklist

- [ ] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2024-11-20 21:42 UTC, tdcmeehan requested changes
Please add a simple test in `TestFunctionResolution`.

2024-11-20 21:42 UTC, tdcmeehan commented on presto-main/src/main/java/com/facebook/presto/sql/relational/FunctionResolution.java
> +    public FunctionHandle lookUpFunction(String functionName, List<Type> inputTypes)
Let's call this `lookupBuiltInFunction` to make clear this does not support session functions or functions supplied by a function namespace manager.

2024-11-20 23:04 UTC, feilong-liu commented
> Please add a simple test in `TestFunctionResolution`.

Added test

2024-11-20 23:14 UTC, feilong-liu commented on presto-main/src/test/java/com/facebook/presto/sql/relational/TestFunctionResolution.java
> +        assertEquals(standardFunctionResolution.countFunction(), standardFunctionResolution.lookupBuiltInFunction("count", ImmutableList.of()));
Add test

2024-11-21 13:46 UTC, tdcmeehan commented
> I need to create function call in connector optimizer, which has no access to presto-main. This change will enable resolve internal functions not exist in OSS

Do you mean, you need to both resolve and evaluate a function call?  Why not use the `ExpressionOptimizer#optimize` method, with `level` set to `EVALUATED`?

2024-11-21 17:30 UTC, feilong-liu commented
> > I need to create function call in connector optimizer, which has no access to presto-main. This change will enable resolve internal functions not exist in OSS
> 
> Do you mean, you need to both resolve and evaluate a function call? Why not use the `ExpressionOptimizer#optimize` method, with `level` set to `EVALUATED`?

I mean I need to construct a new CallExpression calling an internal function, like 
```
new CallExpression(..., functionhandle, ...)
```

2024-11-21 17:38 UTC, merged