[native] TopNRank optimization
prestodb/presto pull request #24138
Opened 2024-11-25 10:54 UTC by aditi-pandit

## Description
https://docs.google.com/document/d/1WQfNigR9bVrbM-PqY7F0mswcetN_tdNahzD9ENye-Q0/edit?tab=t.0

## Motivation and Context
TPC-DS Q67

```
== RELEASE NOTES ==

General Changes
* ... :pr:`12345`
* ... :pr:`12345`

Hive Connector Changes
* ... :pr:`12345`
* ... :pr:`12345`
```

2024-12-11 17:53 UTC, BryanCutler reviewed
LGTM just a couple questions

2024-12-11 17:53 UTC, BryanCutler commented on presto-native-execution/src/test/java/com/facebook/presto/nativeworker/PrestoNativeQueryRunnerUtils.java
> +                                "native-execution-enabled=true" +
does this need a `%n`? I'm guessing that's to give it a newline but not sure

2025-01-09 15:37 UTC, steveburnett commented
Thank you for the release note! Some nits of phrasing and formatting suggestions. 

```
== RELEASE NOTES ==

Prestissimo (Native Execution) Changes
* Improve Window filter pushdown in Prestissimo engine for ``rank`` and ``dense_rank`` functions. :pr:`24138`
```

2025-03-25 19:45 UTC, steveburnett commented
One more nit about the release note entry: we've automated the link to the PR so you don't have to add it manually anymore. 

```
== RELEASE NOTES ==

Prestissimo (Native Execution) Changes
* Improve Window filter pushdown in Prestissimo engine for ``rank`` and ``dense_rank`` functions. 
```

2025-11-07 04:01 UTC, hantangwangd reviewed
@aditi-pandit thanks for this change, the design doc looks great. I have a question: does this change not include the logic to convert the suitable window node with `rank` and `dense_rank` functions into `TopNRowNumberNode`?

2025-11-07 04:30 UTC, aditi-pandit commented
@hantangwangd : Thanks for looking at this PR. All my Velox changes for TopNRowNumber finally got submit last week and I was updating this draft to do the Presto optimizer pieces.

This code change just adds the plumbing for the ranking function. I have to add the optimizer rules. Was going to in the next commit.

Though I'm open to just submitting this first plumbing piece by itself if you feel we should.

wdyt ?

2025-11-07 06:43 UTC, hantangwangd commented
@aditi-pandit thanks for the clarifaction, and it's great to hear about the progress on Velox. Given that you have now changed this PR to draft, I suggest including the change of optimizer pieces as well. It will give us the full context needed to look into both parts together. Does this sound reasonable to you?

2025-11-12 15:31 UTC, steveburnett commented
Thanks for the revised release note! Two things, the first is only a nit.

1. The PR link ( :pr:`24138` ) is now automatically added and we don't have to manually include it anymore. 

2. I don't find `optimizer.optimize-top-n-rank` in the Presto documentation. Could doc be added for it?

2025-11-13 04:04 UTC, aditi-pandit commented
> Thanks for the revised release note! Two things, the first is only a nit.
> 
> 1. The PR link ( :pr:`24138` ) is now automatically added and we don't have to manually include it anymore.
> 2. I don't find `optimizer.optimize-top-n-rank` in the Presto documentation. Could doc be added for it?

@steveburnett : Thanks for your review. Yes, we should add documentation for optimizer.optimize-top-n-rank. 

Though its an interesting one as its applicable only for native engine. So I was undecided if I should document it with th native engine session properties [here](https://prestodb.io/docs/current/presto_cpp/properties-session.html) or the optimizer ones which are usually applicable to both engines. I'm more inclined to add it with the native engine config. what is your suggestion ?

2025-11-13 14:56 UTC, steveburnett commented
> @steveburnett : Thanks for your review. Yes, we should add documentation for optimizer.optimize-top-n-rank.
> 
> Though its an interesting one as its applicable only for native engine. So I was undecided if I should document it with th native engine session properties [here](https://prestodb.io/docs/current/presto_cpp/properties-session.html) or the optimizer ones which are usually applicable to both engines. I'm more inclined to add it with the native engine config. what is your suggestion ?

I agree with you that _I'm more inclined to add it with the native engine config_, and I think the best thing would be to add doc for it to https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/presto_cpp/properties-session.rst.

2025-11-14 00:17 UTC, aditi-pandit commented
> I agree with you that _I'm more inclined to add it with the native engine config_, and I think the best thing would be to add doc for it to https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/presto_cpp/properties-session.rst.

@steveburnett : Added documentation. Please review.

2025-11-14 14:53 UTC, steveburnett requested changes
Thank you for the documentation! Just a couple of nits of formatting.

2025-11-14 14:53 UTC, steveburnett commented on presto-docs/src/main/sphinx/presto_cpp/properties-session.rst
> +If this is true, then filter and limit queries for 'n' rows of
```suggestion
If this is true, then filter and limit queries for ``n`` rows of
```

2025-11-14 14:53 UTC, steveburnett commented on presto-docs/src/main/sphinx/presto_cpp/properties-session.rst
> +rank() and dense_rank() window function values are executed
```suggestion
``rank()`` and ``dense_rank()`` window function values are executed
```

2025-11-17 09:41 UTC, hantangwangd reviewed
@aditi-pandit thanks for adding the optimizer part. I've left some initial comments for discussion.

2025-11-17 09:41 UTC, hantangwangd commented on presto-main-base/src/main/java/com/facebook/presto/sql/planner/optimizations/WindowFilterPushDown.java
> +            return isRankMetadata(functionAndTypeManager, functionAndTypeManager.getFunctionMetadata(node.getWindowFunctions().get(rowNumberVariable).getFunctionHandle()));
```suggestion
            return isRankMetadata(functionAndTypeManager, functionAndTypeManager.getFunctionMetadata(getOnlyElement(node.getWindowFunctions().values()).getFunctionHandle()));
```

nit: it seems unnecessary to fetch the key first and then use it to get the value.

2025-11-17 09:41 UTC, hantangwangd commented on presto-main-base/src/main/java/com/facebook/presto/sql/planner/optimizations/WindowFilterPushDown.java
> +                    TopNRowNumberNode topNRowNumberNode = convertToTopNRowNumber(windowNode, limit);
```suggestion
                    TopNRowNumberNode topNRowNumberNode = convertToTopNRank(windowNode, limit);
```

Should we call `convertToTopNRank` here?

2025-11-17 09:41 UTC, hantangwangd commented on presto-main-base/src/main/java/com/facebook/presto/sql/planner/optimizations/WindowFilterPushDown.java
> +                if (canReplaceWithTopNRowNumber(windowNode)) {
As I understand, `rank` and `dense_rank` cannot use this optimization because the upper bound of their `row number` cannot be simply treated as a `limit`. Is my understanding correct? PLMK if there are any errors.

2025-11-17 09:41 UTC, hantangwangd commented on presto-main-base/src/main/java/com/facebook/presto/sql/planner/optimizations/WindowFilterPushDown.java
> +                        source = convertToTopNRowNumber(windowNode, upperBound.getAsInt());
nit: It seems that we can call `convertToTopNRank` here as well. And completely drop the method `convertToTopNRowNumber`?

2025-11-17 09:41 UTC, hantangwangd commented on presto-main-base/src/main/java/com/facebook/presto/sql/planner/optimizations/WindowFilterPushDown.java
> +                    }
Could we simply remove the `LimitNode` for `rank` and `dense_rank` here? I'm not familiar with the actual implementation of `TopNRowNumber` for `rank` and `dense_rank` in Velox. But as I understand from the design doc, it's possible that they could return more rows than the specified limit. Is my understanding correct? PLMK if there are any errors.

2025-11-17 13:18 UTC, aaneja commented on presto-main-base/src/main/java/com/facebook/presto/sql/planner/optimizations/WindowFilterPushDown.java
> +                    }
+1, I think we should only return directly if the RankingFunction is `ROW_NUMBER`

2025-11-17 13:32 UTC, aaneja commented on presto-main-base/src/test/java/com/facebook/presto/sql/planner/optimizations/TestWindowFilterPushDown.java
> +                rowNumber ? optimizeTopNRowNumber(true) : optimizeTopNRank(true),
Can we also assert on the Ranking function for the TopNRowNumberNode

2025-11-17 15:22 UTC, steveburnett requested changes
Thanks for the update! Just one nit of formatting, everything else looks good.

2025-11-17 15:22 UTC, steveburnett commented on presto-docs/src/main/sphinx/presto_cpp/properties-session.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```suggestion
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

2025-11-22 00:17 UTC, aditi-pandit commented on presto-docs/src/main/sphinx/presto_cpp/properties-session.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Done.

2025-11-22 00:42 UTC, aditi-pandit commented on presto-main-base/src/main/java/com/facebook/presto/sql/planner/optimizations/WindowFilterPushDown.java
> +                    }
My bad. Yes, this is only applicable for row_number()

2025-11-22 00:43 UTC, aditi-pandit commented on presto-main-base/src/main/java/com/facebook/presto/sql/planner/optimizations/WindowFilterPushDown.java
> +                    TopNRowNumberNode topNRowNumberNode = convertToTopNRowNumber(windowNode, limit);
This was a good catch... I intended to remove the original convertToTopNRowNumber and change convertToTopNRank function to convertToTopNRowNumber to match the naming everywhere.

Have fixed that.

2025-11-22 00:47 UTC, aditi-pandit commented on presto-main-base/src/main/java/com/facebook/presto/sql/planner/optimizations/WindowFilterPushDown.java
> +            return isRankMetadata(functionAndTypeManager, functionAndTypeManager.getFunctionMetadata(node.getWindowFunctions().get(rowNumberVariable).getFunctionHandle()));
Had copied this from canOptimizeRowNumberFunction logic. Have modified this code as well as the above function.

2025-11-22 00:53 UTC, aditi-pandit commented on presto-main-base/src/main/java/com/facebook/presto/sql/planner/optimizations/WindowFilterPushDown.java
> +                        source = convertToTopNRowNumber(windowNode, upperBound.getAsInt());
Same comment as above.

2025-11-22 00:58 UTC, aditi-pandit commented on presto-main-base/src/test/java/com/facebook/presto/sql/planner/optimizations/TestWindowFilterPushDown.java
> +                rowNumber ? optimizeTopNRowNumber(true) : optimizeTopNRank(true),
@aaneja : That's a good idea. Though do you have any suggestions on how to cleanly do so ? An option could be to enhance the matcher classes. wdyt ?

2025-11-22 01:53 UTC, aditi-pandit commented
@hantangwangd @aaneja : Thanks for your review comments. Have addressed them. PTAL.

2025-11-24 01:59 UTC, hantangwangd reviewed
Hi @aditi-pandit, thanks for the fixes. I'm seeing some test failures that appear to be related.

2025-11-24 09:54 UTC, aditi-pandit commented
> Hi @aditi-pandit, thanks for the fixes. I'm seeing some test failures that appear to be related.

@hantangwangd : Thanks for pointing out. I had to disable the plan checks for Spark on Native as the session property is not set in those tests.

2025-11-25 08:04 UTC, hantangwangd reviewed
Thanks for the fix, lgtm! Just one little nit.

2025-11-25 08:04 UTC, hantangwangd commented on presto-main-base/src/main/java/com/facebook/presto/sql/planner/optimizations/WindowFilterPushDown.java
> +                    planChanged = true;
nit: should we move this line above the `if` clause?

2025-12-01 15:47 UTC, steveburnett submitted a review, later dismissed
LGTM! (docs)

Pull updated branch, new local doc build. Looks good, thanks!

2026-01-21 09:23 UTC, psantos-denodo commented
Hi! it looks this is ready to merge, just missing one failing check, is that right? if that's the case could you re-run it? it looks this feature can make a significant improvement and it would be great to merge it soon :)

2026-01-21 18:08 UTC, kaikalur commented
Hmm - looks like we already have: optimize_top_n_row_number that does it in the plan? What is this for?

2026-01-21 22:20 UTC, aditi-pandit commented
> Hi! it looks this is ready to merge, just missing one failing check, is that right? if that's the case could you re-run it? it looks this feature can make a significant improvement and it would be great to merge it soon :)

Hi @psantos-denodo : I have one failure to debug and will prioritize submitting this change.

2026-01-21 22:22 UTC, aditi-pandit commented
> Hmm - looks like we already have: optimize_top_n_row_number that does it in the plan? What is this for?

@kaikalur : optimize_top_n_row_number was only for queries with row_number. This PR added support for rank and dense_rank window functions pushdown in that same operator. This had Velox runtime code changes as well. The Velox team wanted to disable the optimization by default (optimize_top_n_row_number is true) and so I added a new config for it.

2026-01-23 20:46 UTC, aditi-pandit commented on presto-main-base/src/main/java/com/facebook/presto/sql/planner/optimizations/WindowFilterPushDown.java
> +                    planChanged = true;
Yes fixed that.

2026-01-25 14:24 UTC, hantangwangd reviewed
Thanks @aditi-pandit, a couple of little nits.

2026-01-25 14:24 UTC, hantangwangd commented on presto-docs/src/main/sphinx/presto_cpp/properties-session.rst
> +>>>>>>> e161ed7dab (feat(optimizer): Add WindowFilterPushdown rule changes for rank queries)
nit: drop this line.

2026-01-25 14:24 UTC, hantangwangd commented on presto-main-base/src/main/java/com/facebook/presto/sql/planner/optimizations/WindowFilterPushDown.java
> +                    planChanged = true;
```suggestion
                    planChanged = true;
                    // Limit can be entirely skipped for row_number without partitioning.
                    if (windowNode.getPartitionBy().isEmpty() &&
                            canOptimizeRowNumberFunction(windowNode, metadata.getFunctionAndTypeManager())) {
                        return topNRowNumberNode;
                    }
```

nit: let's move `planChanged = true` before the if-check. The plan has been optimized at this point, so we need to preserve this state change even if the condition is true.

2026-02-02 00:02 UTC, aditi-pandit commented
Submit only after https://github.com/facebookincubator/velox/pull/16190/ is updated in Velox submodule.

2026-02-02 00:02 UTC, aditi-pandit commented on presto-main-base/src/main/java/com/facebook/presto/sql/planner/optimizations/WindowFilterPushDown.java
> +                    planChanged = true;
Done.

2026-02-02 00:02 UTC, aditi-pandit commented on presto-docs/src/main/sphinx/presto_cpp/properties-session.rst
> +>>>>>>> e161ed7dab (feat(optimizer): Add WindowFilterPushdown rule changes for rank queries)
Done.

2026-02-02 00:03 UTC, aditi-pandit commented
> > Hi! it looks this is ready to merge, just missing one failing check, is that right? if that's the case could you re-run it? it looks this feature can make a significant improvement and it would be great to merge it soon :)
> 
> Hi @psantos-denodo : I have one failure to debug and will prioritize submitting this change.

Hi @psantos-denodo : I have debugged the failure and have the fix in https://github.com/facebookincubator/velox/pull/16190. We can submit this PR after that one is merged in Velox and the module updated.

2026-02-02 09:16 UTC, psantos-denodo commented
> > > Hi! it looks this is ready to merge, just missing one failing check, is that right? if that's the case could you re-run it? it looks this feature can make a significant improvement and it would be great to merge it soon :)
> > 
> > 
> > Hi @psantos-denodo : I have one failure to debug and will prioritize submitting this change.
> 
> Hi @psantos-denodo : I have debugged the failure and have the fix in [facebookincubator/velox#16190](https://github.com/facebookincubator/velox/pull/16190). We can submit this PR after that one is merged in Velox and the module updated.

That's great news, thanks for sharing!

2026-02-11 21:41 UTC, aditi-pandit commented
@hantangwangd @aaneja @tdcmeehan : This PR is finally clean.

Would be great to have a round of review.

Really appreciate the help.

2026-02-11 21:46 UTC, steveburnett approved these changes
LGTM! (docs)

2026-02-12 00:23 UTC, hantangwangd approved these changes
Thanks @aditi-pandit, lgtm!

2026-02-12 00:50 UTC, merged

2026-02-12 00:51 UTC, aditi-pandit commented
Thanks @hantangwangd for all the detailed reviews.

2026-06-02 09:26 UTC, psantos-denodo commented
Hi @aditi-pandit , can you clarify if this feature affects to native only or Java version as well?
I see changes in the planner and analyzer so I assumed it affects both but I see the property to enable it is only documented in the Presto C++ section so my understanding is that the new operator TopNRowNumber  only exists on the Presto C++ version. can you confirm?
In addition, wouldn't make sense to enable it using a config property instead of a session property?

2026-06-02 20:18 UTC, aditi-pandit commented
Hi @psantos-denodo : This optimization is only applicable for PrestoC++ as the runtime code is only available for it.

We didn't document the config, but it can be used as both.

2026-06-02 20:35 UTC, steveburnett commented
> We didn't document the config, but it can be used as both.

Hi @aditi-pandit! I opened #27915 to document the config property. If there's a reason we should not document the config property, please comment there and we can close it if needed.

2026-06-02 21:04 UTC, aditi-pandit commented
> > We didn't document the config, but it can be used as both.
> 
> Hi @aditi-pandit! I opened #27915 to document the config property. If there's a reason we should not document the config property, please comment there and we can close it if needed.

Thanks @steveburnett for the follow up.

2026-06-03 08:28 UTC, psantos-denodo commented
> Hi @psantos-denodo : This optimization is only applicable for PrestoC++ as the runtime code is only available for it.
> 
> We didn't document the config, but it can be used as both.

Hi @aditi-pandit , thanks for clarifying