presto-ui forwardfit
prestodb/presto pull request #24167
Opened 2024-11-28 08:00 UTC by sh-shamsan

## Description

## Motivation and Context

## Impact

## Test Plan

## Contributor checklist

- [ ] Please make sure your submission complies with our [contributing guide](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md), in particular [code style](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#code-style) and [commit standards](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#commit-standards).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ... :pr:`12345`
* ... :pr:`12345`

Hive Connector Changes
* ... :pr:`12345`
* ... :pr:`12345`
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2025-01-21 15:39 UTC, steveburnett approved these changes
LGTM! (docs)

Pull branch, local doc build, doc looks good. Thanks!

2025-01-30 17:04 UTC, ethanyzhang commented
@unidevel Could you help review this?

2025-02-04 18:06 UTC, yhwang approved these changes
Appreciate the efforts for the upgrade and some cleanups

2 minor comments only.

2025-02-04 18:54 UTC, steveburnett commented
New release note guidelines. Please remove the manual PR link in the following format from the release note entries for this PR.

```

:pr:`12345`

```

I have updated the [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) to remove the examples of manually adding the PR link.

Also, suggest rephrase the third release note entry from 

```
Switch from dagre-d3 to dagre-d3-es cuz it's deprecated and in response to a high severity WS-2022-0322
```

to 

```
Replace depreciated ``dagre-d3`` with ``dagre-d3-es`` in response to a high severity vulnerability [WS-2022-0322](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2482). 
```

**Note:** I found the link searching for `WS-2022-0322`. If the link is not the correct link, please correct it.

2025-02-04 21:06 UTC, unidevel commented on presto-ui/src/components/LivePlan.jsx
>                   title={"<h4>" + this.props.name + "</h4>" + this.props.identifier}>
Seems the html tag will be displayed in the tooltip. 

![image](https://github.com/user-attachments/assets/c9f87dd3-c203-48d3-a79b-a3b98a77b982)

2025-02-04 21:42 UTC, unidevel commented
The query items is not well aligned and spaced:

Current:
![image](https://github.com/user-attachments/assets/eba56029-850f-4d7f-9c9c-9b61d081f46c)

Issues (From top to bottom)
1. The height of black background is smaller than the left one. Previously they are same height.
2. There is margin on the right of the time in previous version.
3. The height of gray background for SQL area is smaller than the left area. Previously they are same height.


Previous(0.290): 
![image](https://github.com/user-attachments/assets/15936af1-97ee-4367-92e5-20eb86bb075a)

2025-02-04 21:55 UTC, unidevel commented
In the Query details, at bottom of the page, there is the `Show: All` dropdown, seems the dropdown style is lost.

![image](https://github.com/user-attachments/assets/2cb7b36e-d24c-4d82-9712-75c31f2b9b9a)

2025-02-05 13:19 UTC, unidevel commented
Header misaligned
Current:
![image](https://github.com/user-attachments/assets/21468792-49de-474d-a9df-45d615aa9d3d)

Previous:
![image](https://github.com/user-attachments/assets/9e56b0a6-5ebe-45e5-8606-f5531936e6a3)
i8-[]w34

2025-02-05 13:23 UTC, unidevel commented
Extra space on the right

Current: (consider making the input box a little wider)
![image](https://github.com/user-attachments/assets/2b5dd1ec-9a8c-4e38-9c07-fb6d30969952)

Previous:
![image](https://github.com/user-attachments/assets/64cdfac6-3ec8-425f-9549-3e7aab6af6d4)

2025-02-05 13:30 UTC, unidevel commented
Margin missing

Current:
![image](https://github.com/user-attachments/assets/de6af820-e940-409d-b4a5-861c39bee690)


Previous:
![image](https://github.com/user-attachments/assets/20090aa1-335c-4749-a69d-74ce4a2f7cd5)

2025-02-05 13:36 UTC, unidevel commented
Hint alignment:

Current:
![image](https://github.com/user-attachments/assets/eb5804c7-effc-4cee-977b-50da3c792dbe)

Previous:
![image](https://github.com/user-attachments/assets/9a5fb930-ca56-4e1c-b5ac-c3185d59f038)

2025-02-05 13:39 UTC, unidevel commented
Diagram text alignment:

Current (left):
![image](https://github.com/user-attachments/assets/a06f2257-3655-4da5-8688-b36e2c99813b)

Previous (middle):
![image](https://github.com/user-attachments/assets/a1a9b40e-6e33-4a6e-8235-224a77000abf)

2025-02-05 14:05 UTC, unidevel commented
In consistent dropdown styles (current implementation only), different button color and background color :

![image](https://github.com/user-attachments/assets/4db8402d-8a85-4cef-becc-d9fdaab8dc91)

![image](https://github.com/user-attachments/assets/594f55b4-0d17-451a-bb9c-d04c9b6d027f)

![image](https://github.com/user-attachments/assets/5fa74084-c481-4e40-b82e-ba281f243df1)

2025-02-05 14:11 UTC, unidevel requested changes
@sh-shamsan I put all the issues I noticed as comments, please review and fix when necessary, thanks.

2025-02-06 19:26 UTC, sh-shamsan commented
Fixed the following: 

* Alignment for the rows and submission time
<img width="1213" alt="Querylist rows" src="https://github.com/user-attachments/assets/b7432561-62d5-4929-9700-96e17a541eef" />


* Alignment, longer search bar, and the space after the "show" button
<img width="1224" alt="Screenshot 2025-02-06 at 10 16 48 PM" src="https://github.com/user-attachments/assets/d5e1984b-301a-4092-bf27-398dcf9b9119" />

* alignment for env info and the nav bar
<img width="1224" alt="Screenshot 2025-02-06 at 9 14 10 PM" src="https://github.com/user-attachments/assets/46086cb1-fd52-487b-a9a8-2bce84483f60" />

@unidevel

2025-02-07 20:27 UTC, sh-shamsan commented on presto-ui/src/components/QueryHeader.jsx
>          const queryId = this.props.query.queryId;
applied

2025-02-07 20:27 UTC, sh-shamsan commented on presto-ui/src/components/PageTitle.jsx
>                  //$FlowFixMe$ Bootstrap 3 plugin
applied

2025-02-07 21:26 UTC, steveburnett submitted a review, later dismissed
LGTM! (docs)

Pull updated branch, new local doc build.

2025-02-07 23:39 UTC, sh-shamsan commented
Fixed some more:

* Dropdown styling in Query details 
<img width="321" alt="Screenshot 2025-02-08 at 2 17 21 AM" src="https://github.com/user-attachments/assets/fd3ca3ef-352a-4068-9a7a-76fedc16873f" />

* Alignment for the message in LivePlan "scroll to zoom.."
<img width="1114" alt="Screenshot 2025-02-08 at 1 25 04 AM" src="https://github.com/user-attachments/assets/c0ead264-92e8-4278-a6b0-9d4996fec0a5" />

@unidevel

2025-02-08 09:32 UTC, unidevel commented
Thanks @sh-shamsan, the UI looks much better now.

2025-02-08 09:32 UTC, unidevel submitted a review, later dismissed

2025-02-10 17:51 UTC, yhwang approved these changes

2025-02-10 21:45 UTC, steveburnett approved these changes
LGTM! (docs)

Pull branch, local doc build, doc looks good. Thanks!

2025-02-10 22:46 UTC, yingsu00 reviewed
@sh-shamsan The EasyCLA is failing. Can you please sign it? 
Also, there are some items I didn't see you marked fixed. Can you please confirm everything is fixed?

2025-02-10 22:48 UTC, yingsu00 reviewed
The last two commits failed EasyCLA. Maybe @yhwang need to sign it?

2025-02-10 22:54 UTC, yingsu00 reviewed
Commit "[Upgrade bootstrap and jquery for single page app](https://github.com/prestodb/presto/pull/24167/commits/0ecea195ee2e5cc5cff35cfe05b2e65879a9e325)" has a UI test failure https://github.com/prestodb/presto/actions/runs/13209836310/job/36881104233. Can you please fix it? Every commit needs to pass all tests. Thanks!

2025-02-10 22:59 UTC, yhwang commented
@yingsu00 I have CLA. the CLA failing is from other emails. But I think we can skip that. And for the flow error. @unidevel fixed it in this commit: https://github.com/prestodb/presto/pull/24167/commits/6c370d862b1c9b8fdbe49956473198e14099a05b

2025-02-10 23:05 UTC, yingsu00 commented
> 6c370d8

It cannot be a separate commit. EVERY commit in the PR needs to pass ALL tests. It needs to be squashed with the failing commit.

2025-02-10 23:08 UTC, yingsu00 commented
@sh-shamsan Can you please mark if the changes were fixed on @unidevel's original comments? Like the first a few ones, can you please cross out the lines if it's fixed? Thanks!

2025-02-11 17:53 UTC, ethanyzhang commented
@rschlussel Can you share some guidance on the CLA part - the main authors are all signed but we there were some old commits we cherry-picked from our internal fork and we added coauthors. Those may not have CLA signed. Do we need to spend time to chase all of them?

2025-02-11 21:55 UTC, rschlussel commented
I can't merge it without the cla check passing.

2025-02-11 21:56 UTC, ethanyzhang commented
We are rebasing to fix

2025-02-12 00:28 UTC, yhwang commented
@rschlussel everything passed finally!

2025-02-12 00:55 UTC, yingsu00 approved these changes

2025-02-12 00:55 UTC, merged