Update lucene-core, lucene-analyzers-common, and lucene-queryparser version to 8.10.0
prestodb/presto pull request #24168
Opened 2024-11-28 10:47 UTC by imsayari404

## Description

3 medium CVE resolved. 

**Upgradation performed :**

1. lucene-core(https://www.mend.io/vulnerability-database/WS-2021-0646) : 8.2.0 to 8.10.0
2. lucene-analyzer-common(https://www.mend.io/vulnerability-database/WS-2021-0646) : 7.7.3 to 8.10.0
3. lucene-queryparser(https://vuln.whitesourcesoftware.com/vulnerability/WS-2021-0646) : 8.2.0 to 8.10.0
## Motivation and Context

Apache Lucene through 7.x and 8.x before 8.10 is vulnerable to a denial of service. By sending a specific regular expression query, a remote attacker could exploit this vulnerability to consume all available CPU resources.

## Impact
3 medium cve got resolved.

## Test Plan

In progress

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

Security Changes
* Upgrade lucene-core to 8.10.0  :pr:`#24143`
* Upgrade lucene-queryparser to 8.10.0  :pr:`#24143`
* Upgrade lucene-analyzer-common to 8.10.0  :pr:`#24143`

```

2024-12-03 19:24 UTC, ZacBlanco requested changes
I have a concern that we are just adding an exclusion here for all of the duplicate checkers. We should prevent the duplicate dependency from existing on the classpath in the first place. I would try to modify the strategy for this PR to prevent the duplicated class patterns rather than just adding it to the ignore list everywhere.

2024-12-03 19:24 UTC, ZacBlanco commented on pom.xml
> +<!--            </dependency>-->
please remove these comments

2024-12-03 19:24 UTC, ZacBlanco commented on pom.xml
> +<!--            </dependency>-->
please remove these commented lines

2024-12-03 19:24 UTC, ZacBlanco commented on pom.xml
> +<!--                            <ignoredClassPattern>META-INF.versions.9.org.apache.lucene.util.*</ignoredClassPattern>-->
remove please

2024-12-03 19:24 UTC, ZacBlanco commented on presto-pinot-toolkit/pom.xml
> +            <version>8.10.0</version>
you shouldn't need the `<version>` tag in here if the `luecene-core` dependency is defined in the root pom's `dependencyManagement` section. I would recommend adding it to the root pom's `dependencyManagement` section with the `dep.lucene.version` variable there and remove the `<version>` tag here.

2024-12-05 20:22 UTC, ZacBlanco requested changes

2024-12-05 20:22 UTC, ZacBlanco commented on presto-pinot-toolkit/pom.xml
> +                                </ignoredUnusedDeclaredDependencies>
I found this change didn't seem to be necessary to build `presto-pinot-toolkit` without errors.

```
 ./mvnw clean install -pl presto-pinot-toolkit -am -DskipUI -DskipTests
```

2024-12-06 23:48 UTC, ZacBlanco commented on presto-hive/pom.xml
> +                    </ignoredUnusedDeclaredDependencies>
I also found this seems to be not needed? When I checked out the branch and built the entire repository with these lines removed, it worked fine.

2024-12-07 00:01 UTC, ZacBlanco commented on pom.xml
> +                            <ignoredClassPattern>META-INF.versions.9.org.apache.lucene.*</ignoredClassPattern>
After some further research, I think it would be better to keep this ignored. You can ignore this suggestion

2024-12-09 16:42 UTC, ZacBlanco commented
Last question - 8.10 is actually still a pretty old Lucene version. It was published on [Oct 18, 2021](https://mvnrepository.com/artifact/org.apache.lucene/lucene-core/8.10.1). Have we considered moving to a release later than 8.10?

2024-12-09 18:01 UTC, ZacBlanco commented
After offline discussion, versions >= 9.0 seem to require Java 11, so we will stick with 8.10 for now.

2024-12-09 18:49 UTC, ZacBlanco submitted a review, later dismissed

2024-12-10 09:16 UTC, infvg approved these changes
LGTM

2024-12-13 21:18 UTC, ZacBlanco commented
@tdcmeehan can you help merge this?

2024-12-16 07:48 UTC, pratyakshsharma requested changes
Thank you for the fix @imsayari404. Only one comment. Also please update the commit message to start with `Update` to follow imperative tone - https://cbea.ms/git-commit/#imperative

2024-12-16 07:48 UTC, pratyakshsharma commented on pom.xml
> +                <exclusions>
this exclusion is probably not needed. I tried building without this and the build went fine.

2024-12-16 15:56 UTC, tdcmeehan approved these changes

2024-12-16 15:57 UTC, merged