[native] Update docs for VARCHAR type length value
prestodb/presto pull request #24173
Opened 2024-11-29 23:08 UTC by czentgr

The documentation does not clearly indicate what the length value in the varchar type definition means. Clear up that it is the number of characters and not the number of bytes.

## Description

## Motivation and Context
The documentation is somewhat unclear as to the meaning of the numeric value used for varchar. It is clear when it is used in the CHAR type context. This leaves it up for interpretation: number of characters vs number of bytes.

## Impact

## Test Plan

## Contributor checklist

- [ ] Please make sure your submission complies with our [contributing guide](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md), in particular [code style](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#code-style) and [commit standards](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#commit-standards).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== NO RELEASE NOTE ==
```

2024-12-01 20:15 UTC, elharo requested changes

2024-12-01 20:15 UTC, elharo commented on presto-docs/src/main/sphinx/language/types.rst
> +    are treated as values of the ``DOUBLE`` type by default up to version 0.198.
Just specify the current behavior. It doesn't matter what happened many versions ago.

2024-12-02 17:02 UTC, sh-shamsan approved these changes

2024-12-02 17:08 UTC, steveburnett requested changes
Nit to not use Latin abbreviation, and remove the unneeded parenthesis.

2024-12-02 17:08 UTC, steveburnett commented on presto-docs/src/main/sphinx/language/types.rst
>      For compatibility reasons decimal literals without explicit type specifier (e.g. ``1.2``)
```suggestion
    For compatibility reasons decimal literals without explicit type specifier such as ``1.2``
```

2024-12-04 23:04 UTC, steveburnett approved these changes
LGTM! (docs)

Pull branch, local doc build, looks good. Thanks!

2024-12-05 22:34 UTC, czentgr commented
@elharo can you please take a look at this again? Thanks!

2025-01-13 20:10 UTC, merged