Add two new parameters for trace control
prestodb/presto pull request #24209
Opened 2024-12-05 18:55 UTC by zation99

## Description
This is to improve the trace control experience. We added two new properties:
- native_query_trace_fragment_id
- native_query_trace_shard_id
Once specified, we automatically create a regex for Velox to match the taskID pattern, so developers don't need to compose the complicated regex themselves, and it is controlled at Prestissimo level.
If native_query_trace_task_reg_exp is also provided, it will be overridden.

## Motivation and Context

## Impact

## Test Plan

## Contributor checklist

- [ ] Please make sure your submission complies with our [contributing guide](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md), in particular [code style](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#code-style) and [commit standards](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#commit-standards).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ... :pr:`12345`
* ... :pr:`12345`

2024-12-05 23:59 UTC, xiaoxmeng reviewed
@zation99 looks good % comments. We will deprecate the existing session property for task regular expr in followup? Thanks!

2024-12-05 23:59 UTC, xiaoxmeng commented on presto-native-execution/presto_cpp/main/QueryContextManager.cpp
> +  std::string traceFragmentId = ".*";
```
std::optional<std::string> traceFragmentId;
std::optional<std::string> traceShardId
```

2024-12-05 23:59 UTC, xiaoxmeng commented on presto-native-execution/presto_cpp/main/QueryContextManager.cpp
> +  // Construct query tracing regex and pass to Velox config.
```
if (traceFragmentId.has_value() || traceShardId.has_value()) {
    configs.emplace(
      velox::core::QueryConfig::kQueryTraceTaskRegExp,
      ".*\\." + traceFragmentId.valueOr(".*") + "\\..*\\." + traceShardId.valueOr(".*") + "\\..*");
}
```

2024-12-06 14:28 UTC, steveburnett commented
Please add documentation for these properties to the appropriate pages:
[Presto Session Properties](https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/admin/properties-session.rst)
[Presto Configuration Properties](https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/admin/properties.rst)
[Presto C++ Session Properties](https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/presto_cpp/properties-session.rst)
[Presto C++ Configuration Properties](https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/presto_cpp/properties.rst)

2024-12-07 06:20 UTC, xiaoxmeng approved these changes
@zation99 LGTM. Thanks!

2024-12-07 17:26 UTC, zation99 commented
> Please add documentation for these properties to the appropriate pages: [Presto Session Properties](https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/admin/properties-session.rst) [Presto Configuration Properties](https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/admin/properties.rst) [Presto C++ Session Properties](https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/presto_cpp/properties-session.rst) [Presto C++ Configuration Properties](https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/presto_cpp/properties.rst)

done

2024-12-08 05:33 UTC, xiaoxmeng submitted a review, later dismissed

2024-12-09 06:18 UTC, aditi-pandit requested changes
@zation99 : Please can you merge all your commits into a single one with the same title as this PR.
Yes I will do so with "Squash and merge" when committing the PR.

2024-12-09 17:19 UTC, zation99 commented
> @zation99 : Please can you merge all your commits into a single one with the same title as this PR.

Yes I'll do "Squash and merge" when merging the PR.

2024-12-09 20:32 UTC, xiaoxmeng approved these changes

2024-12-09 22:11 UTC, NikhilCollooru approved these changes

2024-12-10 16:45 UTC, zation99 commented
> @zation99 : Please can you merge all your commits into a single one with the same title as this PR.

2024-12-10 16:49 UTC, aditi-pandit approved these changes
Thanks @zation99

2024-12-10 19:18 UTC, merged