[native] Introduce module presto-native-tests
prestodb/presto pull request #24234
Opened 2024-12-10 15:25 UTC by pramodsatya

## Description
Introduces module `presto-native-tests` to run end-to-end tests with Presto native workers. Adds Github action to run these tests. 

## Motivation and Context
Improves Presto native test coverage by extending product tests from `presto-tests` module to use the native worker. For full context please refer to #23671.

## Contributor checklist

- [x] Please make sure your submission complies with our [development](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#development), [formatting](https://github.com/prestodb/presto/wiki/Presto-Development-Guidelines#formatting), [commit message](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#commit-formatting-and-pull-requests), and [attribution guidelines](https://github.com/prestodb/presto/wiki/Review-and-Commit-guidelines#attribution).
- [x] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [x] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [x] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [x] Adequate tests were added if applicable.
- [x] CI passed.

```
== RELEASE NOTES ==
General Changes
* Introduces module presto-native-tests to run end-to-end tests with Presto native workers. 
```

2025-01-06 18:52 UTC, steveburnett requested changes
Thank you for the documentation! I made some suggestions for ease of reading and clarity. 

If you feel that any of my suggestions change the meaning in a way that is not correct, let me know and we can work on them together.

2025-01-06 18:52 UTC, steveburnett commented on presto-native-tests/README.md
> +`presto-native-execution` first.
Consider adding a link to where the reader can find the instructions to build `presto-native-execution`, such as the presto-native-execution README. 
https://github.com/prestodb/presto/blob/master/presto-native-execution/README.md

2025-01-06 18:52 UTC, steveburnett commented on presto-native-tests/README.md
> +The following command can be used to run all tests in this module:
```suggestion
Run the following command to run all tests in this module:
```

2025-01-06 18:52 UTC, steveburnett commented on presto-native-tests/README.md
> +Please update JVM argument `PRESTO_SERVER` to point to the Presto C++ worker
```suggestion
Update the JVM argument `PRESTO_SERVER` to point to the Presto C++ worker
```

Also, is the timezone `-Duser.timezone=America/Bahia_Banderas ` what all users should use when running this command, or should they need to change this?

2025-01-06 18:52 UTC, steveburnett commented on presto-native-tests/README.md
> +queries. This could be because of missing types, missing function signatures,
```suggestion
queries. This can be because of missing types, missing function signatures,
```

2025-01-06 18:52 UTC, steveburnett commented on presto-native-tests/README.md
> +among other reasons. Tests with these unsupported queries are therefore
```suggestion
among other reasons. Tests with these unsupported queries are 
```

2025-01-06 18:52 UTC, steveburnett commented on presto-native-tests/README.md
> +expected to fail and the test asserts the error message is as expected.
```suggestion
expected to fail and the test returns the error message is as expected. 
```
Is this suggestion correct?

2025-01-06 18:52 UTC, steveburnett commented on presto-native-tests/README.md
> +Issues should also be created for the failing queries, so they are documented
```suggestion
Create issues for the failing queries, so they can be documented
```

2025-01-06 18:52 UTC, steveburnett commented on presto-native-tests/README.md
> +and fixed. Please add the tag `presto-native-tests` for these issues.
```suggestion
and fixed. Use the tag `presto-native-tests` for these issues. 
```

2025-01-14 21:11 UTC, pramodsatya reviewed
Thanks for the feedback @steveburnett, addressed the comments, could you please take another look?

2025-01-14 22:19 UTC, steveburnett submitted a review, later dismissed
LGTM! 

Thanks for addressing the comments! Looks good.

2025-01-16 21:50 UTC, aditi-pandit reviewed
@pramodsatya : Lets move the second commit to refactor presto-tests in a separate PR. That would make it easier to review. Lets add this work as a motivation for that refactoring.

2025-01-16 21:50 UTC, aditi-pandit commented on presto-native-tests/src/test/java/com.facebook.presto.nativetests/TestNonIterativeDistributedQueries.java
> +                ImmutableMap.of("experimental.iterative-optimizer-enabled", "false"),
What does this do ? Its important to specify why this test configuration matters.

2025-01-16 21:50 UTC, aditi-pandit commented on presto-native-tests/src/test/java/com.facebook.presto.nativetests/TestNonIterativeDistributedQueries.java
> +    protected void createTables()
Can this function be moved to AbstractTestQueriesNative ?

2025-01-16 21:50 UTC, aditi-pandit commented on presto-native-tests/src/test/java/com.facebook.presto.nativetests/AbstractTestQueriesNative.java
> +    @Test(enabled = false)
Should we disable all these tests or always force optimizeHashGeneration to false ? That might be better.

2025-01-16 21:50 UTC, aditi-pandit commented on presto-native-tests/src/test/java/com.facebook.presto.nativetests/AbstractTestQueriesNative.java
> +    // The following approx_set function tests are overriden since approx_set returns different results in Presto C++.
Do we have any outward article or documentation for this ? If not, then we should write one.

2025-01-16 21:50 UTC, aditi-pandit commented on presto-native-tests/src/test/java/com.facebook.presto.nativetests/AbstractTestQueriesNative.java
> +        String functionNotRegisteredError = ".*Scalar function presto.default.array_cum_sum not registered with arguments.*";
Do we have this error because we don't have this functionality ? I don't see a reason for not building it. Do we have an issue for this ? Please create one if its not there and add the link here.

2025-01-16 21:50 UTC, aditi-pandit commented on presto-native-tests/src/test/java/com.facebook.presto.nativetests/AbstractTestQueriesNative.java
> +    public void testMergeHyperLogLogGroupBy()
Do we have issues created for Hyperloglog ? Please create and link the issue here.

2025-01-16 21:50 UTC, aditi-pandit commented on presto-native-tests/src/test/java/com.facebook.presto.nativetests/AbstractTestQueriesNative.java
> +    public void testP4ApproxSetBigint()
Link the issue for P4HYPERLOGLOG here.

2025-01-16 21:50 UTC, aditi-pandit commented on presto-native-tests/src/test/java/com.facebook.presto.nativetests/AbstractTestQueriesNative.java
> +    public void testDuplicateUnnestRows()
Do we have an issue for this ?

2025-01-16 21:50 UTC, aditi-pandit commented on presto-native-tests/src/test/java/com.facebook.presto.nativetests/AbstractTestQueriesNative.java
> +    public void testSamplingJoinChain()
key_sampling seems like an important feature. Do we have an issue ?

2025-01-16 21:50 UTC, aditi-pandit commented on presto-native-tests/src/test/java/com.facebook.presto.nativetests/AbstractTestQueriesNative.java
> +    public void testScalarSubquery()
Why is this test separated from the java one ?

2025-01-16 21:50 UTC, aditi-pandit commented on presto-native-tests/src/test/java/com.facebook.presto.nativetests/AbstractTestQueriesNative.java
> +    public void testLikePrefixAndSuffixWithChars()
These failures are because CHAR Is not supported. Lets add the issue here. 

But also any reason these are written with CHAR and not VARCHAR ? We could try to split the original test.

2025-01-16 21:50 UTC, aditi-pandit commented on presto-native-tests/src/test/java/com.facebook.presto.nativetests/AbstractTestQueriesNative.java
> +    public void testMergeKHyperLogLog()
Add an issue for the type not supported and link it here.

2025-01-22 07:09 UTC, pramodsatya reviewed
Thanks @aditi-pandit, addressed the comments and created missing issues. Also modified this PR to only include test classes with fewer modifications as discussed. Will open follow-up PRs for the remaining larger test classes from #23671, such as `AbstractTestQueriesNative.java`.
Could you please take another look?

2025-01-23 06:00 UTC, aditi-pandit commented on presto-native-tests/src/test/java/com.facebook.presto.nativetests/TestOrderByQueries.java
> +    protected QueryRunner createQueryRunner() throws Exception
Do we plan to overload the expected query runner with the JavaQueryRunner as well ?

2025-01-23 06:04 UTC, aditi-pandit commented on presto-native-tests/src/test/java/com.facebook.presto.nativetests/TestRepartitionQueriesWithSmallPages.java
> +        return PrestoNativeQueryRunnerUtils.createNativeQueryRunner(
Does native engine support these session properties ? Will native side-car catch these ?

2025-01-23 06:20 UTC, aditi-pandit commented on .github/workflows/prestocpp-linux-build-and-unit-test.yml
> +      image: prestodb/presto-native-dependency:0.290-20241014120930-e1fc090
Can we remove this hardcoded version ?

2025-01-23 18:36 UTC, pramodsatya commented on presto-native-tests/src/test/java/com.facebook.presto.nativetests/TestOrderByQueries.java
> +    protected QueryRunner createQueryRunner() throws Exception
No we do not plan to overload the expected query runner with javaQueryRunner because it does not account for the datatypes of the computed result when comparing it with the expected values. This limitation is [noted here](https://ibm.box.com/s/2ph2ttr3a2zqs97uu8ik6ie9xshww8sj).

2025-01-23 18:42 UTC, pramodsatya commented on .github/workflows/prestocpp-linux-build-and-unit-test.yml
> +      image: prestodb/presto-native-dependency:0.290-20241014120930-e1fc090
Presto native dependency images [on dockerhub](https://hub.docker.com/r/prestodb/presto-native-dependency/tags) are no longer published with the `latest` tag so we are currently using this hardcoded version in all Prestissimo Github actions. 
We should publish images with the tag `latest`, can we take it up as a separate issue?

2025-01-24 00:47 UTC, pramodsatya commented on presto-native-tests/src/test/java/com.facebook.presto.nativetests/TestRepartitionQueriesWithSmallPages.java
> +        return PrestoNativeQueryRunnerUtils.createNativeQueryRunner(
Thanks for pointing it out, the property `experimental.optimized-repartitioning` is not applicable to the native engine so removed it. Native engine does support `driver.max-page-partitioning-buffer-size`, which is required for this test, so retained this config.
The native sidecar currently does not throw an error if a session property is set that is not supported by native engine, this is to support [heterogeneous environments](https://github.com/prestodb/presto/pull/23045#pullrequestreview-2355256133). The native sidecar plugin is also not setup on the coordinator currently because of [this limitation](https://github.com/prestodb/presto/issues/24422). Can we enable the native sidecar in these tests subsequently?

2025-02-27 00:13 UTC, aditi-pandit commented on presto-native-tests/src/test/java/com.facebook.presto.nativetests/TestDistributedEngineOnlyQueries.java
> +        assertQueryFails("SELECT TIME '3:04:05'", timeTypeUnsupportedError);
@pramodsatya : These are constants and should be evaluated in the co-ordinator. Any more insight into why they failed ?

2025-03-17 15:02 UTC, steveburnett commented
Please remove the manual PR link in the following format from the release note entries for this PR.

```

:pr:`12345`

```

I have updated the [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) to remove the examples of manually adding the PR link.

```
== RELEASE NOTES ==
General Changes
* Introduces module presto-native-tests to run end-to-end tests with Presto native workers. 
```

2025-03-18 20:37 UTC, czentgr commented on .github/workflows/prestocpp-linux-build-and-unit-test.yml
> +        run: ./mvnw de.qaware.maven:go-offline-maven-plugin:resolve-dependencies
Is this properly used? I don't see the target in the pom.xml.
Did you test this job in your fork?

If so please provide the job log.

2025-03-19 00:03 UTC, pramodsatya commented on .github/workflows/prestocpp-linux-build-and-unit-test.yml
> +        run: ./mvnw de.qaware.maven:go-offline-maven-plugin:resolve-dependencies
Thanks for pointing it out @czentgr, this step was borrowed from the initial Github action for Prestissimo e2e tests and it wasn't tested. I see that changes were made recently to use Github action `setup-java` for caching dependencies, and have modified the workflow accordingly. Could you please take another look?

2025-03-20 20:04 UTC, aditi-pandit commented
@amitkdutta @jaystarshot : This PR is the first version of presto-native-tests. This is the suite to run all Java presto-product-tests with the native engine.

Would be great to get your reviews for this PR.

2025-03-20 22:33 UTC, czentgr commented on .github/workflows/prestocpp-linux-build-and-unit-test.yml
> +      image: prestodb/presto-native-dependency:0.290-20241014120930-e1fc090
Note: Deepak has a PR that updates the image. Please rebase and use that one now. See https://github.com/prestodb/presto/pull/24767

2025-03-20 22:39 UTC, pramodsatya commented on .github/workflows/prestocpp-linux-build-and-unit-test.yml
> +      image: prestodb/presto-native-dependency:0.290-20241014120930-e1fc090
Updated and rebased, thanks @czentgr.

2025-03-24 21:02 UTC, jaystarshot commented
> Refactor testcases for presto-native-tests
commit is unrelated here?

2025-03-25 22:53 UTC, pramodsatya commented
> > Refactor testcases for presto-native-tests
> 
> commit is unrelated here?

@jaystarshot, this commit splits the testcases from `presto-tests` based on what is supported by the Prestissimo. It is not necessary here but it would help run more Sql queries from these testcases with the native worker. 
For instance, `testOrderByWithOutputColumnReference` in `AbstractTestOrderByQueries` has three queries involving lambdas that would fail in Prestissimo (since `apply` function is not supported). Moving these to a separate testcase, `testOrderByWithOutputColumnReferenceInLambdas`, lets us just disable this testcase and run the remaining `~35` queries from `testOrderByWithOutputColumnReference` in `presto-native-tests`. 
Is it fine if this commit is retained?

2025-03-26 00:18 UTC, jaystarshot approved these changes

2025-03-26 05:03 UTC, aditi-pandit approved these changes
Thanks @pramodsatya

2025-03-26 14:39 UTC, czentgr approved these changes

2025-03-26 14:39 UTC, czentgr commented on .github/workflows/prestocpp-linux-build-and-unit-test.yml
> +  prestocpp-linux-presto-native-tests:
Too much code copying is happening with these test jobs (E22, sidecar plugin and now this one). We will refactor the test jobs after the merge and not make the refactor part of the PR.

2025-03-26 14:51 UTC, merged