Changes to exclude commons-dbcp2 to remove vulnerabilities
prestodb/presto pull request #24249
Opened 2024-12-12 10:11 UTC by bibith4

## Description
Changes to exclude commons-dbcp2 from presto-pinot-toolkit and presto-product-tests to remove vulnerabilities.

## Motivation and Context
The presto-pinot-toolkit and presto-product-tests have interdependencies with commons-dbcp2 versions 2.6.0 and 2.1, respectively, both of which contain vulnerabilities. These vulnerabilities can be removed by excluding the commons-dbcp2 dependency.

## Impact

## Test Plan

## Contributor checklist

- [ ] Please make sure your submission complies with our [contributing guide](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md), in particular [code style](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#code-style) and [commit standards](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#commit-standards).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

Security Changes
* Fix security vulnerability in presto-pinot-toolkit and presto-product-tests in response to  [CVE-2020-0287](https://nvd.nist.gov/vuln/detail/CVE-2020-0287) :pr:`24199`
```

2024-12-16 09:13 UTC, Dilli-Babu-Godari commented
@bibith4 I noticed that the latest version of commons-dbcp2 is available. Is there any issue with using that version?

2024-12-16 09:25 UTC, Dilli-Babu-Godari commented
@bibith4 LGTM

2024-12-16 09:38 UTC, bibith4 commented
> @bibith4 I noticed that the latest version of commons-dbcp2 is available. Is there any issue with using that version?

@Dilli-Babu-Godari  Recent version 2.13 was released on December 2, 2024. To ensure stability, I opted to use commons-dbcp2 version 2.12, which was released earlier on March 4, 2024

2024-12-16 09:46 UTC, ShahimSharafudeen commented
@bibith4 LGTM

2024-12-16 12:02 UTC, Dilli-Babu-Godari approved these changes

2024-12-16 14:34 UTC, ShahimSharafudeen approved these changes

2025-01-02 18:20 UTC, ZacBlanco requested changes

2025-01-02 18:20 UTC, ZacBlanco commented on presto-pinot/pom.xml
> +            <version>2.12.0</version>
This should be added to the root pom's `dependencyManagement` section

2025-01-02 18:20 UTC, ZacBlanco commented on presto-pinot/pom.xml
> +            <optional>true</optional>
Why is the scope `runtime` and `optional` tag included?

2025-01-03 17:47 UTC, steveburnett commented
Thanks for the release note! Minor formatting nits suggestion:

```
== RELEASE NOTES ==

Security Changes
* Fix security vulnerability in presto-pinot-toolkit and presto-product-tests in response to `CVE-2020-0287 <https://nvd.nist.gov/vuln/detail/CVE-2020-0287>`_. :pr:`24249`
```

2025-01-06 08:36 UTC, bibith4 commented on presto-pinot/pom.xml
> +            <version>2.12.0</version>
@ZacBlanco Moved to root pom. Please check

2025-01-06 15:48 UTC, steveburnett commented
> @steveburnett corrected the format. Please check

Looks good, thanks!

2025-01-08 05:08 UTC, ZacBlanco commented on presto-pinot/pom.xml
> +                            </dependency>
What was the original reason for adding this? I tried building locally without this section and the build succeeded without issue.

2025-01-08 17:27 UTC, ZacBlanco approved these changes

2025-01-09 05:38 UTC, bibith4 commented on presto-pinot/pom.xml
> +                            </dependency>
@ZacBlanco This was added to avoid a build failure. However, after moving the dependency to the root POM.the build started working as expected

2025-01-09 20:38 UTC, tdcmeehan requested changes

2025-01-10 06:15 UTC, bibith4 commented on pom.xml
> +            </dependency>
@tdcmeehan corrected the format. Please check

2025-01-10 14:59 UTC, tdcmeehan approved these changes

2025-01-10 15:00 UTC, merged