Add support for row filtering and column masking access control
prestodb/presto pull request #24277
Opened 2024-12-18 19:07 UTC by BryanCutler

## Description

This adds support for row filtering and column masking to access control as part of governance requirements. Filters/masks are supplied as part of an access control implementation and then applied to queries according to matching table and column names supplied by access control.

These changes are cherry-picked from the following commits:

Adding support for row filters
Cherry-pick of https://github.com/trinodb/trino/commit/fae3147212fe58dac5ad782f0f13a17d9e962dd6
Co-authored-by: Martin Traverso <mtraverso@gmail.com>

Adding support for column masks
Cherry-pick of https://github.com/trinodb/trino/commit/7e0d88e6906cb91387d707f8daf9dc46095ad0bf
Co-authored-by: Martin Traverso <mtraverso@gmail.com>

Disallow multiple masks on a given column
Cherry-pick of https://github.com/trinodb/trino/commit/bdd1cb5dbc66e938de4802145ee75f5cfb1e4bb1
Co-authored-by: Martin Traverso <mtraverso@gmail.com>

For original IBM Presto port 
Co-authored-by: Reetika Agrawal <agrawal.reetika786@gmail.com>

## Motivation and Context

Governance requirements include the ability to restrict access to certain rows of tables or sensitive data in certain columns. This adds the ability to provide filters/masks as expressions to Presto where they will then be applied to relevant queries.

## Impact

Additions to SPI include access control interfaces to get row filters and column masks.

ConnectorAccessControl

```java
    /**
     * Get a row filter associated with the given table and identity.
     *
     * The filter must be a scalar SQL expression of boolean type over the columns in the table.
     *
     * @return the filter, or {@link Optional#empty()} if not applicable
     */
    Optional<ViewExpression> getRowFilter(ConnectorTransactionHandle transactionHandle, ConnectorIdentity identity, AccessControlContext context, SchemaTableName tableName)
    {
        return Optional.empty();
    }

    /**
     * Get a column mask associated with the given table, column and identity.
     *
     * The mask must be a scalar SQL expression of a type coercible to the type of the column being masked. The expression
     * must be written in terms of columns in the table.
     *
     * @return the mask, or {@link Optional#empty()} if not applicable
     */
    default Optional<ViewExpression> getColumnMask(ConnectorTransactionHandle transactionHandle, ConnectorIdentity identity, AccessControlContext context, SchemaTableName tableName, String columnName, Type type)
    {
        return Optional.empty();
    }
```

## Test Plan

Unit tests added.

## Contributor checklist

- [ ] Please make sure your submission complies with our [contributing guide](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md), in particular [code style](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#code-style) and [commit standards](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#commit-standards).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ... :pr:`12345`
* ... :pr:`12345`

Hive Connector Changes
* ... :pr:`12345`
* ... :pr:`12345`
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2024-12-18 19:26 UTC, BryanCutler commented
There are some followup commits that I did not include here, we can add these in or look into as a followup:

Apply filters and masks for view object
https://github.com/trinodb/trino/commit/6721cfad45d47a663c805c496eb40e648a8a1710

Apply filters and masks for tables referenced by views
https://github.com/trinodb/trino/commit/84429d84d8fd75d686aa63d0223885c793089395

Add test for join on masked column
https://github.com/trinodb/trino/commit/705ed21735aaf0c9ffd209662e3d82e4a81116da

Record filter and mask information in query event
https://github.com/trinodb/trino/commit/1b55b866f344b59404c77dd1da0bd3b31fed5f3f

2024-12-18 22:15 UTC, jaystarshot commented
@tdcmeehan Its high time that we consider merging this stuff, as we discussed last time in the meeting doing in connector optimizer is not feasible for all cases and offerrs no benefit

2024-12-20 20:12 UTC, tdcmeehan commented
I'm in favor of this approach.  While it does increase our SPI footprint, I think it's nice to align with Trino's approach in this case because it makes porting plugins easier for folks.  I think this is worth the small increase in footprint.

2025-01-10 01:41 UTC, uarturm commented on presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java
> +                throw new PrestoException(INVALID_ROW_FILTER, format("Column mask for '%s.%s' is recursive", tableName, column), null);
nit: Can you please use INVALID_COLUMN_MASK error code in this method?

2025-01-10 01:41 UTC, uarturm commented on presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java
> +                Map<VariableReferenceExpression, RowExpression> assignments = new LinkedHashMap<>();
Can you please move the creation of assignments and the new planBuilder outside the for loop? This will allow invoking planBuilder.withNewRoot only once per method invocation, rather than creating a new planBuilder for each mask. It will improve efficiency and make the logic cleaner.

2025-01-10 01:41 UTC, uarturm commented on presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java
> +        TranslationMap translations = new TranslationMap(plan, analysis, lambdaDeclarationToVariableMap);
nit: We can simplify this section by reusing some code. Instead of directly using `translations.rewrite(mask)`, you could initialize the PlanBuilder with `PlanBuilder planBuilder = initializePlanBuilder(plan);`. Then, use `planBuilder.rewrite(mask)` to leverage the translations map already stored internally within planBuilder.

2025-02-18 19:25 UTC, BryanCutler commented on presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java
> +                Map<VariableReferenceExpression, RowExpression> assignments = new LinkedHashMap<>();
Yeah, that sounds better.

2025-02-18 19:45 UTC, BryanCutler commented on presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java
> +                Map<VariableReferenceExpression, RowExpression> assignments = new LinkedHashMap<>();
I think I got it working, but still new working with these parts so let me know if it can be improved.

2025-03-13 23:04 UTC, BryanCutler commented
The test failure seems to be sporadic, or maybe from some state not getting reset. I'll have to look into it further.

2025-03-14 00:11 UTC, BryanCutler commented
Found the problem, one test was not calling `executeExclusively` when running the query. So the test access control was getting clobbered.

2025-03-17 08:46 UTC, aaneja requested changes
Can you add one or two tests that demonstrate the end-to-end behavior in `presto-tests` ?

2025-03-17 08:46 UTC, aaneja commented on presto-main/src/test/java/com/facebook/presto/sql/query/TestRowFilter.java
> +public class TestRowFilter
Should we also add some tests that assert on query plans instead of just results ? It will make understanding the impact of the row filter / column masks easier

2025-03-17 19:03 UTC, BryanCutler commented on presto-main/src/main/java/com/facebook/presto/security/FileBasedSystemAccessControl.java
> +    public List<ViewExpression> getRowFilters(Identity identity, AccessControlContext context, CatalogSchemaTableName tableName)
Yes, there is a test that checks the entire interface is implemented, see https://github.com/prestodb/presto/blob/e2ee434321cdf93301e63f09a7a862863dca6a1f/presto-main/src/test/java/com/facebook/presto/security/TestFileBasedSystemAccessControl.java#L429

2025-03-17 19:16 UTC, BryanCutler commented on presto-main/src/test/java/com/facebook/presto/sql/query/TestRowFilter.java
> +    public void testDifferentIdentity()
Yes, that sounds correct to me. I will try to sum this up in a comment.

2025-03-17 21:08 UTC, BryanCutler commented on presto-main/src/test/java/com/facebook/presto/sql/query/TestRowFilter.java
> +public class TestRowFilter
sure, I can add those

2025-03-18 23:24 UTC, BryanCutler commented
> Can you add one or two tests that demonstrate the end-to-end behavior in presto-tests ?

Thanks @aaneja , I added tests to verify the query plan. I can add tests to `presto-tests` but I'm not too sure how they would be much different than what's already in `TestRowFilter`, which run queries and verify the results. Could you explain more what you are looking for?

2025-03-21 17:14 UTC, BryanCutler commented on presto-main/src/test/java/com/facebook/presto/sql/query/TestRowFilter.java
> +public class TestRowFilter
done

2025-04-01 06:36 UTC, aaneja commented
>Thanks @aaneja , I added tests to verify the query plan. I can add tests to presto-tests but I'm not too sure how they would be much different than what's already in TestRowFilter, which run queries and verify the results. Could you explain more what you are looking for?
What I was looking for are test(s) that demonstrate how filter and column masks are picked up by various config mechanisms. `TestRowFilter` uses the `TestingAccessControlManager` to plumb these in; in `presto-tests` we should use some mechanism that does not use this internal fixture

2025-04-01 06:36 UTC, aaneja requested changes

2025-04-01 06:36 UTC, aaneja commented on presto-main-base/src/test/java/com/facebook/presto/sql/planner/TestAccessControlFiltersMasks.java
> +                            node(FilterNode.class, node(TableScanNode.class))));
Can you add more a more detailed filter matcher ? [an example](https://github.com/prestodb/presto/blob/47a708022aba003ebfda483ea3c940231fdbd282/presto-main-base/src/test/java/com/facebook/presto/sql/planner/TestLogicalPlanner.java#L421)

2025-04-01 06:36 UTC, aaneja commented on presto-main-base/src/test/java/com/facebook/presto/sql/planner/TestAccessControlFiltersMasks.java
> +                                anyTree(node(FilterNode.class, node(TableScanNode.class))),
Similar comment to one above

2025-04-07 21:06 UTC, BryanCutler commented
> What I was looking for are test(s) that demonstrate how filter and column masks are picked up by various config mechanisms. TestRowFilter uses the TestingAccessControlManager to plumb these in; in presto-tests we should use some mechanism that does not use this internal fixture

The filters and masked are all retrieved through the AccessControl implementation. If we don't use the `TestingAccessControlManager` then we would need to create another AccessControl implementation and any configuration for the filters and masks would just be arbitrary.

There was some previous discussion about providing a full example, perhaps using Ranger, that would demonstrate more real-world usage. However, that should probably be done separately. Does that sound like it would fit what you are looking for?

2025-04-07 22:14 UTC, BryanCutler commented on presto-main-base/src/test/java/com/facebook/presto/sql/planner/TestAccessControlFiltersMasks.java
> +                            node(FilterNode.class, node(TableScanNode.class))));
done

2025-04-07 22:14 UTC, BryanCutler commented on presto-main-base/src/test/java/com/facebook/presto/sql/planner/TestAccessControlFiltersMasks.java
> +                                anyTree(node(FilterNode.class, node(TableScanNode.class))),
done

2025-04-08 13:01 UTC, aaneja submitted a review, later dismissed
Lets punt on the E2E example with Ranger to later. LGTM

2025-04-14 05:04 UTC, ScrapCodes approved these changes
Did a pass, Looks good!

2025-04-14 05:09 UTC, ScrapCodes commented on presto-main-base/src/main/java/com/facebook/presto/security/FileBasedSystemAccessControl.java
> +        return Collections.emptyList();
May be these can be loaded in the same way other checks are loaded : https://github.com/prestodb/presto/pull/24277/files#diff-05d844acdb3f42de1fbc27315e05243462acea86342d988ade68384ca5a3a094R149

2025-04-14 17:40 UTC, BryanCutler commented on presto-main-base/src/main/java/com/facebook/presto/security/FileBasedSystemAccessControl.java
> +        return Collections.emptyList();
I'm not seeing anything from your link and not quite sure what you're referring to, what other checks?

2025-04-14 18:06 UTC, steveburnett commented
Do we need any documentation added for these features?

2025-04-17 11:42 UTC, ScrapCodes commented
> Do we need any documentation added for these features?

Yes @steveburnett

2025-04-17 17:43 UTC, BryanCutler commented
@steveburnett yes we should have something in the docs. These additions are mainly new SPIs, so it would fit in with an access control implementation guide, maybe under here https://prestodb.io/docs/current/develop/system-access-control.html#implementation wdyt?

2025-04-17 17:49 UTC, steveburnett commented
> @steveburnett yes we should have something in the docs. These additions are mainly new SPIs, so it would fit in with an access control implementation guide, maybe under here https://prestodb.io/docs/current/develop/system-access-control.html#implementation wdyt?

I like it! That seems like a good place to put it. Thanks for thinking about where it should go.

2025-04-17 23:45 UTC, BryanCutler commented on presto-docs/src/main/sphinx/develop/system-access-control.rst
> +
@steveburnett please take a look at the doc additions, thanks!

2025-04-18 14:13 UTC, steveburnett submitted a review, later dismissed
LGTM! (docs)

Pull branch, local doc build, looks good. Thanks!

2025-04-22 11:54 UTC, aaneja submitted a review, later dismissed

2025-04-22 17:59 UTC, BryanCutler commented
@jaystarshot is this something you are available to review and help merge?

2025-04-24 21:55 UTC, ZacBlanco requested changes
Great improvement, just a few nits and a couple tests for complex types would be great

2025-04-24 21:55 UTC, ZacBlanco commented on presto-main-base/src/main/java/com/facebook/presto/security/FileBasedSystemAccessControl.java
> +        return Collections.emptyList();
to stick with our conventions, we probably want to do `ImmutableMap.of()`?

2025-04-24 21:55 UTC, ZacBlanco commented on presto-main-base/src/main/java/com/facebook/presto/security/AllowAllSystemAccessControl.java
> +        return Collections.emptyList();
nit: ImmutableList.of()

2025-04-24 21:55 UTC, ZacBlanco commented on presto-main-base/src/main/java/com/facebook/presto/security/AllowAllSystemAccessControl.java
> +        return Collections.emptyMap();
nit: ImmutableList.of()

2025-04-24 21:55 UTC, ZacBlanco commented on presto-main-base/src/main/java/com/facebook/presto/security/FileBasedSystemAccessControl.java
> +        return Collections.emptyMap();
nit: ImmutableMap.of()

2025-04-24 21:55 UTC, ZacBlanco commented on presto-main-base/src/test/java/com/facebook/presto/security/TestAccessControlManager.java
> +    }
Maybe I am , but I don't actually see any assertions in this test. What are we testing here?

2025-04-24 21:55 UTC, ZacBlanco commented on presto-main-base/src/test/java/com/facebook/presto/sql/query/QueryAssertions.java
> +    }
Can we not re-use this method inside of `TestAccessControlFiltersMasks`?

2025-04-24 21:55 UTC, ZacBlanco commented on presto-main-base/src/test/java/com/facebook/presto/sql/query/TestColumnMask.java
> +            accessControl.reset();
These tests use `accesscontrol.reset()` while others do not? Is it required?

2025-04-24 21:55 UTC, ZacBlanco commented on presto-main-base/src/test/java/com/facebook/presto/sql/query/TestColumnMask.java
> +}
Can we also do a few tests with complex/nested types such as ROW and ARRAY types

2025-04-24 21:55 UTC, ZacBlanco commented on presto-main-base/src/test/java/com/facebook/presto/sql/query/TestRowFilter.java
> +}
similarly, it would be good to add some tests which use complex types

2025-04-24 21:55 UTC, ZacBlanco commented on presto-plugin-toolkit/src/main/java/com/facebook/presto/plugin/base/security/FileBasedAccessControl.java
> +        return Collections.emptyList();
nit: ImmutableList.of()

2025-04-24 21:55 UTC, ZacBlanco commented on presto-plugin-toolkit/src/main/java/com/facebook/presto/plugin/base/security/FileBasedAccessControl.java
> +        return Collections.emptyMap();
nit: ImmutableMap.of()

2025-04-25 18:00 UTC, BryanCutler commented on presto-main-base/src/test/java/com/facebook/presto/security/TestAccessControlManager.java
> +    }
Yeah, only the assertions were removed in this cherry-pick https://github.com/trinodb/trino/commit/bdd1cb5dbc66e938de4802145ee75f5cfb1e4bb1#diff-909e4c713f94af653c076fb89d41721b93d272cc80664238535e3f572c976a79

2025-04-25 18:17 UTC, BryanCutler commented on presto-main-base/src/test/java/com/facebook/presto/sql/query/QueryAssertions.java
> +    }
Not really, in `TestAccessControlFiltersMasks` we are asserting the plan, so `QueryAssertions` isn't used. It could be possible to put in `LocalQueryRunner`, which is used by all tests but this is really to do with a test fixture and not so much a query runner. It's just a few lines, so I figured it's least disruptive to copy in  `TestAccessControlFiltersMasks`.

2025-04-25 18:19 UTC, BryanCutler commented on presto-main-base/src/test/java/com/facebook/presto/sql/query/TestColumnMask.java
> +            accessControl.reset();
It should be called in each test that adds filters or masks to access control - which ones did you see that don't have it?

2025-04-25 18:22 UTC, BryanCutler commented on presto-main-base/src/test/java/com/facebook/presto/sql/query/TestColumnMask.java
> +}
I suppose it would be good to make sure a `ViewExpression` can apply to a complex type. It would take me some time to work this out, would that be ok to work on as a followup?

2025-04-25 18:30 UTC, BryanCutler commented on presto-main-base/src/test/java/com/facebook/presto/sql/query/QueryAssertions.java
> +    }
Since multiple masks are not allowed on a column, this test now throws an exception. There aren't any other tests that check this behavior, so I'll convert it to verify that it throws.

2025-04-25 18:30 UTC, BryanCutler commented on presto-main-base/src/test/java/com/facebook/presto/security/TestAccessControlManager.java
> +    }
Since multiple masks are not allowed on a column, this test now throws an exception. There aren't any other tests that check this behavior, so I'll convert it to verify that it throws.

2025-04-25 20:53 UTC, BryanCutler commented on presto-main-base/src/test/java/com/facebook/presto/security/TestAccessControlManager.java
> +    }
done

2025-04-28 15:39 UTC, ZacBlanco reviewed
LGTM, just open the ticket for complex types first

2025-04-28 15:39 UTC, ZacBlanco commented on presto-main-base/src/test/java/com/facebook/presto/sql/query/TestColumnMask.java
> +}
Can you at least open a ticket and link it to this discussion so we don't lose track of this?

2025-04-28 15:39 UTC, ZacBlanco commented on presto-main-base/src/test/java/com/facebook/presto/sql/query/TestColumnMask.java
> +            accessControl.reset();
Hmm I swear I saw some without it. I don't see the same issue any more. Forget about this comment I guess

2025-04-28 17:34 UTC, BryanCutler commented on presto-main-base/src/test/java/com/facebook/presto/sql/query/TestColumnMask.java
> +}
Issue created: https://github.com/prestodb/presto/issues/24998

2025-04-28 19:03 UTC, ZacBlanco approved these changes

2025-04-28 20:29 UTC, merged