Add UPDATE support for Iceberg
prestodb/presto pull request #24281
Opened 2024-12-18 22:04 UTC by ZacBlanco

## Description

## Motivation and Context

## Impact

## Test Plan

## Contributor checklist

- [ ] Please make sure your submission complies with our [contributing guide](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md), in particular [code style](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#code-style) and [commit standards](https://github.com/prestodb/presto/blob/master/CONTRIBUTING.md#commit-standards).
- [ ] PR description addresses the issue accurately and concisely.  If the change is non-trivial, a GitHub Issue is referenced.
- [ ] Documented new properties (with its default value), SQL syntax, functions, or other functionality.
- [ ] If release notes are required, they follow the [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines).
- [ ] Adequate tests were added if applicable.
- [ ] CI passed.

## Release Notes
Please follow [release notes guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) and fill in the release notes below.

```
== RELEASE NOTES ==

General Changes
* ... :pr:`12345`
* ... :pr:`12345`

Hive Connector Changes
* ... :pr:`12345`
* ... :pr:`12345`
```

If release note is NOT required, use:

```
== NO RELEASE NOTE ==
```

2025-01-03 17:55 UTC, steveburnett commented
Thanks for the release note! Formatting nits:

```
== RELEASE NOTES ==

Iceberg Changes
* Iceberg connector support for ``UPDATE`` SQL statements. :pr:`24281`
```

2025-01-13 18:28 UTC, hantangwangd reviewed
Thanks for implementing this great feature. Some little problems and nits during the first rough inspection, and will take a detailed look in a couple of days.

2025-01-13 18:28 UTC, hantangwangd commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergAbstractMetadata.java
> +        }
Should these validations be placed after adding data files and delete files to `rowDelta`? As I understand, they should be placed after the below validation:

```
rowDelta.validateDataFilesExist(referencedDataFiles.build());
```

We can refer to Spark's relevant example here: https://github.com/apache/iceberg/blob/main/spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java#L206-L278.

2025-01-13 18:28 UTC, hantangwangd commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergAbstractMetadata.java
> +        validateTableMode(session, icebergTable);
Should we check that the update mode must be `merge-on-read` here? Currently without this check, I can create a v2 table with update mode `copy-on-read` as follows:

```
create table mytable(a int, b varchar) with(update_mode = 'copy-on-write');
insert into mytable values(1, '1001'), (2, '1002'), (3, '1003');
```

And then update it successfully:

```
update mytable set b = '1007' where a = 2;
```

It seems that in this scenario, the update statement should fail.

2025-01-13 18:28 UTC, hantangwangd commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergAbstractMetadata.java
> +        Table icebergTable = getIcebergTable(session, ((IcebergTableHandle) tableHandle).getSchemaTableName());
```suggestion
        Table icebergTable = getIcebergTable(session, handle.getSchemaTableName());
```

2025-01-13 20:31 UTC, ZacBlanco commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergAbstractMetadata.java
> +        validateTableMode(session, icebergTable);
Thanks for pointing this out - fixed

2025-01-13 20:32 UTC, ZacBlanco commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergAbstractMetadata.java
> +        }
Good catch. Probably was an artifact when I was refactoring the original commit. Let me know if you still see issues

2025-01-26 17:08 UTC, hantangwangd requested changes
Thanks for this high-quality implementation, overall looks good to me, only some little nits.

2025-01-26 17:08 UTC, hantangwangd commented on presto-iceberg/src/test/java/com/facebook/presto/iceberg/IcebergDistributedTestBase.java
> +    }
Are these codes useful?

2025-01-26 17:51 UTC, imjalpreet reviewed
Thanks for the PR! I'm sorry for the delay in reviewing it. I completed a partial review and will continue with the rest.

2025-01-26 17:51 UTC, imjalpreet commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergPageSourceProvider.java
> +            updateRowIdColumn.getColumnIdentity().getChildren()
nit: we can probably store it in a variable before streaming 
`List<ColumnIdentity> = updateRowIdColumn.getColumnIdentity().getChildren();`

2025-01-26 17:51 UTC, imjalpreet commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/ConnectorPageSourceWithRowPositions.java
> +        this.delegate = requireNonNull(delegate, "connectorPageSource is null");
nit: should we now change the message to `"delegate is null"` since we have renamed the parameter to delegate rather than `connectorPageSource`?

2025-01-26 17:51 UTC, imjalpreet commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergPartitionInsertingPageSource.java
> +                        Type type = column.getType();
nit: we can move this before the if..else and reuse or directly use `column.getType()`.

2025-01-26 17:51 UTC, imjalpreet commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergPartitionInsertingPageSource.java
> +        return delegate.getSystemMemoryUsage();
Should we also include partitionValueBlocks when calculating memory usage here?

2025-01-26 17:51 UTC, imjalpreet commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergPartitionInsertingPageSource.java
> +    public IcebergPartitionInsertingPageSource(
nit: for better readability, should we refactor the constructor into a couple of helper methods? Probably one for creating partitionValueBlocks and another one for filtering nonPartitionColumnIndexes and generating outputIndexes.

2025-01-26 17:51 UTC, imjalpreet commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergPartitionInsertingPageSource.java
> +                }
```suggestion
                blocks[i] = partitionValueBlocks[i] != null
                ? new RunLengthEncodedBlock(partitionValueBlocks[i], batchSize)
                : dataPage.getBlock(outputIndexes[i]);
```

2025-01-27 19:17 UTC, ZacBlanco commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergPageSourceProvider.java
> +        PartitionSpec partitionSpec = PartitionSpecParser.fromJson(tableSchema, split.getPartitionSpecAsJson());
same as before - SchemaParser on the line above and PartitionSpecParser both have `fromJson`. I think it is clearer to leave it non-static

2025-01-27 19:19 UTC, ZacBlanco commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergPageSourceProvider.java
> +                .collect(Collectors.toSet());
I specifically use Collectors.toSet() here because in the next block where we get equality deletes we may add more items to the set

2025-01-27 19:25 UTC, ZacBlanco commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergPageSourceProvider.java
> +            updateRowIdColumn.getColumnIdentity().getChildren()
What's the benefit of storing the variable? I don't see where it would be used later

2025-01-27 19:25 UTC, ZacBlanco commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/ConnectorPageSourceWithRowPositions.java
> +        this.delegate = requireNonNull(delegate, "connectorPageSource is null");
good catch

2025-01-27 19:33 UTC, imjalpreet commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergAbstractMetadata.java
> +        for (Types.NestedField column : SchemaParser.fromJson(table.getTableSchemaJson().get()).columns()) {
Sorry, you are right. Forgot about that.

2025-01-27 19:34 UTC, imjalpreet commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergPageSourceProvider.java
> +            updateRowIdColumn.getColumnIdentity().getChildren()
I agree I also don't see any usage, I probably misread something due to which I wrote this comment. We can ignore this.

2025-01-27 20:27 UTC, ZacBlanco commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergAbstractMetadata.java
> +            switch (task.getContent()) {
refactored

2025-01-27 20:27 UTC, ZacBlanco commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergAbstractMetadata.java
>              }
refactored

2025-01-27 20:28 UTC, ZacBlanco commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergPartitionInsertingPageSource.java
> +    public IcebergPartitionInsertingPageSource(
I have refactored it

2025-01-27 20:29 UTC, ZacBlanco commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergPageSourceProvider.java
> +                            Types.NestedField column = tableSchema.findField(colId.getId());
I added this. Good catch

2025-02-02 19:10 UTC, hantangwangd approved these changes
Thanks for the whole work, looks good to me, only a couple of little nits.

2025-02-02 19:10 UTC, hantangwangd commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergUpdateablePageSource.java
> +                throw new IllegalArgumentException(format("column %s does not exist in delegate column map", outputColumns.get(i)));
nit: Is it appropriate to throw a `PrestoException` with error code `ICEBERG_MISSING_COLUMN` here?

2025-02-02 19:10 UTC, hantangwangd commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergUpdateablePageSource.java
> +    }
nit: This method seems to be useless anymore.

2025-02-02 23:24 UTC, imjalpreet reviewed
Thanks for the PR, almost LGTM, just a couple of nits.

2025-02-02 23:24 UTC, imjalpreet commented on presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/StreamPropertyDerivations.java
> +            StreamProperties properties = Iterables.getOnlyElement(inputProperties);
nit: static import for `getOnlyElement`?

2025-02-03 15:01 UTC, steveburnett commented
New release note guidelines as of last week: PR #24354 automatically adds links to this PR to the release notes. Please remove the manual PR link in the following format from the release note entries for this PR. 

```
:pr:`12345`
```

I have updated the [Release Notes Guidelines](https://github.com/prestodb/presto/wiki/Release-Notes-Guidelines) to remove the examples of manually adding the PR link.

2025-02-04 01:18 UTC, ZacBlanco commented on presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/StreamPropertyDerivations.java
> +            StreamProperties properties = Iterables.getOnlyElement(inputProperties);
There are many instances of `Iterables.getOnlyElement` in the file already. I would prefer to keep the diff small

2025-02-04 01:48 UTC, ZacBlanco commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergUpdateablePageSource.java
> +    }
removed

2025-02-04 01:48 UTC, ZacBlanco commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergUpdateablePageSource.java
> +                throw new IllegalArgumentException(format("column %s does not exist in delegate column map", outputColumns.get(i)));
I like this better. updated to throw PrestoException

2025-02-04 01:48 UTC, ZacBlanco commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergUpdateablePageSource.java
> +                dataPage = new Page(dataPage.getPositionCount(), fullPage);
Thanks, refactored

2025-02-04 15:00 UTC, steveburnett requested changes
Thanks for the doc! A few suggestions, looks good overall.

2025-02-04 15:00 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/iceberg.rst
> +The iceberg connector supports `UPDATE` operations on Iceberg tables. See :doc:`../sql/update` for more details
```suggestion
The Iceberg connector supports :doc:`../sql/update` operations on Iceberg tables. 
```

2025-02-04 15:00 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/iceberg.rst
> +on the syntax and semantics. Only some tables support updates. These tables are require to be at minimum
```suggestion
Only some tables support updates. These tables must be at minimum
```

2025-02-04 15:00 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/iceberg.rst
> +format version 2 and the ``write.update.mode`` must be set to `merge-on-read`
```suggestion
format version 2, and the ``write.update.mode`` must be set to `merge-on-read`.
```

2025-02-04 15:00 UTC, steveburnett commented on presto-docs/src/main/sphinx/connector/iceberg.rst
> +The query will error if the table does not meet the requirements for updates.
```suggestion
The query returns an error if the table does not meet the requirements for updates.
```

2025-02-04 19:44 UTC, steveburnett submitted a review, later dismissed
LGTM! (docs)

Pull updated branch, new local docs build, everything looks good. Thanks!

2025-02-04 23:36 UTC, hantangwangd approved these changes

2025-02-05 10:42 UTC, imjalpreet approved these changes
LGTM, thanks for the PR @ZacBlanco

2025-02-06 21:00 UTC, tdcmeehan reviewed
Just some nits, looks good

2025-02-06 21:00 UTC, tdcmeehan commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergUpdateablePageSource.java
> +        // 3. transform page for update (turn flat blocks into nested update row)
I would convert this into a method level comment and use full sentences, proper punctuation and capitalization

2025-02-06 21:00 UTC, tdcmeehan commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergUpdateablePageSource.java
> +                .orElseGet(() -> CompletableFuture.completedFuture(ImmutableList.of()))
```suggestion
                .orElseGet(() -> completedFuture(ImmutableList.of()))
```

2025-02-06 21:00 UTC, tdcmeehan commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergUpdateablePageSource.java
> +                                .orElseGet(() -> CompletableFuture.completedFuture(ImmutableList.of())),
```suggestion
                                .orElseGet(() -> completedFuture(ImmutableList.of())),
```

2025-02-06 21:00 UTC, tdcmeehan commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergUtil.java
> +     * considering iceberg table properties {@code WRITE_DATA_LOCATION}, {@code OBJECT_STORE_PATH} and {@code WRITE_FOLDER_STORAGE_LOCATION}
I know the comments were improperly formatted before, but can you revert this?  It would just muddle the git blame.

2025-02-06 21:00 UTC, tdcmeehan commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergUtil.java
> +            Optional<Set<Integer>> requestedSchema)
```suggestion
            long snapshot,
            TupleDomain<IcebergColumnHandle> filter,
            Optional<Set<Integer>> requestedPartitionSpec,
            Optional<Set<Integer>> requestedSchema)
```

Can we revert the whitespace only changes?

2025-02-06 21:00 UTC, tdcmeehan commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergPageSourceProvider.java
> +        HashMap<Integer, Object> metadataValues = new HashMap<>();
Does it need to be mutable?

2025-02-06 21:00 UTC, tdcmeehan commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergPartitionInsertingPageSource.java
> +                .mapToObj(idx -> {
```suggestion
                .mapToObj(index -> {
```

2025-02-06 21:00 UTC, tdcmeehan commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergUpdateablePageSource.java
> +                .collect(toImmutableMap(idx -> delegateColumns.get(idx).getColumnIdentity(), identity()));
```suggestion
                .collect(toImmutableMap(index -> delegateColumns.get(index).getColumnIdentity(), identity()));
```

2025-02-06 21:00 UTC, tdcmeehan commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergUpdateablePageSource.java
> +                // nit: Is it appropriate to throw a PrestoException with error code ICEBERG_MISSING_COLUMN here?
Was this comment intentionally left here?

Reading through this, my thinking is this is something that could happen and it would be an Iceberg error.  I think it means there's some sort of mismatch between the table schema in Iceberg and the output columns generated by Presto.  So perhaps just remove the comment?

2025-02-06 23:18 UTC, ZacBlanco commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergUtil.java
> +     * considering iceberg table properties {@code WRITE_DATA_LOCATION}, {@code OBJECT_STORE_PATH} and {@code WRITE_FOLDER_STORAGE_LOCATION}
IntelliJ IDE likes to auto-format these...maybe I'll open a separate PR to apply formatting to the entire connector. This seems to happen quite often

2025-02-06 23:25 UTC, ZacBlanco commented on presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergUpdateablePageSource.java
> +                // nit: Is it appropriate to throw a PrestoException with error code ICEBERG_MISSING_COLUMN here?
Ah it was from a review comment. I think I accidentally pasted the review comment as an actual comment  😅  I will remove it

2025-02-07 20:42 UTC, tdcmeehan approved these changes

2025-02-07 22:13 UTC, merged